### ISSUE TITLE
Metals frequently fails to import project

### ISSUE THREAD

**Issue by matthughes** [scalameta/metals#1014]
**Describe the bug**
Metals in VSCode frequently fails to import my project.  The same SBT command used on the command line, fails in Metals 80% of the time with the following error:

```
INFO  running '/usr/local/bin/sbt -sbt-dir /Users/mhughe008/.sbtenv/vise -ivy /Users/mhughe008/.sbtenv/vise/ivy2 -mem 4098 metalsEnable bloopInstall'
Oct 22, 2019 9:37:32 AM com.zaxxer.nuprocess.osx.OsxProcess start
WARNING: Exception thrown from handler
java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 17
	at com.zaxxer.nuprocess.internal.BasePosixProcess.checkReturnCode(BasePosixProcess.java:639)
	at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:85)
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at scala.meta.internal.metals.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:80)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:55)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1194)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1168)
	at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1038)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

INFO  build tool exit: -2147483648
INFO  time: ran 'sbt bloopInstall' in 2ms
```

**To Reproduce**
1. Import project with SBT arguments
2. Import fails

**Expected behavior**
SBT command should succeed and project should be imported.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.7.6
- Also using Bloop 1.3.4 external server

**Additional context**
This seems to be made worse when I'm switching branches and need to re-import.  It's like Bloop is still holding onto the previous project definition.  However, I'm not sure how much sense this makes as the same SBT command succeeds on the CLI every time.

**Comment by olafurpg** [comment]
Thank you for reporting! What Java version are you using?

**Comment by matthughes** [comment]
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**Comment by matthughes** [comment]
I've tried doing `sbt bloopInstall metalsEnable` outside of VSCode.  That succeeds, but then when I startup VSCode in that directory, VSCode acts like the build still needs to be imported.  I'll even run `bloop compile --cascade root -w` beforehand.  

Could you expand a little on what exactly metalsEnable *does*?  Shouldn't VSCode just connect to the build server automatically and not need an additional metalsEnable?  How does VSCode determine that a re-import is needed?

**Comment by olafurpg** [comment]
A workaround for now is to do the build import manually from the terminal and select "Don't show again" when Metals prompts to import the build.

The error

```
java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 17
```
Indicates Metals is unable to launch a system process using https://github.com/brettwooldridge/NuProcess

**Comment by olafurpg** [comment]
What happens if you upgrade to the latest Java 11?

**Comment by matthughes** [comment]
I upgraded to latest adoptopenjdk:

```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
```

* Quit VSCode.  
* Stopped bloop.  
* Deleted .metals .bloop
* restarted bloop
* Opened VSCode (updated JAVA_HOME setting before quitting)
* Import build failed again with:

```



INFO  time: initialize in 1.38s
WARN  no build target: /Users/mhughe008/development/vise/project/server/src/main/scala/com/corp/project/server/Metas.scala
INFO  running '/usr/local/bin/sbt -sbt-dir /Users/mhughe008/.sbtenv/vise -ivy /Users/mhughe008/.sbtenv/vise/ivy2 -mem 4098 metalsEnable bloopInstall'
Oct 22, 2019 2:07:30 PM com.zaxxer.nuprocess.osx.OsxProcess start
WARNING: Exception thrown from handler
java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 2
	at com.zaxxer.nuprocess.internal.BasePosixProcess.checkReturnCode(BasePosixProcess.java:639)
	at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:85)
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at scala.meta.internal.metals.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:80)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:55)
	at scala.meta.internal.metals.BloopInstall.$anonfun$runIfApproved$2(BloopInstall.scala:151)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

INFO  build tool exit: -2147483648
INFO  time: ran 'sbt bloopInstall' in 0.12s
ERROR sbt command failed: /usr/local/bin/sbt -sbt-dir /Users/mhughe008/.sbtenv/vise -ivy /Users/mhughe008/.sbtenv/vise/ivy2 -mem 4098 metalsEnable bloopInstall
```

**Comment by matthughes** [comment]
Now if I do everything in SBT, launch Code, and then say "Don't Show me" instead of doing the import as prompted, everything seems to be happy.

**Comment by jvican** [comment]
@matthughes can you run or test with bloop? Bloop also uses nuprocess, if you don’t get the same exception then fixing the nuprocess version in Metals might help.

**Comment by matthughes** [comment]
@jvican `bloop test` works fine from CLI.

**Comment by olafurpg** [comment]
Weird, Metals seems to be using the same version of nuprocess as Bloop
```
07:51:58 ❯ cs fetch ch.epfl.scala:bloop-frontend_2.12:latest.stable | grep nuprocess
/Users/lgeirsson/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4.jar
07:52:01 ❯ cs fetch org.scalameta:metals_2.12:latest.stable | grep nuprocess
/Users/lgeirsson/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4.jar
```

**Comment by tgodzik** [comment]
@olafurpg is it possible to replace running nuprocess with normal Java Process? This is not the first time we're having issues with it.

**Comment by olafurpg** [comment]
It's worth looking into if someone is motivated to work on it and we're able to preserve the following features with `j.l.ProcessBuilder`

* `Future[BloopInstallResult]` signature
* streaming stdout/stderr console output
* cancellation

**Comment by tgodzik** [comment]
For now the solution in this case is to run from CLI and not import via Metals.

Additionally, you can just manually add Bloop plugin and add `bloopExportJarClassifiers.in(Global) := Some(Set("sources"))` - later you need only to run `sbt bloopInstall` if anything like dependencies or project structure changes.

I think best would be to use the default Java Process, but with the features mentioned above by Olaf:

> Future[BloopInstallResult] signature
> streaming stdout/stderr console output
> cancellation
