### ISSUE TITLE
Code lenses are not appearing in a test class

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1024]
**Describe the bug**
For example in CompletionLspSuite is throwing for me:
```
Oct 28, 2019 10:49:17 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 5 is not a valid line number, allowed [0..0]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 5 is not a valid line number, allowed [0..0]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:38)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:36)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 5 is not a valid line number, allowed [0..0]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:30)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:26)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:74)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:58)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionLspRange.toMeta(MtagsEnrichments.scala:285)
	at scala.meta.internal.metals.TokenEditDistance.toRevised(TokenEditDistance.scala:48)
	at scala.meta.internal.metals.CodeLensProvider.$anonfun$codeLenses$7(CodeLensProvider.scala:65)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.CodeLensProvider.$anonfun$codeLenses$6(CodeLensProvider.scala:65)
	at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:858)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:857)
	at scala.meta.internal.metals.CodeLensProvider.codeLenses(CodeLensProvider.scala:49)
	at scala.meta.internal.metals.CodeLensProvider.$anonfun$findLenses$3(CodeLensProvider.scala:30)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more
```

Might be corrupted state, but that stacktrace is enough to try to figure out the situation.

**To Reproduce**
1. Open Metals in VS Code
2. Go to CompletionLspSuite
3. No lenses appear.

**Expected behavior**
Code lenses appear.

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: 0.7.6+133-ddafe058-SNAPSHOT

**Additional context**

**Search terms**
lenses run test

**Comment by olafurpg** [comment]
The error ` 5 is not a valid line number, allowed [0..0]` indicates that the `Input` is empty (we don't have any source code associated with that file)

**Comment by tgodzik** [comment]
> The error ` 5 is not a valid line number, allowed [0..0]` indicates that the `Input` is empty (we don't have any source code associated with that file)

Weirdly enough, that happened on an existing file :O I think I need to add some better info to the exception, since it happens from time to time.

**Comment by olafurpg** [comment]
It could be caused by a bug in `Md5Fingerprints`, which we use to map from `TextDocument.md5` digests into source code 🤔

**Comment by tgodzik** [comment]
```scala
override def lookupText(path: AbsolutePath, md5: String): Option[String] = {
    for {
      prints <- Option(fingerprints.get(path))
      fingerprint <- prints.asScala.find(_.md5 == md5)
    } yield {
      prints.add(fingerprint)
      fingerprint.text
    }
  }
```

Hmm... not sure why we add fingerprint here - we will always find the earlier one, no? And in case of a collision, we will always find an old version. Could that be a cause?

**Comment by tgodzik** [comment]
Actually, might be connected to the fact that I had some files renamed and now I am also getting some exceptions:

```
ERROR text document: file:///home/tgodzik/Documents/scalameta/metals/mtags/src/main/scala/scala/meta/internal/metals/FoldingRangeExtractor.scala
java.nio.file.NoSuchFileException: /home/tgodzik/Documents/scalameta/metals/mtags/src/main/scala/scala/meta/internal/metals/FoldingRangeExtractor.scala
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.Semanticdbs$.loadResolvedTextDocument(Semanticdbs.scala:69)
	at scala.meta.internal.mtags.Semanticdbs$.loadTextDocument(Semanticdbs.scala:51)
	at scala.meta.internal.metals.FileSystemSemanticdbs.textDocument(FileSystemSemanticdbs.scala:32)
	at scala.meta.internal.metals.AggregateSemanticdbs.loop$1(AggregateSemanticdbs.scala:28)
	at scala.meta.internal.metals.AggregateSemanticdbs.textDocument(AggregateSemanticdbs.scala:34)
	at scala.meta.internal.metals.ReferenceProvider.$anonfun$references$4(ReferenceProvider.scala:213)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:488)
	at scala.collection.Iterator.toStream(Iterator.scala:1415)
	at scala.collection.Iterator.toStream$(Iterator.scala:1414)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1429)
	at scala.collection.TraversableOnce.toSeq(TraversableOnce.scala:303)
	at scala.collection.TraversableOnce.toSeq$(TraversableOnce.scala:303)
	at scala.collection.AbstractIterator.toSeq(Iterator.scala:1429)
	at scala.meta.internal.metals.ReferenceProvider.references(ReferenceProvider.scala:237)
	at scala.meta.internal.metals.ReferenceProvider.references(ReferenceProvider.scala:82)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$compileAndLookForNewReferences$1(MetalsLanguageServer.scala:946)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$compileAndLookForNewReferences$1$adapted(MetalsLanguageServer.scala:922)
	at scala.util.Success.foreach(Try.scala:253)
	at scala.concurrent.Future.$anonfun$foreach$1$adapted(Future.scala:229)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tgodzik** [comment]
I am closing this until we can get a proper repro.
