### ISSUE TITLE
Illegal argument exception -- object is not an instance of declaring class

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1036]
**Describe the bug**
I noticed this bug with the latest SNAPSHOT and also when I'm currently publishLocal'ing the master branch. I can use 0.7.6 just fine on a brand new hello world project, but with the newest snapshot I'll get the stacktrace in the gist below. After getting it, if I switch back to 0.7.6, everything works as expected.

**To Reproduce**
1. Download latest SNAPSHOT
2. Open a new project and the server fails to start

**Stacktrace**
https://gist.github.com/ckipp01/94b2c6f3ca0ab061cb9daf5eabd48a5d

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code and Vim
- Metals version: v0.7.6+177-220578cd-SNAPSHOT and local build

**Additional context**
I also saw on the Discord that someone else was receiving this same message on the latest snapshot https://discordapp.com/channels/632642981228314653/632652693013528589/639208978408276008

**Comment by olafurpg** [comment]
Thank you for reporting! This looks like a regression from https://github.com/scalameta/metals/pull/1019 cc/  @marek1840 
```
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:112)
	at com.sun.proxy.$Proxy6.configure(Unknown Source)
	at scala.meta.internal.metals.DelegatingLanguageClient.configure(DelegatingLanguageClient.scala:41)
```

**Comment by olafurpg** [comment]
This seems to happen on JDK 11, we should probably start running CI in Java 11 🤔 It might be enough to only compile the sources with Java 8 so we don't double the CI runtime...

**Comment by ckipp01** [comment]
> This seems to happen on JDK 11
I actually had it happen to me on 8 and 11.
