### ISSUE TITLE
VS Code: The Metals server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by lakshmanmallidi** [scalameta/metals#1085]
I am facing a issue with metals with vs code. I am under corporate proxy with authentication. I have set proxy flags accordingly. I am getting following error from global log file. 

`INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\scalameta\metals\cache\lsp.trace.json
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 7: WARNING: (0) : No source files specified\bsp\data
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at scala.meta.io.AbsolutePath$.apply(AbsolutePath.scala:60)
	at scala.meta.internal.metals.BspServers$.$anonfun$globalInstallDirectories$1(BspServers.scala:172)
	at scala.collection.immutable.List.map(List.scala:290)
	at scala.meta.internal.metals.BspServers$.globalInstallDirectories(BspServers.scala:172)
	at scala.meta.internal.metals.MetalsLanguageServer$.$lessinit$greater$default$8(MetalsLanguageServer.scala:61)
	at scala.meta.metals.Main$.main(Main.scala:23)
	at scala.meta.metals.Main.main(Main.scala)`

please help with the issue.

**Comment by tgodzik** [comment]
Hi, thanks for reporting - this looks like an issue with a Windows path. Doesn't seem to be related to proxy exactly. Would you be able to post the metals.log file or at least a bigger part of it with the exception?

**Comment by lakshmanmallidi** [comment]
The same exception I posted above keep on repeating. There's no other log in log file. In vscode I am able to find following output log

`Java home: C:\Program Files\Java\jdk1.8.0_202
[Info  - 3:45:42 PM] Connection to server got closed. Server will restart.
[Info  - 3:45:49 PM] Connection to server got closed. Server will restart.
[Info  - 3:45:56 PM] Connection to server got closed. Server will restart.
[Info  - 3:46:03 PM] Connection to server got closed. Server will restart.
[Error - 3:46:10 PM] Connection to server got closed. Server will not be restarted.`

More log data in global.log file looks like

`INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\scalameta\metals\cache\lsp.trace.json
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 7: WARNING: (0) : No source files specified\bsp\data
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at scala.meta.io.AbsolutePath$.apply(AbsolutePath.scala:60)
	at scala.meta.internal.metals.BspServers$.$anonfun$globalInstallDirectories$1(BspServers.scala:172)
	at scala.collection.immutable.List.map(List.scala:290)
	at scala.meta.internal.metals.BspServers$.globalInstallDirectories(BspServers.scala:172)
	at scala.meta.internal.metals.MetalsLanguageServer$.$lessinit$greater$default$8(MetalsLanguageServer.scala:61)
	at scala.meta.metals.Main$.main(Main.scala:23)
	at scala.meta.metals.Main.main(Main.scala)
INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\scalameta\metals\cache\lsp.trace.json
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 7: WARNING: (0) : No source files specified\bsp\data
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at scala.meta.io.AbsolutePath$.apply(AbsolutePath.scala:60)
	at scala.meta.internal.metals.BspServers$.$anonfun$globalInstallDirectories$1(BspServers.scala:172)
	at scala.collection.immutable.List.map(List.scala:290)
	at scala.meta.internal.metals.BspServers$.globalInstallDirectories(BspServers.scala:172)
	at scala.meta.internal.metals.MetalsLanguageServer$.$lessinit$greater$default$8(MetalsLanguageServer.scala:61)
	at scala.meta.metals.Main$.main(Main.scala:23)
	at scala.meta.metals.Main.main(Main.scala)
INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\scalameta\metals\cache\lsp.trace.json
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 7: WARNING: (0) : No source files specified\bsp\data
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at scala.meta.io.AbsolutePath$.apply(AbsolutePath.scala:60)
	at scala.meta.internal.metals.BspServers$.$anonfun$globalInstallDirectories$1(BspServers.scala:172)
	at scala.collection.immutable.List.map(List.scala:290)
	at scala.meta.internal.metals.BspServers$.globalInstallDirectories(BspServers.scala:172)
	at scala.meta.internal.metals.MetalsLanguageServer$.$lessinit$greater$default$8(MetalsLanguageServer.scala:61)
	at scala.meta.metals.Main$.main(Main.scala:23)
	at scala.meta.metals.Main.main(Main.scala)
INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\scalameta\metals\cache\lsp.trace.json
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 7: WARNING: (0) : No source files specified\bsp\data
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at scala.meta.io.AbsolutePath$.apply(AbsolutePath.scala:60)
	at scala.meta.internal.metals.BspServers$.$anonfun$globalInstallDirectories$1(BspServers.scala:172)
	at scala.collection.immutable.List.map(List.scala:290)
	at scala.meta.internal.metals.BspServers$.globalInstallDirectories(BspServers.scala:172)
	at scala.meta.internal.metals.MetalsLanguageServer$.$lessinit$greater$default$8(MetalsLanguageServer.scala:61)
	at scala.meta.metals.Main$.main(Main.scala:23)
	at scala.meta.metals.Main.main(Main.scala)
INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\scalameta\metals\cache\lsp.trace.json
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 7: WARNING: (0) : No source files specified\bsp\data
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at scala.meta.io.AbsolutePath$.apply(AbsolutePath.scala:60)
	at scala.meta.internal.metals.BspServers$.$anonfun$globalInstallDirectories$1(BspServers.scala:172)
	at scala.collection.immutable.List.map(List.scala:290)
	at scala.meta.internal.metals.BspServers$.globalInstallDirectories(BspServers.scala:172)
	at scala.meta.internal.metals.MetalsLanguageServer$.$lessinit$greater$default$8(MetalsLanguageServer.scala:61)
	at scala.meta.metals.Main$.main(Main.scala:23)
	at scala.meta.metals.Main.main(Main.scala)
. . .
. . .
. . .
`

**Comment by olafurpg** [comment]
@lakshmanmallidi what version of Windows are you using?

**Comment by lakshmanmallidi** [comment]
using windows 10. Both metals and vscode are under corporate proxy. vscode is running under user level permissions.

**Comment by lakshmanmallidi** [comment]
vscode verison is 1.38.1 x64

**Comment by olafurpg** [comment]
@lakshmanmallidi can you check what output is provided by the jvm-directories library on your computer?

Using the Scala REPL and Coursier

```
$ scala -cp $(coursier fetch io.github.soc:directories:11)
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala> io.github.soc.directories.ProjectDirectories.fromPath("bsp")
res0: io.github.soc.directories.ProjectDirectories =
ProjectDirectories (Mac OS X):
  projectPath  = 'bsp'
  cacheDir     = '/Users/lgeirsson/Library/Caches/bsp'
  configDir    = '/Users/lgeirsson/Library/Preferences/bsp'
  dataDir      = '/Users/lgeirsson/Library/Application Support/bsp'
  dataLocalDir = '/Users/lgeirsson/Library/Application Support/bsp'
  runtimeDir   = 'null'
```

**Comment by lakshmanmallidi** [comment]
`ProjectDirectories (Windows 10):
  projectPath  = 'bsp'
  cacheDir     = '\bsp\cache'
  configDir    = 'WARNING: (0) : No source files specified\bsp\config'
  dataDir      = 'WARNING: (0) : No source files specified\bsp\data'
  dataLocalDir = '\bsp\data'
  runtimeDir   = 'null'`

**Comment by lakshmanmallidi** [comment]
ProjectDirectories (Windows 10):
  projectPath  = 'bsp'
  cacheDir     = '\bsp\cache'
  configDir    = 'WARNING: (0) : No source files specified\bsp\config'
  dataDir      = 'WARNING: (0) : No source files specified\bsp\data'
  dataLocalDir = '\bsp\data'
  runtimeDir   = 'null'

**Comment by olafurpg** [comment]
@lakshmanmallidi in what directory would you expect global log files to live for Metals? By default, we use jvm-directories (https://github.com/soc/directories-jvm) which uses the KNOWNFOLDERID API on Windows (https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid)

**Comment by lakshmanmallidi** [comment]
In mycase 
`configDir = 'WARNING: (0) : No source files specified\bsp\config'`

That is why i think i am getting path error as there is `:` symbol after warning in path

`"main" java.nio.file.InvalidPathException: Illegal char <:> at index 7: WARNING: (0) : No source files specified\bsp\data`

**Comment by lakshmanmallidi** [comment]
I don't have any idea why a `WARNING: (0) : No source files specified` is appending to my `configDir` path.

**Comment by olafurpg** [comment]
@lakshmanmallidi i don’t know why it’s failing either but we can fallback to another directory in Metals when the jvm-directories library fails. Any suggestion for what that fallback should be?

 Alternatively, please report an issue to the jvm-directories library with the output from your repl.

**Comment by lakshmanmallidi** [comment]
I suggest to use user home directory as fallback directory. I will also check with jvm-directories library about the issue.

**Comment by olafurpg** [comment]
@lakshmanmallidi thank you for reporting the issue to jvm-directories. I opened #1123 making Metals gracefully handle this situation when the global config directory cannot be found. This should not impact the functionality of Metals on your computer.
