### ISSUE TITLE
NullPointerException in DebugProxy

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1154]
**Describe the bug**

While using Metals with Bloop 1.3.4+251-1d81dfe5 I get the following exception in `.metals/metals.log`

```
SEVERE: An error occurred while processing an incoming message.
java.lang.NullPointerException
        at scala.meta.internal.metals.debug.EndpointLogger.log(EndpointLogger.scala:40)
        at scala.meta.internal.metals.debug.EndpointLogger.consume(EndpointLogger.scala:26)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleClientMessage$1(DebugProxy.scala:50)
        at scala.meta.internal.metals.debug.EndpointLogger.$anonfun$listen$1(EndpointLogger.scala:33)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
```

**Expected behavior**

I expected there to be no NullPointerException in the logs.

**Comment by olafurpg** [comment]
Upcoming fix in #935
