### ISSUE TITLE
Errors on the latest snapshot

### ISSUE THREAD

**Issue by iravid** [scalameta/metals#1226]
**Describe the bug**
Getting the following errors in metals.log:
```
INFO  compiling zio-analytics (7 scala sources)
ERROR /Users/iravid/Library/Caches/bloop/semanticdb/org.scalameta.semanticdb-scalac_2.12.10.4.3.0/semanticdb-scalac_2.12.10-4.3.0.jar
java.nio.file.FileSystemNotFoundException: /Users/iravid/Library/Caches/bloop/semanticdb/org.scalameta.semanticdb-scalac_2.12.10.4.3.0/semanticdb-scalac_2.12.10-4.3.0.jar
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:120)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:103)
	at scala.meta.internal.io.PlatformFileIO$.newJarFileSystem(PlatformFileIO.scala:99)
	at scala.meta.internal.io.PlatformFileIO$.withJarFileSystem(PlatformFileIO.scala:76)
	at scala.meta.internal.io.FileIO$.withJarFileSystem(FileIO.scala:43)
	at scala.meta.internal.metals.CompilerPlugins.liftedTree1$1(CompilerPlugins.scala:63)
	at scala.meta.internal.metals.CompilerPlugins.isSupportedPlugin(CompilerPlugins.scala:62)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$2(CompilerPlugins.scala:44)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1(CompilerPlugins.scala:44)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1$adapted(CompilerPlugins.scala:41)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:256)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:255)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:249)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:347)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:347)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at scala.meta.internal.metals.CompilerPlugins.filterSupportedOptions(CompilerPlugins.scala:41)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:287)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$10(Compilers.scala:238)
	at scala.meta.internal.metals.StatusBar.trackBlockingTask(StatusBar.scala:44)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$9(Compilers.scala:238)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$8(Compilers.scala:234)
	at scala.Option.map(Option.scala:230)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$7(Compilers.scala:231)
	at scala.Option$WithFilter.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$3(Compilers.scala:223)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.loadCompiler(Compilers.scala:222)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3(Compilers.scala:96)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3$adapted(Compilers.scala:95)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.Compilers.$anonfun$load$1(Compilers.scala:95)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

INFO  time: compiled zio-analytics in 19ms
ERROR Unexpected error when compiling zio-analytics: 'xsbt.CompilerInterface'
ERROR Failed to compile 'zio-analytics','zio-analytics-test'
```

Subsequently, features like jump to definition and show type at point do not work.

**To Reproduce**
Using the latest snapshot, try to import github.com/zio/zio-analytics.

**Installation:**
- Operating system: macOS
- Editor: Emacs
- Metals version: 0.7.6+630-b4fc5955-SNAPSHOT

**Comment by iravid** [comment]
Actually, this also happens with 0.7.6.

**Comment by iravid** [comment]
Ok, I think I had a rogue bloop server running. Or something.

After installing the bloop CLI, this is what I was getting when compiling:
```
iravid:zio-analytics/ (master✗) $ bloop compile zio-analytics --verbose                                                                      [8:15:36]
[D] Computing sources and classpath hashes for zio-analytics
[D] Scheduling compilation for zio-analytics...
[D] Ignoring analysis for zio-analytics, directory /Users/iravid/Development/personal/zio-analytics/.bloop/zio-analytics/scala-2.12/classes-empty-zio-analytics is missing
[D] Increasing counter for /Users/iravid/Development/personal/zio-analytics/.bloop/zio-analytics/scala-2.12/classes-empty-zio-analytics to 1
[D] Disabled compiler plugin classloading, unsupported in 2.12.1
[D] External classes directory /Users/iravid/Development/personal/zio-analytics/.bloop/zio-analytics/scala-2.12/classes
[D] Read-only classes directory /Users/iravid/Development/personal/zio-analytics/.bloop/zio-analytics/scala-2.12/classes-empty-zio-analytics
[D] New rw classes directory /Users/iravid/Development/personal/zio-analytics/.bloop/zio-analytics/scala-2.12/bloop-internal-classes/classes-pXbvE3G_RzKPzQ3YaFw0hQ==
[D] No previous setup found, invalidating everything.
[D] Full compilation, no sources in previous analysis.
[D] All sources are invalidated.
[D] Initial set of included nodes:
[D] Recompiling all sources: number of invalidated sources > 50.0% of all sources
Compiling zio-analytics (7 Scala sources)
[D] Returning already retrieved and compiled bridge: /Users/iravid/Library/Caches/bloop/components/ch.epfl.scala-compiler-bridge_2.12-1.3.0-M4+26-045d2c8c-bin_2.12.10__52.0/ch.epfl.scala-compiler-bridge_2.12-1.3.0-M4+26-045d2c8c-bin_2.12.10__52.0.jar.
Compiled zio-analytics (0ms)
[E] Unexpected error when compiling zio-analytics: 'xsbt.CompilerInterface'
[T] java.lang.ClassNotFoundException: xsbt.CompilerInterface
[T]     java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[T]     java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[T]     java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[T]     java.lang.Class.forName0(Native Method)
[T]     java.lang.Class.forName(Class.java:348)
[T]     sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:282)
[T]     sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:249)
[T]     sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:144)
[T]     sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:131)
[T]     sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:100)
[T]     sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[T]     sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:129)
[T]     sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$7(BloopHighLevelCompiler.scala:147)
[T]     scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[T]     sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:72)
[T]     bloop.tracing.BraveTracer.trace(BraveTracer.scala:31)
[T]     sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:71)
[T]     sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$6(BloopHighLevelCompiler.scala:147)
[T]     scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[T]     monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
[T]     monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
[T]     monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
[T]     java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[T]     java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[T]     java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[T]     java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[T]     java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[E] Failed to compile 'zio-analytics'
[D] Elapsed: 10.815475 ms
```

The folder `/Users/iravid/Library/Caches/bloop` did not exist, so I killed the existing server, which I think was started by metals. I then started the server installed through homebrew (`brew services start scalacenter/bloop/bloop`), and then compilation started working again. 🤷🏽‍♂️
