### ISSUE TITLE
TimeoutException & download error on build\initialize

### ISSUE THREAD

**Issue by mrt181** [scalameta/metals#1301]
**Describe the bug**
When VS Code starts I get the following output

```log
Java home: C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\
Using JVM options set in c:\Users\itisme\repos\gtm\skynet\.jvmopts
INFO  logging to file C:\Users\itisme\repos\gtm\skynet\.metals\metals.log
INFO  started: Metals version 0.8.0 in workspace 'C:\Users\itisme\repos\gtm\skynet'
INFO  time: initialize in 0.88s
Initializing Scala Debugger
INFO  skipping build import with status 'Installed'
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\itisme\AppData\Local\scalameta\metals\cache\bsp.trace.json
ERROR Timeout waiting for 'build/initialize' response
ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:259)
	at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:203)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)

WARN  Stopped configuration of SemanticDB in Scala 2.13.1 projects: Error downloading org.scalameta:semanticdb-scalac_2.13.1:4.3.0
  not found: C:\Users\itisme\.ivy2\local\org.scalameta\semanticdb-scalac_2.13.1\4.3.0\ivys\ivy.xml
  download error: Caught java.net.ConnectException: Connection timed out: connect (Connection timed out: connect) while downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.1/4.3.0/semanticdb-scalac_2.13.1-4.3.0.pom
  not found: https://dl.bintray.com/scalacenter/releases/org/scalameta/semanticdb-scalac_2.13.1/4.3.0/semanticdb-scalac_2.13.1-4.3.0.pom
```

**To Reproduce**
1. Delete any `.bloop` and `.metals` directories
2. Configure proxy in `.jvmopts`
3. Configure  `metals.customRepositories` to use corp repo
4. Start VS Code in a scala project directory
5. Open Output view for Metals
6. See error

**Expected behavior**
- build\initialize should not time out
- semanticdb download should use metals.customRepositories config instead of direct Internet connection (can cause proxy issues, like missing auth)

**Installation:**
- Operating system: Windows 10
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Search terms**
0.8.0 TimeoutException SemanticDB download Error

**Comment by tgodzik** [comment]
@mrt181 Thanks for reporting! Are you using Bloop started by Metals or something run separately?

**Comment by mrt181** [comment]
Bloop started by metals

**Comment by tgodzik** [comment]
Alright, I think I know what's going on. You could try to set mirrors for now:
```
Mirrors
coursier got support for mirrors, kind of like Maven has. Mirrors allow to substitute some repositories for others. This can be useful with internal Maven repositories mirroring Maven Central for example. In that case, you'd prefer requests to go to that mirror rather than to Maven Central.

Mirrors are automatically picked from the API (unless explicitly disabled) and the CLI.

They can be configured via configuration files, namely ~/.config/coursier/mirror.properties on Linux, and ~/Library/Preferences/Coursier/mirror.properties on OS X. For example, these settings allow to replace Maven Central with JCenter

jcenter.from=https://repo1.maven.org/maven2
jcenter.to=https://jcenter.bintray.com
Mirrors should be described in more detail in the coursier documentation in a later time.
```
They should be picked up automatically since Bloop uses coursier to resolve semanticDB.

In the meantime I will see how we can reuse  custom repositories

**Comment by tgodzik** [comment]
@jvican any idea how to best forward coursier repositories for BloopLauncher? I am considering adding the additional server system property while running via BloopLauncher and then reading it in the SemanticDBCache.

**Comment by tgodzik** [comment]
Or actually `coursier.repositories` should work too - I will create a PR.

**Comment by mrt181** [comment]
where should I place `mirror.properties` or `coursier.properties` on Win10?
would this work?
```properties
central.from=https://repo1.maven.org/maven2
central.to=http://ecorp.com:8080/nexus/content/groups/public
```
Will this fix the `ERROR Timeout waiting for 'build/initialize' response` too?

**Comment by tgodzik** [comment]
> where should I place `mirror.properties` or `coursier.properties` on Win10?
> would this work?
> 

I would try `%USER_HOME%/.config/coursier/mirror.properties` I will try to dig a bit more.

> ```ini
> central.from=https://repo1.maven.org/maven2
> central.to=http://ecorp.com:8080/nexus/content/groups/public
> ```

That should work.

**Comment by tgodzik** [comment]
Cousier uses `https://github.com/soc/directories-jvm`, so the config directory should be something like:
`// Win: C:\Users\Alice\AppData\Roaming\Coursier\config`

**Comment by mrt181** [comment]
ok, the Alice path is correct and I can progress further.
When I started vs code it downloaded 37 files but I get this now:

```log
INFO  [success] Generated .bloop\root.json
INFO  [success] Generated .bloop\root-test.json
INFO  [success] Total time: 2 s, completed 14.01.2020, 15:50:04
INFO  build tool exit: 0
INFO  time: ran 'sbt bloopInstall' in 14s
INFO  tracing is enabled: C:\Users\itisme\AppData\Local\scalameta\metals\cache\bsp.trace.json
INFO  time: connected to build server in 0.44s
INFO  Connected to Build server v1.4.0-RC1
INFO  time: indexed workspace in 4.61s
INFO  compiling root (110 scala sources)
```
and VS code is stuck at `Compiling root XmYs (15%)`

when i <ctrl> hover over something in my code I get this:
```
ERROR code navigation does not work for the file 'C:\Users\itisme\repos\gtm\skynet\src\main\scala\com\ecorp\skynet\Main.scala' because the SemanticDB file 'C:\Users\itisme\repos\gtm\skynet\.bloop\root\bloop-bsp-clients-classes\classes-Metals-JR9lYpWVT7qbLm_UfO4nWQ==\META-INF\semanticdb\src\main\scala\com\ecorp\skynet\Main.scala.semanticdb' doesn't exist. There can be many reasons for this error. 
ERROR code navigation does not work for the file 'C:\Users\itisme\repos\gtm\skynet\src\main\scala\com\ecorp\skynet\Main.scala' because the SemanticDB file 'C:\Users\itisme\repos\gtm\skynet\.bloop\root\bloop-bsp-clients-classes\classes-Metals-JR9lYpWVT7qbLm_UfO4nWQ==\META-INF\semanticdb\src\main\scala\com\ecorp\skynet\Main.scala.semanticdb' doesn't exist. There can be many reasons for this error. 
```

**Comment by tgodzik** [comment]
For everything to work properly we need to compile the workspace - that will produce the needed semanticDB files.

However, if the compilation is not progressing that might be an issue.

**Comment by mrt181** [comment]
I was able to fix the compilation problem by changing proxy settings...

**Comment by tgodzik** [comment]
> I was able to fix the compilation problem by changing proxy settings...

IT's the same issue as https://github.com/scalameta/metals/issues/1315

Closing this one in favour of the other one.
