### ISSUE TITLE
Debug cannot start with breakpoint

### ISSUE THREAD

**Issue by ZZYSonny** [scalameta/metals#1334]
**Describe the bug**

**To Reproduce**
1. Go to a working scala folder and open a scala file
2. Add some breakpoint and click on 'debug'
3. See error

**Expected behavior**

**Screenshots**

No highlight of current running line
![image](https://user-images.githubusercontent.com/28442838/72758883-f8fdbd80-3bcb-11ea-958d-590d402fd4c7.png)
Works if there's no breakpoint when debugging or using Run
![image](https://user-images.githubusercontent.com/28442838/72758934-1763b900-3bcc-11ea-801d-5450ed180e10.png)

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**

Log that sometimes appears after I click debug
> Jan 20, 2020 9:33:00 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: Illegal character in authority at index 7: file://c:\Users\zhaoz\Documents\Code\Scala\src\main\scala\Main.scala
java.lang.IllegalArgumentException: Illegal character in authority at index 7: file://c:\Users\zhaoz\Documents\Code\Scala\src\main\scala\Main.scala
	at java.base/java.net.URI.create(URI.java:883)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:413)
	at scala.meta.internal.metals.debug.SetBreakpointsRequestHandler.apply(SetBreakpointsRequestHandler.scala:24)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleClientMessage$1(DebugProxy.scala:75)
	at scala.meta.internal.metals.debug.MessageIdAdapter.$anonfun$listen$1(MessageIdAdapter.scala:54)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at scala.meta.internal.metals.debug.SocketEndpoint.listen(SocketEndpoint.scala:24)
	at scala.meta.internal.metals.debug.MessageIdAdapter.listen(MessageIdAdapter.scala:44)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$listenToClient$1(DebugProxy.scala:45)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: file://c:\Users\zhaoz\Documents\Code\Scala\src\main\scala\Main.scala
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3249)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3160)
	at java.base/java.net.URI$Parser.parse(URI.java:3116)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	... 20 more

**Search terms**

**Comment by marek1840** [comment]
Thanks for reporting!

The issue seems to be related to how we handle creation of `URI`:
`java.net.URI.create("file://c:\\Users\\zhaoz\\Documents\\Code\\Scala\\src\\main\\scala\\Main.scala")`
fails with the reported error: `java.net.URISyntaxException: Illegal character in authority at index 7`

The error goes away when we replace `\\` with `/`:
`java.net.URI.create("file://C:/Users/zhaoz/Documents/Code/Scala/src/main/scala/Main.scala")`

**Comment by ZZYSonny** [comment]
I just tried  0.8.0+66-2c63fb7c-SNAPSHOT version of Metal server. I still cannot debug. This is the new log.

Jan 23, 2020 10:10:33 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: \\c\Users\zhaoz\Documents\Code\Scala\src\main\scala\test.scala: The network path was not found.

java.nio.file.FileSystemException: \\c\Users\zhaoz\Documents\Code\Scala\src\main\scala\test.scala: The network path was not found.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionAbsolutePathMetals.toInput(MtagsEnrichments.scala:168)
	at scala.meta.internal.metals.debug.SetBreakpointsRequestHandler.apply(SetBreakpointsRequestHandler.scala:26)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleClientMessage$1(DebugProxy.scala:75)
	at scala.meta.internal.metals.debug.MessageIdAdapter.$anonfun$listen$1(MessageIdAdapter.scala:54)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at scala.meta.internal.metals.debug.SocketEndpoint.listen(SocketEndpoint.scala:24)
	at scala.meta.internal.metals.debug.MessageIdAdapter.listen(MessageIdAdapter.scala:44)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$listenToClient$1(DebugProxy.scala:45)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by tgodzik** [comment]
My bad, should have tested it on windows. Let me try again.
