### ISSUE TITLE
Scala project import is breaking [vscode]

### ISSUE THREAD

**Issue by abhishekvaid** [scalameta/metals#1369]
I downloaded the given project in Coursera course "Function Programming Principles in Scala", Week 4 standard project. [SBT]. The plugin detects the project, tries to import but fails with a ribbon message [Import project failed, no functionality will work, see the logs for m... ]

Here's the output in Output window:

```
Java home: /Library/Java/JavaVirtualMachines/jdk-11.0.4.jdk/Contents/Home
INFO  logging to file /Users/abhishekvaid/Dropbox/moocs/coursera/scala_specialization/01_functional_programming_principles/week_03/objsets/.metals/metals.log
INFO  started: Metals version 0.8.0 in workspace '/Users/abhishekvaid/Dropbox/moocs/coursera/scala_specialization/01_functional_programming_principles/week_03/objsets'
INFO  time: initialize in 1.45s
Initializing Scala Debugger
WARN  no build target for: /Users/abhishekvaid/Dropbox/moocs/coursera/scala_specialization/01_functional_programming_principles/week_03/objsets/src/main/scala/objsets/TweetSet.scala
INFO  running '/Library/Java/JavaVirtualMachines/jdk-11.0.4.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/f8/9f78kgk50jjd3d08h9hdqz_m0000gp/T/metals6700107151706146295/sbt-launch.jar set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall'
INFO  [info] Loading global plugins from /Users/abhishekvaid/.sbt/0.13/plugins
ERROR WARNING: An illegal reflective access operation has occurred
ERROR WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/Users/abhishekvaid/.sbt/boot/scala-2.10.7/org.scala-sbt/sbt/0.13.17/ivy-0.13.17.jar) to field java.net.Authenticator.theAuthenticator
ERROR WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
ERROR WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
ERROR WARNING: All illegal access operations will be denied in a future release
INFO  [info] Loading project definition from /Users/abhishekvaid/Dropbox/moocs/coursera/scala_specialization/01_functional_programming_principles/week_03/objsets/project
INFO  [info] Compiling 8 Scala sources to /Users/abhishekvaid/Dropbox/moocs/coursera/scala_specialization/01_functional_programming_principles/week_03/objsets/project/target/scala-2.10/sbt-0.13/classes...
INFO  [warn] /Users/abhishekvaid/Dropbox/moocs/coursera/scala_specialization/01_functional_programming_principles/week_03/objsets/project/CommonBuild.scala:3: trait Build in package sbt is deprecated: Use .sbt format instead
INFO  [warn] trait CommonBuild extends Build {
INFO  [warn]                           ^
INFO  [warn] one warning found
INFO  Reference to undefined setting: 
INFO  
INFO    it:compileIncremental from it:bloopCompile ((bloop.integrations.sbt.Offloader) Offloader.scala:19)
INFO   
INFO  	at sbt.Init$class.Uninitialized(Settings.scala:270)
INFO  	at sbt.Def$.Uninitialized(Def.scala:10)
INFO  	at sbt.Init$class.delegate(Settings.scala:191)
INFO  	at sbt.Def$.delegate(Def.scala:10)
INFO  	at sbt.Init$class.compiled(Settings.scala:138)
INFO  	at sbt.Def$.compiled(Def.scala:10)
INFO  	at sbt.Init$class.make(Settings.scala:144)
INFO  	at sbt.Def$.make(Def.scala:10)
INFO  	at sbt.Load$$anonfun$8.apply(Load.scala:161)
INFO  	at sbt.Load$$anonfun$8.apply(Load.scala:156)
INFO  	at sbt.Load$.timed(Load.scala:1025)
INFO  	at sbt.Load$.apply(Load.scala:156)
INFO  	at sbt.Load$.defaultLoad(Load.scala:39)
INFO  	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:503)
INFO  	at sbt.BuiltinCommands$.doLoadProject(Main.scala:503)
INFO  	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
INFO  	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
INFO  	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
INFO  	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
INFO  	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
INFO  	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
INFO  	at sbt.Command$.process(Command.scala:93)
INFO  	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
INFO  	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
INFO  	at sbt.State$$anon$1.runCmd$1(State.scala:183)
INFO  	at sbt.State$$anon$1.process(State.scala:187)
INFO  	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
INFO  	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
INFO  	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
INFO  	at sbt.MainLoop$.next(MainLoop.scala:96)
INFO  	at sbt.MainLoop$.run(MainLoop.scala:89)
INFO  	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
INFO  	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
INFO  	at sbt.Using.apply(Using.scala:24)
INFO  	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
INFO  	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
INFO  	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
INFO  	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
INFO  	at sbt.StandardMain$.runManaged(Main.scala:61)
INFO  	at sbt.xMain.run(Main.scala:35)
INFO  	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
INFO  	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
INFO  	at xsbt.boot.Launch$.run(Launch.scala:109)
INFO  	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
INFO  	at xsbt.boot.Launch$.launch(Launch.scala:117)
INFO  	at xsbt.boot.Launch$.apply(Launch.scala:18)
INFO  	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
INFO  	at xsbt.boot.Boot$.main(Boot.scala:18)
INFO  	at xsbt.boot.Boot.main(Boot.scala)
INFO  [error] Reference to undefined setting: 
INFO  [error] 
INFO  [error]   it:compileIncremental from it:bloopCompile ((bloop.integrations.sbt.Offloader) Offloader.scala:19)
INFO  [error]  
INFO  [error] Use 'last' for the full log.
INFO  Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
INFO  time: ran 'sbt bloopInstall' in 27s
INFO  build tool exit: 1
ERROR sbt command failed: /Library/Java/JavaVirtualMachines/jdk-11.0.4.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/f8/9f78kgk50jjd3d08h9hdqz_m0000gp/T/metals6700107151706146295/sbt-launch.jar set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall
INFO  no build target: using presentation compiler with only scala-library
```

**To Reproduce**
1. Go to Coursra -> Functional Programming Principles in Scala -> Week 4 assignment
2. Download the assignment and unzip 
3. Open the folder in vscode 
4. Observe the Error

**Comment by abhishekvaid** [comment]
I was using an old version of the project. Sorry about this.

**Comment by LangInteger** [comment]
> I was using an old version of the project. Sorry about this.

Which version you were using? Does upgrading metals fix the problem?
