### ISSUE TITLE
GitPod demo is not working

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1402]
Steps to reproduce

* open https://gitpod.io/#https://github.com/tgodzik/metals-sample
* "Import build
* "unable to connect to build server"

The logs show an error launching the Bloop server

<img width="743" alt="Screenshot 2020-02-06 at 18 37 46" src="https://user-images.githubusercontent.com/1408093/73967546-fd3a1280-490f-11ea-9bfa-a2bae2273619.png">

**Comment by tgodzik** [comment]
It looks like java is not detected by Bloop:
```
Waiting for the bsp connection to come up...
Exception in thread "bloop-server-background" java.io.IOException: Cannot run program "java" (in directory "/workspace/metals-sample"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at bloop.bloopgun.BloopgunCli.sysproc$1(Bloopgun.scala:477)
	at bloop.bloopgun.BloopgunCli.startServer(Bloopgun.scala:489)
	at bloop.bloopgun.BloopgunCli$FireInBackground$.$anonfun$fire$1(Bloopgun.scala:316)
	at bloop.bloopgun.core.Shell$$anon$2.run(Shell.scala:155)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
```

I will take a look and update the demo tomorrow.

**Comment by tgodzik** [comment]
Ok, the demo should be fixed :sweat_smile: 

@olafurpg Do we want to move it something like `scalameta/metals-demo` ?
