### ISSUE TITLE
Not properly handling moving files

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals#1404]
**Describe the bug**
When moving files in VSCode to different package there is an error showing in console output:
File `DepRename.scala` was moved from package b to package c but metals still thinks it is in package b.

```
ERROR text document: file:///Users/krzysztofbochenek/github/expr/src/main/scala/b/DepRename.scala
java.nio.file.NoSuchFileException: /Users/krzysztofbochenek/github/expr/src/main/scala/b/DepRename.scala
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.nio.file.Files.newByteChannel(Files.java:370)
	at java.nio.file.Files.newByteChannel(Files.java:421)
	at java.nio.file.Files.readAllBytes(Files.java:3205)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.Semanticdbs$.loadResolvedTextDocument(Semanticdbs.scala:69)
	at scala.meta.internal.mtags.Semanticdbs$.loadTextDocument(Semanticdbs.scala:51)
	at scala.meta.internal.metals.FileSystemSemanticdbs.textDocument(FileSystemSemanticdbs.scala:32)
	at scala.meta.internal.metals.AggregateSemanticdbs.loop$1(AggregateSemanticdbs.scala:28)
	at scala.meta.internal.metals.AggregateSemanticdbs.textDocument(AggregateSemanticdbs.scala:34)
	at scala.meta.internal.metals.ReferenceProvider.$anonfun$references$4(ReferenceProvider.scala:341)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:488)
	at scala.collection.Iterator.toStream(Iterator.scala:1415)
	at scala.collection.Iterator.toStream$(Iterator.scala:1414)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1429)
	at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1415)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
	at scala.collection.immutable.Stream.length(Stream.scala:312)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$compileAndLookForNewReferences$1(MetalsLanguageServer.scala:1061)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$compileAndLookForNewReferences$1$adapted(MetalsLanguageServer.scala:1036)
```

**To Reproduce**
1. Open any project
2. Move scala file to another directory (and change package)
3. Open Output console for Metals

**Expected behavior**
No error

**Screenshots**

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! There is already feature https://github.com/scalameta/metals-feature-requests/issues/45 

This is unblocked now since rename is already working.
