### ISSUE TITLE
"Failed to connect with build server, no functionality will work. See logs for more details."

### ISSUE THREAD

**Issue by nsadeh** [scalameta/metals#1627]
**Describe the bug**

Metals no longer works - no features work/no run/debug button displayed. Clicking "connect to build server" yields the error in the title.

This was after I worked with Metals on this project for a while and it was open on my VSCode. When I got back to it this evening nothing worked. Refreshing/restarting didn't work.

I tried deleting .metals, .bloop, and .vscode and re-import. Still doesn't work. See attached logs: [metals_logs.log](https://github.com/scalameta/metals/files/4484486/metals_logs.log). As you can see there are no error lines.

**To Reproduce**
Open a Scala project in VSCode with Metals...

**Expected behavior**

**Screenshots**

**Installation:**
- Operating system: macOS

- Editor: Visual Studio Code
- Metals version: v0.8.4

**Additional context**

**Search terms**

**Comment by nsadeh** [comment]
I opened in IntelliJ, then opened again in Metals and it worked. No idea if that's related.

Keeping it open to investigate.

**Comment by tgodzik** [comment]
Thanks for reporting! I don't see anything wrong in the logs indeed. It does seem to connect to the build server, so don't completely understand where `Failed to connect with build server, no functionality will work. See logs for more details.` comes from.

It might be connected https://github.com/scalameta/metals/issues/1465

Are you sure there was nothing int he logs about it? If you deleted `.metals` then the right logs are probably gone. I wouldn't delete `.metals` directory for sure, I haven't seen it help in any case. For most cases running `Metals: Restart Bloop server` should be enough.

**Comment by nsadeh** [comment]
I had no idea what was going wrong so I figured if there's a malformed
config file somewhere I can just restart the whole process.

I tried killing the bloop server via the command line but apparently it's
not installed. Next time I'll try the VSCode command.

I got the same error after deleting metals, and the logs looked the same
before. So I think something was missed in the logs.

**Comment by tgodzik** [comment]
If this happens again it would be extremely helpful to get some stack traces for both Bloop and Metals. 

But I think in most cases restarting Bloop should help as a short term solution. Also if you get a lot of `deduplicating messages` then it means that the `xss` value for Bloop might be too low.

**Comment by nilskp** [comment]
Not sure if this is helpful.

```log
ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.ExecutionException: Boxed InterruptedException
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:86)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.java8.FuturesConvertersImpl$P.accept(FutureConvertersImpl.scala:100)
	at scala.concurrent.java8.FuturesConvertersImpl$P.accept(FutureConvertersImpl.scala:97)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$3(BuildServerConnection.scala:145)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$2(BuildServerConnection.scala:145)
	at scala.meta.internal.metals.Cancelable$$anon$1.cancel(Cancelable.scala:17)
	at scala.meta.internal.metals.Cancelable$.$anonfun$cancelAll$1(Cancelable.scala:28)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.meta.internal.metals.Cancelable$.cancelAll(Cancelable.scala:27)
	at scala.meta.internal.metals.MutableCancelable.cancel(MutableCancelable.scala:18)
	at scala.meta.internal.metals.BuildServerConnection.cancel(BuildServerConnection.scala:116)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1(BuildServerConnection.scala:56)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1$adapted(BuildServerConnection.scala:51)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$3(BuildServerConnection.scala:145)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$2(BuildServerConnection.scala:145)
	at scala.meta.internal.metals.Cancelable$$anon$1.cancel(Cancelable.scala:17)
	at scala.meta.internal.metals.Cancelable$.$anonfun$cancelAll$1(Cancelable.scala:28)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.meta.internal.metals.Cancelable$.cancelAll(Cancelable.scala:27)
	at scala.meta.internal.metals.MutableCancelable.cancel(MutableCancelable.scala:18)
	at scala.meta.internal.metals.BuildServerConnection.cancel(BuildServerConnection.scala:116)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1(BuildServerConnection.scala:56)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1$adapted(BuildServerConnection.scala:51)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```

**Comment by tgodzik** [comment]
> Failed to connect with build server, no functionality will work.

This is actually an exception that can happen during the first compile if it get's interrupted via build server restart or shutting down Metals.

Why would the first compilation take that long is another thing altogether.

**Comment by nilskp** [comment]
I had to restart the entire OS to get this working again. Is it possible that even when VSCode is entirely shut down, that some failed process lingers?

**Comment by tgodzik** [comment]
Was there anything else in the logs? We are having some issues currently with the connection between bloop and metals, but we are working on it.

Usually you can run 'Metals: Restart Bloop server' which should help in most situations.

**Comment by tgodzik** [comment]
> I had to restart the entire OS to get this working again. Is it possible that even when VSCode is entirely shut down, that some failed process lingers?

Ach! And for sure the Bloop process stays since i'ts reused between different workspaces. That's why when having problems it might help to restart Bloop.

We are working on making sure that situation like that are really rare.

**Comment by nilskp** [comment]
@tgodzik 
Would it be possible to get that as a button in the extension view? I wasn't even aware that was possible.

Also, when I originally started using Metals in VSCode, it wasn't clear that the texts "Import build" and "Connect to build server" where effectively buttons. Is there any way to render them as such, or at least add some icon? It would probably be good to have all commands listed in the extension view, possibly separate from the Projects and Libraries?

**Comment by tgodzik** [comment]
> Would it be possible to get that as a button in the extension view? I wasn't even aware that was possible.

Sure! Good idea!

> When I originally started using Metals in VSCode, it wasn't clear that the texts "Import build" and "Connect to build server" where effectively buttons. Is there any way to render them as such, or at least add some icon? It would probably be good to have all commands listed in the extension view, possibly separate from the Projects and Libraries?

I think we should make it more clear that those are commands, we might need to rethink how we display all those menus.

**Comment by tgodzik** [comment]
There are now a number of trouble shooting options now available and I managed to localize the issue @nilskp mentioned (fixed in https://github.com/scalameta/metals/pull/1677 ). I think we are save to close it.

**Comment by tballard** [comment]
May 2022, same problem, more obfuscated maybe. Saw this post about 8 hours in and rebooted. Yup, still the cure.

**Comment by tgodzik** [comment]
https://github.com/scalameta/metals/issues/3542
