### ISSUE TITLE
vscode and metals doesn't detect build.sbt or pom.xml

### ISSUE THREAD

**Issue by virtualdvid** [scalameta/metals#1756]
**Describe the bug**
I'm starting a new `vscode` workspace. It just have one file: `build.sbt` and metals is not executing the `sbt` file or `pom.xml`.

**SBT file content:**
```
name := "Scala Playground"

version := "1.0"

scalaVersion := "2.12.11"
```

**To Reproduce**
1. Go to 'vscode - new window'
2. Click on extension 'install metals'
3. Setup root folder for workspace
4. place` build.sbt` or `pom.xml` file in root
5. Go to Metals extension and `Run Doctor`
6. There is not import

**Expected behavior**
Metals shows in the right down corner a box with the import options

**logs**

**OUTPUT terminal**
```
Java home: C:\Program Files\Java\jdk1.8.0_131
2020.05.15 16:33:36 INFO  logging to file C:\Users\S372277\damolina\github\scala_playground\.metals\metals.log
2020.05.15 16:33:36 INFO  started: Metals version 0.9.0 in workspace 'C:\Users\S372277\damolina\github\scala_playground'
2020.05.15 16:33:37 INFO  time: initialize in 0.69s
Initializing Scala Debugger
2020.05.15 16:39:42 INFO  no build target: using presentation compiler with only scala-library
```

**vscode developer tools** running `Metals: Import build`
```
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Users/S372277/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/S372277/.vscode/extensions/redhat.vscode-yaml-0.8.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
notificationsAlerts.ts:40 Command 'Metals: Import build' resulted in an error (Internal error.)
onDidChangeNotification @ notificationsAlerts.ts:40
notificationsAlerts.ts:40 Command 'Metals: Import build' resulted in an error (Internal error.)
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
error @ notificationService.ts:59
accept @ commandsQuickAccess.ts:162
processTicksAndRejections @ internal/process/task_queues.js:85
```

**Metals Doctor**
```
These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

⚠️ No build targets were detected in this workspace so most functionality won't work.

Make sure the workspace directory 'C:\Users\S372277\damolina\github\scala_playground' matches the root of your build.
Try removing the directories .metals/ and .bloop/, then restart metals And import the build again.
```

**Metals logs file**
```
2020.05.15 16:33:36 INFO  started: Metals version 0.9.0 in workspace 'C:\Users\S372277\damolina\github\scala_playground'
2020.05.15 16:33:37 INFO  time: initialize in 0.69s
May 15, 2020 4:33:38 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {}
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NumberFormatException: For input string: "<unknown>"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
	at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
	at scala.meta.internal.semver.SemVer$Version$.$anonfun$fromString$1(SemVer.scala:18)
	at scala.meta.internal.semver.SemVer$Version$.$anonfun$fromString$1$adapted(SemVer.scala:18)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at scala.meta.internal.semver.SemVer$Version$.fromString(SemVer.scala:18)
	at scala.meta.internal.semver.SemVer$.isCompatibleVersion(SemVer.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.supportedBuildTool(MetalsLanguageServer.scala:1408)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1429)
	at scala.meta.internal.metals.MetalsLanguageServer.initialized(MetalsLanguageServer.scala:648)
	... 16 more

May 15, 2020 4:35:02 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NumberFormatException: For input string: "<unknown>"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
	at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
	at scala.meta.internal.semver.SemVer$Version$.$anonfun$fromString$1(SemVer.scala:18)
	at scala.meta.internal.semver.SemVer$Version$.$anonfun$fromString$1$adapted(SemVer.scala:18)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at scala.meta.internal.semver.SemVer$Version$.fromString(SemVer.scala:18)
	at scala.meta.internal.semver.SemVer$.isCompatibleVersion(SemVer.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.supportedBuildTool(MetalsLanguageServer.scala:1408)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1429)
	at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1232)
	... 16 more

2020.05.15 16:39:42 INFO  no build target: using presentation compiler with only scala-library
May 15, 2020 4:41:21 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NumberFormatException: For input string: "<unknown>"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
	at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
	at scala.meta.internal.semver.SemVer$Version$.$anonfun$fromString$1(SemVer.scala:18)
	at scala.meta.internal.semver.SemVer$Version$.$anonfun$fromString$1$adapted(SemVer.scala:18)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at scala.meta.internal.semver.SemVer$Version$.fromString(SemVer.scala:18)
	at scala.meta.internal.semver.SemVer$.isCompatibleVersion(SemVer.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.supportedBuildTool(MetalsLanguageServer.scala:1408)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1429)
	at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1232)
	... 16 more

May 15, 2020 4:42:30 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTraceNotification
```

**Installation:**
- Operating system: Windows 10
- Editor: Visual Studio Code v1.45.1
- Metals version: v1.9.0

**Comment by ckipp01** [comment]
Thanks for reporting. So in your scenario, Metals will actually detect the `build.sbt` and `pom.xml`, and you can actually see this reflected in your logs:
> `2020.05.15 16:33:36 INFO  started: Metals version 0.9.0 in workspace 'C:\Users\S372277\damolina\github\scala_playground'`

When trying this locally I was also prompted to import. However, the rest of your errors stem from having an incomplete build, since you have no build targets and modules. So then bloop has nothing to work with, which is why you're seeing this:

> ⚠️ No build targets were detected in this workspace so most functionality won't work.

You'll want to ensure you have a valid sbt workspace, which you can see examples of [here](https://www.scala-sbt.org/1.x/docs/Directories.html). After https://github.com/scalameta/metals/pull/1728 gets merged in, starting a new project like this will become much easier.

**Comment by tgodzik** [comment]
Thanks for reporting, this is releated to the fact that we require a file `project/build.properties` with the sbt version. Once you create it should all work. This was fixed in https://github.com/scalameta/metals/pull/171 and running with the most recent [SNAPSHOT](https://scalameta.org/metals/docs/editors/vscode.html#using-latest-metals-snapshot) version worked in case of the `build.sbt` file you provided.

**Comment by virtualdvid** [comment]
Got it. Thanks for the replay. It would be cool to get a basic folder structure automated when we are in this scenario. I solved the issue yesterday by accident. I just run `sbt` command in the terminal and the command created the folder structure by itself then Metals started working.

**Comment by Haypierre** [comment]
omg just lost two hours because of the lack of build.properties. Thanks, god I found this thread.
