### ISSUE TITLE
NoSuchMethodError when using fastparse in a worksheet

### ISSUE THREAD

**Issue by phdoerfler** [scalameta/metals#1786]
### Reproduction

Create a build.sbt with:

```scala
scalaVersion := "2.13.2"

libraryDependencies ++= Seq(
  "com.lihaoyi" %% "fastparse" % "2.3.0"
)
```

Create a worksheet, e.g., `src/main/scala/Examples.worksheet.sc`:

```scala
import fastparse._, MultiLineWhitespace._

def p[_:P] = P("a")

parse("a", p(_))
```

Observe this error:

```text
java.lang.NoSuchMethodError: 'fastparse.Parsed fastparse.package$.parse(fastparse.ParserInputSource, scala.Function1, boolean, int, fastparse.internal.Instrument)'
	at repl.Session$App.<init>(Examples.worksheet.sc:14)
	at repl.Session$.app(Examples.worksheet.sc:3)
```

as shown in Exhibit A.

### Expected behavior

No error. I expect the code to be executed and the result to be presented next to it.

#### Exhibit A
<img width="733" alt="image" src="https://user-images.githubusercontent.com/163428/83254635-6b506100-a1af-11ea-99f1-68051107de85.png">

#### Exhibit B

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/163428/83255438-b3bc4e80-a1b0-11ea-8008-2dc8ad8666a1.png">

### Installation:

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.9.0

### Additional context

If you do **not** have fastparse in your `libraryDependencies`, it works (see Exhibit B).
It would seem that fastparse is already part of Metals' classpath. Presumably because of scala.meta but this is just an educated guess.

HT @asflierl

**Comment by tgodzik** [comment]
Thanks for reporting, looks like fastparse is coming from scalameta:
```
coursier resolve --tree "org.scalameta:mdoc_2.12:2.1.5"  
...
   │  └─ org.scalameta:parsers_2.12:4.3.6
   │     ├─ org.scala-lang:scala-library:2.12.11
   │     └─ org.scalameta:trees_2.12:4.3.6
   │        ├─ com.thesamet.scalapb:scalapb-runtime_2.12:0.9.6
   │        │  ├─ com.google.protobuf:protobuf-java:3.8.0
   │        │  ├─ com.lihaoyi:fastparse_2.12:2.1.3
   │        │  │  └─ com.lihaoyi:sourcecode_2.12:0.1.7 -> 0.2.0 (possible incompatibility)
   │        │  ├─ com.thesamet.scalapb:lenses_2.12:0.9.6
   │        │  │  └─ org.scala-lang:scala-library:2.12.10 -> 2.12.11
   │        │  └─ org.scala-lang:scala-library:2.12.10 -> 2.12.11
   │        ├─ org.scala-lang:scala-library:2.12.11
   │        ├─ org.scalameta:common_2.12:4.3.6
   │        │  ├─ com.lihaoyi:sourcecode_2.12:0.2.0
   │        │  └─ org.scala-lang:scala-library:2.12.11
   │        └─ org.scalameta:fastparse_2.12:1.0.1
   │           ├─ com.lihaoyi:sourcecode_2.12:0.1.6 -> 0.2.0 (possible incompatibility)
   │           ├─ org.scala-lang:scala-library:2.12.8 -> 2.12.11
   │           └─ org.scalameta:fastparse-utils_2.12:1.0.1
   │              ├─ com.lihaoyi:sourcecode_2.12:0.1.6 -> 0.2.0 (possible incompatibility)
   │              └─ org.scala-lang:scala-library:2.12.8 -> 2.12.1
```
we might need to fix it in mdoc via some kind of shadowing. Will take a closer look next week.

**Comment by kpbochenek** [comment]
Shadowing is already happening, we use version 1.0.1 shadowed to `org.scalameta:fastparse_2.12:1.0.1`

here is our version: https://github.com/scalameta/fastparse/commits/fastparse-v1-shade

but it looks like we also pull original fastparse through scalapb and that dependency is incompatible with what you use in project? (2.3.0 vs 2.1.3)

This can affect potentially any library we use in mdoc? 

(TIL coursier can display dependencies, nice! )

**Comment by olafurpg** [comment]
Thank you for reporting! The Scalameta classpath shouldn’t conflict with the evaluated worksheets. The only library that we impose on worksheets at runtime is mdoc-runtime which brings in pprint but not fastparse.

**Comment by kpbochenek** [comment]
@olafurpg maybe that is how it should work, but (verified locally) as initially reported without `fastparse` in my project dependencies things using fastparse evaluate correctly in worksheet.

**Comment by tgodzik** [comment]
@olafurpg It looks like the `fn` is not used here:
https://github.com/scalameta/mdoc/blob/7a74f604a3c2099070bec601eee77dced659b2b1/mdoc/src/main/scala/mdoc/internal/markdown/MarkdownCompiler.scala#L103-L108

so we are actually loading the full classpath. I tried to change it to:
```scala
  private def defaultClasspath(fn: URL => Boolean): Classpath = {
    val paths =
      getURLs(getClass.getClassLoader)
        .collect {
          case url if fn(url) => AbsolutePath(Paths.get(url.toURI))
        }
    Classpath(paths.toList)
  }
```
however, I am getting then:
```
java.util.ServiceConfigurationError: mdoc.interfaces.Mdoc: Provider mdoc.internal.worksheets.Mdoc could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at scala.meta.internal.metals.Embedded.serviceLoader(Embedded.scala:82)
	at scala.meta.internal.metals.Embedded.mdoc(Embedded.scala:55)
	at scala.meta.internal.worksheets.WorksheetProvider.$anonfun$getMdoc$8(WorksheetProvider.scala:277)
	at scala.Option$WithFilter.map(Option.scala:230)
	at scala.meta.internal.worksheets.WorksheetProvider.$anonfun$getMdoc$4(WorksheetProvider.scala:258)
	at scala.Option.orElse(Option.scala:447)
	at scala.meta.internal.worksheets.WorksheetProvider.getMdoc(WorksheetProvider.scala:258)
	at scala.meta.internal.worksheets.WorksheetProvider.$anonfun$getMdoc$1(WorksheetProvider.scala:250)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.worksheets.WorksheetProvider.getMdoc(WorksheetProvider.scala:249)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:230)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.liftedTree1$1(WorksheetProvider.scala:152)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:152)
Caused by: java.lang.LinkageError: loader constraint violation: loader java.net.URLClassLoader @1dfb5d20 wants to load interface coursierapi.Logger. A different interface with the same name was previously loaded by 'app'. (coursierapi.Logger is in unnamed module of loader 'app')
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at mdoc.internal.cli.Settings$.<init>(Settings.scala:348)
	at mdoc.internal.cli.Settings$.<clinit>(Settings.scala)
	at mdoc.MainSettings$.apply(MainSettings.scala:122)
	at mdoc.MainSettings$.apply(MainSettings.scala:127)
	at mdoc.internal.worksheets.Mdoc.<init>(Mdoc.scala:23)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at scala.meta.internal.metals.Embedded.serviceLoader(Embedded.scala:82)
	at scala.meta.internal.metals.Embedded.mdoc(Embedded.scala:55)
	at scala.meta.internal.worksheets.WorksheetProvider.$anonfun$getMdoc$8(WorksheetProvider.scala:277)
	at scala.Option$WithFilter.map(Option.scala:230)
	at scala.meta.internal.worksheets.WorksheetProvider.$anonfun$getMdoc$4(WorksheetProvider.scala:258)
	at scala.Option.orElse(Option.scala:447)
	at scala.meta.internal.worksheets.WorksheetProvider.getMdoc(WorksheetProvider.scala:258)
	at scala.meta.internal.worksheets.WorksheetProvider.$anonfun$getMdoc$1(WorksheetProvider.scala:250)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.worksheets.WorksheetProvider.getMdoc(WorksheetProvider.scala:249)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:230)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.liftedTree1$1(WorksheetProvider.scala:152)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:152)
```

any idea what is going on?
