### ISSUE TITLE
`NullPointerException` in worksheets while trying to inspect trees

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1831]
**Describe the bug**
While going through the [Symbols, Trees, and Types](https://docs.scala-lang.org/overviews/reflection/symbols-trees-types.html#kinds-of-trees) tutorial in the scala-lang docs I ran into some issues when trying to inspect trees. It looks like when a completion is being triggered a `NullPointerException` is occurring.

**To Reproduce**
In a worksheet, include the following, and I've marked with a `@@` the position that the `NullPointerException` occurs.

```scala
import scala.reflect.runtime.universe._

// This is the line we'll try to type out
// val expr = reify { class Flower { def name = "Rose" } }
val expr = reify { class Flower { d@@ } }
```
The moment you type the `d`, you'll see the following in the logs:

```sh
[2020.06.15 14:09:42 INFO  time: evaluated worksheet 'SymbolsTreesAndTypes.worksheet.sc' in 0.38s
Jun 15, 2020 2:09:52 PM scala.meta.internal.pc.completions.Completions completionPosition
SEVERE: null
java.lang.NullPointerException
	at scala.meta.internal.pc.completions.OverrideCompletions$OverrideCompletion.<init>(OverrideCompletions.scala:46)
	at scala.meta.internal.pc.completions.Completions.completionPositionUnsafe(Completions.scala:489)
	at scala.meta.internal.pc.completions.Completions.completionPositionUnsafe$(Completions.scala:401)
	at scala.meta.internal.pc.MetalsGlobal.completionPositionUnsafe(MetalsGlobal.scala:28)
	at scala.meta.internal.pc.completions.Completions.completionPosition(Completions.scala:393)
	at scala.meta.internal.pc.completions.Completions.completionPosition$(Completions.scala:378)
	at scala.meta.internal.pc.MetalsGlobal.completionPosition(MetalsGlobal.scala:28)
	at scala.meta.internal.pc.CompletionProvider.safeCompletionsAt(CompletionProvider.scala:419)
	at scala.meta.internal.pc.CompletionProvider.completions(CompletionProvider.scala:56)
	at scala.meta.internal.pc.ScalaPresentationCompiler.$anonfun$complete$1(ScalaPresentationCompiler.scala:194)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:129)
	at scala.meta.internal.pc.CompilerAccess.$anonfun$withInterruptableCompiler$1(CompilerAccess.scala:83)
	at scala.meta.internal.pc.CompilerAccess.$anonfun$onCompilerJobQueue$1(CompilerAccess.scala:187)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
I would expect this to not throw a `NullPointerException`.

**Installation:**
- Operating system: macOS
- Editor: Tested with Visual Studio Code and Vim
- Metals version: v0.9.0 and the latest snapshot

**Search terms**
worksheets

**Comment by tgodzik** [comment]
Thanks for reporting! I think we should either put a guard there or try to figure out how to go around the null.

**Comment by tgodzik** [comment]
I tried to reproduce it, but no luck. What Scala version did this happen in?

Seems to work for me in both `2.12.11` and `2.13.3`. Maybe it was a bug in an earlier version?

![bug1](https://user-images.githubusercontent.com/3807253/90249368-9e170680-de3a-11ea-8e67-7d2e365ea94e.gif)

**Comment by ckipp01** [comment]
Just tried reproducing this again and was unable to. 🤷 

I'll go ahead and close this.
