### ISSUE TITLE
Compile request sent twice after file save

### ISSUE THREAD

**Issue by adpi2** [scalameta/metals#1836]
**Describe the bug**

The compile request of the same build target is sent twice after file save. It causes the error reporting to blink.

**To Reproduce**
1. Activate the BSP trace by creating the ~/cache/metals/bsp.trace.json
2. Import a Scala project in Metals in vscode
4. Open the Metals log window
3. Modify a file and save the modification. You should see in the log that the build target is compiled twice. If not repeat the file modification operation until it does.
```
2020.06.17 10:52:56 INFO  compiling root (1 scala source)
2020.06.17 10:52:56 INFO  time: compiled root in 0.2s
2020.06.17 10:52:56 INFO  compiling root (1 scala source)
2020.06.17 10:52:56 INFO  time: compiled root in 0.14s
```
5. In the bsp.trace.json file you should see the two compile requests
```
[Trace - 10:52:56 AM] Sending request 'buildTarget/compile - (11)'
Params: {
  "targets": [
    {
      "uri": "file:/home/adpi2/hello/?id\u003droot"
    }
  ]
}
...
[Trace - 10:52:56 AM] Sending request 'buildTarget/compile - (14)'
Params: {
  "targets": [
    {
      "uri": "file:/home/adpi2/hello/?id\u003droot"
    }
  ]
}
```

Sometime the second compile request contains the same target id twice.

```
[Trace - 10:59:58 AM] Sending request 'buildTarget/compile - (20)'
Params: {
  "targets": [
    {
      "uri": "file:/home/adpi2/hello/?id\u003droot"
    },
    {
      "uri": "file:/home/adpi2/hello/?id\u003droot"
    }
  ]
}
```

**Expected behavior**
Compile request should be sent only once after file save.

**Screenshot**
The error reporting is blinking.
![Peek 2020-06-17 11-21](https://user-images.githubusercontent.com/13123162/84880778-47d15580-b08d-11ea-9b60-5efaee1b7d45.gif)

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Additional context**
I have first experienced this issue with sbt BSP server but then I was able to reproduce it with Bloop as well.

**Search terms**
duplicate compile request

**Comment by tgodzik** [comment]
Thanks for reporting! That seems to be happening because we have didChange coming from file watcher and the editor:
```
        at scala.meta.internal.metals.Compilations.compileFiles(Compilations.scala:83)
        at scala.meta.internal.metals.MetalsLanguageServer.onChange(MetalsLanguageServer.scala:1020)
        at scala.meta.internal.metals.MetalsLanguageServer.didChangeWatchedFiles(MetalsLanguageServer.scala:992)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1(MetalsLanguageServer.scala:158)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1$adapted(MetalsLanguageServer.scala:158)
        at scala.meta.internal.metals.FileWatcher$DirectoryListener.onEvent(FileWatcher.scala:186)
        at io.methvin.watcher.DirectoryWatcher.watch(DirectoryWatcher.java:299)
        at io.methvin.watcher.DirectoryWatcher.lambda$watchAsync$0(DirectoryWatcher.java:216)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020.06.17 12:40:37 INFO  compiling root (1 scala source)
        at scala.meta.internal.metals.Compilations.compileFiles(Compilations.scala:83)
        at scala.meta.internal.metals.MetalsLanguageServer.onChange(MetalsLanguageServer.scala:1020)
        at scala.meta.internal.metals.MetalsLanguageServer.didSave(MetalsLanguageServer.scala:887)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by tgodzik** [comment]
So this seems like an expected behaviour and haven't caused any issues when using Bloop. It might be more noticable in case of sbt though :thinking: 
Fix could be that we ignore the file from file watcher if it exists in buffers.

**Comment by adpi2** [comment]
Thank you @tgodzik for clarifying this behavior. It is indeed more noticeable with sbt than Bloop.

I can tell that sbt sends "reset" diagnostics when it starts compiling whereas Bloop does not. That is why the error report is blinking with sbt. I may be able to change this behavior in sbt.

I am curious about the purpose of the file watcher. In this particular case it seems redundant with the editor. Can you tell me more about it?

**Comment by tgodzik** [comment]
File watcher is important in cases, when file is changed via other means than the editor - for example when using git or via a different editor.
