### ISSUE TITLE
org.scalameta.UnreachableError with () literal type

### ISSUE THREAD

**Issue by d6y** [scalameta/metals#1849]
**Describe the bug**

The literal unit type causes unreachable code error.

**To Reproduce**

1. In VSCode, create a Scala object with a `()` type declaration:

    ```
    object Example {
      val a: () = ()
    }
    ```
2. Observe output window shows:

    ```
    org.scalameta.UnreachableError: this code path should've been unreachable
	at org.scalameta.UnreachableError$.raise(package.scala:40
    ```

**Expected behavior**

Successful compilation. 

For reference: `$ scala -e 'object Example { val a: () = () }'` succeeds with Scala 2.13.2

This is a cut-down example. In reality, I was intending to write `F[Unit]` but typed in `F[()]`. I checked that SBT was compiling, then tried to understand why Metals was unhappy. I've actually no intention of writing `val a: () = ()` or indeed `F[()]` but hey... it compiles in SBT.

Thanks for the amazing work on this tool.

**Installation:**
- Operating system: macOs
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Comment by kpbochenek** [comment]
Thanks for reporting!
Confirmed, it is an issue with trying to parse `()`. Still present in `0.9.1-SNAPSHOT`

It is a problem in scalameta parser, this issue should probably be moved to `scalameta/scalameta` 

We try to parse `()` as tuple type and we expect at least one type to be present but in case of no types we fail. We should treat it as Unit type in that case?

Full log:
```
Caused by: org.scalameta.UnreachableError: this code path should've been unreachable
	at org.scalameta.UnreachableError$.raise(package.scala:40)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$makeTupleType$2(ScalametaParser.scala:827)
	at scala.meta.internal.parsers.ScalametaParser.makeTuple(ScalametaParser.scala:802)
	at scala.meta.internal.parsers.ScalametaParser.makeTupleType(ScalametaParser.scala:827)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$tupleInfixType$7(ScalametaParser.scala:945)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$tupleInfixType$1(ScalametaParser.scala:945)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.tupleInfixType(ScalametaParser.scala:859)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$typRest$1(ScalametaParser.scala:984)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typRest(ScalametaParser.scala:979)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typRest$(ScalametaParser.scala:978)
	at scala.meta.internal.parsers.ScalametaParser$outPattern$.typRest(ScalametaParser.scala:2454)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$typ$1(ScalametaParser.scala:974)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typ(ScalametaParser.scala:965)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typ$(ScalametaParser.scala:964)
	at scala.meta.internal.parsers.ScalametaParser$outPattern$.typ(ScalametaParser.scala:2454)
	at scala.meta.internal.parsers.ScalametaParser.typ(ScalametaParser.scala:2475)
```

**Comment by kpbochenek** [comment]
Already reported here:
https://github.com/scalameta/scalameta/issues/1470
