### ISSUE TITLE
Unit test failure on Oracle JDK 8

### ISSUE THREAD

**Issue by robinraju** [scalameta/metals#1885]
**Describe the bug**
A test on `TreeViewLspSuite` fails on Oracle JDK 8

**To Reproduce**
1. Switch to Oracle JDK 8.

```
❯ java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```
2. Start a new sbt session
```
❯ sbt
[info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_251)
```
3. Run the following test
```scala
sbt:default-3f70c7> testOnly tests.TreeViewLspSuite
```

```scala
==> X tests.TreeViewLspSuite.libraries  2.142s munit.FailException: /Users/robinraju/workspace/scalacenter/metals/tests/unit/src/test/scala/tests/TreeViewLspSuite.scala:145
144:        )
145:        server.assertTreeViewChildren(
146:          s"libraries:",
diff assertion failed
=> Obtained
    """|animal-sniffer-annotations.jar -
       |cats-core_2.12.jar -y 12s
       |cats-kernel_2.12.jar -
       |cats-macros_2.12.jar -
       |charsets.jar -
       |checker-qual.jar -
       |circe-core_2.12.jar -
       |circe-numbers_2.12.jar -
       |error_prone_annotations.jar -
       |failureaccess.jar -
       |gson.jar -
       |guava.jar -
       |j2objc-annotations.jar -
       |jce.jar -
       |jfr.jar -
       |jsr305.jar -
       |jsse.jar -
       |listenablefuture.jar -
       |machinist_2.12.jar -
       |org.eclipse.lsp4j.jar -
       |org.eclipse.lsp4j.generator.jar -
       |org.eclipse.lsp4j.jsonrpc.jar -
       |org.eclipse.xtend.lib.jar -
       |org.eclipse.xtend.lib.macro.jar -
       |org.eclipse.xtext.xbase.lib.jar -
       |resources.jar -
       |rt.jar -
       |scala-library.jar -
       |scala-reflect.jar -
       |sourcecode_2.12.jar -
       |""".stripMargin
=> Diff (- obtained, + expected)
 jce.jar -
-jfr.jar -
 jsr305.jar -
    at tests.Assertions$.assertNoDiff(Assertions.scala:73)
    at tests.TestingServer.assertTreeViewChildren(TestingServer.scala:1349)
    at tests.TreeViewLspSuite.$anonfun$new$9(TreeViewLspSuite.scala:145)
```

**Expected behavior**
Test should run successfully.

**Screenshots**

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.1

**Additional context**
I've tested this on the following JDK versions without any test failures
- openjdk64-1.8.0.252
- openjdk64-11.0.7
- oracle64-11.0.7

I assume `jfr.jar` is bundled only along Oracle JDK 8 (unhandled in the tests) results in the test failure.

**Search terms**

**Comment by kpbochenek** [comment]
Thanks for reporting this issue and checking it for oracle11 too!

Sounds like an easy fix it it might be tricky because we assert on raw strings and sometimes just check for 'count' only.
