### ISSUE TITLE
Boxed Error when Ammonite script starts with a shebang

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#1894]
**Describe the bug**
If you open an Ammonite script that starts with `#!/usr/bin/env amm` in Metals, you get a Boxed Error.

**To Reproduce**
Open the following script in Metals

```scala
#!/usr/bin/env amm

val test = ":("
```

You'll see the following:

<details>
<summary>SEVERE: Internal error: java.util.concurrent.ExecutionException: Boxed Error</summary>
<br>

```
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: Boxed Error
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at ammonite.interp.script.AmmoniteBuildServer$.$anonfun$on$1(AmmoniteBuildServer.scala:475)
	at ammonite.interp.script.AmmoniteBuildServer$.$anonfun$on$1$adapted(AmmoniteBuildServer.scala:473)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more
Caused by: java.lang.AssertionError: assertion failed: wrong startPosInSc Position(0,2)
	at scala.Predef$.assert(Predef.scala:223)
	at ammonite.interp.script.SingleScriptCompiler.adjust$1(SingleScriptCompiler.scala:150)
2020.07.07 11:22:39 INFO  Ammonite:
	at ammonite.interp.script.SingleScriptCompiler.$anonfun$updateSemanticDbs$5(SingleScriptCompiler.scala:180)
	at ammonite.interp.script.SingleScriptCompiler.$anonfun$updateSemanticDbs$5$adapted(SingleScriptCompiler.scala:180)
	at ammonite.interp.script.SemanticdbProcessor$.postProcess(SemanticdbProcessor.scala:29)
	at ammonite.interp.script.SingleScriptCompiler.$anonfun$updateSemanticDbs$3(SingleScriptCompiler.scala:180)
	at ammonite.interp.script.SingleScriptCompiler.$anonfun$updateSemanticDbs$3$adapted(SingleScriptCompiler.scala:162)
	at scala.Option.foreach(Option.scala:407)
	at ammonite.interp.script.SingleScriptCompiler.$anonfun$updateSemanticDbs$2(SingleScriptCompiler.scala:162)
	at ammonite.interp.script.SingleScriptCompiler.$anonfun$updateSemanticDbs$2$adapted(SingleScriptCompiler.scala:161)
	at scala.Option.foreach(Option.scala:407)
	at ammonite.interp.script.SingleScriptCompiler.updateSemanticDbs(SingleScriptCompiler.scala:161)
	at ammonite.interp.script.SingleScriptCompiler.apply(SingleScriptCompiler.scala:288)
	at ammonite.interp.script.ScriptCompiler.doCompile(ScriptCompiler.scala:256)
	at ammonite.interp.script.ScriptCompiler.$anonfun$compileIfNeeded$1(ScriptCompiler.scala:227)
	at scala.Option.getOrElse(Option.scala:189)
	at ammonite.interp.script.ScriptCompiler.compileIfNeeded(ScriptCompiler.scala:225)
	at ammonite.interp.script.ScriptCompiler.compile(ScriptCompiler.scala:90)
	at ammonite.interp.script.AmmoniteBuildServer.$anonfun$compileScript$2(AmmoniteBuildServer.scala:369)
	at scala.Option.getOrElse(Option.scala:189)
	at ammonite.interp.script.AmmoniteBuildServer.compileScript(AmmoniteBuildServer.scala:366)
	at ammonite.interp.script.AmmoniteBuildServer.$anonfun$compileScript$6(AmmoniteBuildServer.scala:391)
	at ammonite.interp.script.ScriptCompiler.$anonfun$compile$10(ScriptCompiler.scala:67)
	at scala.util.Either.flatMap(Either.scala:341)
	at ammonite.interp.script.ScriptCompiler.$anonfun$compile$7(ScriptCompiler.scala:62)
	at scala.util.Either.flatMap(Either.scala:341)
	at ammonite.interp.
2020.07.07 11:22:39 INFO  Ammonite: script.ScriptCompiler.$anonfun$compile$6(ScriptCompiler.scala:61)
	at scala.util.Either.flatMap(Either.scala:341)
	at ammonite.interp.script.ScriptCompiler.$anonfun$compile$1(ScriptCompiler.scala:49)
	at scala.util.Either.flatMap(Either.scala:341)
	at ammonite.interp.script.ScriptCompiler.compile(ScriptCompiler.scala:48)
	at ammonite.interp.script.AmmoniteBuildServer.compileScript(AmmoniteBuildServer.scala:391)
	at ammonite.interp.script.AmmoniteBuildServer.$anonfun$buildTargetCompile$3(AmmoniteBuildServer.scala:402)
	at ammonite.interp.script.AmmoniteBuildServer.$anonfun$buildTargetCompile$3$adapted(AmmoniteBuildServer.scala:401)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.immutable.List.map(List.scala:298)
	at ammonite.interp.script.AmmoniteBuildServer.$anonfun$buildTargetCompile$2(AmmoniteBuildServer.scala:401)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at ammonite.interp.script.AmmoniteBuildServer.$anonfun$buildTargetCompile$1(AmmoniteBuildServer.scala:400)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	... 5 more
```
</details>

**Expected behavior**
I would expect this to still be able to work since it's still a valid Ammonite script.

**Installation:**
- Operating system: macOS
- Editor: Vim
- Metals version: v0.9.1

**Additional context**
I think this will probably have to be fixed on the Ammonite side of things, but I could be wrong.

**Search terms**
Ammonite

**Comment by tgodzik** [comment]
Thanks for reporting! That seems like a bug inside Ammonite when using semanticdb. @alexarchambault should we move the issue to https://github.com/lihaoyi/Ammonite ?

**Comment by alexarchambault** [comment]
> should we move the issue to https://github.com/lihaoyi/Ammonite?
Yes, go ahead!

**Comment by ckipp01** [comment]
Moved to Ammonite here: https://github.com/lihaoyi/Ammonite/issues/1101
