### ISSUE TITLE
v0.9.2 regression "Unexpected error initializing server" crash

### ISSUE THREAD

**Issue by soronpo** [scalameta/metals#1925]
**Describe the bug**
```
2020.07.15 16:58:12 ERROR Unexpected error initializing server
java.nio.file.InvalidPathException: Illegal char <:> at index 30: c:\IdeaProjects\hello-world\?C:\Users\soronpo\AppData\Roaming\Coursier\config\credentials.properties
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.nio.file.Path.of(Path.java:147)
	at java.nio.file.Paths.get(Paths.java:69)
	at coursierapi.shaded.coursier.credentials.FileCredentials.get(FileCredentials.scala:19)
	at coursierapi.shaded.coursier.cache.FileCache.$anonfun$allCredentials0$1(FileCache.scala:49)
	at coursierapi.shaded.scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at coursierapi.shaded.scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at coursierapi.shaded.scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
	at coursierapi.shaded.coursier.cache.FileCache.allCredentials0$lzycompute(FileCache.scala:49)
	at coursierapi.shaded.coursier.cache.FileCache.allCredentials0(FileCache.scala:48)
	at coursierapi.shaded.coursier.cache.FileCache.$anonfun$allCredentials$1(FileCache.scala:52)
	at coursierapi.shaded.scala.concurrent.Future$.$anonfun$apply$1(Future.scala:661)
	at coursierapi.shaded.scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
On my system, any project gives the error above after upgrading from v0.9.1 to v0.9.2

**Expected behavior**
No error

**Installation:**
- Operating system: Windows 7
- Editor: Visual Studio Code
- Metals version: v0.9.2 (no bug in v0.9.1)

**Additional context**
The error references a coursier properties file. It doesn't exist in the path given in the error message.

**Comment by tgodzik** [comment]
Thanks for reporting! @alexarchambault It seems to be coming from coursier after a recent updated. Might be something related to: https://github.com/coursier/coursier/commit/190bfa6f323833e4e96cd79981c404096d51d9c2 ?

**Comment by alexarchambault** [comment]
It might be https://github.com/coursier/coursier/commit/190bfa6f323833e4e96cd79981c404096d51d9c2, yes. Would going back to a former coursier version be an option, until this is fixed?

**Comment by tgodzik** [comment]
We can revert for sure, but any idea where is it coming from?

**Comment by tgodzik** [comment]
I am wondering how widespread could this be? I am not having the same issue in Windows, although I am testing it on Windows 10. 

@soronpo Do you have any properties like `coursier.config-dir` or environment variables set like `COURSIER_CONFIG_DIR` ?

**Comment by soronpo** [comment]
I just have COURSIER_HOME=%LOCALAPPDATA%\Coursier\Cache\v1

**Comment by tgodzik** [comment]
Hmm... that should be an issue.

Would you be able to run:
```scala
import $ivy.`dev.dirs:directories:20`
import dev.dirs.ProjectDirectories

val paths = ProjectDirectories.from(null, null, "Coursier")

paths.configDir
paths.cacheDir
paths.preferenceDir
```

in a worksheet? Do all of the directories look normal?

This will work in 0.9.1.

**Comment by soronpo** [comment]
![image](https://user-images.githubusercontent.com/8167952/87562124-431cb300-c6c6-11ea-91ed-301ed07e5142.png)

**Comment by soronpo** [comment]
It's seems very weird to see `\ufeff` there

**Comment by tgodzik** [comment]
Yeah, it looks super weird, this could be the reason for the issue, although not super sure about the origin of it. Most likely needs to be fixed in https://github.com/dirs-dev/directories-jvm/blob/0ec6dad27be95c102020a69870fc9185bfa9ec04/src/main/java/dev/dirs/Util.java#L138

We can revert for now, you should be able to use the snapshot, although 0.9.2 release was mostly about support for 2.12.12, so you should be good using 0.9.1.

If it becomes a widespread problem I will create an additional release.

**Comment by tgodzik** [comment]
@alexarchambault should we move the issue to coursier or dev-dirs/directories? Any ideas what might be wrong?

**Comment by alexarchambault** [comment]
@tgodzik It seems that's an issue that should be fixed in dev-dirs/directories-jvm, yes. It should probably strip the UTF-8 BOM prefix. [It had to be done in coursier](https://github.com/coursier/coursier/commit/fac264f7b78c945f72b06f2fcad9725afd861510) for POMs some time ago.

**Comment by tgodzik** [comment]
Created an issue here https://github.com/dirs-dev/directories-jvm/issues/37

@soronpo I will not be doing the new release yet, it seems it's not that widespread. You can use the newest version with `0.9.2+9-5c971cc1-SNAPSHOT` server version, which will use the older coursier version. But there were no really big changes for `1.9.2` aside from the Scala 2.12.12 integration.

**Comment by soronpo** [comment]
OK, no worries. I'll be using 0.9.1 for now.
