### ISSUE TITLE
metals doesn't connect to the server

### ISSUE THREAD

**Issue by elyphas** [scalameta/metals#1952]
**Question**

Why vim tells me it can't connect to the build server?

**Screenshots**

```scala
2020.07.27 15:28:23 INFO  started: Metals version 0.9.2 in workspace '/home/elyphas/Prjs/outwatch_components' for client vim-lsc.
2020.07.27 15:28:23 INFO  time: initialize in 0.54s
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher8510933470964782802/bsp.socket'...
Waiting for the bsp connection to come up...
2020.07.27 15:28:26 INFO  Selected port 5031
2020.07.27 15:28:26 INFO  no build target: using presentation compiler with only scala-library
Jul 27, 2020 3:28:26 PM io.undertow.Undertow start
INFO: starting server: Undertow - 2.1.3.Final
Jul 27, 2020 3:28:26 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.8.1.Final
Jul 27, 2020 3:28:26 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.8.1.Final
error: The command bsp --protocol local --socket /tmp/bsp-launcher8510933470964782802/bsp.socket returned with an error
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 26056'...
Waiting for the bsp connection to come up...
error: The command bsp --protocol tcp --port 26056 returned with an error
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.07.27 15:28:26 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jul 27, 2020 3:28:26 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.1.0.Final
2020.07.27 15:28:26 INFO  Started Metals http server at http://127.0.0.1:5031
2020.07.27 15:28:28 INFO  started: Metals version 0.9.2 in workspace '/home/elyphas/Prjs/outwatch_components' for client coc-metals.
2020.07.27 15:28:29 INFO  time: initialize in 0.9s
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher3048591901653532166/bsp.socket'...
Waiting for the bsp connection to come up...
2020.07.27 15:28:30 INFO  no build target: using presentation compiler with only scala-library
2020.07.27 15:28:30 INFO  skipping build import with status 'Requested'
error: The command bsp --protocol local --socket /tmp/bsp-launcher3048591901653532166/bsp.socket returned with an error
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 30779'...
Waiting for the bsp connection to come up...
error: The command bsp --protocol tcp --port 30779 returned with an error
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.07.27 15:28:30 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020.07.27 15:38:03 INFO  running '/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals1776197789545631883/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
2020.07.27 15:38:11 INFO  [info] Loading settings for project outwatch_components-build from plugins.sbt,metals.sbt ...
2020.07.27 15:38:12 INFO  [info] Loading project definition from /home/elyphas/Prjs/outwatch_components/project
2020.07.27 15:38:16 INFO  [info] Loading settings for project outwatch_components from build.sbt ...
2020.07.27 15:38:16 INFO  [info] Set current project to outwatchcomponents (in build file:/home/elyphas/Prjs/outwatch_components/)
2020.07.27 15:38:23 INFO  [warn] 
2020.07.27 15:38:23 INFO  [warn] 	Note: Unresolved dependencies path:
2020.07.27 15:38:23 INFO  [error] sbt.librarymanagement.ResolveException: Error downloading com.github.outwatch.outwatch:outwatch-monix_sjs0.6_2.13:master-SNAPSHOT
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   not found: /home/elyphas/.ivy2/local/com.github.outwatch.outwatch/outwatch-monix_sjs0.6_2.13/master-SNAPSHOT/ivys/ivy.xml
2020.07.27 15:38:23 INFO  [error]   not found: https://repo1.maven.org/maven2/com/github/outwatch/outwatch/outwatch-monix_sjs0.6_2.13/master-SNAPSHOT/outwatch-monix_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error]   not found: https://jitpack.io/com/github/outwatch/outwatch/outwatch-monix_sjs0.6_2.13/master-SNAPSHOT/outwatch-monix_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error] Error downloading com.github.cornerman.colibri:colibri-monix_sjs0.6_2.13:master-SNAPSHOT
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   not found: /home/elyphas/.ivy2/local/com.github.cornerman.colibri/colibri-monix_sjs0.6_2.13/master-SNAPSHOT/ivys/ivy.xml
2020.07.27 15:38:23 INFO  [error]   not found: https://repo1.maven.org/maven2/com/github/cornerman/colibri/colibri-monix_sjs0.6_2.13/master-SNAPSHOT/colibri-monix_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error]   not found: https://jitpack.io/com/github/cornerman/colibri/colibri-monix_sjs0.6_2.13/master-SNAPSHOT/colibri-monix_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error] Error downloading com.github.outwatch.outwatch:outwatch_sjs0.6_2.13:master-SNAPSHOT
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   not found: /home/elyphas/.ivy2/local/com.github.outwatch.outwatch/outwatch_sjs0.6_2.13/master-SNAPSHOT/ivys/ivy.xml
2020.07.27 15:38:23 INFO  [error]   not found: https://repo1.maven.org/maven2/com/github/outwatch/outwatch/outwatch_sjs0.6_2.13/master-SNAPSHOT/outwatch_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error]   not found: https://jitpack.io/com/github/outwatch/outwatch/outwatch_sjs0.6_2.13/master-SNAPSHOT/outwatch_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error] Error downloading com.github.outwatch.outwatch:outwatch-util_sjs0.6_2.13:master-SNAPSHOT
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   not found: /home/elyphas/.ivy2/local/com.github.outwatch.outwatch/outwatch-util_sjs0.6_2.13/master-SNAPSHOT/ivys/ivy.xml
2020.07.27 15:38:23 INFO  [error]   not found: https://repo1.maven.org/maven2/com/github/outwatch/outwatch/outwatch-util_sjs0.6_2.13/master-SNAPSHOT/outwatch-util_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error]   not found: https://jitpack.io/com/github/outwatch/outwatch/outwatch-util_sjs0.6_2.13/master-SNAPSHOT/outwatch-util_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
2020.07.27 15:38:23 INFO  [error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
2020.07.27 15:38:23 INFO  [error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
2020.07.27 15:38:23 INFO  [error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
2020.07.27 15:38:23 INFO  [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
2020.07.27 15:38:23 INFO  [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
2020.07.27 15:38:23 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
2020.07.27 15:38:23 INFO  [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
2020.07.27 15:38:23 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
2020.07.27 15:38:23 INFO  [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
2020.07.27 15:38:23 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
2020.07.27 15:38:23 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
2020.07.27 15:38:23 INFO  [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
2020.07.27 15:38:23 INFO  [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
2020.07.27 15:38:23 INFO  [error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2947)
2020.07.27 15:38:23 INFO  [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
2020.07.27 15:38:23 INFO  [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
2020.07.27 15:38:23 INFO  [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
2020.07.27 15:38:23 INFO  [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
2020.07.27 15:38:23 INFO  [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
2020.07.27 15:38:23 INFO  [error] 	at sbt.Execute.work(Execute.scala:290)
2020.07.27 15:38:23 INFO  [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
2020.07.27 15:38:23 INFO  [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
2020.07.27 15:38:23 INFO  [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
2020.07.27 15:38:23 INFO  [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020.07.27 15:38:23 INFO  [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020.07.27 15:38:23 INFO  [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020.07.27 15:38:23 INFO  [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020.07.27 15:38:23 INFO  [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020.07.27 15:38:23 INFO  [error] 	at java.lang.Thread.run(Thread.java:748)
2020.07.27 15:38:23 INFO  [error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.outwatch.outwatch:outwatch-monix_sjs0.6_2.13:master-SNAPSHOT
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   not found: /home/elyphas/.ivy2/local/com.github.outwatch.outwatch/outwatch-monix_sjs0.6_2.13/master-SNAPSHOT/ivys/ivy.xml
2020.07.27 15:38:23 INFO  [error]   not found: https://repo1.maven.org/maven2/com/github/outwatch/outwatch/outwatch-monix_sjs0.6_2.13/master-SNAPSHOT/outwatch-monix_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error]   not found: https://jitpack.io/com/github/outwatch/outwatch/outwatch-monix_sjs0.6_2.13/master-SNAPSHOT/outwatch-monix_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error] Error downloading com.github.cornerman.colibri:colibri-monix_sjs0.6_2.13:master-SNAPSHOT
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   not found: /home/elyphas/.ivy2/local/com.github.cornerman.colibri/colibri-monix_sjs0.6_2.13/master-SNAPSHOT/ivys/ivy.xml
2020.07.27 15:38:23 INFO  [error]   not found: https://repo1.maven.org/maven2/com/github/cornerman/colibri/colibri-monix_sjs0.6_2.13/master-SNAPSHOT/colibri-monix_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error]   not found: https://jitpack.io/com/github/cornerman/colibri/colibri-monix_sjs0.6_2.13/master-SNAPSHOT/colibri-monix_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error] Error downloading com.github.outwatch.outwatch:outwatch_sjs0.6_2.13:master-SNAPSHOT
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   not found: /home/elyphas/.ivy2/local/com.github.outwatch.outwatch/outwatch_sjs0.6_2.13/master-SNAPSHOT/ivys/ivy.xml
2020.07.27 15:38:23 INFO  [error]   not found: https://repo1.maven.org/maven2/com/github/outwatch/outwatch/outwatch_sjs0.6_2.13/master-SNAPSHOT/outwatch_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error]   not found: https://jitpack.io/com/github/outwatch/outwatch/outwatch_sjs0.6_2.13/master-SNAPSHOT/outwatch_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error] Error downloading com.github.outwatch.outwatch:outwatch-util_sjs0.6_2.13:master-SNAPSHOT
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   Not found
2020.07.27 15:38:23 INFO  [error]   not found: /home/elyphas/.ivy2/local/com.github.outwatch.outwatch/outwatch-util_sjs0.6_2.13/master-SNAPSHOT/ivys/ivy.xml
2020.07.27 15:38:23 INFO  [error]   not found: https://repo1.maven.org/maven2/com/github/outwatch/outwatch/outwatch-util_sjs0.6_2.13/master-SNAPSHOT/outwatch-util_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error]   not found: https://jitpack.io/com/github/outwatch/outwatch/outwatch-util_sjs0.6_2.13/master-SNAPSHOT/outwatch-util_sjs0.6_2.13-master-SNAPSHOT.pom
2020.07.27 15:38:23 INFO  [error] Total time: 6 s, completed Jul 27, 2020 3:38:23 PM
2020.07.27 15:38:23 INFO  build tool exit: 1
2020.07.27 15:38:24 INFO  time: ran 'sbt bloopInstall' in 20s
2020.07.27 15:38:24 ERROR sbt command failed: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals1776197789545631883/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher479573942736362480/bsp.socket'...
Waiting for the bsp connection to come up...
error: The command bsp --protocol local --socket /tmp/bsp-launcher479573942736362480/bsp.socket returned with an error
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 31590'...
Waiting for the bsp connection to come up...
error: The command bsp --protocol tcp --port 31590 returned with an error
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.07.27 15:38:24 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020.07.27 15:41:19 INFO  started: Metals version 0.9.2 in workspace '/home/elyphas/Prjs/outwatch_components' for client vim-lsc.
2020.07.27 15:41:19 INFO  time: initialize in 0.61s
Starting the bsp launcher for bloop...
2020.07.27 15:41:22 INFO  Selected port 5032
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher4070306728429100112/bsp.socket'...
Waiting for the bsp connection to come up...
2020.07.27 15:41:22 INFO  no build target: using presentation compiler with only scala-library
Jul 27, 2020 3:41:22 PM io.undertow.Undertow start
INFO: starting server: Undertow - 2.1.3.Final
Jul 27, 2020 3:41:22 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.8.1.Final
Jul 27, 2020 3:41:22 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.8.1.Final
error: The command bsp --protocol local --socket /tmp/bsp-launcher4070306728429100112/bsp.socket returned with an error
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 30359'...
Waiting for the bsp connection to come up...
2020.07.27 15:41:23 INFO  skipping build import with status 'Failed'
error: The command bsp --protocol tcp --port 30359 returned with an error
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.07.27 15:41:23 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jul 27, 2020 3:41:23 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.1.0.Final
2020.07.27 15:41:23 INFO  Started Metals http server at http://127.0.0.1:5032
2020.07.27 15:41:23 INFO  started: Metals version 0.9.2 in workspace '/home/elyphas/Prjs/outwatch_components' for client coc-metals.
2020.07.27 15:41:25 INFO  time: initialize in 1.41s
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher9070629707095367999/bsp.socket'...
Waiting for the bsp connection to come up...
2020.07.27 15:41:26 INFO  no build target: using presentation compiler with only scala-library
2020.07.27 15:41:26 INFO  skipping build import with status 'Failed'
error: The command bsp --protocol local --socket /tmp/bsp-launcher9070629707095367999/bsp.socket returned with an error
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 22900'...
Waiting for the bsp connection to come up...
error: The command bsp --protocol tcp --port 22900 returned with an error
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.07.27 15:41:26 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Installation:**

- Operating system: Linux
- Vim or nvim version: vim 8.2
- coc.nvim version: 
- coc-metals extension version: 0.9.2
- Metals version: (`:CocConfig` to open settings)

**Additional context**

**Search terms**

`Failed to connect with build server, no funcionality will work. See logs for more details`

**Comment by elyphas** [comment]
oh, thank you very much

**Comment by ckipp01** [comment]
Going to go ahead and close this since you followed up on gitter saying this fixed your issue.
