### ISSUE TITLE
Boxed Interrupt exception when trying "Metals: Import Build" in VSCode

### ISSUE THREAD

**Issue by oharboe** [scalameta/metals#2007]
**Describe the bug**
Suddenly I can't run "Metals: Import Build". I have no idea what changed, it worked one moment and the next it doesn't.

**To Reproduce**
1. In Visual Studio Code run "Metals: ImportBuild"
2. Import fails
3. Inspect logs

**Expected behavior**

No exception.

**Screenshots**

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v1.8.2

**Additional context**

**Search terms**

Boxed Interrupt Exception

** Log **

```
INFO  running '/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals9397946263392614025/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
INFO  [info] Loading global plugins from /home/oyvind/.sbt/1.0/plugins
INFO  [info] Loading settings for project aptos-build from plugins.sbt,metals.sbt ...
INFO  [info] Loading project definition from /home/oyvind/ascenium/ascenium/hardware/aptos/project
INFO  [info] Loading settings for project aptos from build.sbt ...
INFO  [info] Set current project to Aptos (in build file:/home/oyvind/ascenium/ascenium/hardware/aptos/)
INFO  [success] Generated .bloop/aptos.json
INFO  [success] Generated .bloop/aptos-test.json
INFO  [success] Total time: 0 s, completed Aug 19, 2020, 10:58:34 AM
INFO  build tool exit: 0
INFO  time: ran 'sbt bloopInstall' in 5.36s
INFO  disconnected: build server
ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.ExecutionException: Boxed InterruptedException
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:86)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.java8.FuturesConvertersImpl$P.accept(FutureConvertersImpl.scala:92)
	at scala.concurrent.java8.FuturesConvertersImpl$P.accept(FutureConvertersImpl.scala:89)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$3(BuildServerConnection.scala:145)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$2(BuildServerConnection.scala:145)
	at scala.meta.internal.metals.Cancelable$$anon$1.cancel(Cancelable.scala:17)
	at scala.meta.internal.metals.Cancelable$.$anonfun$cancelAll$1(Cancelable.scala:28)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.meta.internal.metals.Cancelable$.cancelAll(Cancelable.scala:27)
	at scala.meta.internal.metals.MutableCancelable.cancel(MutableCancelable.scala:18)
	at scala.meta.internal.metals.BuildServerConnection.cancel(BuildServerConnection.scala:114)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1(BuildServerConnection.scala:54)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1$adapted(BuildServerConnection.scala:49)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$3(BuildServerConnection.scala:145)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$2(BuildServerConnection.scala:145)
	at scala.meta.internal.metals.Cancelable$$anon$1.cancel(Cancelable.scala:17)
	at scala.meta.internal.metals.Cancelable$.$anonfun$cancelAll$1(Cancelable.scala:28)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.meta.internal.metals.Cancelable$.cancelAll(Cancelable.scala:27)
	at scala.meta.internal.metals.MutableCancelable.cancel(MutableCancelable.scala:18)
	at scala.meta.internal.metals.BuildServerConnection.cancel(BuildServerConnection.scala:114)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1(BuildServerConnection.scala:54)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1$adapted(BuildServerConnection.scala:49)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)

INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/oyvind/.cache/metals/bsp.trace.json
INFO  Connected to Build server v1.4.0-RC1-90-70cfd9e2
WARN  Could not find java sources in Some(/usr/lib/jvm/java-11-openjdk-amd64/). Java symbols will not be available.
INFO  time: indexed workspace in 1.2s
INFO  Deduplicating compilation of aptos from bsp client 'Metals 0.8.2' (since 3m 26.365s)
WARN  Disconnecting from deduplication of ongoing compilation for 'aptos'
No progress update for 30 seconds caused bloop to cancel compilation and schedule a new compile.
                
```

**Comment by oharboe** [comment]
I upgraded to Scala Metals plugin v1.9.2 and now it works again.

I have no idea if this is because the problem is fixed in v1.9.2 or if it because the upgrade process purged some poisoned tmp file.

I'm closing this issue now on the assumption that it is fixed in v1.9.2. If I or someone else run into this with v1.9.2, it's time to try to investigate some more.
