### ISSUE TITLE
sbt publishLocal failed

### ISSUE THREAD

**Issue by vasily-kirichenko** [scalameta/metals#203]
```
[info] Done compiling.
[info] Packaging E:\github\metals\lsp4s\target\scala-2.12\lsp4s_2.12-0.1-SNAPSHOT.jar ...
[info] Done packaging.
[info] :: delivering :: org.scalameta#lsp4s_2.12;0.1-SNAPSHOT :: 0.1-SNAPSHOT :: integration :: Thu Mar 08 13:27:37 MSK 2018
[info]  delivering ivy file to E:\github\metals\lsp4s\target\scala-2.12\ivy-0.1-SNAPSHOT.xml
[info]  published lsp4s_2.12 to C:\Users\vaski\.ivy2\local\org.scalameta\lsp4s_2.12\0.1-SNAPSHOT\poms\lsp4s_2.12.pom
[info]  published lsp4s_2.12 to C:\Users\vaski\.ivy2\local\org.scalameta\lsp4s_2.12\0.1-SNAPSHOT\jars\lsp4s_2.12.jar
[info]  published ivy to C:\Users\vaski\.ivy2\local\org.scalameta\lsp4s_2.12\0.1-SNAPSHOT\ivys\ivy.xml
[error] java.lang.RuntimeException: protoc returned exit code: 1
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:139)
[error]         at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:180)
[error]         at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$4(ProtocPlugin.scala:184)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$1(ProtocPlugin.scala:190)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] (metals / Compile / protocGenerate) protoc returned exit code: 1
[error] Total time: 43 s, completed Mar 8, 2018 1:27:37 PM
```

**Comment by vasily-kirichenko** [comment]
I think I need protobuf compiler installed in path?

**Comment by vasily-kirichenko** [comment]
No, protoc is in path.

**Comment by vasily-kirichenko** [comment]
Trying to use it in Code fails:

```
[2KDownloaded 1 missing file(s) / 1
[1A[2KDownloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml

Error:
  org.scalameta:metals_2.12:0.1-SNAPSHOT
    not found: C:\Users\vaski\.ivy2\local\org.scalameta\metals_2.12\0.1-SNAPSHOT\ivys\ivy.xml
    not found: https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
    not found: https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
[Info  - 1:37:23 PM] Connection to server got closed. Server will restart.
[2KDownloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1

Error:
  org.scalameta:metals_2.12:0.1-SNAPSHOT
    not found: C:\Users\vaski\.ivy2\local\org.scalameta\metals_2.12\0.1-SNAPSHOT\ivys\ivy.xml
    not found: https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
    not found: https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
[Info  - 1:37:25 PM] Connection to server got closed. Server will restart.
[2KDownloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml

Error:
  org.scalameta:metals_2.12:0.1-SNAPSHOT
    not found: C:\Users\vaski\.ivy2\local\org.scalameta\metals_2.12\0.1-SNAPSHOT\ivys\ivy.xml
    not found: https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
    not found: https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
[Info  - 1:37:28 PM] Connection to server got closed. Server will restart.
[2KDownloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml

Error:
  org.scalameta:metals_2.12:0.1-SNAPSHOT
    not found: C:\Users\vaski\.ivy2\local\org.scalameta\metals_2.12\0.1-SNAPSHOT\ivys\ivy.xml
    not found: https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
    not found: https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
[Info  - 1:37:30 PM] Connection to server got closed. Server will restart.
[2KDownloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/maven-metadata.xml.sha1

Error:
  org.scalameta:metals_2.12:0.1-SNAPSHOT
    not found: C:\Users\vaski\.ivy2\local\org.scalameta\metals_2.12\0.1-SNAPSHOT\ivys\ivy.xml
    not found: https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
    not found: https://oss.sonatype.org/content/repositories/releases/org/scalameta/metals_2.12/0.1-SNAPSHOT/metals_2.12-0.1-SNAPSHOT.pom
[Error - 1:37:33 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by daniil-timofeev** [comment]
I have the same error message, while trying to publish local project. Additionally, i have the following log messages:
```
[info] Compiling schema C:\Users\...\source\metals\metals\src\main\protobuf\metaserver.proto
protoc-jar: protoc version: 340, detected platform: windows 7/amd64
protoc-jar: executing: [C:\Users\...\AppData\Local\Temp\protocjar13148992946843286079\bin\protoc.exe, --plugin=protoc-gen-scala=C:\Users\...\AppData\Local\Temp\protocbridge18238242221672954552.bat, --scala_out=flat_package,grpc:C:\Users\...\source\metals\metals\target\scala-2.12\src_managed\main\protobuf, -IC:\Users\...\source\metals\metals\src\main\protobuf, -IC:\Users\...\source\metals\metals\target\protobuf_external, C:\Users\...\source\metals\metals\src\main\protobuf\metaserver.proto]
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Temp\protocbridge11848641482550743167.py", **line 6, in <module>
    s.sendall(content)**
**TypeError: a bytes-like object is required, not 'str'**
--scala_out: protoc-gen-scala: Plugin failed with status code 1.
```

**Comment by olafurpg** [comment]
Thanks for reporting! The issue seems to be that the protobuf code generation with scalapb does not work on windows 🤔 We use scalapb in the scalameta repo and run our tests on windows with no problems. What version of python do you have installed?

**Comment by olafurpg** [comment]
Our CI btw releases artifacts to bintray on every merge so you can skip the `sbt publishLocal` step by using these instead https://bintray.com/scalameta/maven/metals/b8b681d4

**Comment by olafurpg** [comment]
A workaround is to use pre-built artifacts from our bintray resolver https://bintray.com/scalameta/maven/metals

The build uses scalapb with default settings so I'm not sure how to fix this problem on our side https://scalapb.github.io/
