### ISSUE TITLE
exception from worksheets

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals#2032]
create worksheet, paste content:

```scala
println(s"WORK ${1 + 3

def add(a: Int, b: Int): Int = a + b

add(add(3, 5), 11)
```
Exception:
```
java.lang.ArrayIndexOutOfBoundsException: Index 55 out of bounds for length 55
	at scala.meta.internal.tokenizers.ScalametaTokenizer.curr$1(ScalametaTokenizer.scala:174)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.emitContents$1(ScalametaTokenizer.scala:222)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(ScalametaTokenizer.scala:254)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:304)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.$anonfun$tokenize$1(ScalametaTokenizer.scala:16)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:16)
	at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:316)
	at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:25)
	at scala.meta.internal.metals.TokenEditDistance$.apply(TokenEditDistance.scala:296)
	at scala.meta.internal.metals.Diagnostics.publishDiagnostics(Diagnostics.scala:191)
	at scala.meta.internal.metals.Diagnostics.onPublishDiagnostics(Diagnostics.scala:165)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:283)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.liftedTree1$1(WorksheetProvider.scala:164)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:164)
```

---

Not a big problem as code is incorrect but still it would be nice not to see exception.
(and in emacs it complains 'Internal Server Error' as you type so you think something is wrong)

**Comment by tgodzik** [comment]
Thanks for reporting, this is an issue with a broken tokenizer. I think in this case we might add a try and:
- set the edit distance as unchanged (not perfect)
- artificially add a fix and rerun
- set the edit distance as no match - though we would need to handle diagnostics differently in that case

Most likely third option is the safest.

**Comment by tgodzik** [comment]
Or we should add a fallback tokenizer maybe? That doesn't parse whole strings but just single quotes? This would help with other similar situations.
