### ISSUE TITLE
Metals on visual studio code fails to connect to BSP server

### ISSUE THREAD

**Issue by filosganga** [scalameta/metals#2074]
**Describe the bug**
After importing a project in VSC, as soon as I try to autocomplete a statements, metals says that fails to connect to the server.

**To Reproduce**
1. Import a project
2. write (for example) `fs2.` and hit ctr+space
4. The output screen shows: 
```
2020.09.17 11:17:43 WARN  no build target for: /Users/filippo.deluca/Documents/Development/OVO/comms-scripts/modules/kafka/src/main/scala/kafka/tools/FeedbackForCommId.scala
2020.09.17 11:19:40 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Expected behavior**
When hitting `ctr`+`space` the possible completions will appear

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.3

Logs:
```
2020.09.17 11:12:50 INFO  started: Metals version 0.9.3 in workspace '/Users/filippo.deluca/Documents/Development/OVO/comms-scripts' for client vscode.
2020.09.17 11:12:50 INFO  time: initialize in 0.55s
2020.09.17 11:12:51 INFO  no build target: using presentation compiler with only scala-library
2020.09.17 11:12:53 WARN  no build target for: /Users/filippo.deluca/Documents/Development/OVO/comms-scripts/modules/kafka/src/main/scala/kafka/tools/KafkaTools.scala
2020.09.17 11:12:53 WARN  no build target for: /Users/filippo.deluca/Documents/Development/OVO/comms-scripts/modules/kafka/src/main/scala/kafka/tools/FeedbackForCommId.scala
2020.09.17 11:15:31 INFO  running '/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/1c/0g_dhcfd2hz_9w3_b2cr8kkr0000gp/T/metals4542619441763224251/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
2020.09.17 11:15:31 INFO  skipping build import with status 'Started'
2020.09.17 11:15:36 INFO  [info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_111)
2020.09.17 11:15:37 INFO  [info] loading settings for project global-plugins from updates.sbt,idea.sbt,dependency-graph.sbt,scalafix.sbt ...
2020.09.17 11:15:37 INFO  [info] loading global plugins from /Users/filippo.deluca/.sbt/1.0/plugins
2020.09.17 11:15:41 INFO  [info] loading settings for project comms-scripts-build-build-build from metals.sbt ...
2020.09.17 11:15:41 INFO  [info] loading project definition from /Users/filippo.deluca/Documents/Development/OVO/comms-scripts/project/project/project
2020.09.17 11:15:42 INFO  [info] loading settings for project comms-scripts-build-build from metals.sbt ...
2020.09.17 11:15:42 INFO  [info] loading project definition from /Users/filippo.deluca/Documents/Development/OVO/comms-scripts/project/project
2020.09.17 11:15:45 INFO  [success] Generated .bloop/comms-scripts-build-build.json
2020.09.17 11:15:45 INFO  [success] Total time: 3 s, completed 17-Sep-2020 11:15:45
2020.09.17 11:15:45 INFO  [info] loading settings for project comms-scripts-build from plugins.sbt,metals.sbt ...
2020.09.17 11:15:45 INFO  [info] loading project definition from /Users/filippo.deluca/Documents/Development/OVO/comms-scripts/project
2020.09.17 11:15:46 INFO  [success] Generated .bloop/comms-scripts-build.json
2020.09.17 11:15:46 INFO  [success] Total time: 1 s, completed 17-Sep-2020 11:15:47
2020.09.17 11:15:46 INFO  [info] loading settings for project tools from build.sbt ...
2020.09.17 11:15:48 INFO  [info] set current project to tools (in build file:/Users/filippo.deluca/Documents/Development/OVO/comms-scripts/)
2020.09.17 11:15:48 INFO  [info] Formatting 1 Scala sources...
2020.09.17 11:15:48 INFO  [success] Generated .bloop/tools.json
2020.09.17 11:15:48 INFO  [success] Generated .bloop/tools-test.json
2020.09.17 11:15:49 INFO  [success] Generated .bloop/common.json
2020.09.17 11:15:49 INFO  [success] Generated .bloop/common-test.json
2020.09.17 11:15:49 INFO  [success] Generated .bloop/dynamodb-test.json
2020.09.17 11:15:49 INFO  [success] Generated .bloop/dynamodb.json
2020.09.17 11:15:49 INFO  [success] Generated .bloop/kafka-test.json
2020.09.17 11:15:49 INFO  [success] Generated .bloop/resend-test.json
2020.09.17 11:15:49 INFO  [success] Generated .bloop/resend.json
2020.09.17 11:15:52 INFO  [success] Generated .bloop/kafka.json
2020.09.17 11:15:52 INFO  [success] Total time: 4 s, completed 17-Sep-2020 11:15:52
2020.09.17 11:15:53 INFO  time: ran 'sbt bloopInstall' in 21s
2020.09.17 11:15:52 INFO  build tool exit: 0
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/1c/0g_dhcfd2hz_9w3_b2cr8kkr0000gp/T/bsp-launcher2907507056632826844/bsp.socket'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 27450'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.09.17 11:17:09 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2020.09.17 11:17:43 WARN  no build target for: /Users/filippo.deluca/Documents/Development/OVO/comms-scripts/modules/kafka/src/main/scala/kafka/tools/FeedbackForCommId.scala
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/1c/0g_dhcfd2hz_9w3_b2cr8kkr0000gp/T/bsp-launcher2178246787611434532/bsp.socket'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 42370'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.09.17 11:19:40 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by tgodzik** [comment]
Thanks for reporting! This kind of problems usually have to do with the java version. Bloop tries to use the java executable from PATH, but might be failing to run it. Is there anything specific about your configuration maybe?

I just fixed an issue in Bloop that caused no logs to be written, which should be useful in the future, but for now if the java executable works correctly then a workaround could be to install Bloop manually https://scalacenter.github.io/bloop/setup

**Comment by tgodzik** [comment]
The current version of Bloop should print more info when failing to start @filosganga could you retry?

**Comment by filosganga** [comment]
It has solved by itself the next couple of days. No idea how 🧐

**Comment by tgodzik** [comment]
That's good! Not so good for us since I can't see to make it work 100%. Well, we do need some better diagnostics here to figure out what is going on. I will work on that in https://github.com/scalameta/metals/issues/2093

Thanks for coming back to us!
