### ISSUE TITLE
NullPointerException on completion

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/metals#2096]
**Describe the bug**

```
Sep 25, 2020 10:52:48 AM scala.meta.internal.pc.completions.Completions completionPosition
SEVERE: null
java.lang.NullPointerException
        at scala.meta.internal.pc.completions.OverrideCompletions$OverrideCompletion.<init>(OverrideCompletions.scala:46)
        at scala.meta.internal.pc.completions.Completions.completionPositionUnsafe(Completions.scala:500)
        at scala.meta.internal.pc.completions.Completions.completionPositionUnsafe$(Completions.scala:409)
        at scala.meta.internal.pc.MetalsGlobal.completionPositionUnsafe(MetalsGlobal.scala:29)
        at scala.meta.internal.pc.completions.Completions.completionPosition(Completions.scala:401)
        at scala.meta.internal.pc.completions.Completions.completionPosition$(Completions.scala:386)
        at scala.meta.internal.pc.MetalsGlobal.completionPosition(MetalsGlobal.scala:29)
        at scala.meta.internal.pc.CompletionProvider.safeCompletionsAt(CompletionProvider.scala:444)
        at scala.meta.internal.pc.CompletionProvider.completions(CompletionProvider.scala:57)
        at scala.meta.internal.pc.ScalaPresentationCompiler.$anonfun$complete$1(ScalaPresentationCompiler.scala:184)
        at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
        at scala.meta.internal.pc.CompilerAccess.$anonfun$withInterruptableCompiler$1(CompilerAccess.scala:87)
        at scala.meta.internal.pc.CompilerAccess.$anonfun$onCompilerJobQueue$1(CompilerAccess.scala:197)
        at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:103)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

No more data in the client stdin, exiting...

Vim: Double signal, exiting
                           zsh: segmentation fault
```

**To Reproduce**

1. Go to some scala project
2. Do completion here or there
3. Be lucky enough to observe the error

**Expected behavior**

No `NullPointerException`

**Installation:**

- Operating system: Linux
- Editor: Vim (coc-metals 0.9.5)
- Metals version: v0.9.4

**Search terms**

**Comment by kpbochenek** [comment]
Error looks similar to one here: https://github.com/scalameta/metals/issues/1831

**Comment by kpbochenek** [comment]
This is in `mtags` which are specific for every scala version, could you provide exact scalaVersion you are using?

**Comment by arbitrary-dev** [comment]
```
$ sbt scalaVersion
[info] welcome to sbt 1.3.13 (Gentoo Java 11.0.8)
[info] scalaVersion
[info] 	2.13.3
```

**Comment by tgodzik** [comment]
Thanks for reporting! Do you have maybe a sample code that this exception is thrown on? We haven't been able to properly reproduce it before.

Alternatively, we could add a try around `val isDecl: Set[Symbol] = typed.tpe.decls.toSet`, but it would nice to figure out what is exactly happening.

**Comment by arbitrary-dev** [comment]
Unable to reproduce it stably, happens randomly.

**Comment by tgodzik** [comment]
`isDecl` is now removed, so this exception should not pop up again.
