### ISSUE TITLE
`NoClassDefFoundError` when hovering on a comment or empty space from the SyntheticsDecorationProvider

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2131]
**Describe the bug**

I haven't been able to nail down exactly what's happening here yet, and I can't get it to happen consistently. However, it's happened a few times now and I've noticed that every time it was when an accidental hover happened while developing. I'll keep trying to reproduce this in a minimal way, but figured it'd submit an issue because I have seen the exact same thing a few times now.

```
Exception in thread "pool-1-thread-94" java.lang.NoClassDefFoundError: scala/meta/internal/decorations/SemanticdbTreePrinter$
        at scala.meta.internal.decorations.SyntheticsDecorationProvider.$anonfun$addSyntheticsHover$4(SyntheticsDecorationProvider.scala:109)
        at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:905)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:904)
        at scala.meta.internal.decorations.SyntheticsDecorationProvider.$anonfun$addSyntheticsHover$2(SyntheticsDecorationProvider.scala:107)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:292)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:289)
        at scala.collection.immutable.List.flatMap(List.scala:394)
        at scala.meta.internal.decorations.SyntheticsDecorationProvider.$anonfun$addSyntheticsHover$1(SyntheticsDecorationProvider.scala:106)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:292)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:289)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at scala.meta.internal.decorations.SyntheticsDecorationProvider.addSyntheticsHover(SyntheticsDecorationProvider.scala:105)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$hover$2(MetalsLanguageServer.scala:1171)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.meta.internal.decorations.SemanticdbTreePrinter$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 32 more
```

**To Reproduce**

1. Have same valid code with a comment or empty line
2. Do a hover a comment or empty line
3. I can't get it to happen all the time, but at times, you'll see the exception above.

**Expected behavior**

I'd never expect to see an exception like this in the logs. The only reason I noticed it the first and consecutive times is because it locks up Metals for me and I have to kill the process.

**Installation:**

- Operating system: Mac
- Editor: Vim
- Metals version: Anything since the synthetics feature was added

**Additional context**

I am using a client that is not a inline-decoration provider, so it's reliant on the sythentic-in-hover functionality as you can see in the stack trace.

For what it's worth, every time this has happened to me it's been when working on the Metals codebase.

**Search terms**

Synthetics-in-hover

**Comment by tgodzik** [comment]
Thanks for reporting! I don't think this is really possible unless you are modifying the jar itself. I've seen issues like that when running publishLocal at the same time and this is expected. Otherwise, the class does exist and is not loaded in any weird way, so I have no explanation here.

**Comment by ckipp01** [comment]
🤔 maybe that's the case then since I've only noticed it while working on Metals. I'll close then. If I see it happen somewhere when I'm not working on Metals I'm reopen.
