### ISSUE TITLE
Syntax Error not highlighted/found

### ISSUE THREAD

**Issue by danielpopescu** [scalameta/metals#2136]
In this example code:

object Bug {

 def foo() = { 1 }

  def main(args : Array[String]) = {
    pri ntln(foo())
  }

}

The "pri ntln" should be highlighted as a syntax  error. Furthermore, hovering over foo or trying to use go to definition for foo is broken.

Remove the space in "pri ntln" and it works again.

Using 0.9.4 version (latest snapshot as of Oct 14) + emacs + Scala 2.13.3 + sbt 1.4.0

**Comment by tgodzik** [comment]
Thanks for reporting!

I used your code snippet and error seems to be correctly highlighted:

![image](https://user-images.githubusercontent.com/3807253/95979691-530a7700-0e1c-11eb-9ad1-ab9427184940.png)

What is the issue you are having?

**Comment by danielpopescu** [comment]
Hmm... I do not get that highlighting in emacs (maybe is an emacs/lsp/lsp-emacs issue?). I am on latest everything (including emacs 27). I get a lot of errors highlighted (so it is not like not working at all) but not the above error. Also, go-to definition for foo doesn't work in this scenario.

**Comment by tgodzik** [comment]
Go to definition does work for me. Did you save the file after splitting `println` ? It is not really a syntax error since we can have expression like that and only after saving it should show up a message from the compiler.

**Comment by danielpopescu** [comment]
Yes. I did save it. As far as if it is an error... compiling the code fails, so it should be flagged as an error (agreed, after save):

[error] test.scala:8:5: not found: value pri
[error]     pri ntln(foo())
[error]     ^
[error] one error found
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[

**Comment by tgodzik** [comment]
The other option is that it's outside sources or we didn't manage to connect to the build server. Could you copy the logs from `.metals/metals.log` ?

**Comment by danielpopescu** [comment]
[metals.log](https://github.com/scalameta/metals/files/5377795/metals.log)

**Comment by tgodzik** [comment]
I do see a message like this:
`2020.10.12 13:46:20 ERROR Unexpected error when compiling scala_thinkstats: 'object java.lang.Object in compiler mirror not found.'`

which most likely means the code hasn't really compiled. That is usually connected to a corrupted or missing jar. Maybe you could try rerunning build import? Or try clean you coursier caches? Not exactly sure what could cause it in this situation.

**Comment by danielpopescu** [comment]
I did reimport. It doesn't work...

This might be the issue:

2020.10.14 07:39:03 INFO  running '/Library/Java/JavaVirtualMachines/jdk-15.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/tr/m81smtld7w396g3m0mc5j8sc0000gn/T/metals3219181155221551823/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
2020.10.14 07:39:04 ERROR Timeout waiting for 'build/initialize' response
2020.10.14 07:39:04 ERROR Failed to connect with build server, no functionality will work.

is java 15 an issue?

**Comment by tgodzik** [comment]
@danielpopescu I think Scala does not yet work properly with 15 and we only test metals with latest 8 and 11, so those are safest choices.

**Comment by danielpopescu** [comment]
Here's a longer output from lsp-log

Cancelling textDocument/codeAction(17) in hook post-command-hook
2020.10.14 07:39:03 INFO  no build target: using presentation compiler with only scala-library
2020.10.14 07:39:03 INFO  no build target: using presentation compiler with only scala-library
2020.10.14 07:39:03 WARN  no build target for: /Users/dpo/projects/scala_thinkstats/src/main/scala/problems/Problems.scala
2020.10.14 07:39:03 WARN  no build target for: /Users/dpo/projects/scala_thinkstats/src/main/scala/problems/LinkedList.scala
2020.10.14 07:39:03 WARN  no build target for: /Users/dpo/projects/scala_thinkstats/src/main/scala/problems/test.scala
2020.10.14 07:39:03 INFO  running '/Library/Java/JavaVirtualMachines/jdk-15.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/tr/m81smtld7w396g3m0mc5j8sc0000gn/T/metals3219181155221551823/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
2020.10.14 07:39:04 ERROR Timeout waiting for 'build/initialize' response
2020.10.14 07:39:04 ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1950)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2085)
	at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:317)
	at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:252)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(Thread.java:832)

2020.10.14 07:39:05 INFO  [info] welcome to sbt 1.4.0 (Oracle Corporation Java 15)
2020.10.14 07:39:06 INFO  time: indexed workspace in 6.42s
2020.10.14 07:39:06 INFO  [info] loading settings for project scala_thinkstats-build-build from metals.sbt ...
2020.10.14 07:39:06 INFO  [info] loading project definition from /Users/dpo/projects/scala_thinkstats/project/project
2020.10.14 07:39:08 INFO  [info] loading settings for project scala_thinkstats-build from metals.sbt ...
2020.10.14 07:39:08 INFO  [info] loading project definition from /Users/dpo/projects/scala_thinkstats/project
2020.10.14 07:39:10 INFO  [success] Generated .bloop/scala_thinkstats-build.json
2020.10.14 07:39:10 INFO  [success] Total time: 2 s, completed Oct 14, 2020, 7:39:10 AM
2020.10.14 07:39:12 INFO  [info] loading settings for project scala_thinkstats from build.sbt ...
2020.10.14 07:39:12 INFO  [info] set current project to ThinkStats (in build file:/Users/dpo/projects/scala_thinkstats/)
2020.10.14 07:39:12 INFO  [success] Generated .bloop/scala_thinkstats-test.json
2020.10.14 07:39:12 INFO  [success] Generated .bloop/scala_thinkstats.json
2020.10.14 07:39:12 INFO  [success] Total time: 1 s, completed Oct 14, 2020, 7:39:13 AM
2020.10.14 07:39:12 INFO  build tool exit: 0
2020.10.14 07:39:13 INFO  time: ran 'sbt bloopInstall' in 9.88s
2020.10.14 07:39:13 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/dpo/Library/Caches/org.scalameta.metals/bsp.trace.json
2020.10.14 07:39:13 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/dpo/Library/Caches/org.scalameta.metals/bsp.trace.json
2020.10.14 07:39:13 INFO  Connected to Build server v1.4.4-13-408f4d80
Creating watch for /Users/dpo/projects/scala_thinkstats/src/main/scala-2.13
Creating watch for /Users/dpo/projects/scala_thinkstats/src/main/scala-2
Creating watch for /Users/dpo/projects/scala_thinkstats/src/main/java
Creating watch for /Users/dpo/projects/scala_thinkstats/project/src
Creating watch for /Users/dpo/projects/scala_thinkstats/project/src/main
Creating watch for /Users/dpo/projects/scala_thinkstats/project/src/main/java
Creating watch for /Users/dpo/projects/scala_thinkstats/project/src/main/scala
Creating watch for /Users/dpo/projects/scala_thinkstats/project/src/main/scala-2
Creating watch for /Users/dpo/projects/scala_thinkstats/project/src/main/scala-2.12
Creating watch for /Users/dpo/projects/scala_thinkstats/project/src/main/scala-sbt-1.0
Creating watch for /Users/dpo/projects/scala_thinkstats/src/test/scala-2.13
Creating watch for /Users/dpo/projects/scala_thinkstats/src/test/scala-2
Creating watch for /Users/dpo/projects/scala_thinkstats/src/test/scala
Creating watch for /Users/dpo/projects/scala_thinkstats/src/test/java
2020.10.14 07:39:16 INFO  time: indexed workspace in 2.82s
2020.10.14 07:39:16 INFO  compiling scala_thinkstats (6 scala sources)
2020.10.14 07:39:16 INFO  time: compiled scala_thinkstats in 0.34s
2020.10.14 07:39:16 ERROR Unexpected error when compiling scala_thinkstats: 'object java.lang.Object in compiler mirror not found.'

**Comment by danielpopescu** [comment]
> @danielpopescu I think Scala does not yet work properly with 15 and we only test metals with latest 8 and 11, so those are safest choices.

Ok. I will revert back to jdk14. I don't remember having issues with that

**Comment by danielpopescu** [comment]
Unfortunately, still not working.... using latest jdk 11. here's the import log:
2020.10.14 08:04:56 INFO  running '/Library/Java/JavaVirtualMachines/jdk-11.0.8.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/tr/m81smtld7w396g3m0mc5j8sc0000gn/T/metals7848099915692639474/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
2020.10.14 08:04:57 INFO  [info] welcome to sbt 1.4.0 (Oracle Corporation Java 11.0.8)
2020.10.14 08:04:57 INFO  [info] loading settings for project scala_thinkstats-build-build from metals.sbt ...
2020.10.14 08:04:58 INFO  [info] loading project definition from /Users/dpo/projects/scala_thinkstats/project/project
2020.10.14 08:04:58 INFO  [info] loading settings for project scala_thinkstats-build from metals.sbt ...
2020.10.14 08:04:58 INFO  [info] loading project definition from /Users/dpo/projects/scala_thinkstats/project
2020.10.14 08:05:00 INFO  [success] Generated .bloop/scala_thinkstats-build.json
2020.10.14 08:05:00 INFO  [success] Total time: 1 s, completed Oct 14, 2020, 8:05:00 AM
2020.10.14 08:05:00 INFO  [info] loading settings for project scala_thinkstats from build.sbt ...
2020.10.14 08:05:00 INFO  [info] set current project to ThinkStats (in build file:/Users/dpo/projects/scala_thinkstats/)
2020.10.14 08:05:00 INFO  [success] Generated .bloop/scala_thinkstats-test.json
2020.10.14 08:05:00 INFO  [success] Generated .bloop/scala_thinkstats.json
2020.10.14 08:05:00 INFO  [success] Total time: 0 s, completed Oct 14, 2020, 8:05:01 AM
2020.10.14 08:05:00 INFO  build tool exit: 0
2020.10.14 08:05:01 INFO  time: ran 'sbt bloopInstall' in 5.14s
2020.10.14 08:05:01 INFO  disconnected: build server
2020.10.14 08:05:01 INFO  tracing is enabled: /Users/dpo/Library/Caches/org.scalameta.metals/bsp.trace.json
2020.10.14 08:05:01 INFO  tracing is enabled: /Users/dpo/Library/Caches/org.scalameta.metals/bsp.trace.json
2020.10.14 08:05:01 INFO  Connected to Build server v1.4.4-13-408f4d80
2020.10.14 08:05:01 INFO  time: indexed workspace in 0.88s
2020.10.14 08:05:02 INFO  compiling scala_thinkstats (6 scala sources)
2020.10.14 08:05:02 INFO  time: compiled scala_thinkstats in 15ms
2020.10.14 08:05:02 ERROR Unexpected error when compiling scala_thinkstats: 'object java.lang.Object in compiler mirror not found.'

**Comment by tgodzik** [comment]
Bloop might still be using JDK15, it uses whatever is on path. You might modify it via https://scalacenter.github.io/bloop/docs/server-reference#custom-java-home

The other options is that maybe some jars indeed were corrupted? I am not sure exactly, this is a pretty enigmatic error. Could you maybe provide a build definition it doesn't work with? Scala version, sbt version etc.

**Comment by danielpopescu** [comment]
I removed jdk 15 on my system, so it cannot use it. I only have jdk11 installed (and jdk 8 that cames with macOS Catalina).

scala 2.13 and sbt 1.4.0

**Comment by tgodzik** [comment]
Nothing pops up as an issue. Did you try cleaning the caches?

Maybe try removing:
- `~/.cache/bloop/` or specifically on MacOS it could be something like `~/Library/Caches/Bloop`,
- `.bloop` directory in the workspace

Not sure if that helps :/ 

The error might have something to do with your environment and that might be hard to figure out on our side.

**Comment by danielpopescu** [comment]
So I cleared the ~/LIbrary/Caches/bloop... and now, I get this in my metals.log:

2020.10.14 08:58:35 ERROR /Users/dpo/Library/Caches/bloop/semanticdb/org.scalameta.semanticdb-scalac_2.13.3.4.3.22/semanticdb-scalac_2.13.3-4.3.22.jar
java.nio.file.FileSystemNotFoundException: /Users/dpo/Library/Caches/bloop/semanticdb/org.scalameta.semanticdb-scalac_2.13.3.4.3.22/semanticdb-scalac_2.13.3-4.3.22.jar
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:120)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:104)
	at scala.meta.internal.io.PlatformFileIO$.newJarFileSystem(PlatformFileIO.scala:100)
	at scala.meta.internal.io.PlatformFileIO$.withJarFileSystem(PlatformFileIO.scala:77)
	at scala.meta.internal.io.FileIO$.withJarFileSystem(FileIO.scala:44)
	at scala.meta.internal.metals.CompilerPlugins.liftedTree1$1(CompilerPlugins.scala:65)
	at scala.meta.internal.metals.CompilerPlugins.isSupportedPlugin(CompilerPlugins.scala:64)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$2(CompilerPlugins.scala:46)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1(CompilerPlugins.scala:46)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1$adapted(CompilerPlugins.scala:43)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:303)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:302)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:296)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:394)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:394)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at scala.meta.internal.metals.CompilerPlugins.filterSupportedOptions(CompilerPlugins.scala:43)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:605)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:582)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompilerForTarget$3(Compilers.scala:469)
	at scala.meta.internal.metals.StatusBar.trackBlockingTask(StatusBar.scala:46)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompilerForTarget$2(Compilers.scala:469)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at scala.meta.internal.metals.Compilers.loadCompilerForTarget(Compilers.scala:465)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$4(Compilers.scala:452)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.loadCompiler(Compilers.scala:452)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3(Compilers.scala:140)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3$adapted(Compilers.scala:139)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.Compilers.$anonfun$load$1(Compilers.scala:139)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020.10.14 08:58:35 INFO  time: compiled scala_thinkstats in 0.39s
2020.10.14 08:58:35 ERROR Unexpected error when compiling scala_thinkstats: 'xsbt.CompilerInterface'
2020.10.14 08:58:35 ERROR /Users/dpo/Library/Caches/bloop/semanticdb/org.scalameta.semanticdb-scalac_2.12.12.4.3.22/semanticdb-scalac_2.12.12-4.3.22.jar
java.nio.file.FileSystemNotFoundException: /Users/dpo/Library/Caches/bloop/semanticdb/org.scalameta.semanticdb-scalac_2.12.12.4.3.22/semanticdb-scalac_2.12.12-4.3.22.jar
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:120)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:104)
	at scala.meta.internal.io.PlatformFileIO$.newJarFileSystem(PlatformFileIO.scala:100)
	at scala.meta.internal.io.PlatformFileIO$.withJarFileSystem(PlatformFileIO.scala:77)
	at scala.meta.internal.io.FileIO$.withJarFileSystem(FileIO.scala:44)
	at scala.meta.internal.metals.CompilerPlugins.liftedTree1$1(CompilerPlugins.scala:65)
	at scala.meta.internal.metals.CompilerPlugins.isSupportedPlugin(CompilerPlugins.scala:64)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$2(CompilerPlugins.scala:46)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1(CompilerPlugins.scala:46)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1$adapted(CompilerPlugins.scala:43)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:303)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:302)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:296)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:394)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:394)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at scala.meta.internal.metals.CompilerPlugins.filterSupportedOptions(CompilerPlugins.scala:43)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:605)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:582)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompilerForTarget$3(Compilers.scala:469)
	at scala.meta.internal.metals.StatusBar.trackBlockingTask(StatusBar.scala:46)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompilerForTarget$2(Compilers.scala:469)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at scala.meta.internal.metals.Compilers.loadCompilerForTarget(Compilers.scala:465)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$4(Compilers.scala:452)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.loadCompiler(Compilers.scala:452)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3(Compilers.scala:140)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3$adapted(Compilers.scala:139)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.Compilers.$anonfun$load$1(Compilers.scala:139)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by danielpopescu** [comment]
One weird things is the exceptions themself. Secondly, why is it even looking for Scala 2.12... I only have Scala 2.13 installed and in my build.sbt I have:
scalaVersion := "2.13.3"

**Comment by tgodzik** [comment]
That should get downloaded automatically, maybe reimport the build and restart the build server? It's possible via command `metals.build-restart`

**Comment by tgodzik** [comment]
> One weird things is the exceptions themself. Secondly, why is it even looking for Scala 2.12... I only have Scala 2.13 installed and in my build.sbt I have:
> scalaVersion := "2.13.3"

Och, that is also weird. That is the default version, what file are you trying to compile?

**Comment by danielpopescu** [comment]
so, after cleaning up bloop caches, clean up project target & caches, reinstall metals and computer restart, things work again fine. Thanks!

The only "problem" (it doesn't seem to affect anything) is that, when I run metal doctor,I get this:

These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

  Build target  Scala  Diagnostics  Goto definition  Completions  Find references  Recommendation    
  scala_thinkstats-test  2.13.3  ✅   ✅   ✅   ✅       
  scala_thinkstats  2.13.3  ✅   ✅   ✅   ✅       
  scala_thinkstats-build  2.12.12  ✅   ✅   ✅   ✅       


Not sure where the 2.12 target is coming from?
