### ISSUE TITLE
Emacs Metals complains about using scala 2.10.7 when the project is not using it

### ISSUE THREAD

**Issue by ashkan-leo** [scalameta/metals#2167]
**Describe the bug**
I have a Scala 2.11.12 project. I use Metals with Emacs to do my work. Recently, I updated Emacs and Metals. When I do build-import, I don't have any auto completion and the log says "Unsupported Scala 2.10.7". The lsp-metals-doctor-run shows the following:

```
Metals Doctor

Build server currently used: Bloop.

These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

  Build target  Scala  Diagnostics  Goto definition  Completions  Find references  Recommendation    
  root  2.11.12  ✅   ✅   ✅   ✅   This Scala version might not be supported in upcoming versions of Metals, please upgrade to Scala 2.12.12.    
  root-test  2.11.12  ✅   ✅   ✅   ✅   This Scala version might not be supported in upcoming versions of Metals, please upgrade to Scala 2.12.12.    
  meng-build  2.10.7  ✅   ⚠️   ⚠️   ⚠️   Code navigation is not supported for this compiler version, change to Scala 2.13.3 or 2.12.12 and run 'Build import' to enable code navigation.    
  meng-build-build  2.10.7  ✅   ⚠️   ⚠️   ⚠️   Code navigation is not supported for this compiler version, change to Scala 2.13.3 or 2.12.12 and run 'Build import' to enable code navigation.    

```

**To Reproduce**

1. Open a Scala project in Emacs.
2. do lsp-metals-build-import
3. do lsp-metals-doctor-run
4. observe the additional projects that use Scala 2.10 are added to the list.

**Expected behavior**
Metals should infer the versions correctly.

**Screenshots**

**Installation:**

- Operating system: macOS
- Editor: Emacs
- Metals version: v0.9.4 and 0.9.4+104-85ff9dc0-SNAPSHOT

**Additional context**

**Search terms**

**Comment by ckipp01** [comment]
Thanks for reporting @ashkan-leo. This is actually expected. Depending on what version you updated from, v0.9.3 introduces support for hover, completions, and goto-definition in your sbt files. So the two extra targets you see listed `meng-build` and `meng-build-build` are actually the targets for you build definition and metabuild. Since you're on 2.11.12, I assume you may be using an old version of sbt as well, and the version of Scala that that version of sbt uses in 2.10.7. Since Metals doesn't support that version of Scala, you'll see the warnings.

If you're able to, you could bump your version of sbt to a newer one, which should make those errors go away.

As an aside, you're not the first one to ask this question, so it might be a good idea to document this better.

**Comment by ashkan-leo** [comment]
Thanks @ckipp01. I upgraded to SBT 1.4.1 and now I'm getting this when I run metals-doctor:

Metals Doctor

Build server currently used: Bloop.

These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two
build targets: main and test.

  Build target  Scala  Diagnostics  Goto definition  Completions  Find references  Recommendation    
  root  2.11.12  ✅   ✅   ✅   ✅   This Scala version might not be supported in upcoming    
              versions of Metals, please upgrade to Scala 2.12.12.    
  root-test  2.11.12  ✅   ✅   ✅   ✅   This Scala version might not be supported in upcoming    
              versions of Metals, please upgrade to Scala 2.12.12.    
  meng-build  2.12.12  ✅   ✅   ✅   ✅       
  project-build  2.12.7  ✅   ⚠️   ⚠️   ⚠️   Upgrade to Scala 2.12.12 and run 'Build import' to    
              enable code navigation.    

Autocomplete still doesn't work.

**Comment by ckipp01** [comment]
🤔 so the 2.12.7 looks a bit fishy. Is it actually called `project-build`? I'd expect this to be `meng-build-build` again like your first example. The version should also be 2.12.12 there to match `meng-build`.

**Comment by tgodzik** [comment]
`project-build` is unexpected here, but aside from that normal completion should work correctly. Is there anything popping up in the logs? `.metals/metals.log`

**Comment by ashkan-leo** [comment]
It is called `project-build`. Go to definitions work, but auto complete is not working.
I also deleted all the relevant files and imported the build again. It didn't help
Here are some relevant info from the logs:
```
2020.11.04 12:56:56 INFO  tracing is enabled: /Users/aaleali/Library/Caches/org.scalameta.metals/bsp.trace.json
Cancelling textDocument/codeAction(4) in hook post-command-hook
2020.11.04 12:56:58 INFO  tracing is enabled: /Users/aaleali/Library/Caches/org.scalameta.metals/bsp.trace.json
2020.11.04 12:56:59 INFO  no build target: using presentation compiler with only scala-library
2020.11.04 12:56:59 WARN  no build target for: /Users/aaleali/w/meng/src/main/scala/com/conversantmedia/dsi/matchengine/modules/history/HistoryModule.scala
Creating watch for /Users/aaleali/w/meng/project/project
Creating watch for /Users/aaleali/w/meng/project/project/project
2020.11.04 12:56:59 INFO  running '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/31/gjbjq8b11z9fgnxnvy3lkn3rc5y5f6/T/metals5598737297765187525/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
2020.11.04 12:57:02 INFO  [info] welcome to sbt 1.4.1 (Oracle Corporation Java 1.8.0_202)
2020.11.04 12:57:03 ERROR Timeout waiting for 'build/initialize' response
2020.11.04 12:57:03 ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:316)
	at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:251)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020.11.04 12:57:03 INFO  [info] loading settings for project global-plugins from plugins.sbt,sbt-updates.sbt ...
2020.11.04 12:57:04 INFO  [info] loading global plugins from /Users/aaleali/.sbt/1.0/plugins
Creating watch for /Users/aaleali/w/meng/project/project/project/project
2020.11.04 12:57:09 INFO  [info] loading settings for project meng-build-build-build from metals.sbt ...
2020.11.04 12:57:09 INFO  [info] loading project definition from /Users/aaleali/w/meng/project/project/project
2020.11.04 12:57:13 INFO  [info] loading settings for project meng-build-build from metals.sbt ...
2020.11.04 12:57:13 INFO  [info] loading project definition from /Users/aaleali/w/meng/project/project
2020.11.04 12:57:16 INFO  [success] Generated .bloop/meng-build-build.json
2020.11.04 12:57:16 INFO  [success] Total time: 2 s, completed Nov 4, 2020 12:57:16 PM
2020.11.04 12:57:19 INFO  [info] loading settings for project meng-build from assembly.sbt,metals.sbt,plugins.sbt ...
2020.11.04 12:57:19 INFO  [info] loading project definition from /Users/aaleali/w/meng/project
2020.11.04 12:57:20 INFO  [success] Generated .bloop/meng-build.json
2020.11.04 12:57:20 INFO  [success] Total time: 1 s, completed Nov 4, 2020 12:57:21 PM
2020.11.04 12:57:22 INFO  [info] loading settings for project root from build.sbt,version.sbt ...
2020.11.04 12:57:22 INFO  [info] set current project to dsi-match-engine-main (in build file:/Users/aaleali/w/meng/)
2020.11.04 12:57:22 INFO  [warn] there's a key that's not used by any other settings/tasks:
2020.11.04 12:57:22 INFO  [warn]  
2020.11.04 12:57:22 INFO  [warn] * root / IntegrationTest / run / fork
2020.11.04 12:57:22 INFO  [warn]   +- /Users/aaleali/w/meng/build.sbt:207
2020.11.04 12:57:22 INFO  [warn]  
2020.11.04 12:57:22 INFO  [warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
2020.11.04 12:57:22 INFO  [warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
2020.11.04 12:57:30 INFO  [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
2020.11.04 12:57:31 INFO  [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
2020.11.04 12:57:33 INFO  [success] Generated .bloop/root.json
2020.11.04 12:57:33 INFO  [success] Generated .bloop/root-test.json
2020.11.04 12:57:33 INFO  [success] Total time: 10 s, completed Nov 4, 2020 12:57:33 PM
2020.11.04 12:57:33 INFO  build tool exit: 0
2020.11.04 12:57:33 INFO  time: ran 'sbt bloopInstall' in 34s
2020.11.04 12:57:36 INFO  tracing is enabled: /Users/aaleali/Library/Caches/org.scalameta.metals/bsp.trace.json
2020.11.04 12:57:37 INFO  tracing is enabled: /Users/aaleali/Library/Caches/org.scalameta.metals/bsp.trace.json
Creating watch for /Users/aaleali/w/meng/project/project/src
Creating watch for /Users/aaleali/w/meng/project/project/src/main
Creating watch for /Users/aaleali/w/meng/project/project/src/main/java
Creating watch for /Users/aaleali/w/meng/project/project/src/main/scala
2020.11.04 12:57:37 INFO  tracing is enabled: /Users/aaleali/Library/Caches/org.scalameta.metals/bsp.trace.json
2020.11.04 12:57:37 INFO  time: connected to build server in 3.45s
2020.11.04 12:57:37 INFO  Connected to Build server v1.4.4-17-6e43cbfd
2020.11.04 12:57:37 INFO  time: imported build in 0.19s
2020.11.04 12:57:46 INFO  time: indexed workspace in 9.15s
2020.11.04 12:57:47 INFO  compiling root (41 scala sources)
2020.11.04 12:58:05 INFO  compiling root-test (5 scala sources)
2020.11.04 12:58:05 INFO  time: compiled root in 19s
2020.11.04 12:58:09 INFO  time: compiled root-test in 3.77s
```

An intersting thing happens if I manually call the build import function from Emacs, the project-build goes away and metals doctor shows the following:
```
Metals Doctor

Build server currently used: Bloop.

These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

  Build target  Scala  Diagnostics  Goto definition  Completions  Find references  Recommendation    
  root  2.11.12  ✅   ✅   ✅   ✅   This Scala version might not be supported in upcoming versions of Metals, please upgrade to Scala    
              2.12.12.    
  root-test  2.11.12  ✅   ✅   ✅   ✅   This Scala version might not be supported in upcoming versions of Metals, please upgrade to Scala    
              2.12.12.    
  meng-build  2.12.12  ✅   ✅   ✅   ✅       
  meng-build-build  2.12.12  ✅   ✅   ✅   ✅       
```

However, the auto complete still doesn't work. I have tried both 0.9.4 and the snapshot version.

**Comment by tgodzik** [comment]
What are you trying to complete? Could you maybe post a code snippet?

If the definition works then auto complete should also work. There is nothing in the logs about any kind of an issue. Could it be Emacs specific? Could you ask around https://github.com/emacs-lsp/lsp-metals ?

You could also try using VS Code in that workspace to check if the problem is emacs specific.

**Comment by propensive** [comment]
I think I'm getting the same error about Scala 2.12.7 in VS Code when trying to work on a Scala 3.0.0-M1 project. I have no references to Scala 2.12.7 anywhere in my configuration files. The configuration files work fine with bloop (via Fury).

The logs show the following:
```
Java home: /home/jpretty/.gentoo/java-config-2/current-user-vm
Metals version: 0.9.6
2020.11.24 22:49:48 INFO  logging to file /home/jpretty/dev/propensive/contextual/.metals/metals.log
2020.11.24 22:49:48 INFO  Started: Metals version 0.9.6 in workspace '/home/jpretty/dev/propensive/contextual' for client vscode.
2020.11.24 22:49:49 INFO  time: initialize in 0.41s
Initializing Scala Debugger
2020.11.24 22:49:48 INFO  Attempting to connect to the build server...
2020.11.24 22:49:49 WARN  no build target for: /home/jpretty/dev/propensive/contextual/src/core/contextual.scala
2020.11.24 22:49:49 INFO  skipping build import with status 'Requested'
2020.11.24 22:49:49 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/jpretty/.cache/metals/bsp.trace.json
2020.11.24 22:49:49 INFO  Attempting to connect to the build server...
2020.11.24 22:49:49 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/jpretty/.cache/metals/bsp.trace.json
2020.11.24 22:49:49 INFO  time: connected to build server in 0.4s
2020.11.24 22:49:49 INFO  Connected to Build server v1.4.5
2020.11.24 22:49:50 INFO  no build target: using presentation compiler with only scala-library
2020.11.24 22:49:51 WARN  Could not find java sources in None. Java symbols will not be available.
2020.11.24 22:49:51 ERROR unexpected error during source scanning
java.nio.file.FileSystemNotFoundException: /home/jpretty/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:120)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:104)
	at scala.meta.internal.io.PlatformFileIO$.newJarFileSystem(PlatformFileIO.scala:100)
	at scala.meta.internal.metals.JarTopLevels.getTopLevels(JarTopLevels.scala:34)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$addSourceJarSymbols$1(MetalsLanguageServer.scala:2221)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$addSourceJarTopLevels$1(OnDemandSymbolIndex.scala:101)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.tryRun(OnDemandSymbolIndex.scala:133)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.addSourceJarTopLevels(OnDemandSymbolIndex.scala:100)
	at scala.meta.internal.metals.MetalsLanguageServer.addSourceJarSymbols(MetalsLanguageServer.scala:2220)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$5(MetalsLanguageServer.scala:2188)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$5$adapted(MetalsLanguageServer.scala:2179)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$2(MetalsLanguageServer.scala:2179)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$2$adapted(MetalsLanguageServer.scala:2178)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.MetalsLanguageServer.indexDependencySources(MetalsLanguageServer.scala:2178)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexWorkspace$10(MetalsLanguageServer.scala:2124)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.indexWorkspace(MetalsLanguageServer.scala:2124)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$profiledIndexWorkspace$2(MetalsLanguageServer.scala:2018)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$profiledIndexWorkspace$1(MetalsLanguageServer.scala:2018)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020.11.24 22:49:51 ERROR unexpected error during source scanning
java.nio.file.FileSystemNotFoundException: /home/jpretty/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2-sources.jar
```
with lots of very similar stack traces after this, including this one:
```
java.nio.file.FileSystemNotFoundException: /home/jpretty/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-sources.jar
```
which suggests that it's trying to access Scala 2.12.7.

Here is my configuration file:
```
{"project":{"classesDir":"/home/jpretty/dev/propensive/contextual/.fury/classes/contextual_core","classpath":["/home/jpretty/dev/propensive/contextual/.fury/classes/scala_compiler","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala3-library_3.0.0-M1-3.0.0-M1.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala-library/2.13.3/scala-library-2.13.3.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala-asm-7.3.1-scala-1.jar","/home/jpretty/dev/propensive/contextual/.fury/classes/contextual_core","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/jline-terminal-3.15.0.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/util-interface-1.2.2.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala3-compiler_3.0.0-M1-3.0.0-M1.jar","/home/jpretty/dev/propensive/contextual/.fury/resources/contextual_core","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/jline-terminal-jna-3.15.0.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/compiler-interface-1.2.5.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala3-interfaces-3.0.0-M1.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/jline-reader-3.15.0.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala-library-2.13.3.jar","/home/jpretty/dev/propensive/contextual/.fury/resources/scala_compiler","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/tasty-core_3.0.0-M1-3.0.0-M1.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/jna-5.3.1.jar"],"dependencies":[],"directory":"/home/jpretty/dev/propensive/contextual/.fury/work/contextual_core","java":{"options":[]},"jvmPlatform":{"config":{"home":"","options":[]},"mainClass":[],"name":"jvm"},"name":"contextual_core","out":"/home/jpretty/dev/propensive/contextual/.fury/analysis/contextual_core","resolution":{"modules":[]},"scala":{"jars":["/home/jpretty/dev/propensive/contextual/.fury/classes/scala_compiler","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala3-library_3.0.0-M1-3.0.0-M1.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala-library/2.13.3/scala-library-2.13.3.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala-asm-7.3.1-scala-1.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/jline-terminal-3.15.0.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/util-interface-1.2.2.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala3-compiler_3.0.0-M1-3.0.0-M1.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/jline-terminal-jna-3.15.0.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/compiler-interface-1.2.5.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala3-interfaces-3.0.0-M1.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/jline-reader-3.15.0.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/scala-library-2.13.3.jar","/home/jpretty/dev/propensive/contextual/.fury/resources/scala_compiler","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/tasty-core_3.0.0-M1-3.0.0-M1.jar","/home/jpretty/.cache/fury/bins/org.scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/jna-5.3.1.jar"],"name":"scala-compiler","options":[],"organization":"org.scala-lang","version":"3.0.0-M1"},"sources":["/home/jpretty/dev/propensive/contextual/src/core"],"test":{"frameworks":[],"options":{"arguments":[],"excludes":[]}}},"version":"1.0.0"}
```

The message `Preparing presentation compiler` is shown continuously in VS Code.

Metals Doctor fails to load, but I was able to capture the LSP message in the trace log, which shows the following (which was magically converted to a markdown table when I pasted it!):

Build target | Scala | Diagnostics | Goto definition | Completions | Find references | Recommendation
-- | -- | -- | -- | -- | -- | --
contextual_core | 3.0.0-M1 | ✅ | ✅ | ✅ | ✅ |  
contextual-build | 2.12.7 | ✅ | ⚠️ | ⚠️ | ⚠️ | Upgrade to Scala 2.12.12 and run 'Build import' to enable code navigation.

Now, `contextual_core.json` is a file I created, and which exists in the `.bloop` directory, but I have no idea what `contextual-build` refers to. It's not a file I created, and it isn't in the `.bloop` directory.

**Comment by ckipp01** [comment]
🤔 I still don't know where the 2.12.7 is coming from, but thinking about this a bit more, I think  what might be happening at least in @propensive's case is that Metals knows Bloop is the build server, but it also may think that the build tool is sbt. So when the BSP connection is made, it falls into the second case here:

https://github.com/scalameta/metals/blob/46628c00c5c40c5911202eb104e9f70abae4403d/metals/src/main/scala/scala/meta/internal/bsp/BspConnector.scala#L92-L107

So then it creates another bsp connection for the meta-build, which doesn't exist, which would explain `contextual-build`. I'm assuming there is no info there to correctly give to Bloop for the connection, and somehow 2.12.7 is being defaulted from somewhere. @propensive does your build have anything that Metals would maybe detect it as an sbt build space? A `build.sbt` or anything in `project`?

**Comment by tgodzik** [comment]
`contextual` has a build.sbt file, which means once sbt was invoked once it will create `project/.bloop` directory. @propensive do you have that directory in your build maybe? If so metals will detect it and try to connect to it to support the `build.sbt` file features.

**Comment by propensive** [comment]
No, it doesn't have an sbt build, actually... I'm rewriting it for Scala 3, and there's only a Fury build.

**Comment by tgodzik** [comment]
There is no other way we would be getting the additional target, unless there is leftover `project/.bloop` files. Bloop will not load a build, unless it's really there. It's just nowhere this could come from really.

**Comment by ashkan-leo** [comment]
I am still facing similar issues even using the latest snapshot release.

The only build target I get is:
<img width="1062" alt="Screen Shot 2021-01-11 at 12 10 14 PM" src="https://user-images.githubusercontent.com/10341965/104221210-3aebc900-5406-11eb-802e-0f65e810e258.png">

And when I call build import I get:
<img width="790" alt="Screen Shot 2021-01-11 at 12 07 58 PM" src="https://user-images.githubusercontent.com/10341965/104221186-30313400-5406-11eb-9650-39f5bdb7be00.png">

Any help would be appreciated. My setup is broken for months now.

**Comment by ckipp01** [comment]
@ashkan-leo is this build by chance public that I could take a look at?
