### ISSUE TITLE
Unable to make a BSP connection with Bloop

### ISSUE THREAD

**Issue by jqno** [scalameta/metals#2207]
**Question**

I saw on twitter there's a new release of coc-metals, so obviously I wanted to upgrade. After the upgrade though, the Metals server no longer starts for me. I reverted to the previous version, and it still doesn't start. Happens both on Maven and SBT projects.

I'm not sure if this is a Metals issue or a coc-metals issue, so I picked one. I'm happy to move this issue if I picked incorrectly :)

**Installation:**

- Operating system: macOS
- Vim or nvim version: 8.2.1650
- coc.nvim version: commit `08190437e386c3841eaaa0c033ca4ee381d7eb78` -- I think that corresponds to 0.0.79
- coc-metals extension version: commit `eb0e501bd74bda475f463af5b7b645f639cf28ad` -- I think that corresponds to 0.9.5
- Metals version: 0.9.4

**Additional context**

I've tried adding an explicit `metals.javaHome` entry to make sure that the correct JVM is used, but it doesn't seem to help. It's managed with sdkman.io, if that's relevant.

Here's (part of) the content of my `.metals/metals.log` file:

```
2020.11.11 12:39:09 INFO  build tool exit: 0
2020.11.11 12:39:09 INFO  time: ran 'sbt bloopInstall' in 29s
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/j6/v64w7c6j40l9nlk85ndy9l480000gn/T/bsp-launcher980179579343575154/bsp.socket'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 18436'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.11.11 12:40:16 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```

**Search terms**

**Comment by jqno** [comment]
I've updated bloop as you said, it's now at 1.4.5.something. I only see it retrying twice, though. Relevant sections of the log:

```
2020.11.11 13:51:57 INFO  mvn bloopInstall exit: 0
2020.11.11 13:51:58 INFO  time: ran 'mvn bloopInstall' in 10s
2020.11.11 13:51:58 INFO  Attempting to connect to the build server...
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/j6/v64w7c6j40l9nlk85ndy9l480000gn/T/bsp-launcher5348833836309647595/bsp.socket'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> No server running at 127.0.0.1:8212, let's fire one...
> Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.5-2-eb51d668...
> Starting bloop server at 127.0.0.1:8212...
> Attempting a connection to the server...
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 39176'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> No server running at 127.0.0.1:8212, let's fire one...
> Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.5-2-eb51d668...
> Starting bloop server at 127.0.0.1:8212...
> Attempting a connection to the server...
error: The launcher failed to establish a bsp connection, aborting...
2020.11.11 13:53:05 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```

**Comment by tgodzik** [comment]
Thanks for reporting! Is this problematic in every workspace or just one? Did you try removing `.bloop` and `.metals` directories?

**Comment by jqno** [comment]
I've tried in 2 workspaces, one maven and one sbt. I've removed these directories several times, but it didn't help. I haven't done an in depth comparison between the two workspaces, but the effects seem the same.

**Comment by tgodzik** [comment]
The weirdest thing is that it used to work for you without problems. Did you maybe change the default java version? Was there anything at all that you changed aside from Metals version? Especially if you reverted it should just go back to normal. Could you try running with `0.9.4` Metals version? With the older Bloop 1.4.4 running?

**Comment by jqno** [comment]
Thanks for all the help, @ckipp01 and @tgodzik. I'm a little embarrased to say, after a restart of my machine, everything worked perfectly again. Should've thought about this earlier, I work in IT after all 😅 

Just to give you all the information that you asked for, in case it may be of help later:

* I didn't change the default Java version. I have several JVMs on my machine for hobby projects, but there's only one that has the required security configuration to be able to connect to servers at work, so I'm mostly bound to that one JVM (OpenJDK 11.0.8+10, on macOS).
* Initially, I only changed the Metals version (through updating coc-metals). Then I reverted and saw the same behaviour. Only later did I update Bloop from 1.4.4 to 1.4.5, though I don't remember if I did that before or after going back to the most recent versions of Metals and coc-metals. After that, I still had the same problems.

This morning, I restarted my machine to install a software update (no, not the Big Sur one yet, I'll wait a bit before I do that one 😉) and things worked again, both in my Maven project and my SBT project.

**Comment by ckipp01** [comment]
> Thanks for all the help, @ckipp01 and @tgodzik. I'm a little embarrased to say, after a restart of my machine, everything worked perfectly again. Should've thought about this earlier, I work in IT after all 😅

🎉 ha, glad it's working!! Although, again, it's not ideal that this happened in the first place. Thanks for all the info that you have us. The issue you described is something we're aware of and have seen pop up a couple times. We do have some ideas and things that we'll be trying to remedy this situation where a user is simply unable to connect to the server. So hopefully these situations will be become more rare. If you have this happen again, feel free to pop in here and let us know.

**Comment by jqno** [comment]
Thanks, I will let you know if I run into it again. In the mean time, if there's something I can do to help with this, please let me know!

**Comment by talestonini** [comment]
I experienced exactly the same issue:
```
> Starting bloop server at 127.0.0.1:8212...
> Attempting a connection to the server...
error: The launcher failed to establish a bsp connection, aborting...
```
And after much debugging and arriving at this page I can confirm that simply **restarting the machine** did the trick.

**Comment by odwrotnie** [comment]
I am experiencing the same issue. Even after restart. In all workspaces :(.
