### ISSUE TITLE
Unable to connect on first attempt with sbt BSP with 1.4.3

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2236]
**Describe the bug**

With a project that worked wtih 1.4.2 and 1.4.1, it seems that with 1.4.3 after generating a `.bsp/sbt.json` file the initial connection fails. After a retry or two it connects, but it fails almost all the time in the first connection attempt. The logs show this:

```
[info] sbt server started at local:///Users/ckipp/.sbt/1.0/server/4ef2969adcd0c3a89f7b/sock
[info] started sbt server
>....>....>....[info] new client connected: network-1
>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....[warn] Metals requires the semanticdb compiler plugin
[warn] consider setting 'Global / semanticdbEnabled := true' in your global sbt settings ($HOME/.sbt/1.0)
>....>....>....>....>....>....>....>....>....Content-Length: 291
Content-Type: application/vscode-jsonrpc; charset=utf-8

"
java.lang.IllegalStateException: Missing header Content-Length in input "[info] welcome to sbt 1.4.3 (BellSoft Java 1.8.0_242)
[info] loading global plugins from /Users/ckipp/.sbt/1.0/plugins
[info] loading settings for project tester-build from metals.sbt,plugins.sbt ...
[info] loading project definition from /Users/ckipp/Documents/scala-workspace/tester/project
[info] loading settings for project root from build.sbt ...
[info] set current project to root (in build file:/Users/ckipp/Documents/scala-workspace/tester/)
[info] sbt server started at local:///Users/ckipp/.sbt/1.0/server/4ef2969adcd0c3a89f7b/sock
[info] started sbt server
>....>....>....[info] new client connected: network-1
>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....>....[warn] Metals requires the semanticdb compiler plugin
[warn] consider setting 'Global / semanticdbEnabled := true' in your global sbt settings ($HOME/.sbt/1.0)
>....>....>....>....>....>....>....>....>....Content-Length: 291
Content-Type: application/vscode-jsonrpc; charset=utf-8

"
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2020.11.16 16:03:47 ERROR Timeout waiting for 'build/initialize' response
2020.11.16 16:03:47 WARN  Retrying connection to the build server sbt
2020.11.16 16:03:47 INFO  tracing is enabled: /Users/ckipp/Library/Caches/org.scalameta.metals/bsp.trace.json
2020.11.16 16:03:47 INFO  time: connected to build server in 1m
2020.11.16 16:03:47 INFO  Connected to Build server v1.4.3
```
There are a couple things that don't make a ton of sense.

> [warn] consider setting 'Global / semanticdbEnabled := true' in your global sbt settings ($HOME/.sbt/1.0)

It's odd that this appears since the plugin does enable it. It also seems to be an order thing since it appears, there is a bunch of logging, and then it connects fine after a bit and there are no issues. So I don't fully get why it complains when it first attempts to make the connection.

Secondly, I think [this issue](https://github.com/sbt/sbt/issues/5993) is biting us hard here since I don't even expect these logs to be in the BSP communication.

**To Reproduce**

1. Create a new project with sbt 1.4.3
2. Do a `generate-bsp-config` or create it manually
3. Attempt to connect to the server

**Expected behavior**

Nice connection as was happening with 1.4.1 and 1.4.2

**Installation:**

- Operating system: macOS
- Editor: Vim
- Metals version: v0.9.5

**Search terms**

sbt BSP

**Comment by ckipp01** [comment]
There is a chance that the connection issue may be fixed with https://github.com/sbt/sbt/pull/6097

**Comment by ckipp01** [comment]
As of 1.4.4 this now works like a charm. The connect is much much smoother. I'll probably follow this up with a post of the FAQ about supported sbt BSP version and mention this to let people know that if they want to use sbt BSP, you can't use 1.4.0, and you also shouldn't use 1.4.3.
