### ISSUE TITLE
Misleading warning when wrong organizeImports has an incorrect setting

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2306]
**Describe the bug**

While using the built-in Organize Imports actions with the following rules:

```
OrganizeImports {
  groups = [
    "javax?\\.",
    "scala.",
    "*"
  ]
  removeUnused = true
  groupedImports = AggressiveMerge
}
```

With the current version of Metals, 0.9.7, if you attempt to ogranize your imports you'll just get the following warning:

```
 Organize import action not found.
```

However, this isn't fully true, and when you look in the logs you see the real issue:

```
SEVERE: Internal error: scala.meta.internal.metals.ScalafixProvider$ScalafixRunException: Unknown input 'AggressiveMerge'. Expected one of: Merge, Explode, Keep.
java.util.concurrent.CompletionException: scala.meta.internal.metals.ScalafixProvider$ScalafixRunException: Unknown input 'AggressiveMerge'. Expected one of: Merge, Explode, Keep.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
        at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.ScalafixProvider$ScalafixRunException: Unknown input 'AggressiveMerge'. Expected one of: Merge, Explode, Keep.
        at scala.meta.internal.metals.ScalafixProvider.$anonfun$organizeImports$2(ScalafixProvider.scala:100)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        ... 4 more
```

**To Reproduce**

1. Copy the config
2. Have some imports that need organzing
3. Execute the organize imports action
4. See warning

**Expected behavior**

In this case, the value is wrong...  but only for the version of the organize-imports rule that Metals is using. If it would be updated, this would work fine. It'd be great if the actual exception message in this case was shown to the user which may give them a better hint of what's going on.

**Installation:**
- Metals version: v0.9.7
- Editor: vim

**Search terms**

Organize import action not found

**Comment by tgodzik** [comment]
We can't actually get the organize imports version from the build definition unfortunately. It would all need to be embedded in the configuration, so I think we need to fix it in scalafix. Or otherwise add a user option to specify a non-default version. What do you think?

**Comment by ckipp01** [comment]
Yea, I _believe_ I've seen it discussed in the Scalafix repo before that the desire is to be able to have
```
version = <scalfix version>
```
Just like it's done in scalafmt right? I think in an ideal world if that could happen, that'd be wonderful. However, I don't know the amount of work that it'd require on the Scalafix side. That leaves me to thinking about what we can do on the Metals side to make this a bit clearer. I don't love the idea of having a user configuration setting to change the version, especially in the future if the version will just be part of the conf file. Do you think it's a bad idea to just catch the `ScalafixRunException` and show it to the user instead of the current message. I know in this case it'd then be

```
Unknown input 'AggressiveMerge'. Expected one of: Merge, Explode, Keep.
```
Instead of 
```
Organize import action not found.
```
Which I think is much clearer. _Howerver_ I unsure if there is situations where the `ScalafixRunException` may not have a message that would be friendly to the user. @mlachkar do you know if this exception message is normally fine to just show to the user?

**Comment by tgodzik** [comment]
It seems that this was fixed by @mlachkar in https://github.com/scalameta/metals/pull/2421

![image](https://user-images.githubusercontent.com/3807253/110665742-f0e65000-81c8-11eb-9d35-b281f17e642d.png)

Going a bit through the issue trying to close as much as possible, let me know if we should reopen.

**Comment by mlachkar** [comment]
Sorry I didn't see this issue! I also think it should be fixed with the last PR about scalafix Errors. thanks

**Comment by tgodzik** [comment]
No worries! That's why I am going through the issues, some of them might have got lost along the way.

**Comment by ckipp01** [comment]
Ah yes, totally forgot this issue even existed. 👍🏼
