### ISSUE TITLE
Exception when trying to run */metalsSetup

### ISSUE THREAD

**Issue by ivanopagano** [scalameta/metals#232]
I'm trying to enable metals on a local project on OSX but when I run the `metalsSetup` task in sbt, I get the following trace

```
[error] java.lang.IllegalStateException
[error] 	at com.swoval.files.apple.FileSystemApi.createStream(FileSystemApi.java:53)
[error] 	at com.swoval.files.AppleDirectoryWatcher.register(AppleDirectoryWatcher.scala:26)
[error] 	at com.swoval.files.AppleDirectoryWatcher.register(AppleDirectoryWatcher.scala:23)
[error] 	at com.swoval.files.FileCacheImpl$$anon$3.$anonfun$register$3(FileCache.scala:99)
[error] 	at com.swoval.files.FileCacheImpl$$anon$3.$anonfun$register$3$adapted(FileCache.scala:99)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at com.swoval.files.FileCacheImpl$$anon$3.register(FileCache.scala:99)
[error] 	at com.swoval.files.FileCacheImpl.register(FileCache.scala:38)
[error] 	at com.swoval.files.FileCacheImpl.list(FileCache.scala:28)
[error] 	at com.swoval.watchservice.MacOSXWatchServicePlugin$.$anonfun$cachedSourcesFor$3(MacOSXWatchServicePlugin.scala:48)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at com.swoval.watchservice.MacOSXWatchServicePlugin$.$anonfun$cachedSourcesFor$1(MacOSXWatchServicePlugin.scala:58)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.IllegalStateException
[error] 	at com.swoval.files.apple.FileSystemApi.createStream(FileSystemApi.java:53)
[error] 	at com.swoval.files.AppleDirectoryWatcher.register(AppleDirectoryWatcher.scala:26)
[error] 	at com.swoval.files.AppleDirectoryWatcher.register(AppleDirectoryWatcher.scala:23)
[error] 	at com.swoval.files.FileCacheImpl$$anon$3.$anonfun$register$3(FileCache.scala:99)
[error] 	at com.swoval.files.FileCacheImpl$$anon$3.$anonfun$register$3$adapted(FileCache.scala:99)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at com.swoval.files.FileCacheImpl$$anon$3.register(FileCache.scala:99)
[error] 	at com.swoval.files.FileCacheImpl.register(FileCache.scala:38)
[error] 	at com.swoval.files.FileCacheImpl.list(FileCache.scala:28)
[error] 	at com.swoval.watchservice.MacOSXWatchServicePlugin$.$anonfun$cachedSourcesFor$3(MacOSXWatchServicePlugin.scala:48)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at com.swoval.watchservice.MacOSXWatchServicePlugin$.$anonfun$cachedSourcesFor$1(MacOSXWatchServicePlugin.scala:58)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (Compile / sources) java.lang.IllegalStateException
[error] (Test / sources) java.lang.IllegalStateException
```

Running on a **Macbook Pro retina 15'' (2015)** with
 - *macOS High Sierra* version 10.13.3
 - quad 2,2 GHz Intel Core i7
 - 16 Gb 1600 MHz DDR3

**Comment by olafurpg** [comment]
I don't see a reference to MetalsPlugin.scala in the stack trace. `metalsSetup` calls `.value` a handful of sbt setting/task keys
https://github.com/scalameta/metals/blob/97213144f91277485857cfb1ade6893b2a4f01ee/project/MetalsPlugin.scala#L29-L71

The stack trace seems to lead to an sbt plugin `com.swoval.files.AppleDirectoryWatcher`, what happens if you disable that plugin?

**Comment by ivanopagano** [comment]
I'll check it up

Sorry, I thought that was part of the metals dependencies...

**Comment by ivanopagano** [comment]
Ok, sorry again for the inconvenience, it was a global plugin I forgot to have enabled.
