### ISSUE TITLE
InvalidPathException on file URLs

### ISSUE THREAD

**Issue by nilskp** [scalameta/metals#2340]
Seems that NIO file system is used for file URLs, e.g. `file://`, which crashes on Windows.

```
[Error - 2:06:00 PM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/nils/git/delta/.metals/readonly/scala/Option.scala
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/nils/git/delta/.metals/readonly/scala/Option.scala
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.resolve(Path.java:515)
	at scala.meta.io.AbsolutePath.resolve(AbsolutePath.scala:43)
	at scala.meta.internal.decorations.SyntheticsDecorationProvider.currentDocument(SyntheticsDecorationProvider.scala:238)
	at scala.meta.internal.decorations.SyntheticsDecorationProvider.addSyntheticsHover(SyntheticsDecorationProvider.scala:104)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$hover$2(MetalsLanguageServer.scala:1202)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more
```

**Comment by tgodzik** [comment]
Thanks for reporting! Did you have implicit decorations enabled at all? It should only be a problem if they are enabled.

**Comment by nilskp** [comment]
> 
> 
> Thanks for reporting! Did you have implicit decorations enabled at all? It should only be a problem if they are enabled.

I've been switching them on and off, so it's very likely that I had them on when this happened.

**Comment by tgodzik** [comment]
I think that there are 3 factors here:
- readonly file with interactive semanticdb
- turned on implicit decorations that uses that semanticdb
- windows

I think I should be able to create a fix soon.

**Comment by niander** [comment]
@tgodzik Hey, I am using version 0.11.12 on VSCode and Windows and I am still getting this same issue reported here. But I seem this marked as resolved, I wonder what is different in my case

**Comment by tgodzik** [comment]
@niander looks like a different place, let's reopen this

**Comment by tgodzik** [comment]
Ach, actually this should already be fixed by https://github.com/scalameta/metals/pull/5325

**Comment by sake92** [comment]
I am getting this in latest snapshot (using mill-bsp), when I run the "doctor".
```
okt 25, 2024 12:01:08 POPODNE org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.nio.file.InvalidPathException: Illegal char <:> at index 10: mill-build:.metals-buildtarget
java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 10: mill-build:.metals-buildtarget
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
```
