### ISSUE TITLE
Issue in installation of Scala (metals) with VScode

### ISSUE THREAD

**Issue by arubhardwaj** [scalameta/metals#2380]
I am very new to scala. 

To make the experience same as other languages, I decided to use VScode for it. But, I am trying hard to run, everytime I am getting an error mentioned below:
```
arubhardwaj@pop-os:~/project/aru$ sbt
[info] Loading global plugins from /home/arubhardwaj/.sbt/1.0/plugins
[info] Loading settings for project aru-build-build from metals.sbt ...
[info] Loading project definition from /home/arubhardwaj/project/aru/project/project
[info] Loading settings for project aru-build from metals.sbt ...
[error] java.lang.NoSuchMethodError: 'sbt.SettingKey sbt.Keys$.reresolveSbtArtifacts()'
[error]         at bloop.integrations.sbt.Compat$.<init>(Compat.scala:40)
[error]         at bloop.integrations.sbt.Compat$.<clinit>(Compat.scala)
[error]         at bloop.integrations.sbt.BloopDefaults$.globalSettings$lzycompute(SbtBloop.scala:164)
[error]         at bloop.integrations.sbt.BloopDefaults$.globalSettings(SbtBloop.scala:164)
[error]         at bloop.integrations.sbt.BloopPlugin$.globalSettings(SbtBloop.scala:43)
[error]         at sbt.internal.GroupedAutoPlugins.$anonfun$globalSettings$1(GroupedAutoPlugins.scala:18)
[error]         at scala.collection.immutable.Stream.flatMap(Stream.scala:485)
[error]         at scala.collection.immutable.Stream.$anonfun$flatMap$1(Stream.scala:493)
[error]         at scala.collection.immutable.Stream.$anonfun$append$1(Stream.scala:251)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1167)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1157)
[error]         at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:414)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1167)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1157)
[error]         at scala.collection.generic.Growable.loop$1(Growable.scala:53)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:57)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:49)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:185)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:43)
[error]         at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:146)
[error]         at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:142)
[error]         at scala.collection.immutable.List.$plus$plus(List.scala:206)
[error]         at sbt.internal.Load$.buildConfigurations(Load.scala:379)
[error]         at sbt.internal.Load$.$anonfun$apply$3(Load.scala:258)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.apply(Load.scala:258)
[error]         at sbt.internal.Load$.buildPluginDefinition(Load.scala:1312)
[error]         at sbt.internal.Load$.buildPlugins(Load.scala:1242)
[error]         at sbt.internal.Load$.plugins(Load.scala:1225)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:694)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:694)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:688)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error]         at sbt.internal.Load$.loadAll(Load.scala:562)
[error]         at sbt.internal.Load$.loadURI(Load.scala:492)
[error]         at sbt.internal.Load$.load(Load.scala:471)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.apply(Load.scala:251)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
[error]         at xsbt.boot.Launch$.run(Launch.scala:111)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:120)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:20)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: 'sbt.SettingKey sbt.Keys$.reresolveSbtArtifacts()'
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r
[info] Loading global plugins from /home/arubhardwaj/.sbt/1.0/plugins
[info] Loading settings for project aru-build-build from metals.sbt ...
[info] Loading project definition from /home/arubhardwaj/project/aru/project/project
[info] Loading settings for project aru-build from metals.sbt ...
[error] java.lang.NoSuchMethodError: 'sbt.SettingKey sbt.Keys$.reresolveSbtArtifacts()'
[error]         at bloop.integrations.sbt.Compat$.<init>(Compat.scala:40)
[error]         at bloop.integrations.sbt.Compat$.<clinit>(Compat.scala)
[error]         at bloop.integrations.sbt.BloopDefaults$.globalSettings$lzycompute(SbtBloop.scala:164)
[error]         at bloop.integrations.sbt.BloopDefaults$.globalSettings(SbtBloop.scala:164)
[error]         at bloop.integrations.sbt.BloopPlugin$.globalSettings(SbtBloop.scala:43)
[error]         at sbt.internal.GroupedAutoPlugins.$anonfun$globalSettings$1(GroupedAutoPlugins.scala:18)
[error]         at scala.collection.immutable.Stream.flatMap(Stream.scala:485)
[error]         at scala.collection.immutable.Stream.$anonfun$flatMap$1(Stream.scala:493)
[error]         at scala.collection.immutable.Stream.$anonfun$append$1(Stream.scala:251)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1167)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1157)
[error]         at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:414)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1167)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1157)
[error]         at scala.collection.generic.Growable.loop$1(Growable.scala:53)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:57)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:49)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:185)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:43)
[error]         at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:146)
[error]         at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:142)
[error]         at scala.collection.immutable.List.$plus$plus(List.scala:206)
[error]         at sbt.internal.Load$.buildConfigurations(Load.scala:379)
[error]         at sbt.internal.Load$.$anonfun$apply$3(Load.scala:258)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.apply(Load.scala:258)
[error]         at sbt.internal.Load$.buildPluginDefinition(Load.scala:1312)
[error]         at sbt.internal.Load$.buildPlugins(Load.scala:1242)
[error]         at sbt.internal.Load$.plugins(Load.scala:1225)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:694)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:694)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:688)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error]         at sbt.internal.Load$.loadAll(Load.scala:562)
[error]         at sbt.internal.Load$.loadURI(Load.scala:492)
[error]         at sbt.internal.Load$.load(Load.scala:471)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.apply(Load.scala:251)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
[error]         at xsbt.boot.Launch$.run(Launch.scala:111)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:120)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:20)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: 'sbt.SettingKey sbt.Keys$.reresolveSbtArtifacts()'
[error] Use 'last' for the full log.
```

I am not able to identify the issue. Can anyone help? 

Thanks in advance

**Comment by tgodzik** [comment]
Thanks for reporting! The issue you encountered is caused by caused by sbt-bloop plugin needing to use a setting that was only added in 1.3.0. You should be fine with using the 1.4.6 version of the plugin or updating sbt to 1.3.0. We also handle it in Metals since #2350 That was not yet released, but you should be able to use a recent snapshot https://scalameta.org/metals/docs/editors/overview.html#latest-metals-server-versions

**Comment by tgodzik** [comment]
Easiest would probably be to change sbt version inside `project/build.properties` to:
```
sbt.version=1.4.6
```

**Comment by arubhardwaj** [comment]
Thanks @tgodzik. It was very quick and I just get it resolved, too.

**Comment by arubhardwaj** [comment]
> Easiest would probably be to change sbt version inside `project/build.properties` to:
> 
> ```
> sbt.version=1.4.6
> ```

Did the same thing and it worked well. Perhaps, I did install metals correctly but the project configurations were demanding some change.
