### ISSUE TITLE
Current snapshots are throwing exceptions and not working.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2403]
**Describe the bug**

When using the current snapshot of Metals, you'll see the following exception in the logs.

```
Exception in thread "pool-7-thread-1" java.lang.NoSuchMethodError: 'scala.tools.nsc.reporters.Reporter scala.meta.internal.pc.MetalsGlobal.reporter()'
        at scala.meta.internal.pc.ScalaCompilerWrapper.resetReporter(ScalaCompilerAccess.scala:17)
        at scala.meta.internal.pc.CompilerAccess.loadCompiler(CompilerAccess.scala:39)
        at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
        at scala.meta.internal.pc.CompilerAccess.$anonfun$withNonInterruptableCompiler$1(CompilerAccess.scala:125)
        at scala.meta.internal.pc.CompilerAccess.$anonfun$onCompilerJobQueue$1(CompilerAccess.scala:197)
        at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:103)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**

1. Set the server version to the latest snapshot.
2. Open a build
3. Look at the logs and see the exception and see that tons of stuff doesn't work

**Expected behavior**

That it works

**Installation:**

- Operating system: All
- Editor: All
- Metals version: `0.9.9+9-372f5c01-SNAPSHOT` and all of them since https://github.com/scalameta/metals/pull/2383

**Additional context**

The issue is that we have the `2.12.13` compiler as a dependency, when our project is on `2.12.12`. So all things related to the presentation compiler are going crazy.

```
❯ cs resolve org.scalameta:metals_2.12:0.9.9+9-372f5c01-SNAPSHOT -r bintray:scalacenter/releases -r sonatype:snapshots | grep compiler
org.scala-lang:scala-compiler:2.12.13:default
```

I'm just adding this in here in case someone searches for it, they will see that we are aware of it.

**Comment by tgodzik** [comment]
Ah yes. that is the issue that caused me to revert the vscode release. Working on it!
