### ISSUE TITLE
SocketTimeoutException when trying to run or debug a main class

### ISSUE THREAD

**Issue by benderpremier** [scalameta/metals#2405]
**Describe the bug**

When trying to run or debug a main class, metals fails with a socket timeout exception. All the other metals commands seem to work correctly (worksheet evaluation, code navigation,...) . See also this discussion on gitter.

**To Reproduce**

1. Create a new scala project e.g. `scala/hello-world.g8`
3. Open the project in VSCode or coc-nvim
3. Click on codeLens `run` or `debug`
4. Check metals logs for the `SocketTimeOutException

**Expected behavior**

The main method should run and print the output on the console.

**Installation:**

- Operating system: macOS Big Sur 11.1 
- Editor: Visual Studio Code and Vim
- Metals version: v0.9.8
- jdk:  openjdk 11 installed with `brew install --cask adoptopenjdk11` 
```
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
```

**Additional context**

metals.log:
```
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/6v/mwbff63n7hq154tw6k31bych0000gn/T/bsp-launcher17604306000524074917/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///var/folders/6v/mwbff63n7hq154tw6k31bych0000gn/T/bsp-launcher17604306000524074917/bsp.socket...
The server is listening for incoming connections at local:///var/folders/6v/mwbff63n7hq154tw6k31bych0000gn/T/bsp-launcher17604306000524074917/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
2021.01.18 17:03:35 INFO  tracing is enabled: /Users/damien/Library/Caches/org.scalameta.metals/bsp.trace.json
2021.01.18 17:03:35 INFO  Attempting to connect to the build server...
Starting the bsp launcher for bloop...
2021.01.18 17:03:35 INFO  Attempting to connect to the build server...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/6v/mwbff63n7hq154tw6k31bych0000gn/T/bsp-launcher12853493234928907947/bsp.socket'...
Waiting for the bsp connection to come up...
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/6v/mwbff63n7hq154tw6k31bych0000gn/T/bsp-launcher17025391069341853533/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///var/folders/6v/mwbff63n7hq154tw6k31bych0000gn/T/bsp-launcher12853493234928907947/bsp.socket...
The server is listening for incoming connections at local:///var/folders/6v/mwbff63n7hq154tw6k31bych0000gn/T/bsp-launcher12853493234928907947/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
2021.01.18 17:03:35 INFO  tracing is enabled: /Users/damien/Library/Caches/org.scalameta.metals/bsp.trace.json
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at local:///var/folders/6v/mwbff63n7hq154tw6k31bych0000gn/T/bsp-launcher17025391069341853533/bsp.socket...
The server is listening for incoming connections at local:///var/folders/6v/mwbff63n7hq154tw6k31bych0000gn/T/bsp-launcher17025391069341853533/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
2021.01.18 17:03:35 INFO  tracing is enabled: /Users/damien/Library/Caches/org.scalameta.metals/bsp.trace.json
2021.01.18 17:03:35 INFO  time: connected to build server in 46ms
2021.01.18 17:03:35 INFO  Connected to Build server v1.4.6-15-209c2a5c
2021.01.18 17:03:36 INFO  time: indexed workspace in 0.97s
Jan 18, 2021 5:03:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.net.SocketTimeoutException: connect timed out
java.util.concurrent.CompletionException: java.net.SocketTimeoutException: connect timed out
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:240)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at scala.meta.internal.metals.debug.DebugProvider.connect(DebugProvider.scala:314)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$start$7(DebugProvider.scala:92)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	... 5 more
```
bsp.trace.json:
```
[Trace - 05:11:47 pm] Received notification 'build/taskStart'
   42 Params: {
   41   taskId: {
   40     id: 9
   39   },
   38   eventTime: 1610989907195,
   37   message: Start no-op compilation for cats-sandbox,
   36   dataKind: compile-task,
   35   data: {
   34     target: {
   33     ¦ ¦uri¦: ¦file:/Users/damien/code/cats-sandbox/?id\u003dcats-sandbox¦
   32     }
   31   }
   30 }
   29
   28
   27 [Trace - 05:11:47 pm] Received notification 'build/taskFinish'
   26 Params: {
   25   taskId: {
   24     id: 9
   23   },
   22   eventTime: 1610989907197,
   21   message: Compiled \u0027cats-sandbox\u0027,
   20   status: 1,
   19   dataKind: compile-report,
   18   data: {
   17     target: {
   16     ¦ ¦uri¦: ¦file:/Users/damien/code/cats-sandbox/?id\u003dcats-sandbox¦
   15     },
   14     errors: 0,
   13     warnings: 0,
   12     isNoOp: true,
   11     isLastCycle: true,
   10     clientDir: file:///Users/damien/code/cats-sandbox/.bloop/cats-sandbox/bloop-bsp-clients-classes/classes-Metals-7u7i73blRc-GAix-SfDZXQ\u003d\u003d/,
    9     analysisOut: file:///Users/damien/code/cats-sandbox/target/streams/compile/bloopAnalysisOut/_global/streams/inc_compile_2.13.zip
    8   }
    7 }
    6
    5
    4 [Trace - 05:11:47 pm] Received response 'debugSession/start - (28)' in 14ms
    3 Result: {
    2   uri: tcp://0.0.0.0:61674
    1 }
  61  Error: null
  ```
  lsp.trace.json:
  ```
   [Trace - 05:11:57 pm] Sending response 'workspace/executeCommand - (87)'. Processing request took 10077ms
    Result: null
  
```

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! I think I might know what is going on:
```
[Trace - 05:11:47 pm] Received response 'debugSession/start - (28)' in 14ms
    3 Result: {
    2   uri: tcp://0.0.0.0:61674
    1 }
```
we've had problems with address being set to `0.0.0.0`instead of 127.0.0.1 for localhost. We should take a look at why it's popping up.

**Comment by benderpremier** [comment]
👍 Let me know if you want more details about my setup/configuration. Is the address returned by bloop ?

**Comment by tgodzik** [comment]
>  Let me know if you want more details about my setup/configuration. Is the address returned by bloop ?

Not sure, I need to dig into that. I thought we updated all urls not to use 0.0.0.0, but I must have missed something.

**Comment by benderpremier** [comment]
I did a fresh install of OSX and I don't run into this issue anymore. It's super likely that my config was somehow messed up, but I am not sure how.

I think it might have been due to running bloop locally at some point. However, I did uninstall it when I ran into this issue  🤷‍♀️.

**Comment by pdziedzic-sumo** [comment]
Hi, I just wanted to bump this one up. I see the issue on OSX 10.15 with vscode/metals/bloop and VPN enabled.
Shutting down VPN gets rid of the SocketTimeout exception and debugging starts working.
$ bloop about
bloop v1.4.8

**Comment by tgodzik** [comment]
@pdziedzic-sumo are you able to check it out with this Metals version:
```
0.10.2+13-f7c152f9-SNAPSHOT
```
?
We recently did some changes that might actually help in this case.

**Comment by pdziedzic-sumo** [comment]
@tgodzik , I just retried debugging in my vscode and it looks like it it starting up fine with my VPN enabled.
I didn't have to download your particular version of metals, the vscode plugin reports Metals 0.10.2.

**Comment by tgodzik** [comment]
Thanks for checking!
