### ISSUE TITLE
Error after offline installation in docker image

### ISSUE THREAD

**Issue by Geronium** [scalameta/metals#2414]
hello, 

we have some vscode server, and they run in a production without internet access. i installed the scalameta / metals extension, but we i run vscode i have this erros 

"Metals version: 0.9.8
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar: repo1.maven.org, ignoring it
Error while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar: repo.typesafe.com, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar: repo1.maven.org, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/argonaut-shapeless_6.2_2.12/1.2.0-M11/argonaut-shapeless_6.2_2.12-1.2.0-M11.jar: repo1.maven.org, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app_2.12/2.0.0-M9/case-app_2.12-2.0.0-M9.jar: repo1.maven.org, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-util_2.12/2.0.0-M9/case-app-util_2.12-2.0.0-M9.jar: repo1.maven.org, ignoring it"

can i finish the installation of this extension, maybe by downloading this jar and  putting them in the right place (but where ?) or is it impossible to use scalameta / metals without internet access ?

Thank you

**Comment by tanishiking** [comment]
Thanks for the report @Geronium , but will you please stick to the issue template / give us more information about your environment as it helps us help troubleshooting. dockerfile, what's build tools do you use, etc ...

I can't tell what's the real problem without seeing your Dockerfile or something, but metals should work fine even without internet connection iff all artifacts are downloaded. However, I would not recommend downloading those artifacts and putting them by hand, it should be done by build tool (library managers).

**Comment by Geronium** [comment]
Hello, 

thank you for your response, 

the Dockefile 

FROM rstudio/r-session-complete:centos7-1.4.1103-3

RUN mkdir -p /app/cfvr /data/SAS /data/work /data/restitution
RUN yum install -y java-1.8.0-openjdk.x86_64
RUN echo "export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk" >> /etc/profile
RUN echo "export JRE_HOME=/usr/lib/jvm/jre" >> /etc/profile
RUN source /etc/profile
RUn yum install -y wget
RUN cd ~ && wget http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.rpm && yum install -y scala-2.11.8.rpm && rm -f scala-2.11.8.rpm
RUN curl -sL https://rpm.nodesource.com/setup_15.x | bash -
RUN yum install -y nodejs
RUN yum clean packages
RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension ms-python.python
RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension scalameta.metals
RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension formulahendry.code-runner
RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension tushortz.python-extended-snippets
RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension cymonk.sql-formatter
RUN python -m pip install pylint

and for the build, i run just a dockerbuild with proxy paramaters

docker build --build-arg http_proxy=http://x.x.x.x --build-arg https_proxy=http://x.x.x.x  -t localhost:5000/rstudio/r-session-complete:centos7-1.4.1103-3.2 .


After that, when i run my vstudio, my extensions are all installed but i have this errors with scalameta / metals.

thanks again for your support.

**Comment by tgodzik** [comment]
@Geronium as an additional step you could run coursier:
`cs launch org.scalameta:metals_2.12:0.9.10 -M scala.meta.metals.DownloadDependencies`
which should download all the needed dependencies. 

Unfortunately Metals, does need internet connection to get all the requires files/jars. We have sample project that tries to fetch everything beforehand, please take a look at https://github.com/scalameta/metals-gitpod-sample/blob/master/gitpod_init.sh

The steps related to METALS_DIR are gitpod specific, so should not be needed in a normal docker image.

**Comment by tgodzik** [comment]
And also there a feature request here: https://github.com/scalameta/metals-feature-requests/issues/159

I will close this issue in favour of that feature request. But if you need any help setting up the docker don't hesitate to ask. Probably best to start a discussion in Q&A, which we can use to explain better what's going on to anyone that will try to the the same docker setup.

**Comment by Geronium** [comment]
hello, i done what you said but i have the same errors, does i need to add parameters ? maybe a target directory for the extension ?


"Java home: /usr/lib/jvm/jre-1.8.0-openjdk
Metals version: 0.9.10
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-util_2.12/2.0.0-M9/case-app-util_2.12-2.0.0-M9.jar: repo1.maven.org, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar: repo1.maven.org, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar: repo1.maven.org, ignoring it
Error while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar: repo.typesafe.com, ignoring it"

my dockerfile 

RUN yum install -y java-1.8.0-openjdk.x86_64
RUN echo "export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk" >> /etc/profile
RUN echo "export JRE_HOME=/usr/lib/jvm/jre" >> /etc/profile
RUN source /etc/profile
RUN yum install -y wget
RUN wget https://downloads.lightbend.com/scala/2.12.13/scala-2.12.13.rpm
**RUN yum install -y scala-2.12.13.rpm**
RUN curl -sL https://rpm.nodesource.com/setup_15.x | bash -
RUN yum install -y nodejs
RUN yum clean packages
RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension ms-python.python
**RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension scalameta.metals**
RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension formulahendry.code-runner
RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension tushortz.python-extended-snippets
RUN /opt/code-server/code-server-3.2.0-linux-x86_64/code-server --extensions-dir /opt/code-server/code-server-3.2.0-linux-x86_64/extensions --install-extension cymonk.sql-formatter
RUN python -m pip install pylint
RUN  curl -fLo cs https://git.io/coursier-cli-"$(uname | tr LD ld)"
RUN chmod +x cs
RUN curl -fLo coursier.jar https://github.com/coursier/coursier/releases/download/v2.0.9/coursier.jar
**RUN java  -Dhttps.proxyHost=ipproxy -Dhttps.proxyPort=portproxy -jar ./coursier.jar  install  --only-prebuilt=true bloop
RUN java  -Dhttps.proxyHost=ipproxy -Dhttps.proxyPort=portproxy -jar ./coursier.jar install sbt
#RUN java  -Dhttps.proxyHost=ipproxy -Dhttps.proxyPort=portproxy -jar ./coursier.jar launch org.scalameta:metals_2.12:0.9.10 -M scala.meta.metals.DownloadDependencies
RUN  java -Dhttps.proxyHost=ipproxy -Dhttps.proxyPort=portproxy -jar ./coursier.jar  fetch org.scalameta:metals_2.12:0.9.10
RUN java -Dhttps.proxyHost=ipproxy -Dhttps.proxyPort=portproxy -jar ./coursier.jar fetch org.scalameta:scalafmt-cli_2.12:2.7.5
RUN java -Dhttps.proxyHost=ipproxy -Dhttps.proxyPort=portproxy -jar ./coursier.jar launch org.scalameta:metals_2.12:0.9.10 -M scala.meta.metals.DownloadDependencies**
# -jar  /root/cs launch org.scalameta:metals_2.12:0.9.10 -M scala.meta.metals.DownloadDependencies
RUN ls -a /

Thanks again

**Comment by Geronium** [comment]
ok, the mv resolve the problem, after that i dont have errors

Java home: /usr/lib/jvm/jre-1.8.0-openjdk
Metals version: 0.9.10

Thank you again for your support

**Comment by Geronium** [comment]
oh, no, i spoke to fast, i have a new error (i will search)

"Error - 7:32:24 PM] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.nio.file.AccessDeniedException: /.metals
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.AccessDeniedException: /.metals
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at scala.meta.internal.metals.MetalsLogger$.redirectSystemOut(MetalsLogger.scala:32)
	at scala.meta.internal.metals.MetalsLogger$.setupLspLogger(MetalsLogger.scala:87)
	at scala.meta.internal.metals.MetalsLanguageServer.updateWorkspaceDirectory(MetalsLanguageServer.scala:289)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$initialize$2(MetalsLanguageServer.scala:691)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	... 5 more

[Error - 7:32:24 PM] Starting client failed
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.nio.file.AccessDeniedException: /.metals
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.AccessDeniedException: /.metals
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at scala.meta.internal.metals.MetalsLogger$.redirectSystemOut(MetalsLogger.scala:32)
	at scala.meta.internal.metals.MetalsLogger$.setupLspLogger(MetalsLogger.scala:87)
	at scala.meta.internal.metals.MetalsLanguageServer.updateWorkspaceDirectory(MetalsLanguageServer.scala:289)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$initialize$2(MetalsLanguageServer.scala:691)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	... 5 more

2021.01.22 19:32:24 INFO  shutting down Metals"

**Comment by Geronium** [comment]
ok, it start, if i just create a directory /.metals with 777 permissions

"Java home: /usr/lib/jvm/jre-1.8.0-openjdk
Metals version: 0.9.10
2021.01.22 20:01:32 INFO  logging to file /.metals/metals.log
2021.01.22 20:01:32 INFO  Started: Metals version 0.9.10 in workspace '/' for client vscode 1.44.2.
2021.01.22 20:01:34 INFO  time: initialize in 2.3s
Initializing Scala Debugger
2021.01.22 20:01:38 WARN  Build server is not auto-connectable.
2021.01.22 20:01:38 WARN  no build tool detected in workspace '/'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. "

but i dont know, why the default workspace is in "/"
