### ISSUE TITLE
Run CI on Windows

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#242]
For the sake of potential contributors using Windows, we should make sure our builds work on that OS too.

Also, it would be nice to add building of the vscode extension on the CI.

**Comment by olafurpg** [comment]
@martijnhoekstra reported problems related to usage of `Fragment` in mtags on Windows. I suspect the culprit is https://github.com/scalameta/metals/blob/5c0827aaafab5548c4ecc71c707c9f30732bc074/metals/src/main/scala/scala/meta/metals/mtags/Mtags.scala#L178
in which case the mtags unit tests should fail.

**Comment by martijnhoekstra** [comment]
stack trace for the mentioned error:

```
java.lang.IllegalArgumentException: Illegal character in opaque part at index 7: file:c:\Users\martijn\scala\scala-partest\src\main\scala\scala\tools\partest\nest\ConsoleRunner.scala
	at java.net.URI.create(URI.java:852)
	at scala.meta.metals.Uri$.apply(Uri.scala:37)
	at scala.meta.metals.search.InMemorySymbolIndex.indexDocument(InMemorySymbolIndex.scala:178)
	at scala.meta.metals.search.InMemorySymbolIndex.$anonfun$indexDatabase$1(InMemorySymbolIndex.scala:158)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.meta.metals.search.InMemorySymbolIndex.indexDatabase(InMemorySymbolIndex.scala:157)
	at scala.meta.metals.MetalsServices.$anonfun$indexedSemanticdbs$1(MetalsServices.scala:110)
	at monix.reactive.internal.operators.MapOperator$$anon$1.onNext(MapOperator.scala:44)
	at monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber$$anon$1.signalNext(AbstractBackPressuredBufferedSubscriber.scala:130)
	at monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber$$anon$1.fastLoop(AbstractBackPressuredBufferedSubscriber.scala:203)
	at monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber$$anon$1.run(AbstractBackPressuredBufferedSubscriber.scala:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 7: file:c:\Users\martijn\scala\scala-partest\src\main\scala\scala\tools\partest\nest\ConsoleRunner.scala
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 18 common frames omitted
```
