### ISSUE TITLE
Metals throws erorrs when Mill `build.sc` file has top level definitions.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2430]
**Describe the bug**

When you open a `build.sc` in a valid Mill workspace that has top level definitions and look at the logs, you'll find this:

```
SEVERE: file%3A%2F%2F%2FUsers%2Fckipp%2FDocuments%2Fscala-workspace%2Fbsp-test%2Fbuild.sc:3: error: expected class or object definition val
val test = 3
^
file%3A%2F%2F%2FUsers%2Fckipp%2FDocuments%2Fscala-workspace%2Fbsp-test%2Fbuild.sc:3: error: expected class or object definition val
val test = 3
^
        at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
        at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
        at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
        at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
        at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
        at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
        at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:4655)
        at scala.meta.internal.parsers.ScalametaParser.topStatSeq(ScalametaParser.scala:4662)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:4876)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:704)
        at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:720)
        at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:4842)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:4825)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:704)
        at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:720)
        at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:4824)
        at scala.meta.internal.parsers.ScalametaParser.entrypointSource(ScalametaParser.scala:4830)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$2(ScalametaParser.scala:142)
        at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:52)
        at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:142)
        at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
        at scala.meta.internal.parsers.ScalametaParser$$anon$259.apply(ScalametaParser.scala:4887)
        at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
        at scala.meta.internal.semanticdb.scalac.ParseOps$XtensionCompilationUnitSource.toSource(ParseOps.scala:11)
        at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:196)
        at scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:34)
```

**To Reproduce**

1. Open any Mill build with top level definitions in the `build.sc` file. (You can use [Ammonite](https://github.com/lihaoyi/Ammonite) as an example.
2. See error in the logs

**Expected behavior**

I'd expect not to see errors in this situation.

- Metals version: 0.9.10

**Search terms**

Mill top level definitions

**Comment by ckipp01** [comment]
Also note that this is currently throwing in Ammonite scripts as well.

**Comment by ckipp01** [comment]
I've been able to isolate this to this commit: https://github.com/scalameta/metals/commit/bd2339c32ce8430879f7c7a5edd0764ee1d7b036

**Comment by tgodzik** [comment]
Ach! It seems that it's because of the standalone files - we treat `.sc` as a normal standalone file. It should be easy to fix after the recent sbt PR. Just use Scala213 dialect with toplevel for ammonite scripts.
