### ISSUE TITLE
"No address associated with hostname" error when debugging in VSCode

### ISSUE THREAD

**Issue by tjm1518** [scalameta/metals#2431]
When I try and either use "run" or "debug" in VSCode, I get an error message saying `run session not started`.  
The logs give the error "No address associated with hostname" - I've tried changing the JVM proxy settings in the extension settings as well as my hostname (to a variety of values including localhost), however neither fixed it. All other aspects of the extension work fine.

**To Reproduce**

1. Set up a Mill project in VSCode with a main object.
2. Press either "run" or "debug" above the main object.

**Expected behavior**

A run/debug session should start

<details>
<summary>Logs</summary>
<br>
[Error - 18:23:56] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.net.UnknownHostException: tm: tm: No address associated with hostname
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: tm: tm: No address associated with hostname
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1642)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:240)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at scala.meta.internal.metals.debug.DebugProvider.connect(DebugProvider.scala:314)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$start$7(DebugProvider.scala:92)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	... 5 more
Caused by: java.net.UnknownHostException: tm: No address associated with hostname
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1637)
	... 15 more
</details>

**Installation:**

- Operating system: Void Linux 
- Editor: Visual Studio Code
- Metals version: v1.19.3

**Comment by tgodzik** [comment]
Thanks for reporting! It seems that `tm` hostname is somehow being picked up by the debugger. Any idea where that might be coming from?

This might be connected to https://github.com/scalameta/metals/issues/2405

**Comment by tjm1518** [comment]
It appears that when setting up my OS the hostname was set in `/etc/hostname` but wasn't added to `/etc/hosts` - I guess this is a (potential?) bug in the OS that Metals uncovered rather than a bug in Metals?

**Comment by tgodzik** [comment]
We should probably just use `127.0.0.1` -  I am not sure why we are getting `tm` at all, which I think is the problem here.

Anyway, glad it works for you! I will close it in favour of https://github.com/scalameta/metals/issues/2405 - since the problem looks the same, that we don't use proper address when running via socket.
