### ISSUE TITLE
NullPointerException in scala 3 due to compilation unit not being set

### ISSUE THREAD

**Issue by smarter** [scalameta/metals#2582]
From metals.log:
```scala
Exception in thread "pool-3-thread-1" java.lang.NullPointerException
	at dotty.tools.dotc.core.NameKinds$UniqueNameKind.fresh(NameKinds.scala:222)
	at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:2269)
	at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$6(Parsers.scala:2237)
	at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:2214)
	at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:2056)
	at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:1931)
	at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$7(Parsers.scala:2375)
	at dotty.tools.dotc.parsing.Parsers$Parser.tokenSeparated(Parsers.scala:591)
	at dotty.tools.dotc.parsing.Parsers$Parser.commaSeparated(Parsers.scala:599)
	at dotty.tools.dotc.parsing.Parsers$Parser.parArgumentExprs$$anonfun$1(Parsers.scala:2361)
	at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:559)
	at dotty.tools.dotc.parsing.Parsers$Parser.inParens(Parsers.scala:566)
	at dotty.tools.dotc.parsing.Parsers$Parser.parArgumentExprs(Parsers.scala:2362)
	at dotty.tools.dotc.parsing.Parsers$Parser.argumentExprs(Parsers.scala:2368)
	at dotty.tools.dotc.parsing.Parsers$Parser.simpleExprRest(Parsers.scala:2318)
	at dotty.tools.dotc.parsing.Parsers$Parser.simpleExprRest(Parsers.scala:2313)
	at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:2305)
	at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$6(Parsers.scala:2237)
	at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:2214)
	at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:2056)
	at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:1931)
	at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq$$anonfun$1(Parsers.scala:3940)
	at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:500)
	at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq(Parsers.scala:3954)
	at dotty.tools.dotc.parsing.Parsers$Parser.block(Parsers.scala:2430)
	at dotty.tools.dotc.parsing.Parsers$Parser.blockExpr$$anonfun$1(Parsers.scala:2422)
	at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:559)
	at dotty.tools.dotc.parsing.Parsers$Parser.inBraces(Parsers.scala:567)
	at dotty.tools.dotc.parsing.Parsers$Parser.inBracesOrIndented(Parsers.scala:580)
	at dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:584)
	at dotty.tools.dotc.parsing.Parsers$Parser.blockExpr(Parsers.scala:2420)
	at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:2278)
	at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$6(Parsers.scala:2237)
	at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:2214)
	at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:2056)
	at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:1931)
	at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$5(Parsers.scala:1911)
	at dotty.tools.dotc.parsing.Parsers$Parser.subPart(Parsers.scala:636)
	at dotty.tools.dotc.parsing.Parsers$Parser.subExpr(Parsers.scala:1913)
	at dotty.tools.dotc.parsing.Parsers$Parser.defDefOrDcl(Parsers.scala:3340)
	at dotty.tools.dotc.parsing.Parsers$Parser.defOrDcl(Parsers.scala:3217)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateStatSeq$$anonfun$1(Parsers.scala:3864)
	at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:500)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateStatSeq(Parsers.scala:3874)
	at dotty.tools.dotc.parsing.Parsers$Parser.$anonfun$32(Parsers.scala:3752)
	at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:559)
	at dotty.tools.dotc.parsing.Parsers$Parser.inBraces(Parsers.scala:567)
	at dotty.tools.dotc.parsing.Parsers$Parser.inBracesOrIndented(Parsers.scala:580)
	at dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:584)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateBody(Parsers.scala:3752)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateBodyOpt(Parsers.scala:3745)
	at dotty.tools.dotc.parsing.Parsers$Parser.template(Parsers.scala:3722)
	at dotty.tools.dotc.parsing.Parsers$Parser.templateOpt(Parsers.scala:3730)
	at dotty.tools.dotc.parsing.Parsers$Parser.objectDef(Parsers.scala:3486)
	at dotty.tools.dotc.parsing.Parsers$Parser.tmplDef(Parsers.scala:3445)
	at dotty.tools.dotc.parsing.Parsers$Parser.defOrDcl(Parsers.scala:3223)
	at dotty.tools.dotc.parsing.Parsers$Parser.topStatSeq(Parsers.scala:3810)
	at dotty.tools.dotc.parsing.Parsers$Parser.topstats$2(Parsers.scala:3990)
	at dotty.tools.dotc.parsing.Parsers$Parser.topstats$2(Parsers.scala:3984)
	at dotty.tools.dotc.parsing.Parsers$Parser.compilationUnit$$anonfun$1(Parsers.scala:3995)
	at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:500)
	at dotty.tools.dotc.parsing.Parsers$Parser.compilationUnit(Parsers.scala:4000)
	at dotty.tools.dotc.parsing.Parsers$Parser.parse(Parsers.scala:182)
	at scala.meta.internal.pc.CompilerInterfaces$.parseErrors(CompilerInterfaces.scala:40)
	at scala.meta.internal.pc.ScalaPresentationCompiler.didChange$$anonfun$1(ScalaPresentationCompiler.scala:338)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
	at scala.meta.internal.pc.CompilerAccess.withNonInterruptableCompiler$$anonfun$1(CompilerAccess.scala:125)
	at scala.meta.internal.pc.CompilerAccess.onCompilerJobQueue$$anonfun$1(CompilerAccess.scala:197)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The NPE is happening because `ctx.compilationUnit` is null, because `CompilerInterfaces` in metals called the compiler with a context without setting `setCompilationUnit` on that context to something.

**Comment by tgodzik** [comment]
Thanks @smarter for pointing this out! We don't actually compile the code, we just want to parse it at that point, which is why we missed it. Fixing it here: https://github.com/scalameta/metals/pull/2584
