### ISSUE TITLE
"Code navigation will not work for 2 build targets in this workspace due to mis-configuration" when do "Import Build" (VSCode, WSL2)

### ISSUE THREAD

**Issue by XuJinNet** [scalameta/metals#2592]
**Describe the bug**

I`m use "VSCode + Metals" to dev Scala project, my project files is in WSL2 Debian, when i do "Import Build", vscode report:
```
Code navigation will not work for 2 build targets in this workspace due to mis-configuration. Select 'More information' to learn how to fix this problem..
```

**To Reproduce**

1. Open the WSL remote project Dir in VSCode
2. Import Build

**Screenshots**

![image](https://user-images.githubusercontent.com/442382/110754434-cb1d8180-8282-11eb-9e7b-97aebe37530c.png)

![image](https://user-images.githubusercontent.com/442382/110754384-bb9e3880-8282-11eb-9013-91dce85ccdbb.png)

**Installation:**

- Operating system: Windows 10 + WSL2 (Debian)
- Editor: Visual Studio Code
- Metals version: v0.10.0

Some error logs:
```
[Error - 4:01:29 PM] Request textDocument/foldingRange failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.NoSuchElementException: BatchedFunction
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: BatchedFunction
	at scala.meta.internal.metals.BatchedFunction.<init>(BatchedFunction.scala:59)
	at scala.meta.internal.metals.MetalsLanguageServer.<init>(MetalsLanguageServer.scala:186)
	at scala.meta.metals.Main$.main(Main.scala:51)
	at scala.meta.metals.Main.main(Main.scala)

2021.03.11 16:02:55 ERROR code navigation does not work for the file '/home/xujin/My_Project/test/learning-scala/hello-world/src/main/scala/Main.scala' because the SemanticDB compiler plugin is not enabled for the build target hello-world.
2021.03.11 16:02:55 ERROR code navigation does not work for the file '/home/xujin/My_Project/test/learning-scala/hello-world/src/main/scala/Main.scala' because the SemanticDB compiler plugin is not enabled for the build target hello-world.
2021.03.11 16:03:04 ERROR code navigation does not work for the file '/home/xujin/My_Project/test/learning-scala/hello-world/src/main/scala/Main.scala' because the SemanticDB compiler plugin is not enabled for the build target hello-world.
2021.03.11 16:03:04 ERROR code navigation does not work for the file '/home/xujin/My_Project/test/learning-scala/hello-world/src/main/scala/Main.scala' because the SemanticDB compiler plugin is not enabled for the build target hello-world.
2021.03.11 16:03:04 ERROR code navigation does not work for the file '/home/xujin/My_Project/test/learning-scala/hello-world/src/main/scala/Main.scala' because the SemanticDB compiler plugin is not enabled for the build target hello-world.
[Error - 4:03:05 PM] Request textDocument/foldingRange failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.NoSuchElementException: BatchedFunction
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: BatchedFunction
	at scala.meta.internal.metals.BatchedFunction.<init>(BatchedFunction.scala:59)
	at scala.meta.internal.metals.MetalsLanguageServer.<init>(MetalsLanguageServer.scala:186)
	at scala.meta.metals.Main$.main(Main.scala:51)
	at scala.meta.metals.Main.main(Main.scala)

[Error - 4:03:11 PM] Request textDocument/foldingRange failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.NoSuchElementException: BatchedFunction
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: BatchedFunction
	at scala.meta.internal.metals.BatchedFunction.<init>(BatchedFunction.scala:59)
	at scala.meta.internal.metals.MetalsLanguageServer.<init>(MetalsLanguageServer.scala:186)
	at scala.meta.metals.Main$.main(Main.scala:51)
	at scala.meta.metals.Main.main(Main.scala)
```

**Comment by tgodzik** [comment]
Thanks for reporting, does it work if you reimport the build? I think this might have something to do with paths not being set correctly with WSL2.

**Comment by XuJinNet** [comment]
> Thanks for reporting, does it work if you reimport the build? I think this might have something to do with paths not being set correctly with WSL2.

I tried several times to re do "Import Build" and it worked, but I didn't make any changes.
Thanks.

**Comment by tgodzik** [comment]
I think that the paths sometimes get generated for the windows path, which causes issues for the build tool. That's my guess. Usually running import build should be enough help here. Glad it worked!
