### ISSUE TITLE
Error: sourcepath is required to load slim semanticdb

### ISSUE THREAD

**Issue by laughedelic** [scalameta/metals#264]
Running metals on itself, noticed this log message during initialization:

```
04:13:48.253 ERROR s.m.m.MetalsServices$ - Error converting s.Document to m.Document where filename=file:/Users/laughedelic/dev/laughedelic/metals/sbt-metals/src/main/scala/scala/meta/sbt/MetalsPlugin.scala
messages {
  position {
    start: 6306
    end: 6322
  }
  severity: WARNING
  text: "method append in class Extracted is deprecated (since 1.2.0): This discards session settings. Migrate to appendWithSession or appendWithoutSession."
}
language: "Scala212"
contents: ""
filename: "file:/Users/laughedelic/dev/laughedelic/metals/sbt-metals/src/main/scala/scala/meta/sbt/MetalsPlugin.scala"

java.lang.IllegalArgumentException: Error converting s.Document to m.Document where filename=file:/Users/laughedelic/dev/laughedelic/metals/sbt-metals/src/main/scala/scala/meta/sbt/MetalsPlugin.scala
messages {
  position {
    start: 6306
    end: 6322
  }
  severity: WARNING
  text: "method append in class Extracted is deprecated (since 1.2.0): This discards session settings. Migrate to appendWithSession or appendWithoutSession."
}
language: "Scala212"
contents: ""
filename: "file:/Users/laughedelic/dev/laughedelic/metals/sbt-metals/src/main/scala/scala/meta/sbt/MetalsPlugin.scala"

	at org.langmeta.internal.semanticdb.package$XtensionSchemaDatabase.$anonfun$toDb$8(package.scala:155)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:310)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:308)
	at scala.collection.AbstractIterator.to(Iterator.scala:1417)
	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:294)
	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:294)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1417)
	at org.langmeta.internal.semanticdb.package$XtensionSchemaDatabase.toDb(package.scala:158)
	at scala.meta.metals.MetalsServices.$anonfun$metaSemanticdbs$1(MetalsServices.scala:102)
	at monix.reactive.internal.operators.MapOperator$$anon$1.onNext(MapOperator.scala:44)
	at monix.reactive.internal.operators.MapOperator$$anon$1.onNext(MapOperator.scala:46)
	at monix.reactive.internal.operators.DoOnErrorOperator$$anon$1.onNext(DoOnErrorOperator.scala:36)
	at monix.reactive.subjects.PublishSubject.sendOnNextToAll(PublishSubject.scala:123)
	at monix.reactive.subjects.PublishSubject.onNext(PublishSubject.scala:101)
	at monix.reactive.observers.Subscriber$Implementation.onNext(Subscriber.scala:208)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.signalNext(SimpleBufferedSubscriber.scala:128)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.fastLoop(SimpleBufferedSubscriber.scala:193)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.run(SimpleBufferedSubscriber.scala:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Sourcepath is required to load slim semanticdb.
	at scala.sys.package$.error(package.scala:27)
	at org.langmeta.internal.semanticdb.package$XtensionSchemaDatabase.$anonfun$toDb$2(package.scala:68)
	at scala.Option.getOrElse(Option.scala:121)
	at org.langmeta.internal.semanticdb.package$XtensionSchemaDatabase.toDb(package.scala:68)
	at org.langmeta.internal.semanticdb.package$XtensionSchemaDatabase.$anonfun$toDb$8(package.scala:150)
	... 28 common frames omitted
```

**Comment by olafurpg** [comment]
Fixed in #332, the logic for loading SemanticDB files has been simplified and we no longer hit the code path that triggered this exception.
