### ISSUE TITLE
Worksheet gives no output nor an error message if toString throws an exception

### ISSUE THREAD

**Issue by julesjacobs** [scalameta/metals#2665]
If I put this code into a worksheet:

```
object foo { override def toString() = assert(false) }
val x = foo
```

Then there is no output displayed for `val x = foo`, nor an error message. If you change it to `val x = foo.toString()`, then an error is displayed.

**Expected behavior**

Display an error message for `val x = foo`, the same as if we did `val x = foo.toString()`.

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.10.0

**Comment by ckipp01** [comment]
Thanks for the report @julesjacobs, although this shouldn't even compile and when testing it, I get the error that I'd expect.

```
error: worksheets.worksheet.sc:2:40: type mismatch;
 found   : Unit
 required: String
object foo { override def toString() = assert(false) }
                                       ^^^^^^^^^^^^^
2021.04.01 11:25:23 INFO  time: evaluated worksheet 'worksheets.worksheet.sc' in 0.26s
```
And then I see the diagnostic reported as I'd expect:

<img width="618" alt="Screenshot 2021-04-01 at 11 27 44" src="https://user-images.githubusercontent.com/13974112/113273800-4cde5900-92dd-11eb-84eb-4baee474ddeb.png">

I'm assuming this isn't what you're seeing?

Just to be sure, I see you're on v1.10.0 of the VS Code extension, but are you using the default Metals version, or have you ever set the metals server version in the extension settings? Also, do you have the fallback scala version set to anything by chance, or is that still the default? Also, what JDK version are you using?

**Comment by julesjacobs** [comment]
Thanks for the response! I am not seeing that!
The precise behaviour depends on how I typed in the code. If I paste it in, then I see this:

![image](https://user-images.githubusercontent.com/476654/113276653-54ebc800-92e0-11eb-8461-0b05d2bf49b8.png)

If I delete foo, and re-type it f-o then it displays:

![image](https://user-images.githubusercontent.com/476654/113276743-6f25a600-92e0-11eb-836c-022c717bc136.png)

If I type the last o:

![image](https://user-images.githubusercontent.com/476654/113276823-7ba9fe80-92e0-11eb-9081-51c34e6d7f6d.png)

If I type .toString():

![image](https://user-images.githubusercontent.com/476654/113276944-8e243800-92e0-11eb-8474-ea1e30cdc664.png)

I have not changed any settings. The only settings in settings.json related to metals are, as far as I can see:

```    
     "files.watcherExclude": {
        "**/.bloop": true,
        "**/.metals": true,
        "**/.ammonite": true
    },
    "metals.javaHome": "/Users/jules/.jabba/jdk/adopt@1.11.0-9/Contents/Home"
```

This is my JDK version: 

```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)
```

**Comment by ckipp01** [comment]
Sort of an aside, but I'm unsure that setting your `javaHome` in that manner will work. I believe it should just be `/Users/jules/.jabba/jdk/adopt@1.11.0-9`. In another note, the example where you have 

```
object foo {
  override def toString(): String =
    assert(true)
    "foo"

    val x = foo
}
```

Are you by chance in a Scala 3 workspace? It was throwing me off for a bit since that didn't even compile for me, but if I bump to a Scala 3 workspace then it does.

Even so after saving the error I get is displayed.

<img width="914" alt="Screenshot 2021-04-01 at 20 03 36" src="https://user-images.githubusercontent.com/13974112/113335546-61deda80-9325-11eb-91f1-eb4694c031ef.png">

Are you able to show the output of the Metals Doctor?

**Comment by tgodzik** [comment]
I am getting that if the worksheet is using Scala 3:

```
2021.04.01 19:56:18 ERROR worksheet: /home/tgodzik/Documents/metals/metals.worksheet.sc
java.lang.AssertionError: assertion failed
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
	at repl.MdocSession$App$foo$.toString(metals.worksheet.sc:8)
	at mdoc.internal.worksheets.WorksheetProvider.$anonfun$3(WorksheetProvider.scala:140)
	at mdoc.internal.worksheets.WorksheetProvider.$anonfun$adapted$1(WorksheetProvider.scala:141)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1279)
	at mdoc.internal.worksheets.WorksheetProvider.renderSummary(WorksheetProvider.scala:141)
	at mdoc.internal.worksheets.WorksheetProvider.renderDecoration(WorksheetProvider.scala:72)
	at mdoc.internal.worksheets.WorksheetProvider.$anonfun$2$$anonfun$1(WorksheetProvider.scala:41)
	at scala.collection.immutable.List.map(List.scala:250)
	at mdoc.internal.worksheets.WorksheetProvider.$anonfun$1(WorksheetProvider.scala:41)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:585)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:599)
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:470)
	at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:574)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1279)
	at mdoc.internal.worksheets.WorksheetProvider.evaluateWorksheet(WorksheetProvider.scala:47)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:52)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:49)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:357)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.liftedTree1$1(WorksheetProvider.scala:261)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:261)
```

That is in Metals actually, since that one is the automatic Scala version (we choose the latest existing in the workspace)

**Comment by tgodzik** [comment]
It looks from your screenshots that you are actually using Scala 3, and it seems the exception is actually thrown when printing the value instead of when we run the code when we do:
`out.append(value.toString.replace("\n",""))`

I am not sure why that is not happening during the evaluation, but we can take a look in mdoc how the code is being translated.

**Comment by julesjacobs** [comment]
Yes I'm using Scala 3! Sorry I forgot to mention that. 

@ckipp01: If I put the `val x = foo` inside the toString method then I do get the same type error as you. The error occurs when the `val x = foo` is on the top level because then the toString method is implicitly called by the worksheet to display the output of a line. By the way I did not edit my settings.json myself. That happened automatically for me :)

@tgodzik: Cool!

Thanks for all the great work, I'm really enjoying the IDE!

**Comment by ckipp01** [comment]
> @ckipp01: If I put the val x = foo inside the toString method then I do get the same type error as you. The bug occurs when the val x = foo is on the top level because then the toString method is implicitly called by the worksheet to display the output of a line, probably outside of the exception handler that displays the error messages. 

ah jeez, I didn't even realize I wasn't actually copying what you had correctly! That was my bad!
