### ISSUE TITLE
Run and debug sessions fail to start in VS-code.

### ISSUE THREAD

**Issue by bent95** [scalameta/metals#2680]
I am trying to setup metals (v1.10.0) in VS-code (1.55.0, Windows 10 x64), and everything seems to be working except that I am unable to run or debug projects. Trying to do so results in an error for any project, including newly created projects using the hello-world and scala3 templates. 

When clicking either the run or debug button above the main function it immediately fails with the error message: “Run [/Debug] session not started Source: Scala (Metals) (Extension)”. It also produces the following error message in the Metals output window:

```
[Error - 20:08:15] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
    at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
    at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
    at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
    at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
    at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
    at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
    at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
    at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
    at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
    at scala.concurrent.Promise.complete(Promise.scala:53)
    at scala.concurrent.Promise.complete$(Promise.scala:52)
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress
    at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:236)
    at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:229)
    at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
    at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
    ... 4 more
```

I don’t know if it is of any use, but here is the metal log from when I open the project as well:

```
Java home: C:\Program Files\Java\jdk-11
Metals version: 0.10.0
2021.04.05 20:21:32 INFO  logging to file C:\Users\Admin\source\intelliJ\other\scala32\.metals\metals.log
2021.04.05 20:21:32 INFO  Started: Metals version 0.10.0 in workspace 'C:\Users\Admin\source\intelliJ\other\scala32' for client vscode 1.55.0.
2021.04.05 20:21:33 INFO  time: initialize in 1.07s
Initializing Scala Debugger
2021.04.05 20:21:33 INFO  Flyway Community Edition 7.5.3 by Redgate
2021.04.05 20:21:33 INFO  Database: jdbc:h2:file:C:\Users\Admin\source\intelliJ\other\scala32\.metals\metals (H2 1.4)
2021.04.05 20:21:33 INFO  Successfully validated 3 migrations (execution time 00:00.020s)
2021.04.05 20:21:33 INFO  Current version of schema "PUBLIC": 3
2021.04.05 20:21:33 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2021.04.05 20:21:34 INFO  Attempting to connect to the build server...
2021.04.05 20:21:34 WARN  no build target for: C:\Users\Admin\source\intelliJ\other\scala32\src\main\scala\Main.scala
2021.04.05 20:21:34 INFO  skipping build import with status 'Installed'
2021.04.05 20:21:34 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\Users\Admin\source\intelliJ\other\scala32\null\scalameta\metals\cache\bsp.trace.json
2021.04.05 20:21:34 INFO  Attempting to connect to the build server...
2021.04.05 20:21:35 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at c:\Users\Admin\source\intelliJ\other\scala32\null\scalameta\metals\cache\bsp.trace.json
2021.04.05 20:21:35 INFO  time: Connected to build server in 0.54s
2021.04.05 20:21:35 INFO  Connected to Build server: Bloop v1.4.8
2021.04.05 20:21:36 INFO  no build target: using presentation compiler with only scala-library: 2.12.13
2021.04.05 20:21:38 INFO  no build target: using presentation compiler with only scala-library: 2.12.13
2021.04.05 20:21:38 INFO  time: code lens generation in 4.35s
2021.04.05 20:21:39 INFO  time: indexed workspace in 2.39s
2021.04.05 20:21:39 INFO  compiling root (1 scala source)
2021.04.05 20:21:39 ERROR error while loading hello,
class file C:\Users\Admin\source\intelliJ\other\scala32\.bloop\root\bloop-internal-classes\classes-Metals-YaB9LNAYSSWcPNumnH6w0g==-E0oOCznLSmmtH-IezV_pdg==\hello.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 0 [unstable release: 1]}
 found   : {majorVersion: 28, minorVersion: 0 [unstable release: 3]}

This TASTy file was produced by an unstable release.
To read this TASTy file, your tooling must be at the same version.
The TASTy file was produced by Scala 3.0.0-RC2.
Note that your tooling is currently using an unstable TASTy version.
```

If anyone has any idea of what the cause of this is, and how to fix it, I’d be grateful to hear it!

**Comment by bent95** [comment]
After a lot of trial and error, clicking on all the settings I could find, deleting caches, and so on, at some point the problem disappeared and I am not really sure why. Anyway, I am closing this issue since I can no longer reproduce the problem.

**Comment by trevoryao** [comment]
Any chance you figured out why the issue was happening? I am currently having the same issue on macOS with Scala 2.13.3.

**Comment by bent95** [comment]
@trevoryao Unfortunately, I never figured out why it was happening. I ended up not using Scala for my project after all, so I have barely used metals since.

**Comment by trevoryao** [comment]
@tgodzik I closed the workspace and metals and just checked on it again, seems to be working, but I did clean compile previously to no avail. I will make an issue if it happens again.
