### ISSUE TITLE
Failed to download Metals Server Version 0.10.1

### ISSUE THREAD

**Issue by AhmedMesawer** [scalameta/metals#2685]
**Describe the bug**

since latest version 0.10.1 and this error appears to me 
![image](https://user-images.githubusercontent.com/35766435/113895140-f5525880-97c8-11eb-91d8-20ac741c4b01.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.10.0

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! Is there any information in the Output (Metals) ?

**Comment by AhmedMesawer** [comment]
@tgodzik 
```
Java home: C:\Program Files\Java\jdk1.8.0_171
Metals version: 0.10.1
Exception in thread "main" java.lang.ExceptionInInitializerError
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
Caused by: java.lang.RuntimeException: Error creating cache directory
	at coursier.bootstrap.launcher.c.<clinit>(Unknown Source)
	... 2 more
Caused by: java.nio.file.AccessDeniedException: C:\Program Files\Microsoft VS Code\null
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at coursier.bootstrap.launcher.o.a(Unknown Source)
	at coursier.bootstrap.launcher.j.a(Unknown Source)
	at coursier.bootstrap.launcher.i.a(Unknown Source)
	... 3 more
Downloading Metals failed with the following:
Process exited with code 1
```

**Comment by tgodzik** [comment]
It look like the https://github.com/scalameta/metals/issues/2451 issue, we need to update coursier in the metals-vscode extension. Seems there are some issues on windows :/

**Comment by tgodzik** [comment]
In the meantime you can use the older version of the extension, it's possible to change it in the extensions window.
