### ISSUE TITLE
test decorator and metals.test-current-file fails when using SBT as language server

### ISSUE THREAD

**Issue by markusa380** [scalameta/metals#2689]
**Describe the bug**

When trying to execute tests using decorator or command, I get different error messages:

```
[Error - 10:07:58 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
```

for the example project below, but

```
[Error - 5:18:50 PM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  no matching test group
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
    at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
    at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
    at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
    at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
    at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
    at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
    at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
    at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
    at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
    at scala.concurrent.Promise.complete(Promise.scala:53)
    at scala.concurrent.Promise.complete$(Promise.scala:52)
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  no matching test group
    at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:237)
    at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:229)
    at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
    at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
    ... 4 more
```

for a real project.

**To Reproduce**

Use VSCode stable with latest Metals plugin (Metals version: `0.10.1`)

* Run `sbt new scala/scala-seed.g8`
* Update SBT version in `build.properties` to `1.5.0`
* Start `sbt --client`
* Run `metals.bsp-switch` command and switch to SBT
* Wait for import to complete
* Navigate to `HelloSpec` and attempt to run using either decorator or command

**Expected behavior**

The test is executed

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.1

**Search terms**

test, command, sbt, bsp

**Comment by tgodzik** [comment]
Thanks for reporting! @adpi2 any idea what might be going on?

**Comment by adpi2** [comment]
The issue is probably that sbt is started before `metals.bsp-switch` is run.

**Comment by markus1189** [comment]
@adpi2 Wrong markus :)

**Comment by markusa380** [comment]
@adpi2 Rebooting SBT did in fact fix it for the test project as described in the reproduction steps - unfortunately for our actual code project the (big) error remains, I yet have to find the reason. I'll close this issue and open a new one when I know more.

**Comment by adpi2** [comment]
@tgodzik maybe we should make sure to run the BSP `workspace/reload` request each time Metals changes the `metals.sbt` file.

**Comment by tgodzik** [comment]
I think we are already doing that? Correct me if I'm wrong @ckipp01

**Comment by ckipp01** [comment]
> I think we are already doing that? Correct me if I'm wrong @ckipp01

Not automatically no. However, when the user does a `bsp-switch` and the `metals.sbt` changes I believe we detect that and prompt them to reload the build. Let me play around with this a bit to see if I can mimic it.
