### ISSUE TITLE
Upgrade io.get-coursier:coursier to 2.0.16 and io.get-coursier:interface to 1.0.4

### ISSUE THREAD

**Issue by greg-a-atkinson** [scalameta/metals#2694]
**Symptom:** Bloop server download, install and error (stack trace below) due to suspected failure to resolve coursier config directory on Windows 10, thereby not discovering the coursier global credentials for authenticating with a private artifact repository. (Private authenticated repository bootstrap download succeed on Windows 10 with metals-vscode 1.10.2 depending on coursier 2.0.16.)
**Root cause:** Windows directory resolution issues resolved in dev.dirs:directories:24 (https://github.com/dirs-dev/directories-jvm#changelog)
**Suggested fix:** Upgrade io.get-coursier:coursier to 2.0.16 and io.get-coursier:interface to 1.0.4

Windows directory resolution issue fixed by:
- https://github.com/dirs-dev/directories-jvm/issues/47

Metals dependencies fixed in:
- dev.dirs:directories:24 @ https://github.com/dirs-dev/directories-jvm#changelog
- io.get-coursier:coursier:2.0.15 @ https://github.com/coursier/coursier/releases/tag/v2.0.15
- io.get-coursier:interface:1.0.4 @ https://github.com/coursier/interface/releases/tag/v1.0.4

Metals fixed in:
- org.scalameta:metals-vscode:1.10.2 @ https://github.com/scalameta/metals-vscode/releases/tag/v1.10.2
  - https://github.com/scalameta/metals-vscode/pull/535
  - https://github.com/scalameta/metals-vscode/issues/534
- org.scalameta:metals proposal:
  - upgrade io.get-coursier:coursier to 2.0.16
  - upgrade io.get-coursier:interface to 1.0.4
    - not sure if these artifacts are published to a public repository, following up: https://github.com/coursier/interface/issues/193

**To Reproduce**

1. Configure coursier's mirror.properties to substitute public repositories for a private repository
2. Configure coursier's credentials.properties for authenticated access to the private repository
3. Open VSCode
4. Install metals-vscode 1.10.2
5. Import the build for an sbt scala project

**Expected behavior**

Project build is successfully imported by Metals in VSCode on Windows 10 against a private artifact repository.

**Installation:**

- Operating system: Windows 10
- Editor: Visual Studio Code
- Metals version: v0.10.1
- Metals-VSCode version: v0.10.2

**Additional context**

From `.metals/metals.log`
```
2021.04.08 15:28:15 INFO Started: Metals version 0.10.1 in workspace 'C:\Users\user\working\src\swaps\flow-manager' for client vscode 1.51.1.
2021.04.08 15:28:17 INFO time: initialize in 1.3s
2021.04.08 15:28:19 INFO Attempting to connect to the build server...
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 11772'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: The command bsp --protocol tcp --port 11772 returned with an error

No server running at 127.0.0.1:8212, let's fire one...
Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.8...
error: Unexpected error when resolving Bloop server via coursier!
error: Error downloading ch.epfl.scala:bloop-frontend_2.12:1.4.8
  not found: C:\Users\user.ivy2\local\ch.epfl.scala\bloop-frontend_2.12\1.4.8\ivys\ivy.xml
  unauthorized: https://artifacts.private.com/artifactory/virtual-java/ch/epfl/scala/bloop-frontend_2.12/1.4.8/bloop-frontend_2.12-1.4.8.pom (Artifactory Realm)
  download error: Caught java.net.UnknownHostException: dl.bintray.com (dl.bintray.com) while downloading https://dl.bintray.com/scalacenter/releases/ch/epfl/scala/bloop-frontend_2.12/1.4.8/bloop-fronte>
bloop.shaded.coursier.error.ResolutionError$CantDownloadModule: Error downloading ch.epfl.scala:bloop-frontend_2.12:1.4.8
not found: C:\Users\user.ivy2\local\ch.epfl.scala\bloop-frontend_2.12\1.4.8\ivys\ivy.xml
unauthorized: https://artifacts.private.com/artifactory/virtual-java/ch/epfl/scala/bloop-frontend_2.12/1.4.8/bloop-frontend_2.12-1.4.8.pom (Artifactory Realm)
download error: Caught java.net.UnknownHostException: dl.bintray.com (dl.bintray.com) while downloading https://dl.bintray.com/scalacenter/releases/ch/epfl/scala/bloop-frontend_2.12/1.4.8/bloop-fronte>
  at bloop.shaded.coursier.Resolve$.$anonfun$validate$1(Resolve.scala:323)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.Iterator.foreach(Iterator.scala:943) at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431) at scala.collection.IterableLike.foreach(IterableLike.scala:74)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:73) at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
  at bloop.shaded.coursier.Resolve$.validate(Resolve.scala:321)
  at bloop.shaded.coursier.Resolve.validate0$1(Resolve.scala:115)
  at bloop.shaded.coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:161)
  at bloop.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
  at bloop.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
  at bloop.shaded.coursier.util.Task$.wrap(Task.scala:84) at bloop.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14) 
  at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
  at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
  at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
error: Server could not be started at None:Some(8212)! Giving up...
error: The launcher failed to establish a bsp connection, aborting...
2021.04.08 15:28:25 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
  at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
  at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
  at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:159)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

**Search terms**

metals coursier authentication credentials bloop

**Comment by tgodzik** [comment]
Thanks for reporting! I am updating coursier version here https://github.com/scalacenter/bloop/pull/1485 - I will later update Bloop version in Metals.

I also need to work a bit on making Bloop more stable, haven't had the chance to properly start yet.

**Comment by greg-a-atkinson** [comment]
> Thanks for reporting! I am updating coursier version here [scalacenter/bloop#1485](https://github.com/scalacenter/bloop/pull/1485) - I will later update Bloop version in Metals.
> 
> I also need to work a bit on making Bloop more stable, haven't had the chance to properly start yet.

Thank you @tgodzik!
