### ISSUE TITLE
Scala 3 error reporting crash for bad `summonInline`

### ISSUE THREAD

**Issue by soronpo** [scalameta/metals#2769]
**Describe the bug**

Scala 3 (v3.0.0-RC3) `summonInline` crashes the metals error reporting.

**To Reproduce**

Use the following code:
```scala
inline def mark[T] = compiletime.summonInline[T]
val x = mark[1 =:= 2]
```

**Expected behavior**

Error should be reported for `x`

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.10.2

**Additional context**

Crash log
```
��� 08, 2021 4:00:54 ������ org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "build/publishDiagnostics",
  "params": {
    "textDocument": {
      "uri": "file:///c:/IdeaProjects/dtest/library/src/scala/compiletime/package.scala"
    },
    "buildTarget": {
      "uri": "file:/C:/IdeaProjects/dtest/?id\u003droot"
    },
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 0
          }
        },
        "severity": 1,
        "message": "cannot reduce summonFrom with\n patterns :  case \u001b[33mgiven \u001b[0mt @ _:\u001b[35m(\u001b[31m1\u001b[0m : Int) \u003d:\u003d (\u001b[31m2\u001b[0m : Int)\u001b[0m"
      }
    ],
    "reset": true
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.nio.file.NoSuchFileException: c:\IdeaProjects\dtest\library\src\scala\compiletime\package.scala
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.CommonMtagsEnrichments$XtensionAbsolutePath.toInput(CommonMtagsEnrichments.scala:435)
	at scala.meta.internal.metals.Diagnostics.onPublishDiagnostics(Diagnostics.scala:143)
	at scala.meta.internal.metals.Diagnostics.onBuildPublishDiagnostics(Diagnostics.scala:123)
	at scala.meta.internal.metals.ForwardingMetalsBuildClient.onBuildPublishDiagnostics(ForwardingMetalsBuildClient.scala:99)
	... 15 more
```
**Search terms**

summon

**Comment by soronpo** [comment]
@tgodzik You are right that the path is bad. It has nothing to do with windows though. It seems that the inlining messes with positioning, so `summonInline` appears to metals that it is in apart of the current source whereas it is part of the dotty source. Maybe this is a bug in the compiler itself.

**Comment by soronpo** [comment]
How can we isolate the problem if this is a scala issue or a metals one?

**Comment by tgodzik** [comment]
What is the error when running sbt? If that is also wrong that means the compiler is at fault, otherwise this might be connected to Bloop (most likely outdated zinc fork.)

**Comment by soronpo** [comment]
Look at the comments of `This location contains code that was inlined from...`
```
[error] -- Error: C:\IdeaProjects\dtest\src\main\scala\Main.scala:11:12 ----------------
[error] 11 |val x = mark[1 =:= 2]
[error]    |        ^^^^^^^^^^^^^
[error]    |        cannot reduce summonFrom with
[error]    |         patterns :  case given t @ _:(1 : Int) =:= (2 : Int)
[error]    | This location contains code that was inlined from package.scala:140
[error]    | This location contains code that was inlined from Main.scala:10
```
I don't know what information is passed on to metals, but maybe it was confused from this inlining.

**Comment by dos65** [comment]
I've tried this sample locally on Linux + Metals `0.10.2`.
The interesting thing here that I don't get any compiler error in diagnostic for this code. Nor on bloop nor on sbt-BSP.

**Comment by soronpo** [comment]
Is there a compiler issue I can follow?
