### ISSUE TITLE
Metals can't connect to sbt bsp on M1 Mac

### ISSUE THREAD

**Issue by suliatis** [scalameta/metals#2798]
**Describe the bug**

Metals raises some JNI related error while initialising. The autosuggestions seems to work though, but the no diagnostics.

**To Reproduce**

1. Launch sbt in a project
2. Open nvim
3. Wait for coc.nvim to connect bsp

**Expected behavior**

Metals should connect to the build server just like on x86

**Installation:**

- Hardware: MacBook Pro 13, Apple M1, 16GB Mem
- OS:  Big Sur 11.3.1
- Editor: NVIM v0.5.0-dev+1319-g7c9569702
- JDK: OpenJDK 64-Bit Server VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)
- Metals version: 0.10.2+66-691c584f-SNAPSHOT (I started with 0.10.2 then I updated to the latest snapshot)

**Additional context**

Metals log:
```
[0m2021.05.15 12:10:42 INFO  Started: Metals version 0.10.2+66-691c584f-SNAPSHOT in workspace '/Users/suliatis/code/event-segmentation-service' for client coc.nvim 0.0.80.[0m
[0m2021.05.15 12:10:46 INFO  time: initialize in 4.51s[0m
[0m2021.05.15 12:10:45 INFO  Attempting to connect to the build server...[0m
[0m2021.05.15 12:10:46 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/suliatis/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
[0m2021.05.15 12:10:46 WARN  no build target for: /Users/suliatis/code/event-segmentation-service/src/main/scala/com/code/common/effect/Schedule.scala[0m
[0m2021.05.15 12:10:46 WARN  No build session currently active to reload.[0m
DanglingParentheses: top-level presets deprecated; use 'preset' subsection
[0m2021.05.15 12:10:49 INFO  no build target: using presentation compiler with only scala-library: 2.12.13[0m
May 15, 2021 12:10:50 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: unsupported signature: class scala.meta.internal.semanticdb.Signature$Empty$ Empty
java.lang.RuntimeException: unsupported signature: class scala.meta.internal.semanticdb.Signature$Empty$ Empty
	at scala.sys.package$.error(package.scala:30)
	at scala.meta.internal.semanticdb.scalac.SymbolInformationOps$XtensionGSymbolMSymbolInformation.sig(SymbolInformationOps.scala:153)
	at scala.meta.internal.semanticdb.scalac.SymbolInformationOps$XtensionGSymbolMSymbolInformation.toSymbolInformation(SymbolInformationOps.scala:243)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.tryFindMtree(TextDocumentOps.scala:370)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:678)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:205)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2505)
	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1296)
	at scala.reflect.internal.Trees.itraverse(Trees.scala:1394)
	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1264)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:744)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:205)
	at scala.reflect.internal.Trees.$anonfun$itraverse$1(Trees.scala:1271)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
	at scala.reflect.internal.Trees.traverseMemberDef$1(Trees.scala:1267)
	at scala.reflect.internal.Trees.itraverse(Trees.scala:1392)
	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1264)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:744)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:205)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2505)
	at scala.reflect.internal.Trees.itraverse(Trees.scala:1390)
	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1264)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:744)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:747)
	at scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:51)

May 15, 2021 12:10:50 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: unsupported signature: class scala.meta.internal.semanticdb.Signature$Empty$ Empty
java.lang.RuntimeException: unsupported signature: class scala.meta.internal.semanticdb.Signature$Empty$ Empty
	at scala.sys.package$.error(package.scala:30)
	at scala.meta.internal.semanticdb.scalac.SymbolInformationOps$XtensionGSymbolMSymbolInformation.sig(SymbolInformationOps.scala:153)
	at scala.meta.internal.semanticdb.scalac.SymbolInformationOps$XtensionGSymbolMSymbolInformation.toSymbolInformation(SymbolInformationOps.scala:243)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.tryFindMtree(TextDocumentOps.scala:370)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:678)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:205)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2505)
	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1296)
	at scala.reflect.internal.Trees.itraverse(Trees.scala:1394)
	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1264)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:744)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:205)
	at scala.reflect.internal.Trees.$anonfun$itraverse$1(Trees.scala:1271)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
	at scala.reflect.internal.Trees.traverseMemberDef$1(Trees.scala:1267)
	at scala.reflect.internal.Trees.itraverse(Trees.scala:1392)
	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1264)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:744)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:205)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2505)
	at scala.reflect.internal.Trees.itraverse(Trees.scala:1390)
	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1264)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:744)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:747)
	at scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:51)
```

sbt logs:

```
[info] new client connected: network-1
sbt:event-segmentation-service> Exception in thread "sbt-network-1-write-thread" java.lang.NoClassDefFoundError: Could not initialize class org.scalasbt.ipcsocket.UnixDomainSocketLibrary
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.write(UnixDomainSocketLibrary.java:247)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.doWrite(UnixDomainSocket.java:185)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.write(UnixDomainSocket.java:176)
	at java.base/java.io.OutputStream.write(OutputStream.java:122)
	at sbt.internal.server.NetworkChannel.impl$1(NetworkChannel.scala:345)
	at sbt.internal.server.NetworkChannel.$anonfun$writeThread$1(NetworkChannel.scala:360)
	at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "sbt-networkchannel-0" java.lang.UnsatisfiedLinkError: /Users/suliatis/Library/Caches/JNA/temp/jna11566927411796505211.tmp: dlopen(/Users/suliatis/Library/Caches/JNA/temp/jna11566927411796505211.tmp, 1): no suitable image found.  Did find:
	/Users/suliatis/Library/Caches/JNA/temp/jna11566927411796505211.tmp: no matching architecture in universal wrapper
	/Users/suliatis/Library/Caches/JNA/temp/jna11566927411796505211.tmp: no matching architecture in universal wrapper
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.<clinit>(UnixDomainSocketLibrary.java:129)
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.read(UnixDomainSocketLibrary.java:238)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.doRead(UnixDomainSocket.java:157)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.read(UnixDomainSocket.java:125)
	at sbt.internal.util.ReadJsonFromInputStream$.apply(ReadJsonFromInputStream.scala:49)
	at sbt.internal.server.NetworkChannel$$anon$3.run(NetworkChannel.scala:181)
```

**Search terms**

m1 mac, apple silicon, jni

**Comment by dos65** [comment]
Thanks for reporting!

This looks like an issue in SBT. What version do you use?
I made a quick search and found that they fixed smth similar to your problem -https://github.com/sbt/sbt/pull/6165

**Comment by suliatis** [comment]
I'm using sbt 1.5.2 and everything seems to work except bsp. I wasn't sure if it metals or sbt related. I will report this issue for the sbt team then we will see.

Than you!

**Comment by tgodzik** [comment]
Alternatively, you could try switching to the newest Bloop version `1.4.8-39-c44bf129` (the version can be changed in settings), there were some recent fixes that might help.

**Comment by suliatis** [comment]
It works fine with bloop, thanks for the tip.

**Comment by suliatis** [comment]
If add this to my `globals.sbt`:

```
serverConnectionType := ConnectionType.Tcp,
```

then metals and sbt bsp works fine. 

Based on this comment: https://github.com/sbt/sbt/issues/6162#issuecomment-732277524

**Comment by tgodzik** [comment]
@suliatis thanks! I added an entry to the FAQ https://github.com/scalameta/metals/pull/2832
