### ISSUE TITLE
SQL error in .metals/metals.h2.db

### ISSUE THREAD

**Issue by DavidGoodenough** [scalameta/metals#2813]
2021.05.21 15:47:08 ERROR error processing file:/home/david/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.0.0/scaladoc_3-3.0.0-sources.jar
org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_3 ON PUBLIC.TOPLEVEL_SYMBOL(JAR, PATH, SYMBOL) VALUES ( /* key:5017 */ 'dotty/tools/scaladoc/SocialLinks.', '/dotty/tools/scaladoc/SocialLinks.scala', 203)"; SQL statement:
insert into toplevel_symbol (symbol, path, jar) values (?, ?, ?) [23505-200]
        at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1235)
        at scala.meta.internal.metals.JarTopLevels.putTopLevels(JarTopLevels.scala:96)
        at scala.meta.internal.metals.MetalsLanguageServer.addSourceJarSymbols(MetalsLanguageServer.scala:2447)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$8(MetalsLanguageServer.scala:2405)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
        at scala.collection.immutable.List.foreach(List.scala:431)
....

**Comment by dos65** [comment]
Thanks for reporting!

Actually, it's already fixed in #2809 so I'll close this one
