### ISSUE TITLE
Failed to download Metals

### ISSUE THREAD

**Issue by mjarosie** [scalameta/metals#2934]
**Describe the bug**

When opening VSCode with powershell (just `code .`) I get the following popup:

![image](https://user-images.githubusercontent.com/9082353/124506591-e2e5bc00-ddc3-11eb-8180-cd50632f5e7a.png)

I also get the following error in Metals' output:

```
Java home: C:\ProgramData\Java\jdk1.8.0_192\
Metals version: 0.10.4
Exception in thread "main" java.lang.RuntimeException: Error creating cache directory
	at coursier.bootstrap.launcher.c.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: C:\Program Files\Microsoft VS Code\null
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at coursier.bootstrap.launcher.u.a(Unknown Source)
	at coursier.bootstrap.launcher.p.a(Unknown Source)
	at coursier.bootstrap.launcher.o.a(Unknown Source)
	... 2 more
Downloading Metals failed with the following:
Process exited with code 1
```

When I open VSCode with the basic Windows command line, the problem doesn't occur.

**To Reproduce**

1. Open some Scala project in VSCode using Powershell (`code .`)
1. See error

**Expected behavior**

I'd like Metals to work when I turn VSCode on.

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.10.4

**Search terms**

Error creating cache directory
Microsoft VS Code\null

**Comment by dos65** [comment]
Thanks for reporting!

There is such an issue with PowerShell in Coursier - https://github.com/coursier/coursier/issues/2031

**Comment by tgodzik** [comment]
It's also related to https://github.com/dirs-dev/directories-jvm/issues/49

**Comment by tgodzik** [comment]
In the meantime I would suggest using linux subsystem for windows, which works pretty great with VS Code.

**Comment by piggybox** [comment]
I ran into the exact same problem and would like to confirm @tgodzik 's suggestion on using WSL works well. Just remember to install JDK and sbt again in WSL. The ones installed natively in Windows (thus outside of WSL) still cause some weird bugs.

**Comment by Rainrider** [comment]
You could also use the "Open with Code" context menu entry in File Explorer if you checked it in the installation of VS Code, it works for now at least.

**Comment by tgodzik** [comment]
The recomendation currently would be not to open vs code from power shell, there is not much on the Metals side we can do, so closing this a won't fix
