### ISSUE TITLE
Visual Studio Code Request textDocument/completion failed Internal error -32603

### ISSUE THREAD

**Issue by Wolf-Tungsten** [scalameta/metals#2976]
**Describe the bug**

Code completion does not work.

**To Reproduce**

1. Import a project.
2. Type some words that should be completed.

**Expected behavior**
There should be code completion like this:
![image](https://user-images.githubusercontent.com/19880884/126415860-575021c3-e80e-4065-8a36-1b0fad783a87.png)

However, same project and same file on a different host shows nothing but some unexpected outputs:
```
[Error - 9:13:27 AM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.ClassNotFoundException: scala.meta.internal.pc.ScalaPresentationCompiler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at scala.meta.internal.metals.Embedded.serviceLoader(Embedded.scala:86)
	at scala.meta.internal.metals.Embedded.presentationCompiler(Embedded.scala:71)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:638)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:619)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:605)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompilerForTarget$3(Compilers.scala:483)
	at scala.meta.internal.metals.StatusBar.trackBlockingTask(StatusBar.scala:46)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompilerForTarget$2(Compilers.scala:483)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2674)
	at scala.meta.internal.metals.Compilers.loadCompilerForTarget(Compilers.scala:479)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$2(Compilers.scala:466)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.loadCompiler(Compilers.scala:466)
	at scala.meta.internal.metals.Compilers.fromBuildTarget$1(Compilers.scala:385)
	at scala.meta.internal.metals.Compilers.loadCompiler(Compilers.scala:390)
	at scala.meta.internal.metals.Compilers.withPCAndAdjustLsp(Compilers.scala:530)
	at scala.meta.internal.metals.Compilers.completions(Compilers.scala:264)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$completion$1(MetalsLanguageServer.scala:1467)
	at scala.meta.internal.metals.CancelTokens$.future(CancelTokens.scala:38)
	at scala.meta.internal.metals.MetalsLanguageServer.completion(MetalsLanguageServer.scala:1467)
	... 16 more

```
**Screenshots**

![image](https://user-images.githubusercontent.com/19880884/126416082-70920bbf-ee13-45a2-9cd2-cb1327b65724.png)

**Installation:**

- Operating system: Linux(both Ubuntu and CentOS)
- Editor: Visual Studio Code
- Metals version: v0.10.8

**Additional context**

Here I use VSCode Remote-SSH extension to coding on a remote host, does this matter?

**Search terms**
Request textDocument/completion failed

**Comment by Wolf-Tungsten** [comment]
Finally, I changed the version back to 0.10.2 and code completion worked.

**Comment by tgodzik** [comment]
Thanks for reporting! This looks like we were unable to download mtags module that contains the ScalaPresentationCompiler class or the jar is invalid. Is there any other errors in the logs? Normally there should not be any issues with that part of code, but maybe it's an issue with the Java version being used on the remote host or proxy issue?

I think the remote is the clue here, but we've never had an issue like that and the code responsible hasn't changed since 0.10.2, it might be possible that you have it cached on the remote host.

**Comment by tgodzik** [comment]
This was most likely an issue with download, let us know if this happens again.
