### ISSUE TITLE
Diagnostics missing and vscode-languageclient logging error

### ISSUE THREAD

**Issue by blikkiee** [scalameta/metals#3026]
Diagnostics are missing. When I make a typo to trigger an compilation error, no diagnostics are shown.

The logs of metals seem ok. Metals correctly diagnoses the compilation error.
However, no visual feedback of the compilation error is shown in the editor. Also the log of the extension host report an error in the vscode-language client:

```
[2021-07-30 22:35:42.391] [exthost] [error] [scalameta.metals] provider FAILED
[2021-07-30 22:35:42.391] [exthost] [error] Canceled: Canceled
	at LanguageClient.makeCancelError (/home/user/.vscode/extensions/scalameta.metals-1.10.8/node_modules/vscode-languageclient/lib/common/client.js:2666:24)
	at LanguageClient.handleFailedRequest (/home/user/.vscode/extensions/scalameta.metals-1.10.8/node_modules/vscode-languageclient/lib/common/client.js:2656:28)
	at /home/user/.vscode/extensions/scalameta.metals-1.10.8/node_modules/vscode-languageclient/lib/common/client.js:908:39
```

**Installation:**

- Operating system: Ubuntu 20.04.2 LTS
- VSCode version: 1.58.2
- VSCode extension version: 1.10.8
- Metals version: 0.10.5

**Comment by blikkiee** [comment]
Not sure what was going wrong. I don't experience these problems any longer. Only notably thing that changed is going from vscode version 1.58.2 to 1.59.0.

Also since I am not able to reproduce it any longer, will close this issue.
