### ISSUE TITLE
[Scala 3] PrettyPrinter cannot always print short type.

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#3030]
**Describe the bug**

```
Exception in thread "pool-11-thread-16" java.lang.AssertionError: assertion failed: P.A
    at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
    at dotty.tools.dotc.core.Types$TypeBounds.<init>(Types.scala:4791)
    at dotty.tools.dotc.core.Types$RealTypeBounds.<init>(Types.scala:4852)
    at dotty.tools.dotc.core.Types$TypeBounds$.apply(Types.scala:4896)
    at scala.meta.internal.pc.Signatures$package$.loop$1(Signatures.scala:184)
    at scala.meta.internal.pc.Signatures$package$.shortType(Signatures.scala:199)
    at scala.meta.internal.pc.SymbolPrinter.paramLabel(SymbolPrinter.scala:266)
    at scala.meta.internal.pc.SymbolPrinter.$anonfun$7(SymbolPrinter.scala:149)
    at scala.collection.immutable.List.flatMap(List.scala:293)
    at scala.meta.internal.pc.SymbolPrinter.label$2$$anonfun$1(SymbolPrinter.scala:149)
    at scala.collection.immutable.List.flatMap(List.scala:293)
    at scala.meta.internal.pc.SymbolPrinter.label$1(SymbolPrinter.scala:153)
    at scala.meta.internal.pc.SymbolPrinter.defaultMethodSignature(SymbolPrinter.scala:156)
    at scala.meta.internal.pc.SymbolPrinter.completionDetailString(SymbolPrinter.scala:99)
    at scala.meta.internal.pc.ScalaPresentationCompiler.completionItems$$anonfun$1(ScalaPresentationCompiler.scala:503)
    at scala.collection.immutable.List.map(List.scala:246)
    at scala.meta.internal.pc.ScalaPresentationCompiler.completionItems(ScalaPresentationCompiler.scala:608)
    at scala.meta.internal.pc.ScalaPresentationCompiler.$anonfun$7(ScalaPresentationCompiler.scala:180)
    at scala.collection.immutable.List.flatMap(List.scala:293)
    at scala.meta.internal.pc.ScalaPresentationCompiler.complete$$anonfun$1(ScalaPresentationCompiler.scala:181)
at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
at scala.meta.internal.pc.CompilerAccess.$anonfun$1(CompilerAccess.scala:87)
(truncated)
```

**To Reproduce**

I haven't managed to reproduce but it seems the cause is https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/Types.scala#L4898

Edit:

Seems using cats-parse and writing `P[NonEmptyList[P.A]]` and trying a completion on that causes the issue.
**Expected behavior**

No exception is thrown.

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.10.5

**Additional context**

Reported on discord https://discord.com/channels/632642981228314653/632841682211045396/873281948183822417

**Search terms**

completions exception scala3 printer

**Comment by tgodzik** [comment]
Ok, looks like this might have been fixed along the way, thanks for checking!
