### ISSUE TITLE
Metals wont work with git worktree

### ISSUE THREAD

**Issue by antosha417** [scalameta/metals#3033]
**Describe the bug**

I want to use awesome git feature called git worktree with scala project. But it seems that metals can't import build due to some error.

**To Reproduce**

1. Clone any scala repository. For example `git clone https://github.com/alonsodomin/cron4s`
2. Run `git worktree add 0.4.x` to add another worktree for branch `0.4.x`. Or any other branch
3. Go to created forlder `0.4.x`. Open VS code and  try to import build.
4. See error in metals.log

**Expected behavior**
I expected for metals to be able to import project. 

**Screenshots**
Here is my metals.log file
```
[0m2021.08.12 00:20:10 INFO  Started: Metals version 0.10.5 in workspace '/Users/antosha417/dev/workspace-cron4s/0.4.x' for client Visual Studio Code 1.59.0.[0m
[0m2021.08.12 00:20:12 INFO  time: initialize in 1.4s[0m
[0m2021.08.12 00:20:12 WARN  Build server is not auto-connectable.[0m
DanglingParentheses: top-level presets deprecated; use 'preset' subsection
[0m2021.08.12 00:20:15 INFO  running '/Users/antosha417/Library/Java/JavaVirtualMachines/azul-15.0.3/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Dfile.encoding=UTF8 -Xms1G -Xmx6G -XX:MaxMetaspaceSize=512M -XX:ReservedCodeCacheSize=250M -XX:+TieredCompilation -jar /var/folders/3c/zhvmm9t50ssdl0176vrv0h5w0000gp/T/metals6325464151109413648/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
[0m2021.08.12 00:20:15 WARN  no build target for: /Users/antosha417/dev/workspace-cron4s/0.4.x/project/metals.sbt[0m
[0m2021.08.12 00:20:15 WARN  no build target for: /Users/antosha417/dev/workspace-cron4s/0.4.x/project/project/metals.sbt[0m
[0m2021.08.12 00:20:15 INFO  skipping build import with status 'Started'[0m
[0m2021.08.12 00:20:16 INFO  [info] welcome to sbt 1.5.5 (Azul Systems, Inc. Java 15.0.3)[0m
[0m2021.08.12 00:20:17 INFO  [info] loading global plugins from /Users/antosha417/.sbt/1.0/plugins[0m
[0m2021.08.12 00:20:18 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.08.12 00:20:20 INFO  [info] loading settings for project root-0-4-x-build-build-build from metals.sbt ...[0m
[0m2021.08.12 00:20:20 INFO  [info] loading project definition from /Users/antosha417/dev/workspace-cron4s/0.4.x/project/project/project[0m
[0m2021.08.12 00:20:21 INFO  [info] loading settings for project root-0-4-x-build-build from metals.sbt ...[0m
[0m2021.08.12 00:20:21 INFO  [info] loading project definition from /Users/antosha417/dev/workspace-cron4s/0.4.x/project/project[0m
[0m2021.08.12 00:20:23 INFO  [success] Generated .bloop/root-0-4-x-build-build.json[0m
[0m2021.08.12 00:20:23 INFO  [success] Total time: 1 s, completed 12 Aug 2021, 00:20:23[0m
[0m2021.08.12 00:20:24 INFO  [info] loading settings for project root-0-4-x-build from metals.sbt,plugins.sbt ...[0m
[0m2021.08.12 00:20:24 INFO  [info] loading project definition from /Users/antosha417/dev/workspace-cron4s/0.4.x/project[0m
[0m2021.08.12 00:20:27 INFO  [success] Generated .bloop/root-0-4-x-build.json[0m
[0m2021.08.12 00:20:27 INFO  [info] compiling 3 Scala sources to /Users/antosha417/dev/workspace-cron4s/0.4.x/project/target/scala-2.12/sbt-1.0/classes ...[0m
[0m2021.08.12 00:20:31 INFO  [info] done compiling[0m
[0m2021.08.12 00:20:31 INFO  [success] Total time: 7 s, completed 12 Aug 2021, 00:20:31[0m
[0m2021.08.12 00:20:35 INFO  [info] loading settings for project cron4s from build.sbt ...[0m
[0m2021.08.12 00:20:35 INFO  [info] resolving key references (19739 settings) ...[0m
[0m2021.08.12 00:20:38 ERROR org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index[0m
[0m2021.08.12 00:20:38 ERROR 	at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1518)[0m
[0m2021.08.12 00:20:38 ERROR 	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:115)[0m
[0m2021.08.12 00:20:38 ERROR 	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:97)[0m
[0m2021.08.12 00:20:38 ERROR 	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:140)[0m
[0m2021.08.12 00:20:38 ERROR 	at com.typesafe.sbt.git.JGit.hasUncommittedChanges(JGit.scala:89)[0m
[0m2021.08.12 00:20:38 ERROR 	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21(SbtGit.scala:123)[0m
[0m2021.08.12 00:20:38 ERROR 	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21$adapted(SbtGit.scala:123)[0m
[0m2021.08.12 00:20:38 ERROR 	at com.typesafe.sbt.git.DefaultReadableGit.withGit(ReadableGit.scala:42)[0m
[0m2021.08.12 00:20:38 ERROR 	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$20(SbtGit.scala:123)[0m
[0m2021.08.12 00:20:38 ERROR 	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$20$adapted(SbtGit.scala:123)[0m
[0m2021.08.12 00:20:38 ERROR 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)[0m
[0m2021.08.12 00:20:38 ERROR 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)[0m
[0m2021.08.12 00:20:38 ERROR 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)[0m
[0m2021.08.12 00:20:38 ERROR 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)[0m
[0m2021.08.12 00:20:38 ERROR 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)[0m
[0m2021.08.12 00:20:38 ERROR 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)[0m
[0m2021.08.12 00:20:38 ERROR 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)[0m
[0m2021.08.12 00:20:38 ERROR 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)[0m
[0m2021.08.12 00:20:38 ERROR 	at java.base/java.lang.Thread.run(Thread.java:832)[0m
[0m2021.08.12 00:20:38 INFO  [error] org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index[0m
[0m2021.08.12 00:20:38 INFO  [error] Use 'last' for the full log.[0m
[0m2021.08.12 00:20:38 INFO  [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)[0m
[0m2021.08.12 00:20:38 INFO  sbt bloopInstall exit: 1[0m
[0m2021.08.12 00:20:38 INFO  time: ran 'sbt bloopInstall' in 23s[0m
[0m2021.08.12 00:20:38 ERROR sbt command failed: /Users/antosha417/Library/Java/JavaVirtualMachines/azul-15.0.3/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Dfile.encoding=UTF8 -Xms1G -Xmx6G -XX:MaxMetaspaceSize=512M -XX:ReservedCodeCacheSize=250M -XX:+TieredCompilation -jar /var/folders/3c/zhvmm9t50ssdl0176vrv0h5w0000gp/T/metals6325464151109413648/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall[0m
```

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.5

**Additional context**

**Search terms**
git worktree

**Comment by dos65** [comment]
Thanks for reporting but I don't think that it's an Metals issue.

I've cloned the repo and tried to run sbt in worktree directory and got the same error:
```
> cron4s/0.4.x$ sbt
[info] welcome to sbt 1.5.5 (Ubuntu Java 11.0.11)
[info] loading global plugins from /home/dos65/.sbt/1.0/plugins
[info] loading settings for project root-0-4-x-build from plugins.sbt ...
[info] loading project definition from /home/dos65/projects/metals/samples/cron4s/0.4.x/project
[info] compiling 3 Scala sources to /home/dos65/projects/metals/samples/cron4s/0.4.x/project/target/scala-2.12/sbt-1.0/classes ...
[info] loading settings for project cron4s from build.sbt ...
[info] resolving key references (18497 settings) ...
org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
	at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1518)
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:115)
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:97)
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:140)
	at com.typesafe.sbt.git.JGit.hasUncommittedChanges(JGit.scala:89)
	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21(SbtGit.scala:123)
	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21$adapted(SbtGit.scala:123)
	at com.typesafe.sbt.git.DefaultReadableGit.withGit(ReadableGit.scala:42)
	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$20(SbtGit.scala:123)
	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$20$adapted(SbtGit.scala:123)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[error] org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

It looks like a problem with some of sbt-plugins that are used in this project

**Comment by tgodzik** [comment]
Closing for now, let us know if there is something we might need to fix in Metals!
