### ISSUE TITLE
[Scala3] Interactive semanticdb might fail internally in compiler

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#3044]
Steps to reproduce:
- set up scala3 project with :
  ```scala
  scalaVersion := "3.0.2-RC1"
  libraryDependencies ++= Seq(
      "org.typelevel" %% "cats-effect" % "3.2.0"
  )
  ```
- open `cats.effect.kernel.Resource` source from dependency.
- notice the following in metals.log:
  <details>
     <summary>Error</summary>
     <code><pre>
        Exception in thread "pool-4-thread-7" java.lang.AssertionError: assertion failed: Attempt to commit TS[160796X, 160786X, 158994, 137830, 137829, 137827] into already committed TS[160786X, 158994, 137830, 137829, 137827]
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.core.TyperState.commit(TyperState.scala:146)
	at dotty.tools.dotc.typer.Inferencing$.isFullyDefined(Inferencing.scala:40)
	at dotty.tools.dotc.typer.Implicits.ignoredInstanceNormalImport$1(Implicits.scala:881)
	at dotty.tools.dotc.typer.Implicits.$anonfun$1(Implicits.scala:896)
	at dotty.tools.dotc.typer.ImplicitSearchError.hiddenImplicitsAddendum(ErrorReporting.scala:419)
	at dotty.tools.dotc.typer.ImplicitSearchError.missingArgMsg(ErrorReporting.scala:267)
	at dotty.tools.dotc.typer.Implicits.missingArgMsg(Implicits.scala:897)
	at dotty.tools.dotc.typer.Implicits.missingArgMsg$(Implicits.scala:774)
	at dotty.tools.dotc.typer.Typer.missingArgMsg(Typer.scala:106)
	at dotty.tools.dotc.typer.Typer.issueErrors$1$$anonfun$1$$anonfun$1(Typer.scala:3353)
	at dotty.tools.dotc.reporting.NoExplanation.msg(Message.scala:132)
	at dotty.tools.dotc.reporting.Message.message(Message.scala:87)
	at dotty.tools.dotc.reporting.Message.isNonSensical(Message.scala:99)
	at dotty.tools.dotc.reporting.HideNonSensicalMessages.isHidden(HideNonSensicalMessages.scala:16)
	at dotty.tools.dotc.reporting.HideNonSensicalMessages.isHidden$(HideNonSensicalMessages.scala:10)
	at dotty.tools.dotc.interactive.InteractiveDriver$$anon$5.isHidden(InteractiveDriver.scala:154)
	at dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:148)
	at dotty.tools.dotc.reporting.Reporter.flush$$anonfun$1(Reporter.scala:206)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.reporting.Reporter.flush(Reporter.scala:206)
	at dotty.tools.dotc.core.TyperState.commit(TyperState.scala:143)
	at dotty.tools.dotc.typer.Applications.fail$1(Applications.scala:986)
	at dotty.tools.dotc.typer.Applications.realApply$7$$anonfun$6$$anonfun$2(Applications.scala:992)
	at scala.Option.getOrElse(Option.scala:201)
	at dotty.tools.dotc.typer.Applications.realApply$8$$anonfun$7(Applications.scala:993)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2952)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:994)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1032)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:317)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:106)
	at dotty.tools.dotc.typer.Typer.typedInfixOp(Typer.scala:2584)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2732)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
	at dotty.tools.dotc.typer.Typer.$anonfun$34(Typer.scala:2156)
	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:225)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2156)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2670)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2755)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2847)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2897)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2352)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2681)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2685)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2755)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2847)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2897)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2475)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2726)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
	at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:120)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:120)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
	at dotty.tools.dotc.interactive.InteractiveDriver.run(InteractiveDriver.scala:163)
	at scala.meta.internal.pc.ScalaPresentationCompiler.hover$$anonfun$1(ScalaPresentationCompiler.scala:301)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
	at scala.meta.internal.pc.CompilerAccess.withNonInterruptableCompiler$$anonfun$1(CompilerAccess.scala:125)
	at scala.meta.internal.pc.CompilerAccess.onCompilerJobQueue$$anonfun$1(CompilerAccess.scala:197)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:139)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

     </pre></code>
  </details>

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: 0.10.6-M1+29-22f5a4b1-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for finding this one! Should we report it in Dotty repository?
