### ISSUE TITLE
NullPointerException when assigning null to a variable in a Scala 3 worksheet

### ISSUE THREAD

**Issue by cayhorstmann** [scalameta/metals#3054]
**Describe the bug**

A statement such as

```
val x: String = null
```

in a worksheet causes VS Code to stop evaluating the worksheet, with an exception 
```
java.lang.NullPointerException
	at mdoc.internal.worksheets.WorksheetProvider.$anonfun$4(WorksheetProvider.scala:141)
	at mdoc.internal.worksheets.WorksheetProvider.$anonfun$adapted$1(WorksheetProvider.scala:143)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1288)
	at mdoc.internal.worksheets.WorksheetProvider.renderSummary(WorksheetProvider.scala:143)
	at mdoc.internal.worksheets.WorksheetProvider.renderDecoration(WorksheetProvider.scala:73)
	at mdoc.internal.worksheets.WorksheetProvider.$anonfun$3$$anonfun$1(WorksheetProvider.scala:42)
	at scala.collection.immutable.List.map(List.scala:246)
	at mdoc.internal.worksheets.WorksheetProvider.$anonfun$2(WorksheetProvider.scala:42)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:585)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:599)
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:470)
	at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:574)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1288)
	at mdoc.internal.worksheets.WorksheetProvider.evaluateWorksheet(WorksheetProvider.scala:48)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:55)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:363)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.liftedTree1$1(WorksheetProvider.scala:267)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:267)
	
```
**To Reproduce**

1. `sbt new scala/scala3.g8 --name=ch1`
2. `echo "val x: String = null" > ch1/src/main/scala/my.worksheet.sc`
3. `codium ch1`
4. Trust the authors
5. Import build
6. Open src/main/my.worksheet.sc
7. Observe that the worksheet is not evaluated
8. Find the exception stack trace in the logs

**Expected behavior**

The worksheet should be evaluated and display
`// : String = null`

**Installation:**

- Operating system: Linux
- Visual Studio Code/
- Metals version: v1.10.8

**Comment by tgodzik** [comment]
Thanks for reporting! We need to fix this upstream in https://github.com/scalameta/mdoc/pull/550

**Comment by ckipp01** [comment]
This is fixed in the latest snapshot that includes mdoc 2.2.23 so closing.
