### ISSUE TITLE
Unique index or primary key violation Error

### ISSUE THREAD

**Issue by 1mdc** [scalameta/metals#3068]
Classes are not compiling due to h2 error. I have to reconnect or recompile the whole project every time this happens

It happens randomly so it is hard to know exact steps to re-produce the issue. Below is the error:
```
2021.08.25 12:07:33 ERROR error processing file:///Users/....jar
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_E ON PUBLIC.INDEXED_JAR(MD5) VALUES ( /* 759 */ 'AEF5EEA59BE9DF5F2B2A9D778A9FFACF' )"; SQL statement:
insert into indexed_jar (md5) values (?) [23505-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.pagestore.db.PageBtree.find(PageBtree.java:120)
	at org.h2.pagestore.db.PageBtreeLeaf.addRow(PageBtreeLeaf.java:148)
	at org.h2.pagestore.db.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:101)
	at org.h2.pagestore.db.PageBtreeNode.addRowTry(PageBtreeNode.java:204)
	at org.h2.pagestore.db.PageBtreeIndex.addRow(PageBtreeIndex.java:98)
	at org.h2.pagestore.db.PageBtreeIndex.add(PageBtreeIndex.java:89)
	at org.h2.pagestore.db.PageStoreTable.addRow(PageStoreTable.java:89)
	at org.h2.command.dml.Insert.insertRows(Insert.java:195)
	at org.h2.command.dml.Insert.update(Insert.java:151)
	at org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:272)
	at org.h2.command.CommandContainer.update(CommandContainer.java:191)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152)
	at scala.meta.internal.metals.JarTopLevels.putTopLevels(JarTopLevels.scala:75)
	at scala.meta.internal.metals.MetalsLanguageServer.addSourceJarSymbols(MetalsLanguageServer.scala:2461)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$8(MetalsLanguageServer.scala:2419)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$3(MetalsLanguageServer.scala:2407)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$3$adapted(MetalsLanguageServer.scala:2406)
	at scala.Option.foreach(Option.scala:407)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$2(MetalsLanguageServer.scala:2406)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$2$adapted(MetalsLanguageServer.scala:2405)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.MetalsLanguageServer.indexDependencySources(MetalsLanguageServer.scala:2405)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexWorkspace$10(MetalsLanguageServer.scala:2350)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.indexWorkspace(MetalsLanguageServer.scala:2350)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$profiledIndexWorkspace$2(MetalsLanguageServer.scala:2243)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$profiledIndexWorkspace$1(MetalsLanguageServer.scala:2243)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Class should be compiled and auto completed/ go to reference should work in Vs Code.

**Installation:**

- Operating system: macOS (intel CPU)
- Editor: Visual Studio Code
- Metals for vscode: v1.10.8

**Comment by dos65** [comment]
Thanks for reporting!

@1mdc Could you look at jar that causes this error? Does it contain any scala or java sources? It's hard to say what happens. According to code, I have an assumption that might happen in case if jar is empty.

**Comment by 1mdc** [comment]
You are right. It seems that jar file is empty source. At the location, `lib-5.5-sources.jar` is empty but `lib-5.5.jar` is not empty. It is one of dependency we rely on. I'm not sure how it happened
