### ISSUE TITLE
Exception being thrown on hover at times in Scala 3

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3072]
**Describe the bug**

I've seen this pop up a handful of times lately. I haven't been able to consistently reproduce it, so I don't have steps. I'm not even sure this is something we can fix on the Metals side and may be an issue with the upstream presentation compiler. However, I'll add this here for now and try to include any more information if I get any.

This will happen as I try to hover at times.

```
Exception in thread "pool-5-thread-16" dotty.tools.dotc.core.MissingType:
        at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:776)
        at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:204)
        at dotty.tools.dotc.core.Signature.$anonfun$2(Signature.scala:113)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Signature.prependTermParams(Signature.scala:113)
        at dotty.tools.dotc.core.Types$MethodOrPoly.computeSignature$1(Types.scala:3398)
        at dotty.tools.dotc.core.Types$MethodOrPoly.signature(Types.scala:3415)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:612)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.matchesLoosely(Denotations.scala:1033)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.matches(Denotations.scala:1016)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.filterDisjoint(Denotations.scala:1066)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.mapInherited(Denotations.scala:1061)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.mapInherited(Denotations.scala:1058)
        at dotty.tools.dotc.core.SymDenotations$ClassDenotation.collect$1(SymDenotations.scala:1974)
        at dotty.tools.dotc.core.SymDenotations$ClassDenotation.collect$1(SymDenotations.scala:1970)
        at dotty.tools.dotc.core.SymDenotations$ClassDenotation.addInherited(SymDenotations.scala:1979)
        at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeMembersNamed(SymDenotations.scala:1964)
        at dotty.tools.dotc.core.SymDenotations$ClassDenotation.membersNamed(SymDenotations.scala:1931)
        at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1982)
        at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:671)
        at dotty.tools.dotc.core.Types$Type.goThis$1(Types.scala:795)
        at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:688)
        at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:858)
        at dotty.tools.dotc.core.Types$Type.memberBasedOnFlags(Types.scala:654)
        at dotty.tools.dotc.core.Types$Type.member(Types.scala:638)
        at dotty.tools.dotc.core.Types$Type.allMembers$$anonfun$1(Types.scala:999)
        at scala.runtime.function.JProcedure2.apply(JProcedure2.java:15)
        at scala.runtime.function.JProcedure2.apply(JProcedure2.java:10)
        at dotty.tools.dotc.core.Types$Type.memberDenots$$anonfun$1(Types.scala:904)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.BitmapIndexedSetNode.foreach(HashSet.scala:937)
        at scala.collection.immutable.HashSet.foreach(HashSet.scala:944)
        at dotty.tools.dotc.core.Types$Type.memberDenots(Types.scala:904)
        at dotty.tools.dotc.core.Types$Type.allMembers(Types.scala:999)
        at scala.meta.internal.pc.IndexedContext$.accesibleMembers$1(IndexedContext.scala:145)
        at scala.meta.internal.pc.IndexedContext$.scala$meta$internal$pc$IndexedContext$$$extractNames(IndexedContext.scala:204)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:86)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:72)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:85)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:72)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:85)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:72)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:85)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:72)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:85)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:72)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:85)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:72)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:85)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:72)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:85)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:72)
        at scala.meta.internal.pc.ScalaPresentationCompiler.$anonfun$9(ScalaPresentationCompiler.scala:341)
        at scala.Option.map(Option.scala:242)
        at scala.meta.internal.pc.ScalaPresentationCompiler.hover$$anonfun$1(ScalaPresentationCompiler.scala:349)
        at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
        at scala.meta.internal.pc.CompilerAccess.withNonInterruptableCompiler$$anonfun$1(CompilerAccess.scala:125)
        at scala.meta.internal.pc.CompilerAccess.onCompilerJobQueue$$anonfun$1(CompilerAccess.scala:197)
        at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:139)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
**To Reproduce**

I don't have specific steps atm since I can't reproduce it on demand.

**Expected behavior**

No exceptions

**Installation:**

- Operating system: macOS
- Editor: nvim-metals
- Metals version:  0.10.6-M1+42-6710a21e-SNAPSHOT

**Comment by ckipp01** [comment]
I haven't seen this for a while, so either it was fixed in newer version of Dotty or something else fixed it. If I see it pop up again I'll re-open.
