### ISSUE TITLE
Error:  Vim:E117: Unknown function: coc#util#has_preview

### ISSUE THREAD

**Issue by timjstewart** [scalameta/metals#3096]
After I visit a scala buffer, I see a message saying "Metals is Ready"  and then after a few seconds a stack trace message is displayed (see below).

**To Reproduce**

1. Visit a scala source file in neovim
2. See error: 
```
[coc.nvim]: UnhandledRejection: request error nvim_call_function - Vim:E117: Unknown function: coc#util#has_preview
Error
    at NeovimClient2.request (/home/tim/.vim/plugged/coc.nvim/build/index.js:10144:21)
    at NeovimClient2.call (/home/tim/.vim/plugged/coc.nvim/build/index.js:11361:21)
    at /home/tim/.config/coc/extensions/node_modules/coc-metals/lib/index.js:28:8185
    at Generator.next (<anonymous>)
    at /home/tim/.config/coc/extensions/node_modules/coc-metals/lib/index.js:28:856
    at new Promise (<anonymous>)
    at r (/home/tim/.config/coc/extensions/node_modules/coc-metals/lib/index.js:28:604)
    at /home/tim/.config/coc/extensions/node_modules/coc-metals/lib/index.js:28:7801
    at handleNotification (/home/tim/.vim/plugged/coc.nvim/build/index.js:13926:17)
    at processMessageQueue (/home/tim/.vim/plugged/coc.nvim/build/index.js:13700:13)
```

**Expected behavior**

No error message appears.

What is curious is that there is a `coc#list#has_preview` in the `coc` plugin but not the function referred to by the error message.

**Installation:**

- Operating system: Linux (Arch)
- Editor: neovim
- Metals version: v0.10.5

**Additional context**

Output of neovim :version command:

```
NVIM v0.6.0-dev+206-g284199bc4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wi
mplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim
/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az50-370
```
Relevant vim-plug plugins:

```
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
Plug 'scalameta/coc-metals', {'do': 'yarn install --frozen-lockfile'}
```

Thanks!!

**Comment by ckipp01** [comment]
Thanks for the report @timjstewart! This was already reported here: https://github.com/scalameta/coc-metals/issues/421 and actually fixed. You should be able to update to the latest updates on the `main` branch of `coc-metals` and the issue should be fixed.
