### ISSUE TITLE
Failed to connect with build server on M1 Mac

### ISSUE THREAD

**Issue by Meowcolm024** [scalameta/metals#3228]
**Describe the bug**

**To Reproduce**

Opens a metal project, and import the build. The plugin prompts for installing JDK 11. After installing, everything works fine.

But when reopening the project, it fails to connect to the build server. It is strange that it works for the first, but fails later.

**Expected behavior**

The server should be running.

**Screenshots**

``` txt
Java home: /Users/yatchunglaw/.jabba/jdk/adopt@1.11.0-11/Contents/Home
Metals version: 0.10.7
2021.10.26 15:25:20 INFO  logging to file /Users/yatchunglaw/VSCodeProjects/amy-lab3/.metals/metals.log
2021.10.26 15:25:20 INFO  Started: Metals version 0.10.7 in workspace '/Users/yatchunglaw/VSCodeProjects/amy-lab3' for client Visual Studio Code 1.61.2.
2021.10.26 15:25:25 INFO  time: initialize in 4.89s
Initializing Scala Debugger
2021.10.26 15:25:25 INFO  Flyway Community Edition 7.14.1 by Redgate
2021.10.26 15:25:25 INFO  Database: jdbc:h2:file:/Users/yatchunglaw/VSCodeProjects/amy-lab3/.metals/metals (H2 1.4)
2021.10.26 15:25:25 INFO  Successfully validated 3 migrations (execution time 00:00.039s)
2021.10.26 15:25:25 INFO  Current version of schema "PUBLIC": 3
2021.10.26 15:25:25 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2021.10.26 15:25:26 INFO  Attempting to connect to the build server...
2021.10.26 15:25:25 WARN  no build target for: /Users/yatchunglaw/VSCodeProjects/amy-lab3/src/amyc/parsing/Parser.scala
2021.10.26 15:25:26 INFO  skipping build import with status 'Installed'
2021.10.26 15:25:33 INFO  no build target: using presentation compiler with only scala-library: 2.12.15
2021.10.26 15:25:37 INFO  time: code lens generation in 7.21s
2021.10.26 15:26:39 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

**Installation:**

- Operating system: macOS 12.0 (Apple Silicon)
- Editor: Visual Studio Code (Universal)
- Metals version: v0.10.7

**Additional context**

The Scala version of the project is `3.0.2`.

`sbt` works and the project successfully compiles.

``` txt
sbt:amyc> compile
[info] compiling 1 Scala source to /Users/yatchunglaw/VSCodeProjects/amy-lab3/target/scala-3.0.2/classes ...
[success] Total time: 3 s, completed 2021年10月26日 下午3:34:02
```

The JDK I'm using for my system and `sbt` is OpenJDK 17 from Zulu (apple silicon version)

``` txt
openjdk 17.0.1 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)
```  

**Search terms**

**Comment by ckipp01** [comment]
Hey @Meowcolm024, just checking back in here, with the newest Metals are you still having an issue with this?

**Comment by Meowcolm024** [comment]
> Hey @Meowcolm024, just checking back in here, with the newest Metals are you still having an issue with this?

I think there're no problems now :P

**Comment by ckipp01** [comment]
> I think there're no problems now :P

Ok great, if this springs up again, please don't hesitate commenting back.
