### ISSUE TITLE
Code with no empty safety was used.

### ISSUE THREAD

**Issue by tribbloid** [scalameta/metals#3235]
**Describe the bug**

The following stacktrace was displayed at some point:

2021.10.27 16:21:37 ERROR java.lang.UnsupportedOperationException: empty.max
	at scala.collection.TraversableOnce.max(TraversableOnce.scala:275)
	at scala.collection.TraversableOnce.max$(TraversableOnce.scala:273)
	at scala.collection.AbstractTraversable.max(Traversable.scala:108)
	at sbt.internal.server.BuildServerProtocol$.$anonfun$globalSettings$49(BuildServerProtocol.scala:191)
	at sbt.internal.server.BuildServerProtocol$.$anonfun$globalSettings$49$adapted(BuildServerProtocol.scala:190)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.ru

if the code is in good quality, it should avoid using Seq.max

**To Reproduce**

I can't remember, this is a code quality problem, even if it doesn't cause a bug it should be fixed

**Installation:**

- Operating system: Pop! OS 20.04
- Editor: Visual Studio Code
- Metals version: v0.10.8

**Additional context**

N/A

**Search terms**

Code quality

**Comment by ckipp01** [comment]
Since there hasn't been any response to this I'll go ahead and close.
