### ISSUE TITLE
[Worksheet] Issues with using coursier

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#3333]
**To Reproduce**

Create worksheet in Metals repo at `metals/src/main/scala/scala/meta/internal/metals/`t with the following code:
```scala
import scala.meta.internal.metals.Embedded

val result = Embedded.downloadMdoc("2.13.5", "2.13")
```

Notice the error from mdoc:
```
java.lang.NoClassDefFoundError: scalapb/GeneratedEnum
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:574)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at scala.meta.internal.metals.Embedded$.downloadDependency(Embedded.scala:239)
	at scala.meta.internal.metals.Embedded$.downloadMdoc(Embedded.scala:275)
	at repl.MdocSession$App.<init>(test.worksheet.sc:11)
	at repl.MdocSession$.app(test.worksheet.sc:3)
Caused by: java.lang.ClassNotFoundException: scalapb.GeneratedEnum
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 15 more
```

**Installation:**

- Metals version: v0.10.9

**Comment by tgodzik** [comment]
That looks like an issue with scalapb versions :thinking:

**Comment by tgodzik** [comment]
Looks to be working now
