### ISSUE TITLE
Unable to "Step In" to a Java Source

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3358]
**Describe the bug**

When trying to "Step In" to a java source while debugging an exception is throw, which then floats up to the UI causing nothing to work.

**To Reproduce**

The piece of code I'm using for this is:

```scala
package example

object Main extends App {

  val x = 3

  val y = x * 3

  println(s"Your total for y is $y") <-- set a breakpoint on this line

}
```

1. Have a minimal Main like shown above
2. Set a breakpoint on the line that contains the `println`
3. Trigger a debug and when it stops at that point, try to step in
4. Depending on your client see some sort of error in your UI, but also in the logs

```
2021.12.12 16:55:22 INFO  Starting debug proxy for [example.Main]
2021.12.12 16:55:28 ERROR Could not resolve jar:file:///Users/ckipp/.sdkman/candidates/java/current/lib/src.zip!/java.base/java/lang/ClassLoader.java
java.nio.file.FileSystemNotFoundException
        at jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
        at jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
        at java.nio.file.Path.of(Path.java:208)
        at java.nio.file.Paths.get(Paths.java:97)
        at scala.meta.internal.metals.debug.SourcePathAdapter.toMetalsPath(SourcePathAdapter.scala:46)
        at scala.meta.internal.metals.debug.MetalsDebugAdapter2x.adaptStackFrameSource(MetalsDebugAdapter.scala:103)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$4(DebugProxy.scala:175)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$4$adapted(DebugProxy.scala:172)
        at scala.Option.foreach(Option.scala:407)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$3(DebugProxy.scala:172)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$3$adapted(DebugProxy.scala:171)
        at scala.Option.foreach(Option.scala:407)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$2(DebugProxy.scala:171)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$2$adapted(DebugProxy.scala:170)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$1(DebugProxy.scala:170)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$1$adapted(DebugProxy.scala:160)
        at scala.meta.internal.metals.debug.ServerAdapter.$anonfun$onReceived$1(ServerAdapter.scala:25)
        at scala.meta.internal.metals.debug.MessageIdAdapter.$anonfun$listen$1(MessageIdAdapter.scala:57)
        at scala.meta.internal.metals.debug.EndpointLogger.$anonfun$listen$1(EndpointLogger.scala:35)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at scala.meta.internal.metals.debug.SocketEndpoint.listen(SocketEndpoint.scala:26)
        at scala.meta.internal.metals.debug.EndpointLogger.listen(EndpointLogger.scala:33)
        at scala.meta.internal.metals.debug.MessageIdAdapter.listen(MessageIdAdapter.scala:47)
        at scala.meta.internal.metals.debug.ServerAdapter.onReceived(ServerAdapter.scala:18)
        at scala.meta.internal.metals.debug.DebugProxy.$anonfun$listenToServer$1(DebugProxy.scala:67)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**

I'd expect this to work and be able to step into the Java source. If I'm not mistaken this worked in the past.

**Installation:**

- Operating system: macOS
- Editor: `nvim-metals`
- Metals version: `0.10.9+138-baa10cc4-SNAPSHOT`

**Additional context**

```
❯ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
```

**Comment by ckipp01** [comment]
After a bit more debugging, this seems to work when I switch to jdk 8, but breaks when using 11.

**Comment by tgodzik** [comment]
I will close it for now and reopen if it is still a problem.

**Comment by ckipp01** [comment]
Hey, sorry totally missed the mention. Just double checked and it looks like I no longer have the issue. So either something was funky with my system before or some update fixed it. 🎉

**Comment by tgodzik** [comment]
Awesome! Thanks for confirming!
