### ISSUE TITLE
Metals fails to index not existing file

### ISSUE THREAD

**Issue by WojciechMazur** [scalameta/metals#3387]
**Describe the bug**

Inside Scala Native project there is a project `sandbox` with a single file `Test.scala`. For some reason, when Metals tries to index it its name is resolved with the name `.scala` instead of `Test.scala`, which leads to failure.

**To Reproduce**

1. Clone [Scala Native repository](https://github.com/scala-native/scala-native) at revision `e93c62603bddd1c8b99ea54a2ddd510b88e7251f` (current HEAD at the time of creating this issue)
2. Import build and observe the logs

**Expected behavior**

There should be no exception in the logs

**Stacktrace**

```
2021.12.20 12:46:21 ERROR .../scala-native/sandbox/src/main/scala/.scala
java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.file.Files.read(Files.java:3105)
	at java.nio.file.Files.readAllBytes(Files.java:3158)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.CommonMtagsEnrichments$XtensionAbsolutePath.toInput(CommonMtagsEnrichments.scala:448)
	at scala.meta.internal.metals.MetalsLanguageServer.indexSourceFile(MetalsLanguageServer.scala:2237)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexWorkspaceSources$4(MetalsLanguageServer.scala:2189)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexWorkspaceSources$4$adapted(MetalsLanguageServer.scala:2183)
	at geny.Generator.$anonfun$foreach$1(Generator.scala:50)
	at geny.Generator$Filtered.$anonfun$generate$3(Generator.scala:276)
	at geny.Generator$Mapped.$anonfun$generate$4(Generator.scala:283)
	at geny.Generator$SelfClosing.generate(Generator.scala:229)
	at geny.Generator$Mapped.generate(Generator.scala:283)
	at geny.Generator$Filtered.generate(Generator.scala:276)
	at geny.Generator.foreach(Generator.scala:49)
	at geny.Generator.foreach$(Generator.scala:49)
	at geny.Generator$Filtered.foreach(Generator.scala:274)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexWorkspaceSources$2(MetalsLanguageServer.scala:2183)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexWorkspaceSources$2$adapted(MetalsLanguageServer.scala:2182)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.meta.internal.metals.MetalsLanguageServer.indexWorkspaceSources(MetalsLanguageServer.scala:2182)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexWorkspace$9(MetalsLanguageServer.scala:2381)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.indexWorkspace(MetalsLanguageServer.scala:2381)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$profiledIndexWorkspace$2(MetalsLanguageServer.scala:2280)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$profiledIndexWorkspace$1(MetalsLanguageServer.scala:2280)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.9

**Comment by tgodzik** [comment]
Thanks for reporting! We are most likely treating any file that ends with `.scala` as a Scala file. We should also check if it's a file.

**Comment by kpodsiad** [comment]
> Thanks for reporting! We are most likely treating any file that ends with `.scala` as a Scala file. We should also check if it's a file.

What's more disturbing is fact that `scala-native/sandbox/src/main/scala/Test.scala` is somehow transformed into `scala-native/sandbox/src/main/scala/.scala`. Adding a check if the path is a file won't solve the root cause of this issue. I'll try to add more logging in that area and maybe we'll discover what's going on.

**Comment by kpodsiad** [comment]
@WojciechMazur Does the problem still exist? I wasn't able to reproduce described behavior using Metals 0.11.1. In case it'll return we can always reopen this issue.

**Comment by WojciechMazur** [comment]
With the last release, this problem seems to no longer exist. Thanks!
