### ISSUE TITLE
Metals Bloop Install failed

### ISSUE THREAD

**Issue by liubenyuan** [scalameta/metals#3403]
**Describe the bug**

Install metals vscode on windows 11, scala-2.13.7 and 
```bash
VSCODE:
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

scala --version
Scala code runner version 2.13.7 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.
```

The error log is:
```bash
Java home: C:\Program Files\Java\jdk-11.0.12
Metals version: 0.10.9
2021.12.25 15:16:21 INFO  logging to file D:\scala\SpinalTemplateMill\.metals\metals.log
2021.12.25 15:16:21 INFO  Started: Metals version 0.10.9 in workspace 'D:\scala\SpinalTemplateMill' for client Visual Studio Code 1.63.2.
2021.12.25 15:16:22 INFO  time: initialize in 1.2s
Initializing Scala Debugger
2021.12.25 15:16:22 INFO  Flyway Community Edition 8.0.2 by Redgate
2021.12.25 15:16:22 INFO  Database: jdbc:h2:file:D:\scala\SpinalTemplateMill\.metals\metals (H2 1.4)
2021.12.25 15:16:22 INFO  Successfully validated 3 migrations (execution time 00:00.020s)
2021.12.25 15:16:22 INFO  Creating Schema History table "PUBLIC"."flyway_schema_history" ...
2021.12.25 15:16:22 INFO  Current version of schema "PUBLIC": << Empty Schema >>
2021.12.25 15:16:22 INFO  Migrating schema "PUBLIC" to version "1 - Create tables"
2021.12.25 15:16:22 INFO  Migrating schema "PUBLIC" to version "2 - Server discovery"
2021.12.25 15:16:22 INFO  Migrating schema "PUBLIC" to version "3 - Jar symbols"
2021.12.25 15:16:22 INFO  Successfully applied 3 migrations to schema "PUBLIC", now at version v3 (execution time 00:00.076s)
2021.12.25 15:16:22 WARN  Build server is not auto-connectable.
2021.12.25 15:16:25 INFO  running 'C:\Users\postgres\AppData\Local\Temp\metals949132616411734593\millw.bat --mill-version 0.9.11 -i --predef C:\Users\postgres\AppData\Local\Temp\metals949132616411734593\predef.sc mill.contrib.Bloop/install'
2021.12.25 15:16:26 INFO  Compiling C:\Users\postgres\AppData\Local\Temp\metals949132616411734593\predef.sc
2021.12.25 15:16:26 INFO  java.lang.IllegalArgumentException: 'other' has different root
2021.12.25 15:16:26 INFO    sun.nio.fs.WindowsPath.relativize(WindowsPath.java:404)
2021.12.25 15:16:26 INFO    sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
2021.12.25 15:16:26 INFO    os.Path.relativeTo(Path.scala:457)
2021.12.25 15:16:26 INFO    mill.main.MainRunner$CustomCodeWrapper$.apply(MainRunner.scala:182)
2021.12.25 15:16:26 INFO    ammonite.compiler.iface.CodeWrapper.wrapCode(CodeWrapper.scala:31)
2021.12.25 15:16:26 INFO    ammonite.compiler.DefaultPreprocessor.$anonfun$transform$2(DefaultPreprocessor.scala:44)
2021.12.25 15:16:26 INFO    ammonite.util.Res$Success.map(Res.scala:67)
2021.12.25 15:16:26 INFO    ammonite.compiler.DefaultPreprocessor.transform(DefaultPreprocessor.scala:40)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:535)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:585)
2021.12.25 15:16:26 INFO    ammonite.util.Res$Success.flatMap(Res.scala:62)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:582)
2021.12.25 15:16:26 INFO    ammonite.util.Res$Success.flatMap(Res.scala:62)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:579)
2021.12.25 15:16:26 INFO    scala.Option.getOrElse(Option.scala:201)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.loop$1(Interpreter.scala:579)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:617)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:412)
2021.12.25 15:16:26 INFO    ammonite.util.Catching.flatMap(Res.scala:115)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:403)
2021.12.25 15:16:26 INFO    ammonite.util.Res$Success.flatMap(Res.scala:62)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.processModule(Interpreter.scala:393)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.$anonfun$initializePredef$3(Interpreter.scala:146)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.$anonfun$initializePredef$3$adapted(Interpreter.scala:146)
2021.12.25 15:16:26 INFO    ammonite.interp.PredefInitialization$.$anonfun$apply$2(PredefInitialization.scala:79)
2021.12.25 15:16:26 INFO    ammonite.util.Res$.$anonfun$fold$1(Res.scala:32)
2021.12.25 15:16:26 INFO    scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
2021.12.25 15:16:26 INFO    scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
2021.12.25 15:16:26 INFO    scala.collection.immutable.List.foldLeft(List.scala:79)
2021.12.25 15:16:26 INFO    ammonite.util.Res$.fold(Res.scala:30)
2021.12.25 15:16:26 INFO    ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:67)
2021.12.25 15:16:26 INFO    ammonite.interp.Interpreter.initializePredef(Interpreter.scala:148)
2021.12.25 15:16:26 INFO    ammonite.Main.$anonfun$instantiateInterpreter$1(Main.scala:198)
2021.12.25 15:16:26 INFO    scala.util.Either$RightProjection.flatMap(Either.scala:757)
2021.12.25 15:16:26 INFO    ammonite.Main.instantiateInterpreter(Main.scala:155)
2021.12.25 15:16:26 INFO    mill.main.MainRunner.$anonfun$runScript$2(MainRunner.scala:112)
2021.12.25 15:16:26 INFO    mill.main.RunScript$.runScript(RunScript.scala:46)
2021.12.25 15:16:26 INFO    mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:119)
2021.12.25 15:16:26 INFO    mill.main.MainRunner.watchLoop2(MainRunner.scala:68)
2021.12.25 15:16:26 INFO    mill.main.MainRunner.runScript(MainRunner.scala:94)
2021.12.25 15:16:26 INFO    mill.MillMain$.main0(MillMain.scala:322)
2021.12.25 15:16:26 INFO    mill.MillMain$.main(MillMain.scala:109)
2021.12.25 15:16:26 INFO    mill.MillMain.main(MillMain.scala)
2021.12.25 15:16:27 INFO  time: ran 'mill bloopInstall' in 1.75s
2021.12.25 15:16:27 ERROR Mill command failed: C:\Users\postgres\AppData\Local\Temp\metals949132616411734593\millw.bat --mill-version 0.9.11 -i --predef C:\Users\postgres\AppData\Local\Temp\metals949132616411734593\predef.sc mill.contrib.Bloop/install
```

The build.sc is 
```scala
// build.sc
import mill._, scalalib._, publish._

trait CommonSpinalModule extends ScalaModule {
  def scalaVersion = "2.13.7"
  def spinalVersion = "1.6.1"

  def scalacOptions = Seq("-unchecked", "-deprecation", "-feature")

  def ivyDeps = Agg(
    ivy"com.github.spinalhdl::spinalhdl-core:$spinalVersion",
    ivy"com.github.spinalhdl::spinalhdl-lib:$spinalVersion",
  )
  def scalacPluginIvyDeps = Agg(ivy"com.github.spinalhdl::spinalhdl-idsl-plugin:$spinalVersion")
}

object simple extends CommonSpinalModule with PublishModule {
  def mainClass = Some("mylib.MyTopLevelSim")
  def publishVersion = "0.0.1-SNAPSHOT"

  def pomSettings = PomSettings(
    description = "Simple SpinalHDL Module",
    organization = "com.github.typingArtist",
    url = "https://github.com/typingArtist/SpinalTemplateMill",
    licenses = Seq(License.`LGPL-3.0-or-later`),
    versionControl = VersionControl.github("typingArtist", "SpinalTemplateMill"),
    developers = Seq(
      Developer("typingArtist", "Matthias Wächter", "https://github.com/typingArtist"),
      Developer("Dolu1990", "Dolu1990", "none")
    )
  )
}

**Comment by ckipp01** [comment]
Thanks for reporting @liubenyuan 

> 2021.12.25 15:16:25 INFO  running 'C:\Users\postgres\AppData\Local\Temp\metals949132616411734593\millw.bat --mill-version 0.9.11 -i --predef C:\Users\postgres\AppData\Local\Temp\metals949132616411734593\predef.sc mill.contrib.Bloop/install'
> 2021.12.25 15:16:26 INFO  Compiling C:\Users\postgres\AppData\Local\Temp\metals949132616411734593\predef.sc
> 2021.12.25 15:16:26 INFO  java.lang.IllegalArgumentException: 'other' has different root

I've hit on this issue in other projects before when dealing with temp paths on windows. Since at times when you create a temp path it will be on a different drive than your actual cwd. Then when you call `relativize` it blows up since it tries to compute it given two paths on two different drives. In theory I guess this could happen here since we do create these files in a temp dir, but I'm unsure why we wouldn't have hit on this in the past then. I'll try to look a bit more into what's going on here, but it'll be hard to not be able to reproduce as I don't have a windows machine.

**Comment by liubenyuan** [comment]
Yes, I do have a arch linux machine and metals on vscode works fine. I do have success run Metals on vscode on this windows 11 box, but I uninstalled sbt, scala, tried scoop and reinstall scala, sbt, mill, and it all messed up. I will try if it is reproducible on my another windows box.

**Comment by tgodzik** [comment]
Actually this will no longer be a problem with newer versions of Mill and Metals thanks to https://github.com/scalameta/metals/pull/3356

This should work with new Metals version (probably 0.11.0) and Mill >= 0.9.10

**Comment by liubenyuan** [comment]
Though, I can run these command under windows terminal successfully.
```
PS C:\Temp\metals7969330910592684373> .\millw.bat --mill-version 0.9.11 -i --predef .\predef.sc mill.contrib.Bloop/install
Compiling C:\Temp\metals7969330910592684373\predef.sc
No build file found, you should create build.sc to do something useful
Compiling C:\Temp\metals7969330910592684373\build.sc
[1/1] mill.contrib.bloop.BloopImpl.install
PS C:\Temp\metals7969330910592684373> C:\Temp\metals6879232035003927587\millw.bat --mill-version 0.9.11 -i --predef C:\Temp\metals6879232035003927587\predef.sc mill.contrib.Bloop/install
Compiling C:\Temp\metals6879232035003927587\predef.sc
No build file found, you should create build.sc to do something useful
Compiling C:\Temp\metals7969330910592684373\build.sc
[1/1] mill.contrib.bloop.BloopImpl.install
PS C:\Temp\metals7969330910592684373>
```

**Comment by liubenyuan** [comment]
> Actually this will no longer be a problem with newer versions of Mill and Metals thanks to #3356
> 
> This should work with new Metals version (probably 0.11.0) and Mill >= 0.9.10

Hi, I tried the latest snapshot version `0.10.9+271-a8bb69f6-SNAPSHOT`
It reports `Cannot resolve --mill-version. Try `mill resolve _` to see what's available.`, so, does it mean that we do not need to provide mill version to millw.bat?

```bash
Java home: C:\Program Files\Java\jre1.8.0_202
Metals version: 0.10.9+271-a8bb69f6-SNAPSHOT
2022.01.03 11:59:21 INFO  logging to file D:\scala\SpinalTemplateMill\.metals\metals.log
2022.01.03 11:59:21 INFO  Started: Metals version 0.10.9+271-a8bb69f6-SNAPSHOT in workspace 'D:\scala\SpinalTemplateMill' for client Visual Studio Code 1.63.2.
2022.01.03 11:59:22 INFO  time: initialize in 0.34s
Initializing Scala Debugger
2022.01.03 11:59:22 INFO  Flyway Community Edition 8.2.3 by Redgate
2022.01.03 11:59:22 INFO  Database: jdbc:h2:file:D:\scala\SpinalTemplateMill\.metals\metals (H2 1.4)
2022.01.03 11:59:22 INFO  Successfully validated 3 migrations (execution time 00:00.022s)
2022.01.03 11:59:22 INFO  Current version of schema "PUBLIC": 3
2022.01.03 11:59:22 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2022.01.03 11:59:22 WARN  Build server is not auto-connectable.
2022.01.03 11:59:22 INFO  skipping build import with status 'Failed'
2022.01.03 11:59:36 INFO  running 'C:\Temp\metals8966300519384294782\millw.bat --mill-version 0.9.11 -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install'
2022.01.03 11:59:37 INFO  Mill version changed (0.9.10 -> 0.9.11), re-starting server
2022.01.03 11:59:37 INFO  java.io.IOException: ReadFile() failed: 109
2022.01.03 11:59:37 INFO  	at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketInputStream.read(Win32NamedPipeSocket.java:154)
2022.01.03 11:59:37 INFO  	at java.io.InputStream.read(Unknown Source)
2022.01.03 11:59:37 INFO  	at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketInputStream.read(Win32NamedPipeSocket.java:134)
2022.01.03 11:59:37 INFO  	at mill.main.client.ProxyStreamPumper.run(ProxyStreamPumper.java:23)
2022.01.03 11:59:37 INFO  	at java.lang.Thread.run(Unknown Source)
2022.01.03 11:59:36 INFO  time: ran 'mill bloopInstall' in 0.59s
2022.01.03 11:59:37 ERROR Mill command failed: C:\Temp\metals8966300519384294782\millw.bat --mill-version 0.9.11 -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install
2022.01.03 12:00:01 INFO  running 'C:\Temp\metals2544476370202408708\millw.bat --mill-version 0.9.11 -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install'
2022.01.03 12:00:03 INFO  Compiling D:\scala\SpinalTemplateMill\build.sc
2022.01.03 12:00:07 INFO  Cannot resolve --mill-version. Try `mill resolve _` to see what's available.
2022.01.03 12:00:07 INFO  time: ran 'mill bloopInstall' in 6.41s
2022.01.03 12:00:07 ERROR Mill command failed: C:\Temp\metals2544476370202408708\millw.bat --mill-version 0.9.11 -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install
```
