### ISSUE TITLE
Ammonite >= 2.5.0 not supported

### ISSUE THREAD

**Issue by LoranceChen** [scalameta/metals#3455]
**Describe the bug**
- summary: occurred a error in Metals Ouput window when open a sc file( ammonite scala script) in vscode.
- affect: Can not start Metals server for amm scala script.
- env:
  - Metals version: 0.10.9
  - vscode: 1.63.2 
  - macOS: 11.3.1
  - amm: 2.5.0
- Metals output:
```
Java home: /Users/lorance/soft/tjdk-11.0.12.jdk/Contents/Home
Metals version: 0.10.9
2022.01.02 19:17:41 INFO  logging to file /Users/lorance/project/test/metalstest/.metals/metals.log
2022.01.02 19:17:41 INFO  Started: Metals version 0.10.9 in workspace '/Users/lorance/project/test/metalstest' for client Visual Studio Code 1.63.2.
2022.01.02 19:17:42 INFO  time: initialize in 1.21s
Initializing Scala Debugger
2022.01.02 19:17:43 INFO  Flyway Community Edition 8.0.2 by Redgate
2022.01.02 19:17:43 INFO  Database: jdbc:h2:file:/Users/lorance/project/test/metalstest/.metals/metals (H2 1.4)
2022.01.02 19:17:43 INFO  Successfully validated 3 migrations (execution time 00:00.020s)
2022.01.02 19:17:43 INFO  Creating Schema History table "PUBLIC"."flyway_schema_history" ...
2022.01.02 19:17:43 INFO  Current version of schema "PUBLIC": << Empty Schema >>
2022.01.02 19:17:43 INFO  Migrating schema "PUBLIC" to version "1 - Create tables"
2022.01.02 19:17:43 INFO  Migrating schema "PUBLIC" to version "2 - Server discovery"
2022.01.02 19:17:43 INFO  Migrating schema "PUBLIC" to version "3 - Jar symbols"
2022.01.02 19:17:43 INFO  Successfully applied 3 migrations to schema "PUBLIC", now at version v3 (execution time 00:00.061s)
2022.01.02 19:17:43 WARN  Build server is not auto-connectable.
2022.01.02 19:17:43 WARN  no build tool detected in workspace '/Users/lorance/project/test/metalstest'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 
2022.01.02 19:17:43 WARN  no build target for: /Users/lorance/project/test/metalstest/test.sc
2022.01.02 19:17:46 INFO  no build target: using presentation compiler with only scala-library: 3.1.0
2022.01.02 19:17:46 INFO  tracing is enabled: /Users/lorance/Library/Caches/org.scalameta.metals/bsp.trace.json
2022.01.02 19:17:47 INFO  Ammonite: Error: main method not found in class ammonite.Main

2022.01.02 19:17:47 INFO  time: code lens generation in 3.96s
2022.01.02 19:18:07 ERROR Timeout waiting for 'build/initialize' response
2022.01.02 19:18:07 WARN  Retrying connection to the build server Ammonite
2022.01.02 19:18:07 INFO  tracing is enabled: /Users/lorance/Library/Caches/org.scalameta.metals/bsp.trace.json
2022.01.02 19:18:07 INFO  Ammonite: Error: main method not found in class ammonite.Main

2022.01.02 19:18:27 ERROR Timeout waiting for 'build/initialize' response
2022.01.02 19:18:27 WARN  Retrying connection to the build server Ammonite
2022.01.02 19:18:27 INFO  tracing is enabled: /Users/lorance/Library/Caches/org.scalameta.metals/bsp.trace.json
2022.01.02 19:18:27 INFO  Ammonite: Error: main method not found in class ammonite.Main

2022.01.02 19:18:47 ERROR Timeout waiting for 'build/initialize' response
2022.01.02 19:18:47 WARN  Retrying connection to the build server Ammonite
2022.01.02 19:18:47 INFO  tracing is enabled: /Users/lorance/Library/Caches/org.scalameta.metals/bsp.trace.json
2022.01.02 19:18:47 INFO  Ammonite: Error: main method not found in class ammonite.Main

2022.01.02 19:19:07 ERROR Timeout waiting for 'build/initialize' response
2022.01.02 19:19:07 WARN  Retrying connection to the build server Ammonite
2022.01.02 19:19:07 INFO  tracing is enabled: /Users/lorance/Library/Caches/org.scalameta.metals/bsp.trace.json
2022.01.02 19:19:07 INFO  Ammonite: Error: main method not found in class ammonite.Main

2022.01.02 19:19:27 ERROR Timeout waiting for 'build/initialize' response
2022.01.02 19:19:27 WARN  Retrying connection to the build server Ammonite
2022.01.02 19:19:27 INFO  tracing is enabled: /Users/lorance/Library/Caches/org.scalameta.metals/bsp.trace.json
2022.01.02 19:19:27 INFO  Ammonite: Error: main method not found in class ammonite.Main

2022.01.02 19:19:47 ERROR Timeout waiting for 'build/initialize' response
2022.01.02 19:19:47 WARN  Error importing Ammonite script /Users/lorance/project/test/metalstest/test.sc
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:386)
	at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:298)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

- reproduce:
1. create a file `test.sc` with content:
```
// Ammonite 2.5.0

val test = "TEST"
```
2. open with vscode
3. see error in Metals output

- attempted:
1. add mirror.properties in `~/Library/Preferences/Coursier/mirror.properties`
```
jcenter.from=https://repo1.maven.org/maven2
jcenter.to=https://jcenter.bintray.com
```
2. create a empty file in `/Users/lorance/Library/Caches/org.scalameta.metals/bsp.trace.json`
3. create a empty file in `~/.bloop/.jvmopts`

- besides, Metals wrok fine in windows.

Thanks

**Comment by ckipp01** [comment]
Hey @LoranceChen thanks for the report. Amm 2.5.0 isn't yet supported by Metals as it needs some changes in the [library](https://github.com/alexarchambault/ammonite-runner/pull/127) we use for Ammonite support. Are you able to try with 2.4.0 instead?

**Comment by LoranceChen** [comment]
@ckipp01 Thanks for you quick response! 
with test.sc:
```
// Ammonite 2.4.0

val test = "TEST"
```

another error occurred:
```
2022.01.02 19:31:46 ERROR Error getting Ammonite 2.4.0 (scala 2.13.7)
ammrunner.CoursierError: Error fetching Ammonite 2.4.0 for scala 2.13.7
	at ammrunner.AmmoniteFetcher.maybeResult$1(AmmoniteFetcher.scala:90)
	at ammrunner.AmmoniteFetcher.command(AmmoniteFetcher.scala:108)
	at scala.meta.internal.metals.ammonite.Ammonite.command(Ammonite.scala:161)
	at scala.meta.internal.metals.ammonite.Ammonite.$anonfun$start$4(Ammonite.scala:239)
	at scala.Option.map(Option.scala:230)
	at scala.meta.internal.metals.ammonite.Ammonite.start(Ammonite.scala:239)
	at scala.meta.internal.metals.ammonite.Ammonite.doImport$1(Ammonite.scala:190)
	at scala.meta.internal.metals.ammonite.Ammonite.$anonfun$maybeImport$3(Ammonite.scala:215)
	at scala.meta.internal.metals.ammonite.Ammonite.$anonfun$maybeImport$3$adapted(Ammonite.scala:208)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
Caused by: coursierapi.error.MultipleResolutionError: Error downloading com.lihaoyi:ammonite-compiler_2.13.7:2.4.0
  not found: /Users/lorance/.ivy2/local/com.lihaoyi/ammonite-compiler_2.13.7/2.4.0/ivys/ivy.xml
  not found: https://jcenter.bintray.com/com/lihaoyi/ammonite-compiler_2.13.7/2.4.0/ammonite-compiler_2.13.7-2.4.0.pom
Error downloading com.lihaoyi:ammonite-repl-api_2.13.7:2.4.0
  not found: /Users/lorance/.ivy2/local/com.lihaoyi/ammonite-repl-api_2.13.7/2.4.0/ivys/ivy.xml
  not found: https://jcenter.bintray.com/com/lihaoyi/ammonite-repl-api_2.13.7/2.4.0/ammonite-repl-api_2.13.7-2.4.0.pom

	at coursierapi.error.MultipleResolutionError.of(MultipleResolutionError.java:28)
	at coursierapi.shaded.coursier.internal.api.ApiHelper$.doFetch(ApiHelper.scala:356)
	at coursierapi.shaded.coursier.internal.api.ApiHelper.doFetch(ApiHelper.scala)
	at coursierapi.Fetch.fetchResult(Fetch.java:244)
	at ammrunner.AmmoniteFetcher.maybeResult$1(AmmoniteFetcher.scala:87)
	at ammrunner.AmmoniteFetcher.command(AmmoniteFetcher.scala:108)
	at scala.meta.internal.metals.ammonite.Ammonite.command(Ammonite.scala:161)
	at scala.meta.internal.metals.ammonite.Ammonite.$anonfun$start$4(Ammonite.scala:239)
	at scala.Option.map(Option.scala:230)
	at scala.meta.internal.metals.ammonite.Ammonite.start(Ammonite.scala:239)
	at scala.meta.internal.metals.ammonite.Ammonite.doImport$1(Ammonite.scala:190)
	at scala.meta.internal.metals.ammonite.Ammonite.$anonfun$maybeImport$3(Ammonite.scala:215)
	at scala.meta.internal.metals.ammonite.Ammonite.$anonfun$maybeImport$3$adapted(Ammonite.scala:208)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

It seems amm not match some scala version.

**Comment by LoranceChen** [comment]
try fixing scala version, seems works!
// Ammonite 2.4.0, scala 2.12.11

![image](https://user-images.githubusercontent.com/8775828/147874522-f62731b1-6ce7-4747-964f-1e374f61cc1a.png)

**Comment by ckipp01** [comment]
Huh, looks like you're right with the version. From looking at 
```
❯ cs complete-dep com.lihaoyi:ammonite-repl-api_2.13.7:
https://repo1.maven.org/maven2/com/lihaoyi/ammonite-repl-api_2.13.7/maven-metadata.xml
  100.0% [##########] 967B (4.7 KiB / s)
2.4.0-24-b4a313e0
2.4.0-27-65476446
2.4.0-28-60dca3cf
2.4.0-29-d9c16e33
2.4.0-30-5fe6da56
2.4.0-31-ba6214b1
2.4.1
2.4.1-1-230b38e9
2.4.1-2-63e98591
2.4.1-3-7aaa308b
2.4.1-4-6f18e134
2.4.1-5-3e8a87a4
2.4.1-6-5f9cddf3
2.4.1-8-a6696a8f
2.4.1-9-0c71fcca
2.5.0
```
You should also be able to use 2.4.1 with 2.13.7

**Comment by LoranceChen** [comment]
ammonite 2.4.1 works fine with 2.13.7
![image](https://user-images.githubusercontent.com/8775828/147874627-2f8c273b-6589-462a-adab-84f8b69ff0eb.png)

thanks.

**Comment by ckipp01** [comment]
Glad it works! I went ahead and changed the title to reflect the original issue and I'll leave this open to track progress on that.

**Comment by tgodzik** [comment]
Newest Ammonite is now supported.
