### ISSUE TITLE
Running latest snapshop, Cannot resolve --mill-version. Try `mill resolve _` to see what's available.

### ISSUE THREAD

**Issue by liubenyuan** [scalameta/metals#3456]
**Describe the bug**

The project settings are the same as #3403 , I use the latest snapshot, `0.10.9+271-a8bb69f6-SNAPSHOT`

It reports the following error:
```bash
Java home: C:\Program Files\Java\jre1.8.0_202
Metals version: 0.10.9+271-a8bb69f6-SNAPSHOT
2022.01.03 11:59:21 INFO  logging to file D:\scala\SpinalTemplateMill\.metals\metals.log
2022.01.03 11:59:21 INFO  Started: Metals version 0.10.9+271-a8bb69f6-SNAPSHOT in workspace 'D:\scala\SpinalTemplateMill' for client Visual Studio Code 1.63.2.
2022.01.03 11:59:22 INFO  time: initialize in 0.34s
Initializing Scala Debugger
2022.01.03 11:59:22 INFO  Flyway Community Edition 8.2.3 by Redgate
2022.01.03 11:59:22 INFO  Database: jdbc:h2:file:D:\scala\SpinalTemplateMill\.metals\metals (H2 1.4)
2022.01.03 11:59:22 INFO  Successfully validated 3 migrations (execution time 00:00.022s)
2022.01.03 11:59:22 INFO  Current version of schema "PUBLIC": 3
2022.01.03 11:59:22 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2022.01.03 11:59:22 WARN  Build server is not auto-connectable.
2022.01.03 11:59:22 INFO  skipping build import with status 'Failed'
2022.01.03 11:59:36 INFO  running 'C:\Temp\metals8966300519384294782\millw.bat --mill-version 0.9.11 -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install'
2022.01.03 11:59:37 INFO  Mill version changed (0.9.10 -> 0.9.11), re-starting server
2022.01.03 11:59:37 INFO  java.io.IOException: ReadFile() failed: 109
2022.01.03 11:59:37 INFO  	at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketInputStream.read(Win32NamedPipeSocket.java:154)
2022.01.03 11:59:37 INFO  	at java.io.InputStream.read(Unknown Source)
2022.01.03 11:59:37 INFO  	at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketInputStream.read(Win32NamedPipeSocket.java:134)
2022.01.03 11:59:37 INFO  	at mill.main.client.ProxyStreamPumper.run(ProxyStreamPumper.java:23)
2022.01.03 11:59:37 INFO  	at java.lang.Thread.run(Unknown Source)
2022.01.03 11:59:36 INFO  time: ran 'mill bloopInstall' in 0.59s
2022.01.03 11:59:37 ERROR Mill command failed: C:\Temp\metals8966300519384294782\millw.bat --mill-version 0.9.11 -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install
2022.01.03 12:00:01 INFO  running 'C:\Temp\metals2544476370202408708\millw.bat --mill-version 0.9.11 -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install'
2022.01.03 12:00:03 INFO  Compiling D:\scala\SpinalTemplateMill\build.sc
2022.01.03 12:00:07 INFO  Cannot resolve --mill-version. Try `mill resolve _` to see what's available.
2022.01.03 12:00:07 INFO  time: ran 'mill bloopInstall' in 6.41s
2022.01.03 12:00:07 ERROR Mill command failed: C:\Temp\metals2544476370202408708\millw.bat --mill-version 0.9.11 -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install
```

**Comment by ckipp01** [comment]
Thanks for the report @liubenyuan! Looks like there was actually a bug in the last millw.bat script that we were using. I've opened #3457 to fix this.
