### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by kpodsiad** [scalameta/metals#3526]
### Describe the bug

I noticed that there are no code lenses for test suites in scala-yaml. For example after opening [this test suite](https://github.com/VirtusLab/scala-yaml/blob/7c0f31a69a2e87bd31d9375d127498d9b4fdba5c/core/jvm/src/test/org/virtuslab/yaml/YamlEncoderSuite.scala)
which starts as below, there are multiple errors in `metals.log`
```scala
package org.virtuslab.yaml

import org.virtuslab.yaml.*

class YamlEncoderSuite extends munit.FunSuite:
```

I suspect this is a configuration error since scalameta parser cannot parse `:` or `derives`. 

```shell
YamlEncoderSuite.scala:5: error: ; expected but : found
class YamlEncoderSuite extends munit.FunSuite:
                                             ^
        at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
        at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
        at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
        at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
        at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
        at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
        at scala.meta.internal.parsers.ScalametaParser.syntaxErrorExpected(ScalametaParser.scala:960)
        at scala.meta.internal.parsers.ScalametaParser.accept(ScalametaParser.scala:966)
        at scala.meta.internal.parsers.ScalametaParser.acceptStatSep(ScalametaParser.scala:976)
        at scala.meta.internal.parsers.ScalametaParser.acceptStatSepOpt(ScalametaParser.scala:980)
        at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:5139)
        at scala.meta.internal.parsers.ScalametaParser.topStatSeq(ScalametaParser.scala:5145)
        at scala.meta.internal.parsers.ScalametaParser.bracelessPackageStats$1(ScalametaParser.scala:5377)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$12(ScalametaParser.scala:5383)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:907)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:5383)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:907)
        at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:941)
        at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:5344)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:5327)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:907)
        at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:941)
        at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:5326)
        at scala.meta.internal.parsers.ScalametaParser.entrypointSource(ScalametaParser.scala:5332)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$2(ScalametaParser.scala:143)
        at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:53)
        at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:143)
        at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
        at scala.meta.internal.parsers.ScalametaParser$$anon$264.apply(ScalametaParser.scala:5396)
        at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
        at scala.meta.internal.semanticdb.scalac.ParseOps$XtensionCompilationUnitSource.toSource(ParseOps.scala:17)
        at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:201)
        at scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:51)
```

### Expected behavior

There is no scalameta parser error and file can be parsed successfully.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.0

**Comment by tgodzik** [comment]
Thanks for reporting! I think that the dialect might be wrongly detected for the file. Could you check the doctor?

**Comment by kpodsiad** [comment]
Yes, I checked the doctor. Every target has `Scala 3.1.0` type.
I'll check what's going on at these lines, see what target is passed to the parser.
```shell
at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
at scala.meta.internal.semanticdb.scalac.ParseOps$XtensionCompilationUnitSource.toSource(ParseOps.scala:17)
at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:201)
at scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:51)
```

**Comment by tgodzik** [comment]
The issue seems to not be the parser. I haven't looked before closely enough, but that class is in mtags for Scala 2 and will only be invoked when no target is available.

My guess is that you have a fallback Scala version set to Scala 2 and the file is not being recognised as being part of any target.

**Comment by kpodsiad** [comment]
> My guess is that you have a fallback Scala version set to Scala 2 and the file is not being recognised as being part of any target.

Thanks, that was the case.

 I'll have to investigate why this source file is not being recognized as a part of the scala3 target.

**Comment by tgodzik** [comment]
Let's reopen this in case of a reproduction.
