### ISSUE TITLE
Running tests after failed compilation stops tests working

### ISSUE THREAD

**Issue by Arthurm1** [scalameta/metals#3570]
### Describe the bug

1. Run a test using VSCode's `Run Test` icon in margin. (Successful)
2. Introduce an error into that test source file and save it so it won't compile
3. The `Run Test` icon is still there - so use it to run the test again.  Test will fail to run because the codebase doesn't compile
4. Fix the codebase and save the file
5. Run the test again - test won't run.  VSCode needs a restart to get it to work again.

On step 3 I get...
```
[Error - 3:07:07 PM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.$anonfun$applyOrElse$4(BuildServerConnection.scala:282)
	at scala.Option.getOrElse(Option.scala:189)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:280)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:268)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more
```

I'm on Windows + WSL2 using Metals as the codebase here.

### Expected behavior

Tests are expected to be runnable again once the codebase compiles

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.1

### Extra context or search terms

Test Explorer

**Comment by tgodzik** [comment]
Looks like an issue on the VS Code side, no request is being sent and we are getting:
```
[2022-01-26 17:09:12.848] [exthost] [error] Error: Internal error.
	at handleResponse (/home/tgodzik/.vscode/extensions/scalameta.metals-1.12.5/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
	at processMessageQueue (/home/tgodzik/.vscode/extensions/scalameta.metals-1.12.5/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
	at Immediate.<anonymous> (/home/tgodzik/.vscode/extensions/scalameta.metals-1.12.5/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at processImmediate (internal/timers.js:461:21) debug-adapter-start {"value":"scalameta.metals","_lower":"scalameta.metals"}
```
