### ISSUE TITLE
Cannot index swagger-ui package

### ISSUE THREAD

**Issue by chessman** [scalameta/metals#3594]
### Describe the bug

1. Add `libraryDependencies += "org.webjars" % "swagger-ui" % "4.2.1"`
2. `sbt bloopInstall`

There is a stacktrace in metals.log:

```
2022.02.01 14:18:06 ERROR issues while parsing: /home/ea/.cache/coursier/v1/https/repo1.maven.org/maven2/org/webjars/swagger-ui/4.2.1/swagger-ui-4.2.1-sources.jar
scala.meta.internal.mtags.IndexingExceptions$PathIndexingException: /home/ea/.cache/coursier/v1/https/repo1.maven.org/maven2/org/webjars/swagger-ui/4.2.1/swagger-ui-4.2.1-sources.jar
	at scala.meta.internal.mtags.OnDemandSymbolIndex.tryRun(OnDemandSymbolIndex.scala:126)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.addSourceJar(OnDemandSymbolIndex.scala:80)
	at scala.meta.internal.metals.MetalsLanguageServer.addSourceJarSymbols(MetalsLanguageServer.scala:2568)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$8(MetalsLanguageServer.scala:2527)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$3(MetalsLanguageServer.scala:2515)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$3$adapted(MetalsLanguageServer.scala:2514)
	at scala.Option.foreach(Option.scala:407)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$2(MetalsLanguageServer.scala:2514)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexDependencySources$2$adapted(MetalsLanguageServer.scala:2513)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.MetalsLanguageServer.indexDependencySources(MetalsLanguageServer.scala:2513)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$indexWorkspace$10(MetalsLanguageServer.scala:2455)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.indexWorkspace(MetalsLanguageServer.scala:2455)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$profiledIndexWorkspace$2(MetalsLanguageServer.scala:2347)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$profiledIndexWorkspace$1(MetalsLanguageServer.scala:2347)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The source file doesn't contain any sources actually, only one yaml file. Maybe indexer expects to find something.

### Expected behavior

No stacktrace.

### Operating system

Linux

### Editor/Extension

Emacs (lsp-metals)

### Version of Metals

v0.11.1

**Comment by tgodzik** [comment]
Thanks for reporting! That jar seems to be a bit weird, someone put their home directory path, which I've seen break in a couple places. I am not able to reproduce it however. Does it show more information for you if you use the newest Metals snapshot?

**Comment by tgodzik** [comment]
Actually I managed to reproduce it, no need to report an exception in this case since the jar itself is unreadable.
