### ISSUE TITLE
Missed dependency when running test through VS Code testing API 

### ISSUE THREAD

**Issue by damienzhang** [scalameta/metals#3623]
### Describe the bug

sbt version: 1.6.1
scala version: 2.13.7
vs code version: 1.64

metals build server: sbt

When I run a project that has a transitive dependency on jffi-1.3.1-native, running a test through `sbt test` succeeds, but running the same test through the VS Code testing UI fails. It appears that whatever code determines the classpath is not including this critical JAR: `$HOME/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.3.1/jffi-1.3.1-                                        native.jar`. 

I suspect it has something to do with the dependency having a "native" classifier, but I'm not sure how to debug further.

I have a minimal repo here that reproduces the problem: https://github.com/damienzhang/jffi_metals_bug

Missing the jar leads to the following error when running the test through the UI:
```
  Cause: java.lang.UnsatisfiedLinkError: could not get native definition for type `POINTER`, original error message follows: java.lang.UnsatisfiedLinkError: could not locate stub library in jar file.  Tried [jni/x86_64-Linux/libjffi-1.2.so, /jni/x86_64-Linux/libjffi-1.2.so]
	at com.kenai.jffi.internal.StubLoader.getStubLibraryStream(StubLoader.java:474)
	at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:399)
	at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:300)
	at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:511)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.kenai.jffi.Init.load(Init.java:68)
	at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:50)
	at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:46)
	at com.kenai.jffi.Foreign.getInstance(Foreign.java:104)
	at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
	at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
	at com.kenai.jffi.Type.resolveSize(Type.java:155)
	at com.kenai.jffi.Type.size(Type.java:138)
	at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:182)
	at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:61)
	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:45)
	at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:57)
	at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:53)
	at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
	at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
	at jnr.ffi.LibraryLoader.create(LibraryLoader.java:88)
	at org.lmdbjava.Library.<clinit>(Library.java:125)
	at org.lmdbjava.Env$Builder.open(Env.java:486)
	at org.lmdbjava.Env$Builder.open(Env.java:512)
	at test.scala.BugSpec.$anonfun$new$1(BugSpec.scala:15)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1812)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1810)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1822)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1822)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1804)
	at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1880)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1880)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1879)
	at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1925)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1925)
	at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1923)
	at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
  at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:253)
  at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
  at com.kenai.jffi.Type.resolveSize(Type.java:155)
  at com.kenai.jffi.Type.size(Type.java:138)
  at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:182)
  at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
  at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:61)
  at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:45)
  at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:57)
  at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:53)
  ...
Uncaught exception when running test.scala.BugSpec: java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
```

### Expected behavior

Running the code in https://github.com/damienzhang/jffi_metals_bug through sbt produces the expect result

```
sbt> test
[info] BugSpec:
## some classpaths ##
$HOME/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.3.1/jffi-1.3.1-native.jar
## some other classpaths ##

org.lmdbjava.Env@211b5b19

[info] - should have classpath
[info] Run completed in 2 seconds, 512 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.

```

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.1

**Comment by kpodsiad** [comment]
First of all, thanks for already minimized reproduction @damienzhang! 

I won't be able to check this today, but I'll look at that tomorrow ;)

**Comment by damienzhang** [comment]
Yeah it's quite mysterious. I tried a workaround that also failed, and maybe this one will fail for you too. 

I tried adding the JFFI jars as unmanaged dependencies into `lib/` and then excluded jffi as a dependency in `build.sbt`. Here is the branch for that https://github.com/damienzhang/jffi_metals_bug/tree/unmanaged_dep 

This works fine with `sbt test`, and `display build target info` now shows the jars in the new location:

```
Scala Classpath
    /disks/d4/dev/sdz/src/jffi_metals_bug/target/scala-2.13/test-classes               
    jffi-1.3.1.jar                                                                      $HOME/src/jffi_metals_bug/lib/jffi-1.3.1.jar
    jffi-1.3.1-javadoc.jar                                                    NO SOURCE $HOME/src/jffi_metals_bug/lib/jffi-1.3.1-javadoc.jar
    jffi-1.3.1-sources.jar                                                    NO SOURCE $HOME/src/jffi_metals_bug/lib/jffi-1.3.1-sources.jar
    jffi-1.3.1-native.jar                                                     NO SOURCE $HOME/src/jffi_metals_bug/lib/jffi-1.3.1-native.jar
<snip>
```

But when I press "run" in the testing UI, none of these jars are included in the classpath. This causes a slightly different error, since `jffi-1.3.1.jar` is also not found:

```
test.scala.BugSpec *** ABORTED ***
  java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
  at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:49)
  at jnr.ffi.LibraryLoader.load(LibraryLoader.java:417)
  at jnr.ffi.LibraryLoader.load(LibraryLoader.java:396)
  at org.lmdbjava.Library.<clinit>(Library.java:125)
  at org.lmdbjava.Env$Builder.open(Env.java:486)
  at org.lmdbjava.Env$Builder.open(Env.java:512)
  at test.scala.BugSpec.$anonfun$new$1(BugSpec.scala:15)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  ...
  Cause: java.lang.NoClassDefFoundError: com/kenai/jffi/Type
  at jnr.ffi.provider.jffi.NativeRuntime.jafflType(NativeRuntime.java:197)
  at jnr.ffi.provider.jffi.NativeRuntime.buildTypeMap(NativeRuntime.java:80)
  at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:61)
  at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:45)
  at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:57)
  at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:53)
  at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  ...
  Cause: java.lang.ClassNotFoundException: com.kenai.jffi.Type
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at jnr.ffi.provider.jffi.NativeRuntime.jafflType(NativeRuntime.java:197)
  at jnr.ffi.provider.jffi.NativeRuntime.buildTypeMap(NativeRuntime.java:80)
  at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:61)
  at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:45)
  at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:57)
  at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:53)
  ...
```

**Comment by tgodzik** [comment]
I think I managed to fix the issue in https://github.com/scalacenter/scala-debug-adapter/pull/192 :tada:

**Comment by kpodsiad** [comment]
This should be fixed now with the new version of scala debug adapter
