### ISSUE TITLE
Misplaced type annotation on backticked definitions

### ISSUE THREAD

**Issue by prolativ** [scalameta/metals#3785]
### Describe the bug

Invoking `Insert type annotation` code action on a backticked definition adds the annotation in a wrong position.
For a `def`:
```scala
object Foo {
  def `bar` = 1
}
```
becomes
```scala
object Foo {
  def `ba: Intr` = 1
}
```
in scala 2.13.8 but works correctly in scala 3.1.1

For a `val`:
```scala
object Foo {
  val `bar` = 1
}
```
gives
```scala
object Foo {
  val `ba: Intr` = 1
}
```
in scala 2.13.8 and
```scala
object Foo {
  val `bar: Int` = 1
}
```
in scala 3.1.1

### Expected behavior

```scala
object Foo {
  def `bar`: Int = 1
}
```

```scala
object Foo {
  val `bar`: Int = 1
}
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.2+123-b44dc8c0-SNAPSHOT

**Comment by prolativ** [comment]
Additionally it looks like if the backticked identifier contains a dash, the ascription can be added in a different (although still incorrect) place, e.g
```scala
def `bar-baz` = 1
```
in scala 2.13.8 becomes
```scala
def `bar-baz` = : Int1
```

**Comment by prolativ** [comment]
In scala 2.13.8 in case of a `def` with backquoted name consisting of 3 parts, e.g
```scala
object Foo {
  def `bar-ba-z` = 1
}
```
an exception is thrown
```scala
[Error - 2:30:56 PM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.concurrent.Future$$anon$2: Future.filter predicate is not satisfied
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.concurrent.Future$$anon$2: Future.filter predicate is not satisfied
```
