### ISSUE TITLE
exception logged (after workspace/didChangeConfiguration)

### ISSUE THREAD

**Issue by moberer** [scalameta/metals#3870]
### Describe the bug

When using `metals-emacs` with `lsp-mode`/`lsp-metals` there are repeatedly exceptions logged to the metals.log file.
While the expected features at the client side (jump to definition, jump to reference) still work, it still seems that this is unintendend.

The metals log up until the first occurence of the issue is:
```
2022.04.26 01:40:39 INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/user/projects/p01/src/main/scala/.metals/lsp.trace.json or /home/max/.cache/metals/lsp.trace.json
2022.04.26 01:40:40 INFO  logging to file /home/user/projects/p01/src/main/scala/.metals/metals.log
2022.04.26 01:40:40 INFO  Started: Metals version 0.11.2 in workspace '/home/user/projects/p01/src/main/scala' .
2022.04.26 01:40:40 WARN  Can't instantiate JavaInteractiveSemanticdb (version: None, jdkHome: /usr/lib/jvm/java-11-openjdk-amd64, javac exists: false)
2022.04.26 01:40:43 INFO  time: initialize in 3.63s
2022.04.26 01:40:44 WARN  Build server is not auto-connectable.
2022.04.26 01:40:44 WARN  no build tool detected in workspace '/home/user/projects/p01/src/main/scala'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 
2022.04.26 01:40:45 WARN  no build target for: /home/user/projects/p01/src/main/scala/Main.scala
Apr. 26, 2022 1:40:45 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNUNG: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "workspace/didChangeConfiguration",
  "params": {}
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because the return value of "org.eclipse.lsp4j.DidChangeConfigurationParams.getSettings()" is null
	at scala.meta.internal.metals.MetalsLanguageServer.didChangeConfiguration(MetalsLanguageServer.scala:1252)
	... 16 more
```

### Expected behavior

No exceptions in log file.

### Operating system

Linux

### Editor/Extension

Emacs (lsp-metals)

### Version of Metals

v0.11.2

**Comment by tgodzik** [comment]
Thanks for reporting! It looks like an issue on the client side. The settings field should not be null (it's actually marked as NonNull) and that's what seems to be sent to the server.

**Comment by moberer** [comment]
Hmm, interesting. I've just tried it with eglot too and get the same exception in the log.

**Comment by moberer** [comment]
Opened an issue with the eglot client.

**Comment by tgodzik** [comment]
> Opened an issue with the eglot client.

https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration allows for `any`, so I would assume that's not a null? Nullable fields are usually indicated with `?:`

**Comment by moberer** [comment]
Was resolved on the client side. Thanks for your help!
