### ISSUE TITLE
Extension takes too long to load?

### ISSUE THREAD

**Issue by vishalovercome** [scalameta/metals#3895]
### Describe the bug

I'm not sure whether this is a Metals issue or a VSCode issue or issue with some other extension but I've noticed that one of the VSCode's node process takes too much CPU for about 10-15 minutes during which the entire IDE becomes unresponsive (no text editing, etc.). One behavior that is consistent across restarts is that the node process is managing all my Java/Scala extensions. Below is the output of ps command (74355 is the PID of the node command)

root 74355 241 99 16:09 ? 00:00:47 /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-fork --type=extensionHost --transformURIs --useHostProxy=false
root 74470 74355 0 16:09 ? 00:00:00 /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node /root/.vscode-server/extensions/mtxr.sqltools-0.23.0/dist/languageserver.js --node-ipc --clientProcessId=74355
root 74477 74355 1 16:09 ? 00:00:00 /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node /root/.vscode-server/extensions/redhat.vscode-yaml-1.7.0/dist/languageserver.js --node-ipc --clientProcessId=74355
root 74664 74355 41 16:09 ? 00:00:14 /opt/java/openjdk/bin/java -Xss4m -Xms100m -Dmetals.client=vscode -XX:+UnlockExperimentalVMOptions -XX:MaxRAM=3584m -XX:MaxInlineLevel=20 -XX:NativeMemoryTracking=detail -Xmx1G -classpath A_WHOLE_BUNCH_OF_JAVA_DEPENDENCIES scala.meta.metals.Main
root 74695 74355 0 16:09 ? 00:00:00 /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=74355

Is there a way to determine whether one of these extensions have all of a sudden become too slow to load or whether newer VSCode (1.66.2) has some issue? 

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.5

**Comment by vishalovercome** [comment]
I see this in metals.log

`2022.05.04 13:11:16 INFO  shutting down Metals
2022.05.04 13:11:17 INFO  Shut down connection with build server.
2022.05.04 13:11:17 INFO  Shut down connection with build server.
May 04, 2022 1:11:17 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint notify
INFO: Failed to send notification message.
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.nio.channels.AsynchronousCloseException
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
        at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
        at com.sun.proxy.$Proxy11.onBuildExit(Unknown Source)
        at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1(BuildServerConnection.scala:107)
        at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1$adapted(BuildServerConnection.scala:103)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at java.base/sun.nio.ch.SinkChannelImpl.endWrite(SinkChannelImpl.java:241)
        at java.base/sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:259)
        at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
        at java.base/java.nio.channels.Channels.writeFully(Channels.java:94)
        at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
        at java.base/java.io.OutputStream.write(OutputStream.java:122)
        at java.base/java.nio.channels.Channels$1.write(Channels.java:152)
        at scala.meta.internal.metals.ClosableOutputStream.write(ClosableOutputStream.scala:26)
        at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:137)
        at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:67)
        ... 9 more

2022.05.04 13:11:17 INFO  Shut down connection with build server.
May 04, 2022 1:11:17 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireStreamClosed
INFO: The input stream was closed.
java.nio.channels.ClosedByInterruptException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
        at java.base/sun.nio.ch.SourceChannelImpl.endRead(SourceChannelImpl.java:241)
        at java.base/sun.nio.ch.SourceChannelImpl.read(SourceChannelImpl.java:259)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
        at java.base/java.io.InputStream.read(InputStream.java:205)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:81)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by tgodzik** [comment]
Thanks for reporting! It's probably best to turn off one extension at a time to see which one is causing it. Metals extension itself is rather minimal, so it shouldn't cause any long load time. The bulk of the work is done by the Metals server and it's outside VS Code.

**Comment by Arthurm1** [comment]
VSCode can do this automatically for you using the `Help: Start Extension Bisect` command

**Comment by vishalovercome** [comment]
Thanks for the suggestions. I had done a bisect prior to creating this ticket. Unfortunately that didn't yield anything. My guess is that this is a one time startup related issue. Metals and other Java/Scala extensions don't consume any cpu at all. I'm almost certain that this is a VSCode issue rather than an extension issue. Only reason I created this is because it seems to only happen with the node process managing Java/Scala extensions.
