### ISSUE TITLE
Error while importing build in MacOS

### ISSUE THREAD

**Issue by ratoshniuk** [scalameta/metals#400]
Hi there, 

I am trying to import build but got follow error reason:

```
java.lang.NoClassDefFoundError: Could not initialize class bloop.config.ConfigEncoderDecoders$
```

it occurs for each artifact

**Comment by gabro** [comment]
Hi @ratoshniuk, thanks for reporting.

I've moved this issue to the Metals main repo since it doesn't look specific to the VSCode extension.

Is that the entire output of the log? If not, can you post the rest?

**Comment by ratoshniuk** [comment]
Yes, sure.

I had a huge log, I will print it partially.

```
[success] Generated .bloop/root.json
[error] sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime.
[error] setting(ScopedKey(Scope(Select(ProjectRef(file:/my-project/sbt/sbt-project-deps)), Select(ConfigKey(compile)), Zero, Zero),bloopGenerate)) at LinePosition((bloop.integrations.sbt.BloopDefaults.configSettings) SbtBloop.scala,139) referenced from ScopedKey(Scope(Select(ProjectRef(file:/my-project/sbt/sbt-project-deps/,sbt-project-deps)), Select(ConfigKey(compile)), Zero, Zero),pluginData)
[error] 	at sbt.internal.util.Init.sbt$internal$util$Init$$handleUndefined(Settings.scala:684)
[error] 	at sbt.internal.util.Init$$anon$9.apply(Settings.scala:688)
[error] 	at sbt.internal.util.Init$$anon$9.apply(Settings.scala:688)
[error] 	at sbt.internal.util.$tilde$greater$$anon$5.apply(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$anon$5.apply(TypeFunctions.scala:39)
[error] 	at sbt.std.FullInstance$.$anonfun$flatten$2(TaskMacro.scala:70)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ratoshniuk** [comment]
and that's for all artifacts...

```
[error] java.lang.NoClassDefFoundError: io/circe/derivation/DerivedDecoder
[error] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[error] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[error] 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
[error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at bloop.config.ConfigEncoderDecoders$.<init>(ConfigEncoderDecoders.scala:80)
[error] 	at bloop.config.ConfigEncoderDecoders$.<clinit>(ConfigEncoderDecoders.scala)
[error] 	at bloop.config.package$.toStr(package.scala:11)
[error] 	at bloop.config.package$.write(package.scala:16)
[error] 	at bloop.integrations.sbt.BloopDefaults$.$anonfun$bloopGenerate$3(SbtBloop.scala:766)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ratoshniuk** [comment]
```
(artifact1 / Compile / bloopGenerate) java.lang.NoClassDefFoundError: io/circe/derivation/DerivedDecoder
...
(artifact22 / Compile / bloopGenerate) java.lang.NoClassDefFoundError: io/circe/derivation/DerivedDecoder
```

**Comment by olafurpg** [comment]
Thanks for reporting! Judging by the stack trace, it might help to enable source dependencies https://scalacenter.github.io/bloop/docs/build-tools/sbt#enable-sbt-project-references

```scala
SettingKey[Boolean]("bloopAggregateSourceDependencies") in Global := true
```

If that doesn't help please report this issue here: https://github.com/scalacenter/bloop there's not much we can do on the Metals side.

**Comment by kag0** [comment]
I'm running into this same issue. Ideally I wouldn't need to change the build file since bloop/metals is a local development detail and not one shared by all developers on the project.
That said, adding the setting key didn't seem to help for me.

**Comment by ckipp01** [comment]
@kag0 can you include some details about the version of Metals you are using and your system? Is the error you're seeing the exact same as the above?

**Comment by kag0** [comment]
It was the exact same as above, I'm on osx 11.4. But somehow after a reboot and a metals update it's working now.
I have some other issues now with symbols not being recognized across sbt projects, but that looks like a different issue.
