### ISSUE TITLE
Trouble when using a VPN

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#406]
I'm connecting to my company network using a VPN, and apparently that changes my hostname and metals is now unable to connect to its database. Is there a reason why it doesn't just use localhost?

Here's a relevant piece from my metals log:

```
Dec 12, 2018 5:43:15 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to obtain connection from database (jdbc:h2:file:/Users/j.kozlowski/IdeaProjects/tapir/.metals/metals;MV_STORE=false;AUTO_SERVER=true) for user 'sa': IO Exception: "java.net.UnknownHostException: lt30692.ocado.com: lt30692.ocado.com: nodename nor servname provided, or not known" [90028-197]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 90028
Error Code : 90028
Message    : IO Exception: "java.net.UnknownHostException: lt30692.ocado.com: lt30692.ocado.com: nodename nor servname provided, or not known" [90028-197]

java.util.concurrent.CompletionException: org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to obtain connection from database (jdbc:h2:file:/Users/j.kozlowski/IdeaProjects/tapir/.metals/metals;MV_STORE=false;AUTO_SERVER=true) for user 'sa': IO Exception: "java.net.UnknownHostException: lt30692.ocado.com: lt30692.ocado.com: nodename nor servname provided, or not known" [90028-197]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 90028
Error Code : 90028
Message    : IO Exception: "java.net.UnknownHostException: lt30692.ocado.com: lt30692.ocado.com: nodename nor servname provided, or not known" [90028-197]

        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21)
        at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
        at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
        at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:874)
        at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
        at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:872)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
        at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
        at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
        at scala.concurrent.Promise.complete(Promise.scala:53)
        at scala.concurrent.Promise.complete$(Promise.scala:52)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to obtain connection from database (jdbc:h2:file:/Users/j.kozlowski/IdeaProjects/tapir/.metals/metals;MV_STORE=false;AUTO_SERVER=true) for user 'sa': IO Exception: "java.net.UnknownHostException: lt30692.ocado.com: lt30692.ocado.com: nodename nor servname provided, or not known" [90028-197]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by gabro** [comment]
I've seen that error before in an unrelated context (not using a VPN).

Can you try killing the H2 server (I don't know a smart way of doing that other than randomly killing java processes...)

**Comment by kubukoz** [comment]
I killed all my JVM instances (I could see some apps in `jps`, incuding `Nailgun(...)`, so maybe that's a way to find the right one...), but it didn't change anything... until I restarted metals (it worked until I connected to the VPN).

**Comment by ritschwumm** [comment]
at first glance i'd guess this is a name resolution issue - does your DNS change when you connect to the VPN?

**Comment by olafurpg** [comment]
Metals uses the AUTO_SERVER mode in h2 to support multiple running Metals servers in the same workspace directory. If you only have one open editor in a project at a time, it should not start the h2 TCP server.

As mentioned by @ritschwumm , this might be a DNS mis-configuration that can maybe be fixed with the recommendations here https://stackoverflow.com/a/16617143

**Comment by olafurpg** [comment]
What we can do on the Metals side is gracefully fallback to an in-memory database. Currently, the database provides several nice-to-have features but the server should function fine without it. Even if it's a DNS misconfiguration, I don't think this should result in a fatal error in Metals.

**Comment by olafurpg** [comment]
Opened #408 to gracefully handle database connection errors. There should be a release out later today with the fix.

**Comment by kubukoz** [comment]
Thanks a lot for handling this so fast!
