### ISSUE TITLE
Metals worksheet broken?

### ISSUE THREAD

**Issue by Swoorup** [scalameta/metals#4138]
### Describe the bug

It appears that VS worksheet appears to be broken for 3.2.0-RC2 Scala 

for a simple worksheet containing `println("hello")`

I get the following error

```shell
test.worksheet.sc:2 (mdoc generated code) 
 package scala.compiletime does not have a member method erasedValue
object MdocSession extends _root_.mdoc.internal.document.DocumentBuilder {
```

Other times I get 

```shell
2022.07.12 21:20:03 INFO  time: evaluated worksheet 'circe.worksheet.sc' in 0.67s
2022.07.12 21:20:07 ERROR worksheet: /Users/swoorup/circe.worksheet.scjava.lang.ClassCastException: class dotty.tools.dotc.core.Types$NoType$ cannot be cast to class dotty.tools.dotc.typer.Implicits$SearchFailureType (dotty.tools.dotc.core.Types$NoType$ and dotty.tools.dotc.typer.Implicits$SearchFailureType are in unnamed module of loader java.net.URLClassLoader @65991992)
	at dotty.tools.dotc.typer.Implicits$SearchFailure.reason(Implicits.scala:412)
	at dotty.tools.dotc.typer.ErrorReporting$Errors.selectErrorAddendum$$anonfun$1$$anonfun$1(ErrorReporting.scala:182)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.typer.ErrorReporting$Errors.selectErrorAddendum$$anonfun$1(ErrorReporting.scala:186)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.Option.foreach(Option.scala:437)
	at dotty.tools.dotc.typer.ErrorReporting$Errors.selectErrorAddendum(ErrorReporting.scala:186)
	at dotty.tools.dotc.typer.TypeAssigner.addendum$1(TypeAssigner.scala:170)
	at dotty.tools.dotc.typer.TypeAssigner.$anonfun$4(TypeAssigner.scala:173)
	at dotty.tools.dotc.reporting.NotAMember.msg(messages.scala:349)
	at dotty.tools.dotc.reporting.Message.message(Message.scala:87)
	at dotty.tools.dotc.reporting.Diagnostic.message(Diagnostic.scala:97)
	at mdoc.internal.markdown.MarkdownCompiler.report$$anonfun$1(MarkdownCompiler.scala:240)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at mdoc.internal.markdown.MarkdownCompiler.report(MarkdownCompiler.scala:256)
	at mdoc.internal.markdown.MarkdownCompiler.compileSources(MarkdownCompiler.scala:124)
	at mdoc.internal.markdown.MarkdownCompiler.compile(MarkdownCompiler.scala:151)
	at mdoc.internal.markdown.MarkdownBuilder$.buildDocument(MarkdownBuilder.scala:32)
	at mdoc.internal.worksheets.WorksheetProvider.evaluateWorksheet(WorksheetProvider.scala:38)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:55)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:366)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.liftedTree1$1(WorksheetProvider.scala:267)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:267)
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.7+24-425cc9e0-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! I need to check out why mdoc will not work with Scala 3.2.x. Worst case scenario we will need to release for each binary version :/

**Comment by kpodsiad** [comment]
@tgodzik this might be useful https://github.com/scalameta/mdoc/pull/568
