### ISSUE TITLE
Interrupting presentation compiler thread closes jar filesystem

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#4196]
### Describe the bug

I managed to reproduce it often by trying to get completions for `for@@` in weird places in ScalaPrecentationCompiler for Scala 3
```
2022.07.27 19:17:07 ERROR searching for `scala/Equals#canEqual().` failedjava.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:171)
	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:844)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:824)
	at jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
	at jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
	at jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2417)
	at jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2359)
	at jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2309)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.InputStream.readNBytes(InputStream.java:409)
	at java.io.InputStream.readAllBytes(InputStream.java:346)
	at jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:977)
	at jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:864)
	at jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:238)
	at java.nio.file.Files.newByteChannel(Files.java:380)
	at java.nio.file.Files.newByteChannel(Files.java:432)
	at java.nio.file.Files.readAllBytes(Files.java:3288)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.CommonMtagsEnrichments$XtensionAbsolutePath.toInput(CommonMtagsEnrichments.scala:529)
	at scala.meta.internal.mtags.SymbolIndexBucket.addMtagsSourceFile(SymbolIndexBucket.scala:198)
	at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$query0$1(SymbolIndexBucket.scala:163)
	at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$query0$1$adapted(SymbolIndexBucket.scala:163)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
	at scala.meta.internal.mtags.SymbolIndexBucket.query0(SymbolIndexBucket.scala:163)
	at scala.meta.internal.mtags.SymbolIndexBucket.query(SymbolIndexBucket.scala:140)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$findSymbolDefinition$1(OnDemandSymbolIndex.scala:133)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.findSymbolDefinition(OnDemandSymbolIndex.scala:133)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.definition(OnDemandSymbolIndex.scala:44)
	at scala.meta.internal.metals.Docstrings.indexSymbol(Docstrings.scala:104)
	at scala.meta.internal.metals.Docstrings.documentation(Docstrings.scala:44)
	at scala.meta.internal.metals.MetalsSymbolSearch.documentation(MetalsSymbolSearch.scala:42)
	at scala.meta.internal.mtags.MtagsEnrichments$.symbolDocumentation(MtagsEnrichments.scala:169)
	at scala.meta.internal.pc.printer.MetalsPrinter.paramsDocs$lzyINIT1$1(MetalsPrinter.scala:162)
	at scala.meta.internal.pc.printer.MetalsPrinter.paramsDocs$1(MetalsPrinter.scala:166)
	at scala.meta.internal.pc.printer.MetalsPrinter.$anonfun$4(MetalsPrinter.scala:183)
	at scala.meta.internal.pc.printer.MetalsPrinter.paramLabel(MetalsPrinter.scala:332)
	at scala.meta.internal.pc.printer.MetalsPrinter.$anonfun$3(MetalsPrinter.scala:184)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.meta.internal.pc.printer.MetalsPrinter.label$1$$anonfun$1(MetalsPrinter.scala:187)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.meta.internal.pc.printer.MetalsPrinter.label$1(MetalsPrinter.scala:192)
	at scala.meta.internal.pc.printer.MetalsPrinter.defaultMethodSignature(MetalsPrinter.scala:195)
	at scala.meta.internal.pc.printer.MetalsPrinter.completionSymbol(MetalsPrinter.scala:123)
	at scala.meta.internal.pc.completions.CompletionValue.description(CompletionValue.scala:59)
	at scala.meta.internal.pc.completions.CompletionValue.description$(CompletionValue.scala:20)
	at scala.meta.internal.pc.completions.CompletionValue$Compiler.description(CompletionValue.scala:77)
	at scala.meta.internal.pc.completions.CompletionsProvider.completionItems(CompletionsProvider.scala:171)
	at scala.meta.internal.pc.completions.CompletionsProvider.$anonfun$1(CompletionsProvider.scala:88)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.meta.internal.pc.completions.CompletionsProvider.completions(CompletionsProvider.scala:89)
	at scala.meta.internal.pc.ScalaPresentationCompiler.complete$$anonfun$1(ScalaPresentationCompiler.scala:105)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:138)
	at scala.meta.internal.pc.CompilerAccess.$anonfun$1(CompilerAccess.scala:88)
	at scala.meta.internal.pc.CompilerAccess.onCompilerJobQueue$$anonfun$1(CompilerAccess.scala:198)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
```

later it's not possible to navigate to some of the sources

### Expected behavior

User should still be able to navigate to all the libraries.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.7

### Extra context or search terms

ClosedByInterruptException scala3

**Comment by tgodzik** [comment]
I will try and look at it soon as it's blocking for the release.

**Comment by tanishiking** [comment]
How did you reproduce it? I tried to by writing `for` at random places in `mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala` but I couldn't reproduce it.
using `0.11.7+68-57b05f3f-SNAPSHOT` on VSCode on Mac

**Comment by tgodzik** [comment]
It might actually be a lot of hovers and cancelling them maybe? I had it happen multiple times so this is for sure an issue, but not super clear on reproduction yet.

**Comment by vzmerr** [comment]
I get this a lot next to this exception:

> 2022.07.29 14:31:56 ERROR searching for `dotty/tools/dotc/ast/Trees.Match.` failedjava.nio.channels.ClosedChannelException
> 	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:156)
> 	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:790)
> 	at jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
> 	at jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1231)
> 	at jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2263)
> 	at jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2205)
> 	at jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2155)
> 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
> 	at java.io.InputStream.readNBytes(InputStream.java:409)
> 	at java.io.InputStream.readAllBytes(InputStream.java:346)
> 	at jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:972)
> 	at jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:864)
> 	at jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:238)
> 	at java.nio.file.Files.newByteChannel(Files.java:380)
> 	at java.nio.file.Files.newByteChannel(Files.java:432)
> 	at java.nio.file.Files.readAllBytes(Files.java:3288)
> 	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
> 	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
> 	at scala.meta.internal.mtags.CommonMtagsEnrichments$XtensionAbsolutePath.toInput(CommonMtagsEnrichments.scala:529)
> 	at scala.meta.internal.mtags.SymbolIndexBucket.addMtagsSourceFile(SymbolIndexBucket.scala:198)
> 	at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$query0$1(SymbolIndexBucket.scala:163)
> 	at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$query0$1$adapted(SymbolIndexBucket.scala:163)
> 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
> 	at scala.meta.internal.mtags.SymbolIndexBucket.query0(SymbolIndexBucket.scala:163)
> 	at scala.meta.internal.mtags.SymbolIndexBucket.query(SymbolIndexBucket.scala:140)
> 	at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$findSymbolDefinition$1(OnDemandSymbolIndex.scala:133)
> 	at scala.collection.immutable.List.flatMap(List.scala:293)
> 	at scala.meta.internal.mtags.OnDemandSymbolIndex.findSymbolDefinition(OnDemandSymbolIndex.scala:133)
> 	at scala.meta.internal.mtags.OnDemandSymbolIndex.definition(OnDemandSymbolIndex.scala:44)
> 	at scala.meta.internal.metals.Docstrings.indexSymbol(Docstrings.scala:104)
> 	at scala.meta.internal.metals.Docstrings.documentation(Docstrings.scala:44)
> 	at scala.meta.internal.metals.MetalsSymbolSearch.documentation(MetalsSymbolSearch.scala:42)
> 	at scala.meta.internal.mtags.MtagsEnrichments$.symbolDocumentation(MtagsEnrichments.scala:169)
> 	at scala.meta.internal.pc.CompletionItemResolver$.docs$1(CompletionItemResolver.scala:51)
> 	at scala.meta.internal.pc.CompletionItemResolver$.fullDocstring(CompletionItemResolver.scala:73)
> 	at scala.meta.internal.pc.CompletionItemResolver$.resolve$$anonfun$2(CompletionItemResolver.scala:36)
> 	at scala.meta.internal.pc.ItemResolver.enrichDocs(ItemResolver.scala:75)
> 	at scala.meta.internal.pc.ItemResolver.enrichDocs$(ItemResolver.scala:10)
> 	at scala.meta.internal.pc.CompletionItemResolver$.enrichDocs(CompletionItemResolver.scala:14)
> 	at scala.meta.internal.pc.CompletionItemResolver$.resolve(CompletionItemResolver.scala:37)
> 	at scala.meta.internal.pc.ScalaPresentationCompiler.completionItemResolve$$anonfun$1(ScalaPresentationCompiler.scala:151)
> 	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:138)
> 	at scala.meta.internal.pc.CompilerAccess.withNonInterruptableCompiler$$anonfun$1(CompilerAccess.scala:126)
> 	at scala.meta.internal.pc.CompilerAccess.onCompilerJobQueue$$anonfun$1(CompilerAccess.scala:198)
> 	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:152)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.lang.Thread.run(Thread.java:833)



To reproduce, in a Scala 3 document, where you have never typed or used one of these collections: `Seq`, `Map` `IndexedSeq` `Iterable` , start typing `new Seq` and then choose one of the suggestions by `enter`.

**Comment by vzmerr** [comment]
You can as well reproduce by typing `val a: Str` then pressing ctrl-space

**Comment by kpodsiad** [comment]
@tgodzik I wonder, is this issue related to the following?
<img width="452" alt="Screenshot 2022-07-30 at 07 58 50" src="https://user-images.githubusercontent.com/37124721/182089950-912e41c3-1ea0-4a3b-8703-c31d746ec440.png">

**Comment by tgodzik** [comment]
> @tgodzik I wonder, is this issue related to the following? <img alt="Screenshot 2022-07-30 at 07 58 50" width="452" src="https://user-images.githubusercontent.com/37124721/182089950-912e41c3-1ea0-4a3b-8703-c31d746ec440.png">

Might be, if the exception was thrown. Although status bar should handle it :thinking:
