### ISSUE TITLE
import path.{*, given} wrongly marked as illegal

### ISSUE THREAD

**Issue by Bersier** [scalameta/metals#4502]
### Describe the bug

Use an import of the form

```Scala
import <path>.{*, given}
```

Error:
```
Wildcard import must be in the last position
```

### Expected behavior

No error, as the code compiles fine.

### Version of Metals

v1.20.0

**Comment by tgodzik** [comment]
Thanks for reporting! I can't seems to reproduce it in a Scala 3 codebase. This only shows up if the last import is neither given nor *. Do you perhaps have repository with a reproduction?

**Comment by Bersier** [comment]
I cannot share my repository at this time. But I now see that it only happens for one import:
```Scala
import dimensional.typelevelint.{*, given}
```
In my `build.sbt`, that project is imported with
```Scala
.dependsOn(RootProject(uri("https://github.com/Bersier/physical.git")))
```
Hopefully, that is enough to reproduce the issue.

**Comment by tgodzik** [comment]
Maybe the code is not seen as a Scala 3 one? In that case given would be treated as any other identifier.

**Comment by Bersier** [comment]
@tgodzik yes, that seems likely, actually. Is there some setting I missed to get Metals to interpret the code as Scala 3?

**Comment by tgodzik** [comment]
It should automatically pick up the build tool's Scala version. What build tool do you use? Did you import the build after changes to Scala 3? Do you get any warnings in the metals output?

**Comment by Bersier** [comment]
I use sbt. I found these logs:
```
Java home: C:\Program Files\Java\jdk-17.0.1
Metals version: 0.11.9
2022.10.11 10:41:48 INFO  logging to file C:\Users\steph\Repositories\exchanger\.metals\metals.log
2022.10.11 10:41:48 INFO  Started: Metals version 0.11.9 in workspace 'C:\Users\steph\Repositories\exchanger' for client Visual Studio Code 1.72.0.
2022.10.11 10:41:48 INFO  Flyway Community Edition 9.4.0 by Redgate
2022.10.11 10:41:48 INFO  See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.4.0
2022.10.11 10:41:48 INFO  
2022.10.11 10:41:48 INFO  Database: jdbc:h2:file:C:\Users\steph\Repositories\exchanger\.metals\metals (H2 2.1)
2022.10.11 10:41:48 INFO  Successfully validated 4 migrations (execution time 00:00.020s)
2022.10.11 10:41:48 INFO  Current version of schema "PUBLIC": 4
2022.10.11 10:41:48 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2022.10.11 10:41:49 INFO  time: initialize in 0.9s
Initializing Scala Debugger
Release notes was not shown: not showing release notes since they've already been seen for your current version
2022.10.11 10:41:50 INFO  Attempting to connect to the build server...
2022.10.11 10:41:50 INFO  Bloop uses C:\Program Files\Java\jdk-17.0.1 defined at C:\Users\steph\.bloop\bloop.json
2022.10.11 10:41:50 INFO  skipping build import with status 'Installed'
2022.10.11 10:41:51 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\steph\Repositories\exchanger\.metals\bsp.trace.json or C:\Users\steph\AppData\Local\scalameta\metals\cache\bsp.trace.json
2022.10.11 10:41:51 INFO  Attempting to connect to the build server...
2022.10.11 10:41:51 INFO  Bloop uses C:\Program Files\Java\jdk-17.0.1 defined at C:\Users\steph\.bloop\bloop.json
2022.10.11 10:41:51 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\steph\Repositories\exchanger\project\.metals\bsp.trace.json or C:\Users\steph\AppData\Local\scalameta\metals\cache\bsp.trace.json
2022.10.11 10:41:51 WARN  Scala instance jar c:\home\bersier\.sbt\boot\scala-2.12.16\lib\scala-library.jar doesn't exist!
2022.10.11 10:41:51 WARN  Scala instance jar c:\home\bersier\.sbt\boot\scala-2.12.16\lib\scala-compiler.jar doesn't exist!
2022.10.11 10:41:51 WARN  Scala instance jar c:\home\bersier\.sbt\boot\scala-2.12.16\lib\scala-reflect.jar doesn't exist!
2022.10.11 10:41:51 WARN  Scala instance jar c:\home\bersier\.sbt\boot\scala-2.12.16\lib\scala-xml_2.12-1.0.6.jar doesn't exist!
2022.10.11 10:41:51 ERROR Failed to connect with build server, no functionality will work.java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:497)
	at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:406)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)

2022.10.11 10:41:51 WARN  no build target for: C:\Users\steph\Repositories\exchanger\src\main\scala\exchanger\geometry\coordinates.scala
2022.10.11 10:41:53 INFO  no build target found for C:\Users\steph\Repositories\exchanger\src\main\scala\exchanger\geometry\coordinates.scala. Using presentation compiler with project's scala-library version: 3.2.0
2022.10.11 10:41:55 INFO  time: code lens generation in 3.33s
```

**Comment by tgodzik** [comment]
`2022.10.11 10:41:51 WARN  Scala instance jar c:\home\bersier\.sbt\boot\scala-2.12.16\lib\scala-library.jar doesn't exist!`

Does that file exist but with capital C: ? Could you try reimporting the build? It seems we are unable to start the build server because it can't find the jars for compiling Scala.

**Comment by tgodzik** [comment]
Alternatively you can try and switch to sbt BSP with Switch build server command

**Comment by Bersier** [comment]
For the record, in my case, it looks like metals was shooting for the corrected path below
```
\\wsl.localhost\Ubuntu\home\bersier\.sbt\boot\scala-2.12.16\lib\scala-library.jar
```
