### ISSUE TITLE
Metals debugger stops on vscode if classpath contains empty jar (eg. com.google.guava.listenablefuture) with "zip END header not found"

### ISSUE THREAD

**Issue by rcdmk** [scalameta/metals#4532]
### Describe the bug

When compiling a project that has a dependency like `com.google.guava.listenablefuture`, which contains empty jar files like `9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-999.0-empty-to-avoid-conflict-with-guava-sources.jar`, the debugger crashes with an error and stops, leaving vscode hanging while trying to start debugging.

The project compiles fine on bloop or sbt.

Running or compiling the project with `sbt` on the commandline works just fine, but trying to attach the debugger to a running process also causes the same issue.

### Expected behavior

Metals debugger should run the project, since it compiles successfully, and attach the debugger to allow stepping the code. It should also allow to attach the debugger to a running process (eg: started with `sbt run -jvm-debug 5005`) and step through the code.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

### Extra context or search terms

Error from Metals output, including stacktrace:
```
ERROR error processing file:///Users/ricardo.souza/Library/Caches/Coursier/v1/https/artifactory.xxxxxxxxxxxxxxxx.com/artifactory/xxxxxxxxxxxxx-mvn/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jarjava.util.zip.ZipException: zip END header not found
	at jdk.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1908)
	at jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1052)
	at jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1061)
	at jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:135)
	at jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:109)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:104)
	at scala.meta.internal.io.PlatformFileIO$.newJarFileSystem(PlatformFileIO.scala:100)
	at scala.meta.internal.metals.JarTopLevels.$anonfun$getTopLevels$2(JarTopLevels.scala:40)
	at scala.Option.getOrElse(Option.scala:201)
	at scala.meta.internal.metals.JarTopLevels.getTopLevels(JarTopLevels.scala:40)
	at scala.meta.internal.metals.Indexer.addSourceJarSymbols(Indexer.scala:581)
	at scala.meta.internal.metals.Indexer.$anonfun$indexDependencySources$5(Indexer.scala:436)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
	at scala.meta.internal.metals.Indexer.$anonfun$indexDependencySources$1(Indexer.scala:427)
	at scala.meta.internal.metals.Indexer.$anonfun$indexDependencySources$1$adapted(Indexer.scala:426)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at scala.meta.internal.metals.Indexer.indexDependencySources(Indexer.scala:426)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$21(Indexer.scala:346)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$20(Indexer.scala:339)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$20$adapted(Indexer.scala:335)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.Indexer.indexWorkspace(Indexer.scala:335)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$2(Indexer.scala:143)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$1(Indexer.scala:143)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

**Comment by adpi2** [comment]
Thanks for opening this issue! I am taking a look.

**Comment by adpi2** [comment]
@rcdmk It kind of surprises me that you got a `java.util.zip.ZipException` and not a `java.util.zip.ZipError`.

What is your Java version?

**Comment by rcdmk** [comment]
> @rcdmk It kind of surprises me that you got a `java.util.zip.ZipException` and not a `java.util.zip.ZipError`.
> 
> What is your Java version?

I'm on OpenJDK 11, but also tried on 8 with the same results.

Thank you for fixing this. When should I expect to see a release?

**Comment by adpi2** [comment]
> Thank you for fixing this. When should I expect to see a release?

Metals is released every month, more or less. So it should be released in about 3 weeks.
