### ISSUE TITLE
Method Autocompletion Freezes VSCode Editor

### ISSUE THREAD

**Issue by objektwerks** [scalameta/metals#4534]
Using Metals ( v1.20.0 ) ) and VSCode ( 1.73.0-insider ) on an Apple M1, method autocompletion on Scala objects occasionally freezes VSCode, requiring the closing and reopening of affected window/editor. Having used VSCode and Metals for the past 2+ years, I've never seen this bug before.

**Comment by tgodzik** [comment]
Thanks for reporting! I have few questions that might help figure out what is happening:
- Does it happen on a particular project or always?
- What Scala version are you using? 
- Is there anything in `.metals/metals.log`?
- Would you be able to provide us with [jstack](https://www.baeldung.com/java-thread-dump) output?

**Comment by objektwerks** [comment]
1. I've been working exclusively on a particular project. So, yes, I've only seen the bug with said project.
2. I'm using Scala 3.2.1-RC2
3. There is a metals.log. It's rather large, though. I'll reset and examine when the bug occurs again.
4. I'll attempt to capture a jstack thread dump. :)

**Comment by tgodzik** [comment]
There has been issues with the compiler hanging in some cases, but that should be fixed in 3.2.x and we should now reset the compiler when this happens.

Jstack should be super useful since that would help us to fix it in the compiler, where the issue probably occurs.

**Comment by objektwerks** [comment]
The bug occurs when I attempt autocompletion on a scala.util.Try, looking for an isSuccess method.

I managed to capture a jstack for Main and Server. Enjoyable reading. :)

1. [jstack.10.15.1.txt](https://github.com/scalameta/metals/files/9794505/jstack.10.15.1.txt)
2. [jstack.10.15.2.txt](https://github.com/scalameta/metals/files/9794506/jstack.10.15.2.txt)

**Comment by tgodzik** [comment]
I don't see anything weird in there :/ Does this happen on different versions of metals or/and Scala?

**Comment by objektwerks** [comment]
Since I've been using VSCode-Metals the past few years, I've never seen the editor freeze, popup a dialog to reopen or wait and then reopen the editor as directed. Perhaps, this is a VSCode issue? And it'll disappear in a few versions. :) Or better yet, this only happens on my laptop. :)

**Comment by tgodzik** [comment]
Actually, now that I check on the machine I see:
```
"scala-execution-context-global-6868" #6868 [34651] daemon prio=5 os_prio=31 cpu=151857091.63ms elapsed=154100.07s tid=0x0000000131176e00 nid=34651 runnable  [0x00000001750cf000]
   java.lang.Thread.State: RUNNABLE
        at dotty.tools.dotc.parsing.Scanners$Scanner.handleNewLine(Scanners.scala:610)
        at dotty.tools.dotc.parsing.Scanners$Scanner.nextToken(Scanners.scala:403)
        at dotty.tools.dotc.parsing.Scanners$Scanner.skip(Scanners.scala:319)
        at dotty.tools.dotc.parsing.Parsers$Parser.skip(Parsers.scala:259)
        at dotty.tools.dotc.parsing.Parsers$Parser.recur$2(Parsers.scala:358)
        at dotty.tools.dotc.parsing.Parsers$Parser.statSepOrEnd(Parsers.scala:362)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq$$anonfun$1(Parsers.scala:4181)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1804/0x000000080172ed20.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:493)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq(Parsers.scala:4184)
        at dotty.tools.dotc.parsing.Parsers$Parser.block(Parsers.scala:2608)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockExpr$$anonfun$1(Parsers.scala:2600)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1803/0x000000080172ea78.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:549)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBraces(Parsers.scala:552)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBracesOrIndented(Parsers.scala:563)
        at dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:566)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockExpr(Parsers.scala:2598)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:2433)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$9(Parsers.scala:2387)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1770/0x000000080171abb0.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:2364)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:2206)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:2099)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$8(Parsers.scala:2065)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1769/0x000000080171a908.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.nextSegment$1(Parsers.scala:1308)
        at dotty.tools.dotc.parsing.Parsers$Parser.interpolatedString(Parsers.scala:1317)
        at dotty.tools.dotc.parsing.Parsers$Parser.literal(Parsers.scala:1275)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:2451)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$9(Parsers.scala:2387)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1770/0x000000080171abb0.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:2364)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:2206)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:2099)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq$$anonfun$1(Parsers.scala:4172)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1804/0x000000080172ed20.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:493)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq(Parsers.scala:4184)
        at dotty.tools.dotc.parsing.Parsers$Parser.block(Parsers.scala:2608)
        at dotty.tools.dotc.parsing.Parsers$Parser.closureRest(Parsers.scala:2351)
        at dotty.tools.dotc.parsing.Parsers$Parser.closure(Parsers.scala:2340)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq$$anonfun$1(Parsers.scala:4174)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1804/0x000000080172ed20.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:493)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq(Parsers.scala:4184)
        at dotty.tools.dotc.parsing.Parsers$Parser.block(Parsers.scala:2608)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockExpr$$anonfun$1(Parsers.scala:2600)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1803/0x000000080172ea78.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:549)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBraces(Parsers.scala:552)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBracesOrIndented(Parsers.scala:563)
        at dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:566)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockExpr(Parsers.scala:2598)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:2433)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$9(Parsers.scala:2387)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1770/0x000000080171abb0.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.recur$5(Parsers.scala:1054)
        at dotty.tools.dotc.parsing.Parsers$Parser.infixOps(Parsers.scala:1066)
        at dotty.tools.dotc.parsing.Parsers$Parser.postfixExprRest(Parsers.scala:2372)
        at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:2364)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:2206)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:2099)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq$$anonfun$1(Parsers.scala:4172)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1804/0x000000080172ed20.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:493)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq(Parsers.scala:4184)
        at dotty.tools.dotc.parsing.Parsers$Parser.block(Parsers.scala:2608)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockExpr$$anonfun$1(Parsers.scala:2600)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1803/0x000000080172ea78.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:549)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBracesOrIndented(Parsers.scala:560)
        at dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:566)
        at dotty.tools.dotc.parsing.Parsers$Parser.blockExpr(Parsers.scala:2598)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:2433)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$9(Parsers.scala:2387)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1770/0x000000080171abb0.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:2364)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:2206)
        at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:2099)
        at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$8(Parsers.scala:2065)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1769/0x000000080171a908.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.subPart(Parsers.scala:622)
        at dotty.tools.dotc.parsing.Parsers$Parser.subExpr(Parsers.scala:2067)
        at dotty.tools.dotc.parsing.Parsers$Parser.defDefOrDcl(Parsers.scala:3548)
        at dotty.tools.dotc.parsing.Parsers$Parser.defOrDcl(Parsers.scala:3438)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateStatSeq$$anonfun$1(Parsers.scala:4098)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1785/0x0000000801722c88.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:493)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateStatSeq(Parsers.scala:4106)
        at dotty.tools.dotc.parsing.Parsers$Parser.$anonfun$44(Parsers.scala:3977)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1784/0x00000008017229e0.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:549)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBracesOrIndented(Parsers.scala:560)
        at dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:566)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateBody(Parsers.scala:3977)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateBodyOpt(Parsers.scala:3970)
        at dotty.tools.dotc.parsing.Parsers$Parser.template(Parsers.scala:3947)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateOpt(Parsers.scala:3955)
        at dotty.tools.dotc.parsing.Parsers$Parser.classDefRest(Parsers.scala:3678)
        at dotty.tools.dotc.parsing.Parsers$Parser.classDef(Parsers.scala:3673)
        at dotty.tools.dotc.parsing.Parsers$Parser.tmplDef(Parsers.scala:3649)
        at dotty.tools.dotc.parsing.Parsers$Parser.defOrDcl(Parsers.scala:3444)
        at dotty.tools.dotc.parsing.Parsers$Parser.topStatSeq(Parsers.scala:4034)
        at dotty.tools.dotc.parsing.Parsers$Parser.topstats$1(Parsers.scala:4220)
        at dotty.tools.dotc.parsing.Parsers$Parser.topstats$1(Parsers.scala:4214)
        at dotty.tools.dotc.parsing.Parsers$Parser.compilationUnit$$anonfun$1(Parsers.scala:4225)
        at dotty.tools.dotc.parsing.Parsers$Parser$$Lambda$1776/0x0000000801719000.apply(Unknown Source)
        at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:493)
        at dotty.tools.dotc.parsing.Parsers$Parser.compilationUnit(Parsers.scala:4230)
        at dotty.tools.dotc.parsing.Parsers$Parser.parse(Parsers.scala:182)
        at dotty.tools.dotc.parsing.Parser.parse$$anonfun$1(ParserPhase.scala:32)
        at dotty.tools.dotc.parsing.Parser.parse$$anonfun$adapted$1(ParserPhase.scala:39)
        at dotty.tools.dotc.parsing.Parser$$Lambda$1754/0x00000008016fa650.apply(Unknown Source)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:429)
        at dotty.tools.dotc.parsing.Parser.parse(ParserPhase.scala:39)
        at dotty.tools.dotc.parsing.Parser.runOn$$anonfun$1(ParserPhase.scala:48)
        at dotty.tools.dotc.parsing.Parser$$Lambda$1753/0x00000008016fa260.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.parsing.Parser.runOn(ParserPhase.scala:48)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:233)
        at dotty.tools.dotc.Run$$Lambda$1748/0x00000008016f87f8.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:244)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:252)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:261)
        at dotty.tools.dotc.Run$$Lambda$1710/0x00000008016dc018.apply(Unknown Source)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:261)
        at dotty.tools.dotc.Run.compileSources(Run.scala:185)
        at dotty.tools.dotc.Run.compile(Run.scala:169)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
```

This might indicate some kind of infinite loop in the parser, which will make the completions freeze, but it shouldn't free VS Code itself and most other issues should work.

Maybe it's an issue with RAM? I had sometimes VS Code hanging when having way too many projects open. You can set Xmx for Bloop or sbt BSP to make sure that the expected ram is not exceeded.

**Comment by objektwerks** [comment]
Interesting.

I'm using an Apple M1 with 16GB of RAM. I have only 2 VSCode projects open at one time, leaving me with 4 to 6 GB of free RAM according to my Clean Memory utility app. That said, I'll look into tuning Bloop and SBT RAM.

While the affected code editor tab freezes, VSCode does not freeze. Instead, it pops up a dialog asking me to wait or reopen the project window. I've always selected reopen. And all is well again.

**Comment by tgodzik** [comment]
Might it actually be a VS Code issue? Metals can't freeze any tab since it's a separate process. Maybe related to https://github.com/microsoft/vscode/issues/145387 ?

**Comment by objektwerks** [comment]
Wow! The plot thickens. :) It could be the issue - but, then, what is the issue? To date, nobody really seems to know.

Oddly enough, I was immersed in a Typescript project, using only VSCode, throughout August and September. And I never experienced an editor freeze.

Only when I recently returned to VSCode, Metals and Scala did I start to experience the occasional editor freeze.

I'm currently working on an Apple M1, 16GB RAM, Big Sur 11.6 My VSCode profile is:

Version: 1.73.0-insider
Commit: 6455bf1608dfa1b955717f66295f0f9200db0f73
Date: 2022-10-17T05:33:53.480Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 20.6.0
Sandboxed: Yes

**Comment by tgodzik** [comment]
Typescript doesn't use LSP, so this might be related to some interaction between LSP and editor and M1

**Comment by tgodzik** [comment]
From what I see you can try disabling some of the other extensions to see if maybe it's an interaction between different installed ones? Did you install any particular extensions recently?

**Comment by tgodzik** [comment]
Let's reopen this if the freezes happen again without other extensions enabled.
