### ISSUE TITLE
Test failures (HoverDocSuite, CompletionSuite) on JDK 8 only

### ISSUE THREAD

**Issue by SethTisue** [scalameta/metals#4585]
### Describe the bug

If I do `++2.13.10 cross/test` I get the following failures:

```
[error] Failed tests:
[error] 	tests.hover.HoverDocSuite
[error] 	tests.pc.CompletionSuite
```

<details>
```
==> X tests.hover.HoverDocSuite.java-method_2.13.10  0.066s munit.ComparisonFailException: /Users/tisue/metals/tests/cross/src/test/scala/tests/hover/HoverDocSuite.scala:102
101:
102:  check(
103:    "java-method",
diff assertion failed
=> Diff (- obtained, + expected)
 Converts a path string, or a sequence of strings that when joined form
-a path string, to a `Path`. If `more` does not specify any
-elements then the value of the `first` parameter is the path string
-to convert. If `more` specifies one or more elements then each
-non-empty string, including `first`, is considered to be a sequence
-of name elements (see [Path](Path)) and is joined to form a path string.
-The details as to how the Strings are joined is provider specific but
-typically they will be joined using the [name-separator](FileSystem#getSeparator) as the separator. For example, if the name separator is
-"`/`" and `getPath("/foo","bar","gus")` is invoked, then the
-path string `"/foo/bar/gus"` is converted to a `Path`.
-A `Path` representing an empty path is returned if `first`
-is the empty string and `more` does not contain any non-empty
-strings.
-
- The `Path` is obtained by invoking the [getPath](FileSystem#getPath) method of the [default](FileSystems#getDefault) [
-FileSystem](
-FileSystem).
-
- Note that while this method is very convenient, using it will imply
-an assumed reference to the default `FileSystem` and limit the
-utility of the calling code. Hence it should not be used in library code
-intended for flexible reuse. A more flexible alternative is to use an
-existing `Path` instance as an anchor, such as:
-
-```
-Path dir = ...
-Path path = dir.resolve("file");
-```
+a path string, to a `Path`.
    at munit.Assertions.failComparison(Assertions.scala:274)
```
</details>

<details>
```
==> X tests.pc.CompletionSuite.fuzzy1_2.13.10  0.118s munit.ComparisonFailException: /Users/tisue/metals/tests/cross/src/test/scala/tests/pc/CompletionSuite.scala:316
315:
316:  check(
317:    "fuzzy1",
diff assertion failed
=> Obtained
    """|ProcessBuilder java.lang
       |ProcessBuilder - scala.sys.process
       |CertPathBuilder - java.security.cert
       |CertPathBuilderSpi - java.security.cert
       |ProcessBuilderImpl - scala.sys.process
       |CertPathBuilderResult - java.security.cert
       |PKIXBuilderParameters - java.security.cert
       |CertPathBuilderException - java.security.cert
       |PKIXCertPathBuilderResult - java.security.cert
       |""".stripMargin
=> Diff (- obtained, + expected)
 PKIXBuilderParameters - java.security.cert
+PooledConnectionBuilder - javax.sql
 CertPathBuilderException - java.security.cert
    at munit.Assertions.failComparison(Assertions.scala:274)
```
</details>

<details>
```
==> X tests.pc.CompletionSuite.import3_2.13.10  0.198s munit.ComparisonFailException: /Users/tisue/metals/tests/cross/src/test/scala/tests/pc/CompletionSuite.scala:441
440:
441:  check(
442:    "import3",
diff assertion failed
=> Obtained
    """|Path - java.nio.file
       |Paths - java.nio.file
       |XPath - javax.xml.xpath
       |Path2D - java.awt.geom
       |CertPath - java.security.cert
       |TreePath - javax.swing.tree
       |XPathType - javax.xml.crypto.dsig.spec
       |LayoutPath - java.awt.font
       |PathMatcher - java.nio.file
       |GeneralPath - java.awt.geom
       |XPathResult - org.w3c.dom.xpath
       |""".stripMargin
=> Diff (- obtained, + expected)
 LayoutPath - java.awt.font
+XPathNodes - javax.xml.xpath
 PathMatcher - java.nio.file
-GeneralPath - java.awt.geom
 XPathResult - org.w3c.dom.xpath
    at munit.Assertions.failComparison(Assertions.scala:274)
```
</details>

### Expected behavior

tests pass

### Operating system

macOS

### Version of Metals

current HEAD (ee4ac3d23b39310d3ce6bd76356886e04751544f)

### Extra context or search terms

this came up at scala/community-build#1602

Java version is

```
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Temurin)(build 25.345-b01, mixed mode)
```

**Comment by SethTisue** [comment]
ah, okay, that's good to know

ironically, the reason I was testing on JDK 8 is that in the community build, metals depends on scalafix, and scalafix fails on JDK 11 and 17

over at scala/community-build#1602, I'll see if I can get scalafix green on JDK 11 and/or 17 by any means necessary, and then see how metals is on those same JDK versions

**Comment by SethTisue** [comment]
I've confirmed that `cross/test` is green for me on JDK 17, and JDK 11 too

**Comment by SethTisue** [comment]
Great! This succeeded for me in a local test, so I pushed it on the assumption it will probably work in CI as well: scala/community-build@9ffadff48b781f4446dc07a781ac6da6b58f0a66
