### ISSUE TITLE
BSP support is broke for servers that don't implement `JvmRunEnvironmentResult`

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#4610]
### Describe the bug

When using a BSP server that isn't on the latest version that implements `JvmRunEnvironmentResult` the connection fails with the following:

```
2022.11.06 14:22:20 ERROR Failed to connect with build server, no functionality will work.scala.meta.i
nternal.metals.MetalsBspException: BSP connection failed in the attempt to get: JvmRunEnvironmentResult
        at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.$anonfun$applyOrElse$6(BuildSer
verConnection.scala:377)
        at scala.Option.getOrElse(Option.scala:201)
        at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnecti
on.scala:375)
        at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnecti
on.scala:358)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
        at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.ja
va:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.ja
va:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)

2022.11.06 14:22:20 INFO  Shut down connection with build server.
```

### Expected behavior

I'd expect for this not to happen since there is no guarantee that a server is on a version that implements a new endpoint like this. So we should either do an explicit check to see if it's there first and then ask, or this situation should be handled better in BSP.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.9+105-80f10362-SNAPSHOT

**Comment by ckipp01** [comment]
Ignore this, it's wrong. Mill declares it, but isn't able to handle it, so the issue is there.
