### ISSUE TITLE
Metals (+vscode): Nullpointer exceptions from metals in simple hello world application

### ISSUE THREAD

**Issue by GiGurra** [scalameta/metals#4636]
### Describe the bug

After discussion with Tomasz Godzik on Discord was asked to post here.

A full reproduction case is prepared in the following repo: https://github.com/GiGurra/metals-issue-1

A summary of the issue below:

Metals logs the following every time I define a method with an output type I have not yet imported?
```
[Error - 10:52:51] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
    at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
    at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
```

Seems like it is triggered only if the type in question actually exists, but you have not imported it yet.

Example code from a minimal scala 2.13.10 project triggering it
```
object Main extends App {
  def foofoo: AtomicLong = ???
  println("Hello, World!")
}
```

However the following will not trigger it
```
object Main extends App {
  def foofoo: Blah = ???
  println("Hello, World!")
}
```

### Expected behavior

No NullpointerException from Metals/in Metals logs :D 
Preferably also a suggestion on what to import.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by kpodsiad** [comment]
I can't reproduce it on MacOS. Do you mind attaching logs from newer jdk (one with enhanced null pointer exception message)?

**Comment by tgodzik** [comment]
Thanks for reporting! This seems to be coming from the presentation compiler, you should be able to find something in `.metals/metals.log` that points to the actual stack trace. 

Also, what Java are you using? I can't reproduce it either on Ubuntu, I can also take a look on Windows a bit later.

**Comment by GiGurra** [comment]
> I can't reproduce it on MacOS. Do you mind attaching logs from newer jdk (one with enhanced null pointer exception message)?

Which jdk version do you want me to test with?

**Comment by tgodzik** [comment]
Which one are you actually using?

**Comment by GiGurra** [comment]
.metals/metals.log also contains the same:
```Nov 16, 2022 2:37:11 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.NullPointerException: Cannot invoke "scala.collection.IterableOnce.iterator()" because the return value of "scala.Function1.apply(Object)" is null
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "scala.collection.IterableOnce.iterator()" because the return value of "scala.Function1.apply(Object)" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "scala.collection.IterableOnce.iterator()" because the return value of "scala.Function1.apply(Object)" is null
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.collection.immutable.List.flatMap(List.scala:79)
	at scala.meta.internal.metals.codeactions.ImportMissingSymbol.joinActionEdits$1(ImportMissingSymbol.scala:39)
	at scala.meta.internal.metals.codeactions.ImportMissingSymbol.$anonfun$contribute$18(ImportMissingSymbol.scala:135)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.collection.immutable.HashMap.map(HashMap.scala:39)
	at scala.meta.internal.metals.codeactions.ImportMissingSymbol.$anonfun$contribute$16(ImportMissingSymbol.scala:131)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	... 3 more

```

**Comment by tgodzik** [comment]
Thanks, that looks like something we can take a look at or at least guard against

**Comment by kpodsiad** [comment]
@GiGurra could you try `0.11.9+147-e2159db2-SNAPSHOT` version?

**Comment by GiGurra** [comment]
> Member

How do I do that?

![image](https://user-images.githubusercontent.com/1761299/202512479-5c0d2598-90c6-4b33-88c6-341671c04fdf.png)

**Comment by ckipp01** [comment]
> How do I do that?

You'll want to look for the `Metals: Server Version` setting:
<img width="1156" alt="Screenshot 2022-11-17 at 18 25 42" src="https://user-images.githubusercontent.com/13974112/202515406-70b3980d-eb70-485d-bfd9-0d2a6ab46732.png">

**Comment by GiGurra** [comment]
LGTM!
![image](https://user-images.githubusercontent.com/1761299/202516347-988dcc2a-fd53-4510-a518-956ce6beb994.png)

no NPE in metals log either
