### ISSUE TITLE
Implement members doesn't work in scala 3

### ISSUE THREAD

**Issue by Odomontois** [scalameta/metals#4668]
### Describe the bug

1. go to https://github.com/evolution-gaming/derivation/blob/implement-repro/modules/tapir/src/main/scala/evo/derivation/EvoSchema.scala
2. use action "implement all members" on object EvoSchema
3. receive no error in output and compiler error in the logs
```log
Nov 22, 2022 11:27:10 AM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: NoDenotation.owner
java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2511)
	at scala.meta.internal.pc.printer.ShortenedNames.loop$1(ShortenedNames.scala:143)
	at scala.meta.internal.pc.printer.ShortenedNames.$anonfun$7(ShortenedNames.scala:184)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.meta.internal.pc.printer.ShortenedNames.loop$1(ShortenedNames.scala:184)
	at scala.meta.internal.pc.printer.ShortenedNames.shortType(ShortenedNames.scala:207)
	at scala.meta.internal.pc.printer.MetalsPrinter.tpe(MetalsPrinter.scala:75)
	at scala.meta.internal.pc.printer.MetalsPrinter.paramLabel(MetalsPrinter.scala:351)
	at scala.meta.internal.pc.printer.MetalsPrinter.$anonfun$3(MetalsPrinter.scala:184)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.meta.internal.pc.printer.MetalsPrinter.label$1$$anonfun$1(MetalsPrinter.scala:187)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.meta.internal.pc.printer.MetalsPrinter.label$1(MetalsPrinter.scala:192)
	at scala.meta.internal.pc.printer.MetalsPrinter.defaultMethodSignature(MetalsPrinter.scala:195)
	at scala.meta.internal.pc.completions.OverrideCompletions$.toCompletionValue(OverrideCompletions.scala:405)
	at scala.meta.internal.pc.completions.OverrideCompletions$.$anonfun$9(OverrideCompletions.scala:272)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at scala.meta.internal.pc.completions.OverrideCompletions$.implementAllFor(OverrideCompletions.scala:272)
	at scala.meta.internal.pc.completions.OverrideCompletions$.implementAll$lzyINIT1$1$$anonfun$1(OverrideCompletions.scala:190)
	at scala.meta.internal.pc.completions.OverrideCompletions$.implementAllAt(OverrideCompletions.scala:196)
```

### Expected behavior

Metals will generate methods with signatures more or less like the commented ones.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.9 or v0.11.9+160-d38ccc53-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting and the reproduction!
