### ISSUE TITLE
Failed to connect with build server, no functionality will work. See logs for more details.

### ISSUE THREAD

**Issue by linuxlonelyeagle** [scalameta/metals#4721]
### Describe the bug

When i Import build.I build failed.There is the log.
```
2022.12.10 14:00:29 INFO  time: ran 'mill bloopInstall' in 1.99s
2022.12.10 14:00:29 INFO  Attempting to connect to the build server...
2022.12.10 14:00:29 INFO  Bloop uses /usr/lib/jvm/java-11-openjdk-amd64 defined at /root/.bloop/bloop.json
2022.12.10 14:00:29 ERROR Starting the bsp launcher for bloop...
2022.12.10 14:00:29 ERROR Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher13219480949259736148/bsp.socket'...
2022.12.10 14:00:29 ERROR Waiting for the bsp connection to come up...
2022.12.10 14:00:29 ERROR error: The command bsp --protocol local --socket /tmp/bsp-launcher13219480949259736148/bsp.socket returned with an error
2022.12.10 14:00:29 ERROR > No server running at 127.0.0.1:8212, let's fire one...
2022.12.10 14:00:29 ERROR > Resolving ch.epfl.scala:bloop-frontend_2.12:v1.5.4...
2022.12.10 14:00:29 ERROR > error: Unexpected error when resolving Bloop server via coursier!
2022.12.10 14:00:29 ERROR > error: Error downloading ch.epfl.scala:bloop-frontend_2.12:v1.5.4
2022.12.10 14:00:29 ERROR >   not found: /root/.ivy2/local/ch.epfl.scala/bloop-frontend_2.12/v1.5.4/ivys/ivy.xml
2022.12.10 14:00:29 ERROR >   not found: https://repo1.maven.org/maven2/ch/epfl/scala/bloop-frontend_2.12/v1.5.4/bloop-frontend_2.12-v1.5.4.pom
2022.12.10 14:00:29 ERROR > bloop.shaded.coursierapi.error.SimpleResolutionError$1: Error downloading ch.epfl.scala:bloop-frontend_2.12:v1.5.4
2022.12.10 14:00:29 ERROR >   not found: /root/.ivy2/local/ch.epfl.scala/bloop-frontend_2.12/v1.5.4/ivys/ivy.xml
2022.12.10 14:00:29 ERROR >   not found: https://repo1.maven.org/maven2/ch/epfl/scala/bloop-frontend_2.12/v1.5.4/bloop-frontend_2.12-v1.5.4.pom
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.error.SimpleResolutionError.of(SimpleResolutionError.java:11)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.shaded.coursier.internal.api.ApiHelper$.simpleResError(ApiHelper.scala:326)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.shaded.coursier.internal.api.ApiHelper$.doFetch(ApiHelper.scala:359)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.shaded.coursier.internal.api.ApiHelper.doFetch(ApiHelper.scala)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.Fetch.fetchResult(Fetch.java:244)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.Fetch.fetch(Fetch.java:239)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.core.DependencyResolution$.resolveWithErrors(DependencyResolution.scala:66)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.core.ServerStatus$.resolveServer(ServerStatus.scala:16)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.BloopgunCli.fireServer(Bloopgun.scala:364)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.BloopgunCli.fireCommand(Bloopgun.scala:269)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.BloopgunCli.run(Bloopgun.scala:214)
2022.12.10 14:00:29 ERROR > 	at bloop.launcher.bsp.BspBridge$$anon$1.run(BspBridge.scala:82)
2022.12.10 14:00:29 ERROR > error: Server could not be started at None:Some(8212)! Giving up...
2022.12.10 14:00:29 ERROR error: Trying a tcp-based connection to the server instead...
2022.12.10 14:00:29 ERROR Opening a bsp server connection with 'bsp --protocol tcp --port 24799'...
2022.12.10 14:00:29 ERROR Waiting for the bsp connection to come up...
2022.12.10 14:00:29 ERROR error: The command bsp --protocol tcp --port 24799 returned with an error
2022.12.10 14:00:29 ERROR > No server running at 127.0.0.1:8212, let's fire one...
2022.12.10 14:00:29 ERROR > Resolving ch.epfl.scala:bloop-frontend_2.12:v1.5.4...
2022.12.10 14:00:29 ERROR > error: Unexpected error when resolving Bloop server via coursier!
2022.12.10 14:00:29 ERROR > error: Error downloading ch.epfl.scala:bloop-frontend_2.12:v1.5.4
2022.12.10 14:00:29 ERROR >   not found: /root/.ivy2/local/ch.epfl.scala/bloop-frontend_2.12/v1.5.4/ivys/ivy.xml
2022.12.10 14:00:29 ERROR >   not found: https://repo1.maven.org/maven2/ch/epfl/scala/bloop-frontend_2.12/v1.5.4/bloop-frontend_2.12-v1.5.4.pom
2022.12.10 14:00:29 ERROR > bloop.shaded.coursierapi.error.SimpleResolutionError$1: Error downloading ch.epfl.scala:bloop-frontend_2.12:v1.5.4
2022.12.10 14:00:29 ERROR >   not found: /root/.ivy2/local/ch.epfl.scala/bloop-frontend_2.12/v1.5.4/ivys/ivy.xml
2022.12.10 14:00:29 ERROR >   not found: https://repo1.maven.org/maven2/ch/epfl/scala/bloop-frontend_2.12/v1.5.4/bloop-frontend_2.12-v1.5.4.pom
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.error.SimpleResolutionError.of(SimpleResolutionError.java:11)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.shaded.coursier.internal.api.ApiHelper$.simpleResError(ApiHelper.scala:326)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.shaded.coursier.internal.api.ApiHelper$.doFetch(ApiHelper.scala:359)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.shaded.coursier.internal.api.ApiHelper.doFetch(ApiHelper.scala)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.Fetch.fetchResult(Fetch.java:244)
2022.12.10 14:00:29 ERROR > 	at bloop.shaded.coursierapi.Fetch.fetch(Fetch.java:239)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.core.DependencyResolution$.resolveWithErrors(DependencyResolution.scala:66)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.core.ServerStatus$.resolveServer(ServerStatus.scala:16)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.BloopgunCli.fireServer(Bloopgun.scala:364)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.BloopgunCli.fireCommand(Bloopgun.scala:269)
2022.12.10 14:00:29 ERROR > 	at bloop.bloopgun.BloopgunCli.run(Bloopgun.scala:214)
2022.12.10 14:00:29 ERROR > 	at bloop.launcher.bsp.BspBridge$$anon$1.run(BspBridge.scala:82)
2022.12.10 14:00:29 ERROR > error: Server could not be started at None:Some(8212)! Giving up...
2022.12.10 14:00:29 ERROR error: The launcher failed to establish a bsp connection, aborting...
2022.12.10 14:00:29 ERROR Failed to connect with build server, no functionality will work.java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:92)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:119)
	at scala.meta.internal.metals.BloopServers$$anon$2.run(BloopServers.scala:496)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

### Expected behavior

Successfully built.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

0.11.9

### Extra context or search terms

I use mill to build scala.Sbt will run successfully.

**Comment by tgodzik** [comment]
Thanks for reporting! Are you behind a proxy? Are you able to download dependencies from Maven Central normally?

**Comment by linuxlonelyeagle** [comment]
> Thanks for reporting! Are you behind a proxy? Are you able to download dependencies from Maven Central normally?

Sorry for my late reply, no proxy is needed on this machine, i can download all the dependencies through mill, I have not used maven. Thank you for your reply.

**Comment by tgodzik** [comment]
Did you maybe change the bloop version setting to `v1.5.4` ? It should be `1.5.4` without the `v`

**Comment by linuxlonelyeagle** [comment]
I'm very sorry, I don't know how to solve this problem in the end. There are times when suddenly there is no more this problem.
