### ISSUE TITLE
Metals crashes with internal error when using SBT as build server and a JAVA_HOME path that contains spaces

### ISSUE THREAD

**Issue by JakobLyngPetersen** [scalameta/metals#4832]
### Describe the bug

[myproject.zip](https://github.com/scalameta/metals/files/10373560/myproject.zip)

After having installed Metals 0.11.10 I experienced that - when using SBT as build server, Metals crashed with an internal error.

To replicate:

1. Make sure your JAVA_HOME points to a folder containing spaces (on Windows, the default path to Java is typically something like `C:\Program Files\Eclipse Adoptium\jdk-8.0.352.8-hotspot`)
2. Download the attached test project (myproject.zip)
3. Start Metals/VSCode on that project
4. Switch to using SBT as build server

Now, when the project is imported, Metals crashes with an internal error: 
```
2023.01.09 13:25:10 INFO  Processing workspace/reload
2023.01.09 13:25:10 INFO  compiling myproject-build-build
2023.01.09 13:25:12 INFO  compiling myproject-build
2023.01.09 13:25:12 INFO  Processing workspace/buildTargets
2023.01.09 13:25:12 INFO  Processing buildTarget/scalacOptions
2023.01.09 13:25:12 INFO  Processing buildTarget/sources
2023.01.09 13:25:12 INFO  Processing buildTarget/dependencySources
2023.01.09 13:25:13 INFO  Processing buildTarget/jvmRunEnvironment
2023.01.09 13:25:13 INFO  compiling root
2023.01.09 13:25:13 INFO  time: compiled root in 0.38s
2023.01.09 13:25:13 INFO  compiling root-test
2023.01.09 13:25:13 INFO  time: compiled root-test in 4ms
2023.01.09 13:25:13 INFO  time: Imported build in 0.77s
2023.01.09 13:25:13 INFO  Correctly reloaded workspace
2023.01.09 13:25:13 ERROR failed to index classpath for workspace/symboljava.lang.IllegalArgumentException: Illegal character in path at index 16: file:/C:/Program Files/Eclipse Adoptium/jdk-8.0.352.8-hotspot/lib/tools.jar
	at java.net.URI.create(URI.java:852)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionStringMtags.toAbsolutePath(MtagsEnrichments.scala:158)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:609)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:606)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionScalacOptions.$anonfun$jarClasspath$4(MetalsEnrichments.scala:916)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionScalacOptions.jarClasspath(MetalsEnrichments.scala:916)
	at scala.meta.internal.metals.TargetData.$anonfun$targetJarClasspath$1(TargetData.scala:130)
	at scala.Option.map(Option.scala:242)
	at scala.meta.internal.metals.TargetData.targetJarClasspath(TargetData.scala:130)
	at scala.meta.internal.metals.TargetData.$anonfun$allWorkspaceJars$1(TargetData.scala:159)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.collection.immutable.List.flatMap(List.scala:79)
	at scala.meta.internal.metals.TargetData.allWorkspaceJars(TargetData.scala:158)
	at scala.meta.internal.metals.BuildTargets.$anonfun$allWorkspaceJars$1(BuildTargets.scala:142)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:480)
	at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
	at scala.collection.immutable.List.prependedAll(List.scala:155)
	at scala.collection.immutable.List$.from(List.scala:684)
	at scala.collection.immutable.List$.from(List.scala:681)
	at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
	at scala.collection.immutable.Seq$.from(Seq.scala:42)
	at scala.collection.IterableOnceOps.toSeq(IterableOnce.scala:1300)
	at scala.collection.IterableOnceOps.toSeq$(IterableOnce.scala:1300)
	at scala.collection.AbstractIterator.toSeq(Iterator.scala:1300)
	at scala.meta.internal.metals.WorkspaceSymbolProvider.indexClasspathUnsafe(WorkspaceSymbolProvider.scala:121)
	at scala.meta.internal.metals.WorkspaceSymbolProvider.indexClasspath(WorkspaceSymbolProvider.scala:77)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$16(Indexer.scala:327)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.indexWorkspace(Indexer.scala:327)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$2(Indexer.scala:145)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$1(Indexer.scala:145)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/Eclipse Adoptium/jdk-8.0.352.8-hotspot/lib/tools.jar
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.parseHierarchical(URI.java:3104)
	at java.net.URI$Parser.parse(URI.java:3052)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionStringMtags.toAbsolutePath(MtagsEnrichments.scala:158)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:609)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:606)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionScalacOptions.$anonfun$jarClasspath$4(MetalsEnrichments.scala:916)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionScalacOptions.jarClasspath(MetalsEnrichments.scala:916)
	at scala.meta.internal.metals.TargetData.$anonfun$targetJarClasspath$1(TargetData.scala:130)
	at scala.Option.map(Option.scala:242)
	at scala.meta.internal.metals.TargetData.targetJarClasspath(TargetData.scala:130)
	at scala.meta.internal.metals.TargetData.$anonfun$allWorkspaceJars$1(TargetData.scala:159)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.collection.immutable.List.flatMap(List.scala:79)
	at scala.meta.internal.metals.TargetData.allWorkspaceJars(TargetData.scala:158)
	at scala.meta.internal.metals.BuildTargets.$anonfun$allWorkspaceJars$1(BuildTargets.scala:142)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:480)
	at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
	at scala.collection.immutable.List.prependedAll(List.scala:155)
	at scala.collection.immutable.List$.from(List.scala:684)
	at scala.collection.immutable.List$.from(List.scala:681)
	at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
	at scala.collection.immutable.Seq$.from(Seq.scala:42)
	at scala.collection.IterableOnceOps.toSeq(IterableOnce.scala:1300)
	at scala.collection.IterableOnceOps.toSeq$(IterableOnce.scala:1300)
	at scala.collection.AbstractIterator.toSeq(Iterator.scala:1300)
	at scala.meta.internal.metals.WorkspaceSymbolProvider.indexClasspathUnsafe(WorkspaceSymbolProvider.scala:121)
	at scala.meta.internal.metals.WorkspaceSymbolProvider.indexClasspath(WorkspaceSymbolProvider.scala:77)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$16(Indexer.scala:327)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.indexWorkspace(Indexer.scala:327)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$2(Indexer.scala:145)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$1(Indexer.scala:145)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

2023.01.09 13:25:13 INFO  time: indexed workspace in 0.38s
2023.01.09 13:25:13 INFO  Processing buildTarget/scalaMainClasses
2023.01.09 13:25:13 INFO  compiling root
2023.01.09 13:25:14 INFO  time: compiled root in 0.78s
2023.01.09 13:25:14 INFO  compiling root-test
2023.01.09 13:25:14 INFO  time: compiled root-test in 619μs
2023.01.09 13:25:14 INFO  Processing buildTarget/scalaTestClasses
2023.01.09 13:25:14 INFO  compiling root
2023.01.09 13:25:14 INFO  time: compiled root in 518μs
2023.01.09 13:25:14 INFO  compiling root-test
2023.01.09 13:25:14 INFO  time: compiled root-test in 699μs
```
There may be multiple issues: a) the spaces should be encoded for the URI, and b) something like `file:/C:/` seems to be wrong (I would expect something like: `file:///C:/`

If I change my `JAVA_HOME` to the corresponding Windows short path, e.g., `C:\PROGRA~1\ECLIPS~1\jdk-8.0.352.8-hotspot` the crash does not occur (I don't know why the `file:/C:/...` is accepted?

### Expected behavior

I would expect Metals to work properly with Windows-like file paths and with paths containing spaces.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.10.11

**Comment by tgodzik** [comment]
Thanks for reporting! Could you test it under the newest snapshot version? You need to change the metals server version option to `0.11.10+31-181ba661-SNAPSHOT` or switch to prerelease version

**Comment by JakobLyngPetersen** [comment]
Hi @tgodzik ,
I have now tested with that version, and it seems to work there.
Thanks.

**Comment by tgodzik** [comment]
Closing the issue then. Most likely I will try to release in a couple of weeks (max at the end of January)
