### ISSUE TITLE
java.nio.file.NoSuchFileException during sources indexing

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#4989]
### Describe the bug

I'm not sure what exactly happens but probably Metals closes jar filesystem somewhere.

Right now, when I'm opening metals repo I'm getting the following error in log:
```
2023.02.20 00:36:50 INFO  time: Imported build in 0.46s
2023.02.20 00:37:00 ERROR issues while parsing: /home/dos65/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/epfl/scala/bloop-maven-plugin/2.0.0/bloop-maven-plugin-2.0.0-sources.jarjava.nio.file.NoSuchFileException: /META-INF/maven/ch.epfl.scala
	at jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:702)
	at jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:815)
	at jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:252)
	at java.nio.file.Files.newByteChannel(Files.java:371)
	at java.nio.file.Files.newByteChannel(Files.java:422)
	at java.nio.file.Files.readAllBytes(Files.java:3206)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.SymbolIndexBucket.indexSource(SymbolIndexBucket.scala:126)
	at scala.meta.internal.mtags.SymbolIndexBucket.addSourceFile(SymbolIndexBucket.scala:105)
	at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$addSourceJar$2(SymbolIndexBucket.scala:67)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$addSourceJar$1(SymbolIndexBucket.scala:65)
	at scala.meta.internal.io.PlatformFileIO$.withJarFileSystem(PlatformFileIO.scala:87)
	at scala.meta.internal.io.FileIO$.withJarFileSystem(FileIO.scala:44)
	at scala.meta.internal.mtags.SymbolIndexBucket.addSourceJar(SymbolIndexBucket.scala:63)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$addSourceJar$2(OnDemandSymbolIndex.scala:83)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.tryRun(OnDemandSymbolIndex.scala:128)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.addSourceJar(OnDemandSymbolIndex.scala:82)
	at scala.meta.internal.metals.Indexer.addSourceJarSymbols(Indexer.scala:593)
	at scala.meta.internal.metals.Indexer.$anonfun$indexDependencySources$5(Indexer.scala:448)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
	at scala.meta.internal.metals.Indexer.$anonfun$indexDependencySources$1(Indexer.scala:439)
	at scala.meta.internal.metals.Indexer.$anonfun$indexDependencySources$1$adapted(Indexer.scala:438)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at scala.meta.internal.metals.Indexer.indexDependencySources(Indexer.scala:438)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$22(Indexer.scala:358)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$21(Indexer.scala:351)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$21$adapted(Indexer.scala:347)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.Indexer.indexWorkspace(Indexer.scala:347)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$2(Indexer.scala:147)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$1(Indexer.scala:147)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

### Expected behavior

No error

### Operating system

Linux

### Editor/Extension

None

### Version of Metals

0.11.10+155-4d6ef86a-SNAPSHOT

**Comment by tgodzik** [comment]
Looks like something is wrong with that source jar file that we publish along the maven plugin :thinking: Any idea what is going on @ckipp01 ?

**Comment by dos65** [comment]
Hm, I took a look at this jar file and it seems that everything is fine with it

**Comment by tgodzik** [comment]
Ach! I think I know the issue, did you check the newest Metals? We treat anything `.scala` as a file, but I added a fix that should help with that.

**Comment by tgodzik** [comment]
Ok, I see the issue, The fix should be quick.

**Comment by ckipp01** [comment]
> Looks like something is wrong with that source jar file that we publish along the maven plugin 🤔 Any idea what is going on @ckipp01 ?

Ah yikes, no I didn't notice this! I see you found the issue, but if it does happen to be something with the Maven plugin, just let me know!
