### ISSUE TITLE
Method not found: window/showMessageRequest when using Helix.

### ISSUE THREAD

**Issue by Renkai** [scalameta/metals#5114]
### Describe the bug

1. create a new project, for example, `sbt new scala/scala-seed.g8`
2. change the working directory to the project, open with `hx .`
3. metals started, these logs were shown, and metals not respond to commands.

```
2023.04.03 21:19:23 INFO  Started: Metals version 0.11.11 in workspace '/Users/renkaige/renkai-lab/scala-seed-project' for client helix 23.03 (3cf03723).[0m
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/renkaige/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/outr/scribe-slf4j_2.13/3.11.0/scribe-slf4j_2.13-3.11.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
2023.04.03 21:19:23 INFO  time: initialize in 0.58s[0m
2023.04.03 21:19:23 WARN  Build server is not auto-connectable.[0m
2023.04.03 21:19:23 WARN  no build target for: /Users/renkaige/renkai-lab/scala-seed-project/project/Dependencies.scala[0m
2023.04.03 21:19:23 WARN  no build target for: /Users/renkaige/renkai-lab/scala-seed-project/src/main/scala/example/Hello.scala[0m
2023.04.03 21:19:23 INFO  Selected port 5031[0m
Apr 03, 2023 9:19:23 PM io.undertow.Undertow start
INFO: starting server: Undertow - 2.2.20.Final
Apr 03, 2023 9:19:23 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.8.8.Final
2023.04.03 21:19:23 ERROR Unexpected error initializing server: 
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Method not found: window/showMessageRequest
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
[0m
Apr 03, 2023 9:19:23 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.8.8.Final
Apr 03, 2023 9:19:24 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.1.0.Final
2023.04.03 21:19:23 INFO  Started Metals http server at http://127.0.0.1:5031[0m
2023.04.03 21:19:26 INFO  no build target found for /Users/renkaige/renkai-lab/scala-seed-project/.metals/readonly/dependencies/scala-library-2.13.10-sources.jar/scala/Predef.scala. Using presentation compiler with project's scala-library version: 3.2.2[0m
Apr 03, 2023 9:19:28 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: assertion failed

```

### Expected behavior

No error logs and have response to commands like `new-scala-file`

### Operating system

macOS

### Editor/Extension

Other

### Version of Metals

v0.11.11

### Extra context or search terms

`hx` is [helix](https://github.com/helix-editor/helix/)

**Comment by ckipp01** [comment]
Hey @Renkai! Thanks for the report! I believe the reason you're seeing this is because many of the requests Metals uses need the client to have `window/showMessageRequest` implemented. This is currently [not implemented](https://github.com/helix-editor/helix/issues/4699) in Helix.
