### ISSUE TITLE
scala.meta.internal.pc.CompilerAccess handleError

### ISSUE THREAD

**Issue by soronpo** [scalameta/metals#5217]
### Describe the bug

Not sure how to recreate this error.
Hoping the stack trace makes sense.
```
May 11, 2023 2:06:38 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: C:\Users\xxxx\IdeaProjects\Ad-Astra\.bloop\root\bloop-bsp-clients-classes\classes-Metals-4KU4enPNQnuAxXRLZ3JLMQ==\lfsr$package.class
java.nio.file.NoSuchFileException: C:\Users\xxxx\IdeaProjects\Ad-Astra\.bloop\root\bloop-bsp-clients-classes\classes-Metals-4KU4enPNQnuAxXRLZ3JLMQ==\lfsr$package.class
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1843)
	at java.base/java.nio.file.Files.getLastModifiedTime(Files.java:2394)
	at dotty.tools.io.Path.lastModified(Path.scala:196)
	at dotty.tools.io.PlainFile.lastModified(PlainFile.scala:84)
	at dotty.tools.dotc.core.SymDenotations$PackageClassDenotation.$anonfun$14(SymDenotations.scala:2500)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.collection.immutable.Set$Set2.map(Set.scala:183)
	at dotty.tools.dotc.core.SymDenotations$PackageClassDenotation.dropStale$1(SymDenotations.scala:2500)
	at dotty.tools.dotc.core.SymDenotations$PackageClassDenotation.recur$5(SymDenotations.scala:2474)
	at dotty.tools.dotc.core.SymDenotations$PackageClassDenotation.computeMembersNamed(SymDenotations.scala:2533)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.membersNamed(SymDenotations.scala:2083)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:2134)
	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:689)
	at dotty.tools.dotc.core.Types$Type.goThis$1(Types.scala:804)
	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:706)
	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:872)
	at dotty.tools.dotc.core.Types$Type.memberBasedOnFlags(Types.scala:672)
	at dotty.tools.dotc.core.Types$Type.member(Types.scala:656)
	at dotty.tools.dotc.core.Types$Type.allMembers$$anonfun$1(Types.scala:1013)
	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:15)
	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:10)
	at dotty.tools.dotc.core.Types$Type.memberDenots$$anonfun$1(Types.scala:918)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.BitmapIndexedSetNode.foreach(HashSet.scala:937)
	at scala.collection.immutable.BitmapIndexedSetNode.foreach(HashSet.scala:944)
	at scala.collection.immutable.HashSet.foreach(HashSet.scala:944)
	at dotty.tools.dotc.core.Types$Type.memberDenots(Types.scala:918)
	at dotty.tools.dotc.core.Types$Type.allMembers(Types.scala:1013)
	at scala.meta.internal.pc.IndexedContext$.accesibleMembers$1(IndexedContext.scala:149)
	at scala.meta.internal.pc.IndexedContext$.scala$meta$internal$pc$IndexedContext$$$extractNames(IndexedContext.scala:207)
	at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:99)
	at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
	at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
	at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
	at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
	at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
	at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
	at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
	at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
	at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
	at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
	at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
	at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
	at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
	at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
	at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
	at scala.meta.internal.pc.PcDefinitionProvider.definitions(PcDefinitionProvider.scala:53)
	at scala.meta.internal.pc.PcDefinitionProvider.definitions(PcDefinitionProvider.scala:33)
```

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

**Comment by tgodzik** [comment]
Thanks for reporting! Did you maybe get anything created in `.metals/reports` ? We try to save some additional data about exceptions there. If not we might need to add even more there.

**Comment by tgodzik** [comment]
> > Did you maybe get anything created in `.metals/reports` ?
> 
> I don't see any `reports` folder. If it's not deleted automatically than nothing was created.

most likely nothing got created then. We need to add something there, thanks for checking!

**Comment by tgodzik** [comment]
We should now properly save a report, though it might be hard to reproduce it. Let us know if this happens again at any point and if there is a report in `/.metals/reprots`
