### ISSUE TITLE
InvalidPathException: Trailing char < > at index 0:

### ISSUE THREAD

**Issue by MichalPorazko** [scalameta/metals#5230]
```
2023.05.15 20:13:46 WARN  No build session currently active to reload.
2023.05.15 20:14:17 WARN  No build session currently active to reload.
2023.05.15 20:14:21 INFO  Attempting to connect to the build server...
2023.05.15 20:14:21 INFO  Running BSP server List(C:\JDK\jdk-11.0.19.7-hotspot/bin/java, -Xms100m, -Xmx100m, -classpath, C:\Program Files (x86)\sbt\\bin\sbt-launch.jar, xsbt.boot.Boot, -bsp, --sbt-launch-jar=C:\Program%20Files%20(x86)\sbt\\bin\sbt-launch.jar)
2023.05.15 20:14:21 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\jpora\OneDrive\Pulpit\Michal\Scala\ToDoList\.metals\bsp.trace.json or C:\Users\jpora\AppData\Local\scalameta\metals\cache\bsp.trace.json
2023.05.15 20:14:22 INFO  time: Connected to build server in 1.3s
2023.05.15 20:14:22 INFO  Connected to Build server: sbt v1.6.1
2023.05.15 20:14:22 INFO  Processing workspace/buildTargets
2023.05.15 20:14:22 INFO  Processing buildTarget/scalacOptions
2023.05.15 20:14:22 INFO  Processing buildTarget/sources
2023.05.15 20:14:22 INFO  Processing buildTarget/dependencySources
2023.05.15 20:14:23 INFO  time: Imported build in 0.71s
2023.05.15 20:14:23 INFO  Disconnecting from sbt session...
2023.05.15 20:14:23 ERROR Failed to connect with build server, no functionality will work.
java.nio.file.InvalidPathException: Trailing char < > at index 0:  
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:191)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.nio.file.Path.of(Path.java:147)
	at java.nio.file.Paths.get(Paths.java:69)
	at scala.meta.io.AbsolutePath$.apply(AbsolutePath.scala:60)
	at scala.meta.internal.metals.JdkSources$.$anonfun$candidates$2(JdkSources.scala:45)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.meta.internal.metals.JdkSources$.candidates(JdkSources.scala:44)
	at scala.meta.internal.metals.JdkSources$.apply(JdkSources.scala:20)
	at scala.meta.internal.metals.doctor.ProblemResolver.javaSourcesProblem$1(ProblemResolver.scala:243)
	at scala.meta.internal.metals.doctor.ProblemResolver.$anonfun$findProblem$5(ProblemResolver.scala:311)
	at scala.Option.orElse(Option.scala:477)
	at scala.meta.internal.metals.doctor.ProblemResolver.findProblem(ProblemResolver.scala:311)
	at scala.meta.internal.metals.doctor.ProblemResolver.$anonfun$problemMessage$1(ProblemResolver.scala:69)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.meta.internal.metals.doctor.ProblemResolver.problemMessage(ProblemResolver.scala:68)
	at scala.meta.internal.metals.doctor.Doctor.check(Doctor.scala:168)
	at scala.meta.internal.metals.MetalsLspService.$anonfun$connectToNewBuildServer$3(MetalsLspService.scala:2540)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$13(Indexer.scala:307)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.indexWorkspace(Indexer.scala:306)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$2(Indexer.scala:147)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$1(Indexer.scala:147)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)

2023.05.15 20:14:23 INFO  Shut down connection with build server.
```

### Expected behaviour:

**Operating system:**
Windows 10

**Java version:**
11.0.19

**Editor/extension:**
Visual Studio Code v1.78.1

**Metals version:**
0.11.12

### Workspace information:

 - **Scala versions:** 3.1.0; 2.12.15
 - **Build server:** Disconnected: sbt
 - **All build tools in workspace:** Bloop; sbt

**Comment by tgodzik** [comment]
Thanks for reporting! Trying a fix in https://github.com/scalameta/metals/pull/5240

**Comment by tgodzik** [comment]
Is it possible that there is an extra space in your configuration somewhere? `Trailing char < > at index 0:` seems to indicate that. Trimming and adding it into Try should help, but I wanted to make sure
