### ISSUE TITLE
java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by soronpo** [scalameta/metals#5231]
### Describe the bug

Not sure how to replicate this.
```scala
2023.05.15 21:59:47 ERROR searching for `dfhdl/ops$package.printCodeString().` failed
java.io.EOFException: Unexpected end of ZLIB input stream
	at jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2143)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.InputStream.readNBytes(InputStream.java:409)
	at java.io.InputStream.readAllBytes(InputStream.java:346)
	at jdk.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:967)
	at jdk.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:864)
	at jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:238)
	at java.nio.file.Files.newByteChannel(Files.java:375)
	at java.nio.file.Files.newByteChannel(Files.java:426)
	at java.nio.file.Files.readAllBytes(Files.java:3272)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.ScalametaCommonEnrichments$XtensionAbsolutePath.toInput(ScalametaCommonEnrichments.scala:380)
	at scala.meta.internal.mtags.SymbolIndexBucket.addMtagsSourceFile(SymbolIndexBucket.scala:248)
	at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$query0$1(SymbolIndexBucket.scala:184)
	at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$query0$1$adapted(SymbolIndexBucket.scala:184)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
	at scala.meta.internal.mtags.SymbolIndexBucket.query0(SymbolIndexBucket.scala:184)
	at scala.meta.internal.mtags.SymbolIndexBucket.query(SymbolIndexBucket.scala:158)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$findSymbolDefinition$1(OnDemandSymbolIndex.scala:139)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.findSymbolDefinition(OnDemandSymbolIndex.scala:139)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.definition(OnDemandSymbolIndex.scala:46)
	at scala.meta.internal.metals.Docstrings.indexSymbol(Docstrings.scala:104)
	at scala.meta.internal.metals.Docstrings.documentation(Docstrings.scala:44)
	at scala.meta.internal.metals.MetalsSymbolSearch.documentation(MetalsSymbolSearch.scala:42)
	at scala.meta.internal.mtags.MtagsEnrichments$.symbolDocumentation(MtagsEnrichments.scala:189)
	at scala.meta.internal.pc.CompletionItemResolver$.resolve(CompletionItemResolver.scala:27)
	at scala.meta.internal.pc.ScalaPresentationCompiler.completionItemResolve$$anonfun$1(ScalaPresentationCompiler.scala:185)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
	at scala.meta.internal.pc.CompilerAccess.withNonInterruptableCompiler$$anonfun$1(CompilerAccess.scala:125)
	at scala.meta.internal.pc.CompilerAccess.onCompilerJobQueue$$anonfun$1(CompilerAccess.scala:197)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(Thread.java:831)
```

Checked the reports folder and found:
```
Symbol: dfhdl/ops$package.printCodeString().
Error message: dfhdl/ops$package.printCodeString().
Error: scala.meta.internal.mtags.IndexingExceptions$InvalidSymbolException: dfhdl/ops$package.printCodeString().
```

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

**Comment by tgodzik** [comment]
Thanks for reporting! This looks like an issue with a bad jar, we should probably make sure that issues like that are isolated. Is that an existing open source library maybe or some internal jar that this failed on?

**Comment by soronpo** [comment]
This is while prototyping a library that is being built locally as a snapshot and used in VSCode with metals for testing. Maybe something in this type of workflow causes this kind of exception.

**Comment by tgodzik** [comment]
> This is while prototyping a library that is being built locally as a snapshot and used in VSCode with metals for testing. Maybe something in this type of workflow causes this kind of exception.

Maybe the jar was being written and read at the same time?
