### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by phdoerfler** [scalameta/metals#5250]
### Describe the bug

I'm not at all certain of what I did the moment the crash happened, but I'm sharing this in the hopes that this log is useful anyway. I'm using metals 0.11.12 with neovim and vs code simultaneously and sbt running separately.

```
May 21, 2023 8:12:26 AM scala.meta.internal.pc.CompilerAccess retryWithCleanCompiler
INFO: compiler crashed due to an error in the Scala compiler, retrying with new compiler instance.
May 21, 2023 8:12:26 AM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: 
  Can't rename a package object to `package`
     while compiling: file:///Users/phi/Documents/workspace/Scala/spiht/build.sbt
        during phase: globalPhase=<no phase>, enteringPhase=parser
     library version: version 2.12.17
    compiler version: version 2.12.17
  reconstructed args: -deprecation -Wconf:cat=unused-nowarn:s -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws -classpath A_REALLY_LONG_CLASSPATH -Xplugin-require:semanticdb -Xsource:3.0.0 -Yrangepos -Ymacro-expand:discard -Ycache-plugin-class-loader:last-modified -Ypresentation-any-thread

  last tree to typer: TypeTree(object Main)
       tree position: line 1 of file:///Users/phi/Documents/workspace/Scala/spiht/build.sbt
            tree tpe: Main.type
              symbol: object Main
   symbol definition: class Main extends AnyRef (a ModuleClassSymbol)
      symbol package: <empty>
       symbol owners: object Main
           call site: <none> in <none>

== Source file context for tree position ==

     1 import _root_.scala.xml.{TopScope=>$scope}
     2 import _root_.sbt._
     3 import _root_.sbt.Keys._
     4 import _root_.sbt.nio.Keys._
     5 import _root_.sbt.ScriptedPlugin.autoImport._, _root_.sbt.plugins.JUnitXmlReportPlugin.autoImport._, _root_.sbt.plugins.MiniDependencyTreePlugin.autoImport._, _root_.bloop.integrations.sbt.BloopPlugin.autoImport._, _root_.com.timushev.sbt.updates.UpdatesPlugin.autoImport._
     6 import _root_.sbt.plugins.IvyPlugin, _root_.sbt.plugins.JvmPlugin, _root_.sbt.plugins.CorePlugin, _root_.sbt.ScriptedPlugin, _root_.sbt.plugins.SbtPlugin, _root_.sbt.plugins.SemanticdbPlugin, _root_.sbt.plugins.JUnitXmlReportPlugin, _root_.sbt.plugins.Giter8TemplatePlugin, _root_.sbt.plugins.MiniDependencyTreePlugin, _root_.bloop.integrations.sbt.BloopPlugin, _root_.com.timushev.sbt.updates.UpdatesPlugin
     7 val scala3Version = "3.2.2"
scala.reflect.internal.FatalError: 
  Can't rename a package object to `package`
     while compiling: file:///Users/phi/Documents/workspace/Scala/spiht/build.sbt
        during phase: globalPhase=<no phase>, enteringPhase=parser
     library version: version 2.12.17
    compiler version: version 2.12.17
  reconstructed args: -deprecation -Wconf:cat=unused-nowarn:s -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws -classpath A_REALLY_LONG_CLASSPATH -Xplugin-require:semanticdb -Xsource:3.0.0 -Yrangepos -Ymacro-expand:discard -Ycache-plugin-class-loader:last-modified -Ypresentation-any-thread

  last tree to typer: TypeTree(object Main)
       tree position: line 1 of file:///Users/phi/Documents/workspace/Scala/spiht/build.sbt
            tree tpe: Main.type
              symbol: object Main
   symbol definition: class Main extends AnyRef (a ModuleClassSymbol)
      symbol package: <empty>
       symbol owners: object Main
           call site: <none> in <none>

== Source file context for tree position ==

     1 import _root_.scala.xml.{TopScope=>$scope}
     2 import _root_.sbt._
     3 import _root_.sbt.Keys._
     4 import _root_.sbt.nio.Keys._
     5 import _root_.sbt.ScriptedPlugin.autoImport._, _root_.sbt.plugins.JUnitXmlReportPlugin.autoImport._, _root_.sbt.plugins.MiniDependencyTreePlugin.autoImport._, _root_.bloop.integrations.sbt.BloopPlugin.autoImport._, _root_.com.timushev.sbt.updates.UpdatesPlugin.autoImport._
     6 import _root_.sbt.plugins.IvyPlugin, _root_.sbt.plugins.JvmPlugin, _root_.sbt.plugins.CorePlugin, _root_.sbt.ScriptedPlugin, _root_.sbt.plugins.SbtPlugin, _root_.sbt.plugins.SemanticdbPlugin, _root_.sbt.plugins.JUnitXmlReportPlugin, _root_.sbt.plugins.Giter8TemplatePlugin, _root_.sbt.plugins.MiniDependencyTreePlugin, _root_.bloop.integrations.sbt.BloopPlugin, _root_.com.timushev.sbt.updates.UpdatesPlugin
     7 val scala3Version = "3.2.2"
	at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
	at scala.reflect.internal.Symbols$PackageObjectClassSymbol.setName(Symbols.scala:3497)
	at scala.reflect.internal.Symbols$PackageObjectClassSymbol.setName(Symbols.scala:3491)
	at scala.meta.internal.pc.MetalsGlobal.backtickify(MetalsGlobal.scala:266)
	at scala.meta.internal.pc.MetalsGlobal.backtickifiedSymbol$1(MetalsGlobal.scala:286)
	at scala.meta.internal.pc.MetalsGlobal.loop$1(MetalsGlobal.scala:357)
	at scala.meta.internal.pc.MetalsGlobal.loop$1(MetalsGlobal.scala:356)
	at scala.meta.internal.pc.MetalsGlobal.shortType(MetalsGlobal.scala:476)
	at scala.meta.internal.pc.completions.Completions.infoString(Completions.scala:264)
	at scala.meta.internal.pc.completions.Completions.infoString$(Completions.scala:247)
	at scala.meta.internal.pc.MetalsGlobal.infoString(MetalsGlobal.scala:33)
	at scala.meta.internal.pc.completions.Completions.detailString(Completions.scala:283)
	at scala.meta.internal.pc.completions.Completions.detailString$(Completions.scala:277)
	at scala.meta.internal.pc.MetalsGlobal.detailString(MetalsGlobal.scala:33)
	at scala.meta.internal.pc.completions.Completions$$anon$1.compare(Completions.scala:235)
	at scala.meta.internal.pc.completions.Completions$$anon$1.compare(Completions.scala:175)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:239)
	at java.base/java.util.Arrays.sort(Arrays.java:1441)
	at scala.collection.SeqLike.sorted(SeqLike.scala:659)
	at scala.collection.SeqLike.sorted$(SeqLike.scala:647)
	at scala.collection.AbstractSeq.sorted(Seq.scala:45)
	at scala.meta.internal.pc.CompletionProvider.completions(CompletionProvider.scala:72)

2023.05.21 08:12:30 INFO  skipping build import with status 'Installed'[0m
```

### Expected behavior

I expect no crash

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like this is an issue with adding backticks:
```
	at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
	at scala.reflect.internal.Symbols$PackageObjectClassSymbol.setName(Symbols.scala:3497)
	at scala.reflect.internal.Symbols$PackageObjectClassSymbol.setName(Symbols.scala:3491)
	at scala.meta.internal.pc.MetalsGlobal.backtickify(MetalsGlobal.scala:266)
	at scala.meta.internal.pc.MetalsGlobal.backtickifiedSymbol$1(MetalsGlobal.scala:286)
	at scala.meta.internal.pc.MetalsGlobal.loop$1(MetalsGlobal.scala:357)
	at scala.meta.internal.pc.MetalsGlobal.loop$1(MetalsGlobal.scala:356)
	at scala.meta.internal.pc.MetalsGlobal.shortType(MetalsGlobal.scala:476)
	at scala.meta.internal.pc.completions.Completions.infoString(Completions.scala:264)
	at scala.meta.internal.pc.completions.Completions.infoString$(Completions.scala:247)
	at scala.meta.internal.pc.MetalsGlobal.infoString(MetalsGlobal.scala:33)
	at scala.meta.internal.pc.completions.Completions.detailString(Completions.scala:283)
	at scala.meta.internal.pc.completions.Completions.detailString$(Completions.scala:277)
	at scala.meta.internal.pc.MetalsGlobal.detailString(MetalsGlobal.scala:33)
	at scala.meta.internal.pc.completions.Completions$$anon$1.compare(Completions.scala:235)
	at scala.meta.internal.pc.completions.Completions$$anon$1.compare(Completions.scala:175)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:239)
	at java.base/java.util.Arrays.sort(Arrays.java:1441)
	at scala.collection.SeqLike.sorted(SeqLike.scala:659)
	at scala.collection.SeqLike.sorted$(SeqLike.scala:647)
	at scala.collection.AbstractSeq.sorted(Seq.scala:45)
	at scala.meta.internal.pc.CompletionProvider.completions(CompletionProvider.scala:72)
```
@kasiaMarek any chance you could take a look at it?

**Comment by kasiaMarek** [comment]
Yeah, I think I know why this happens.
