### ISSUE TITLE
Multiple `assertion failed: asTerm called on not-a-Term val <none>` on a fresh clone of the Dotty codebase

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#5268]
### Describe the bug

I'm assuming this might actually need to be an upstream fix, I'm throwing it here for now. On a fresh clone of Dotty doing the following:

- `git clone git@github.com:lampepfl/dotty.git`
- `cd dotty`
- Open the `build.sbt` and import the build
- Once imported jump to `messages.scala`
- See the following in the logs

```
exception caught when loading trait Deprecated: java.lang.AssertionError: assertion failed: asTerm called on not-a-Term val <none>
May 24, 2023 7:40:41 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: assertion failed: asTerm called on not-a-Term val <none>
java.lang.AssertionError: assertion failed: asTerm called on not-a-Term val <none>
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.Symbols$Symbol.asTerm(Symbols.scala:169)
        at dotty.tools.dotc.ast.tpd$.New(tpd.scala:512)
        at dotty.tools.dotc.core.Annotations$Annotation$.apply(Annotations.scala:211)
        at dotty.tools.dotc.core.Annotations$Annotation$.apply(Annotations.scala:205)
        at dotty.tools.dotc.core.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:767)
        at dotty.tools.dotc.core.classfile.ClassfileParser.parseAttributes$$anonfun$1(ClassfileParser.scala:825)
        at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.scala:18)
        at scala.collection.immutable.Range.foreach(Range.scala:190)
        at dotty.tools.dotc.core.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:825)
        at dotty.tools.dotc.core.classfile.ClassfileParser.parseMember(ClassfileParser.scala:256)
        at dotty.tools.dotc.core.classfile.ClassfileParser.parseClass$$anonfun$2(ClassfileParser.scala:207)
        at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.scala:18)
        at scala.collection.immutable.Range.foreach(Range.scala:190)
        at dotty.tools.dotc.core.classfile.ClassfileParser.parseClass(ClassfileParser.scala:207)
        at dotty.tools.dotc.core.classfile.ClassfileParser.$anonfun$1(ClassfileParser.scala:87)
        at dotty.tools.dotc.core.classfile.ClassfileParser.run(ClassfileParser.scala:82)
        at dotty.tools.dotc.core.ClassfileLoader.load(SymbolLoaders.scala:412)
        at dotty.tools.dotc.core.ClassfileLoader.doComplete(SymbolLoaders.scala:407)
        at dotty.tools.dotc.core.SymbolLoader.complete(SymbolLoaders.scala:341)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:174)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeOnce(SymDenotations.scala:382)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.isAbsent(SymDenotations.scala:612)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.isAccessibleFrom(SymDenotations.scala:922)
        at scala.meta.internal.pc.IndexedContext$.accessibleSymbols$1$$anonfun$1(IndexedContext.scala:145)
        at scala.collection.immutable.List.filter(List.scala:559)
        at scala.meta.internal.pc.IndexedContext$.accessibleSymbols$1(IndexedContext.scala:145)
        at scala.meta.internal.pc.IndexedContext$.allAccessibleSymbols$1(IndexedContext.scala:163)
        at scala.meta.internal.pc.IndexedContext$.fromImportInfo$1(IndexedContext.scala:184)
        at scala.meta.internal.pc.IndexedContext$.scala$meta$internal$pc$IndexedContext$$$extractNames(IndexedContext.scala:201)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:99)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
        at scala.meta.internal.pc.IndexedContext$LazyWrapper.<init>(IndexedContext.scala:98)
        at scala.meta.internal.pc.IndexedContext$.apply(IndexedContext.scala:87)
        at scala.meta.internal.pc.HoverProvider$.hover(HoverProvider.scala:39)

2023.05.24 19:40:42 INFO  time: compiled scala3-interfaces in 1.99s
java.lang.AssertionError: assertion failed: asTerm called on not-a-Term val <none> while typechecking /Users/ckipp/Documents/scratch-workspace/dotty/compiler/src/dotty/tools/dotc/reporting/messages.scala
May 24, 2023 7:40:44 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: assertion failed: asTerm called on not-a-Term val <none>
java.lang.AssertionError: assertion failed: asTerm called on not-a-Term val <none>
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.Symbols$Symbol.asTerm(Symbols.scala:169)
        at dotty.tools.dotc.ast.tpd$.New(tpd.scala:512)
        at dotty.tools.dotc.core.Annotations$Annotation$Child$.makeChildLater$1(Annotations.scala:231)
        at dotty.tools.dotc.core.Annotations$Annotation$Child$.later$$anonfun$1(Annotations.scala:234)
        at dotty.tools.dotc.core.Annotations$LazyAnnotation.tree(Annotations.scala:140)
        at dotty.tools.dotc.core.Annotations$Annotation$Child$.unapply(Annotations.scala:242)
        at dotty.tools.dotc.typer.Namer.insertInto$1(Namer.scala:477)
        at dotty.tools.dotc.typer.Namer.addChild(Namer.scala:488)
        at dotty.tools.dotc.typer.Namer$Completer.register$1(Namer.scala:899)
        at dotty.tools.dotc.typer.Namer$Completer.registerIfChild$$anonfun$1(Namer.scala:908)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.typer.Namer$Completer.registerIfChild(Namer.scala:908)
        at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:811)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:174)
        at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:187)
        at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:189)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:390)
        at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2869)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2894)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2990)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3084)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3130)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2562)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2916)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2920)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2990)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3084)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3130)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2692)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2961)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3111)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3130)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2692)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2961)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3111)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3130)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2692)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2961)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3174)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:44)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:54)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:437)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:54)
        at dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:88)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:88)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:247)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:263)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:271)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:280)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:280)
        at dotty.tools.dotc.Run.compileSources(Run.scala:195)
        at dotty.tools.dotc.interactive.InteractiveDriver.run(InteractiveDriver.scala:165)
        at scala.meta.internal.pc.MetalsDriver.run(MetalsDriver.scala:45)
        at scala.meta.internal.pc.PcCollector.<init>(PcCollector.scala:42)
        at scala.meta.internal.pc.PcDocumentHighlightProvider.<init>(PcDocumentHighlightProvider.scala:16)
```

### Expected behavior

No exceptions

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.12+73-f470c9c8-SNAPSHOT

**Comment by tgodzik** [comment]
It's hard to say what happened, we could add Try in those cases, but that will only work around the issue, could you report it upstream also?

**Comment by tgodzik** [comment]
I am fixing the first one in https://github.com/scalameta/metals/pull/5271 but the second one even if we add Try there is nothing we can do, so would need to be fixed in the compiler (unless we're doing something completely wrong)

**Comment by tgodzik** [comment]
Thanks!
