### ISSUE TITLE
Cannot invoke "scala.meta.pc.PresentationCompiler.restart()" because "compiler" is null

### ISSUE THREAD

**Issue by ghostbuster91** [scalameta/metals#5277]
### Describe the bug

I don't have a way to reproduce it for now. It happens very rarely when I reimport the project. I will update this post with any additional information that I will discover. 

```
May 26, 2023 6:07:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1030
May 26, 2023 6:07:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1031
May 26, 2023 6:07:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1032
May 26, 2023 6:07:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1033
May 26, 2023 6:07:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1034
May 26, 2023 6:07:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1036
May 26, 2023 6:07:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1037
2023.05.26 18:07:40 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /xxx/.metals/bsp.trace.json or /xxx/.cache/metals/bsp.trace.json
2023.05.26 18:07:40 INFO  Attempting to connect to the build server...
2023.05.26 18:07:40 INFO  Bloop uses /nix/store/yhgxqd2jcp4jy6s82cfkzjlzjrj6rxzi-openjdk-19.0.2+7 defined at /home/kghost/.bloop/bloop.json
2023.05.26 18:07:40 INFO  Attempting to connect to the build server...
2023.05.26 18:07:40 INFO  Bloop uses /nix/store/yhgxqd2jcp4jy6s82cfkzjlzjrj6rxzi-openjdk-19.0.2+7 defined at /home/kghost/.bloop/bloop.json
2023.05.26 18:07:40 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /xxx/project/project/.metals/bsp.trace.json or /home/kghost/.cache/metals/bsp.trac
e.json
2023.05.26 18:07:40 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /xxx/project/.metals/bsp.trace.json or /home/kghost/.cache/metals/bsp.trace.json
2023.05.26 18:07:40 INFO  time: Connected to build server in 0.12s
2023.05.26 18:07:40 INFO  Connected to Build server: Bloop v1.5.6
2023.05.26 18:07:41 INFO  time: indexed workspace in 1.39s
2023.05.26 18:07:41 INFO  compiling xxx (6 java sources)
May 26, 2023 6:07:43 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "build/taskFinish",
  "params": {
    "taskId": {
      "id": "1"
    },
    "eventTime": 1685117261912,
    "message": "Compiled \u0027codegen\u0027",
    "status": 1,
    "dataKind": "compile-report",
    "data": {
      "target": {
        "uri": "file:/xxx/codegen/?id\u003dcodegen"
      },
      "errors": 0,
      "warnings": 0,
      "isNoOp": true,
      "isLastCycle": true,
      "clientDir": "file:///xxx/.bloop/codegen/bloop-bsp-clients-classes/classes-Metals-rzehBIAGTNa7J7eDWU5vqA\u003d\u003d/",
      "analysisOut": "file:///home/xxx/.bloop/codegen/codegen-analysis.bin"
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
        ... 11 more
Caused by: java.lang.NullPointerException: Cannot invoke "scala.meta.pc.PresentationCompiler.restart()" because "compiler" is null
        at scala.meta.internal.metals.Compilers.$anonfun$didCompile$3(Compilers.scala:257)
        at scala.meta.internal.metals.Compilers.$anonfun$didCompile$3$adapted(Compilers.scala:255)
        at scala.Option.foreach(Option.scala:437)
        at scala.meta.internal.metals.Compilers.$anonfun$didCompile$2(Compilers.scala:255)
        at scala.meta.internal.metals.Compilers.$anonfun$didCompile$2$adapted(Compilers.scala:254)
        at scala.collection.mutable.HashSet$Node.foreach(HashSet.scala:435)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:361)
        at scala.meta.internal.metals.Compilers.didCompile(Compilers.scala:254)
        at scala.meta.internal.metals.MetalsLspService.$anonfun$buildClient$1(MetalsLspService.scala:417)
        at scala.meta.internal.metals.MetalsLspService.$anonfun$buildClient$1$adapted(MetalsLspService.scala:415)
        at scala.meta.internal.metals.clients.language.ForwardingMetalsBuildClient.$anonfun$buildTaskFinish$2(ForwardingMetalsBuildClient.scala:165)
        at scala.Option.foreach(Option.scala:437)
        at scala.meta.internal.metals.clients.language.ForwardingMetalsBuildClient.$anonfun$buildTaskFinish$1(ForwardingMetalsBuildClient.scala:162)
        at scala.meta.internal.metals.clients.language.ForwardingMetalsBuildClient.$anonfun$buildTaskFinish$1$adapted(ForwardingMetalsBuildClient.scala:161)
        at scala.Option.foreach(Option.scala:437)
        at scala.meta.internal.metals.clients.language.ForwardingMetalsBuildClient.buildTaskFinish(ForwardingMetalsBuildClient.scala:161)
        ... 15 more

2023.05.26 18:07:43 INFO  compiling xxx (1 java source)
2023.05.26 18:07:43 INFO  compiling xxx (3 java sources)
2023.05.26 18:07:43 WARN  javac exited with exit code 1
2023.05.26 18:07:43 INFO  time: compiled xxx in 4ms
2023.05.26 18:07:43 WARN  javac exited with exit code 1
2023.05.26 18:07:43 INFO  time: compiled xxx in 6ms
2023.05.26 18:07:43 WARN  javac exited with exit code 1
2023.05.26 18:07:43 INFO  time: compiled xxx in 2.04s
2023.05.26 18:11:28 WARN  Using indexes to guess the definition of xxx
2023.05.26 18:11:28 INFO  compiling xxx (6 java sources)
2023.05.26 18:11:28 WARN  javac exited with exit code 1
2023.05.26 18:11:28 INFO  time: compiled xxx in 0.92s
```

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.12

**Comment by tgodzik** [comment]
@ghostbuster91 Let us know if you encounter this issue again!

**Comment by ghostbuster91** [comment]
@tgodzik Sure thing! Maybe we can close it as the potential fix has been merged? If I ever run into the same issue again, we can always reopen. Wdyt?

**Comment by tgodzik** [comment]
Sure!
