### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to trigger completion

### ISSUE THREAD

**Issue by zhranklin** [scalameta/metals#5308]
### Describe the bug

I'm using scala-cli, and I met an ArrayIndexOutOfBoundsException exception when trying to trigger code completion.

```
6月 05, 2023 10:08:25 上午 scala.meta.internal.pc.CompilerAccess handleError
严重: Index -1 out of bounds for length 709
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 709
	at dotty.tools.dotc.util.SourceFile.lineToOffset(SourceFile.scala:159)
	at scala.meta.internal.pc.AutoImports$.$anonfun$11(AutoImports.scala:353)
	at scala.Option.getOrElse(Option.scala:201)
	at scala.meta.internal.pc.AutoImports$.forScript$1$$anonfun$1(AutoImports.scala:353)
	at scala.Option.map(Option.scala:242)
	at scala.meta.internal.pc.AutoImports$.forScript$1(AutoImports.scala:355)
	at scala.meta.internal.pc.AutoImports$.autoImportPosition(AutoImports.scala:370)
	at scala.meta.internal.pc.AutoImports$.generator(AutoImports.scala:99)
	at scala.meta.internal.pc.completions.CompletionProvider.completions(CompletionProvider.scala:70)
```

### Expected behavior

popup the completion

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v0.11.12

### Extra context or search terms

I've found the code that cause the exception:

https://github.com/scalameta/metals/blob/f10f32694ed1a15d0e7e73129bda9e9984a4707f/mtags/src/main/scala-3/scala/meta/internal/pc/AutoImports.scala#L351-L353

And I just fixed it in an ugly way:

```scala
           scriptOffset.orElse(
             scala.util.Try(pos.source.lineToOffset(tmpl.self.srcPos.line)).toOption
           ).getOrElse(0)
```

I am not familiar with the technical details here, but I am eager to use metals normally, so I found a rough way to fix it(I built the project locally). I hope you can fix this problem in a way that you think is reasonable. Thank you

**Comment by tgodzik** [comment]
Thanks for reporting! It might be related to a recent regression in Scala CLI, but we should for sure handle it correctly.

**Comment by tgodzik** [comment]
> Should I move this to Scala CLI?

Let's check if it works with 1.0.1 and then close it if it does

**Comment by jkciesluk** [comment]
It works for me on 1.0.1
