### ISSUE TITLE
java.lang.ClassNotFoundException while debugging a scala file on eclipse theia

### ISSUE THREAD

**Issue by passion123** [scalameta/metals#5349]
### Describe the bug

Hi,my versions as below;
theia :1.36.0
java :1.8
metals plugin:1.16.0
While i debug a scala file named"Test",and the the main class is 'com.test.Test',it shows an errror  java.lang.ClassNotFoundException  as below:
**
2023.06.19 03:11:56 INFO  compiling 168109017169280_tasks-2928 (1 scala source)
2023.06.19 03:11:56 INFO  time: compiled 168109017169280_tasks-2928 in 41ms
2023.06.19 03:12:10 ERROR Failed to fetch mtags for 2.11.8
Error downloading org.scalameta:mtags_2.11.8:0.11.5
  not found: /home/theia/.ivy2/local/org.scalameta/mtags_2.11.8/0.11.5/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scalameta/mtags_2.11.8/0.11.5/mtags_2.11.8-0.11.5.pom
  not found: https://oss.sonatype.org/content/repositories/public/org/scalameta/mtags_2.11.8/0.11.5/mtags_2.11.8-0.11.5.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/mtags_2.11.8/0.11.5/mtags_2.11.8-0.11.5.pom
2023.06.19 03:12:10 WARN  unsupported Scala 2.11.8
2023.06.19 03:12:10 INFO  compiling 168109017169280_tasks-2928 (1 scala source)
2023.06.19 03:12:10 INFO  time: compiled 168109017169280_tasks-2928 in 38ms
2023.06.19 03:12:10 INFO  compiling 168109017169280_tasks-2928 (1 scala source)
2023.06.19 03:12:10 INFO  time: compiled 168109017169280_tasks-2928 in 39ms
2023.06.19 03:12:17 INFO  No mtags for 2.11.8.
2023.06.19 03:12:17 WARN  unsupported Scala 2.11.8
2023.06.19 03:17:37 INFO  compiling 168109017169280_tasks-2928 (1 scala source)
2023.06.19 03:17:37 INFO  time: compiled 168109017169280_tasks-2928 in 43ms
[Error - 3:17:38 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.ClassNotFoundException: com.test.Test.scala
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: com.test.Test.scala
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.$anonfun$findClassAndBuildTarget$1(BuildTargetClassesFinder.scala:112)
	at scala.Option.fold(Option.scala:263)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findClassAndBuildTarget(BuildTargetClassesFinder.scala:113)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findMainClassAndItsBuildTarget(BuildTargetClassesFinder.scala:36)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$1(DebugProvider.scala:460)
	at scala.meta.internal.metals.debug.DebugProvider$$anonfun$withRebuildRetry$1.$anonfun$applyOrElse$6(DebugProvider.scala:730)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	... 3 more
**

Is there any solution on this ?

### Expected behavior

Is there any solution on this ?

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.16.0

**Comment by ckipp01** [comment]
Thanks for the report @passion123. I think a big part of this issue is this:

> 2023.06.19 03:12:10 WARN unsupported Scala 2.11.8

You're using a very very old version of Scala that is no longer supported by Metals. Could you try updating to 2.11.12 to see if it fixes your issue?

**Comment by passion123** [comment]
Thx for ur response.I 've tried to use scala 2.11.12 but useless ,and i also use the newest latest metals plugin for scala 2.11.8 and 2.11.12 but both failed.And btw, i use the maven tool to the project,and the *.scala file does't  generate to *.class file in the  target folder, may this result in the issue ?

**Comment by tgodzik** [comment]
How are you running the test? `com.test.Test.scala` will not be a proper name for a test class. If done manually you can omit .scala and do `com.test.Test`

**Comment by passion123** [comment]
> 



> > And btw, i use the maven tool to the project,and the *.scala file does't compile to *.class file in the target folder, may this result in the issue ?
> 
> Are you saying that the project doesn't compile with Maven? If so, then you'll probably have issues with Metals. You'll want to ensure it compiles with Maven so the export can correctly work.
Yes,seems the maven is not very steady to compile scala project. The maven compile the *.scala to a temp


> How are you running the test? `com.test.Test.scala` will not be a proper name for a test class. If done manually you can omit .scala and do `com.test.Test`

I debug the scala file by the launch.json configured in the .theia folder.Its content is as below :
{
        "type": "scala",
        "request": "launch",
        "name": "LaunchTest",
        "mainClass": "com.test.Test",
        "args": [ "--driver-memory", "8g"],
        "jvmOptions": []
      },
After i clicked deubg button,it shows the above logs:

**2023.06.19 03:17:37 INFO compiling 168109017169280_tasks-2928 (1 scala source)
2023.06.19 03:17:37 INFO time: compiled 168109017169280_tasks-2928 in 43ms
[Error - 3:17:38 AM] Request workspace/executeCommand failed.
Message: Internal error.
Code: -32603
java.util.concurrent.CompletionException: java.lang.ClassNotFoundException: com.test.Test.scala**

**Comment by passion123** [comment]
> > And btw, i use the maven tool to the project,and the *.scala file does't compile to *.class file in the target folder, may this result in the issue ?
> 
> Are you saying that the project doesn't compile with Maven? If so, then you'll probably have issues with Metals. You'll want to ensure it compiles with Maven so the export can correctly work.

yes, maven does't compile the project successfully and the metals compiles not steadily.
![pic-1](https://github.com/scalameta/metals/assets/9447543/8ed749ec-728e-4c32-aace-68de3961e8a9)
On the pic, the .scala file was compiled successfully to **bloop-bsp-* folder** and the **bloop-internal-* folder**,but **not compiled to the classed folder**.
And sometimes, the .scala file can only be compiled to  bloop-internal folder and not in bloop-bsp folder and the classes folder as below logs:
_2023.06.20 09:13:05 ERROR Unexpected error initializing server
scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: CompileResult.  /home/project/ide-server/model-files/scala/temp_tasks/target/bloop-bsp-clients-classes/classes-Metals-7Dc4LpprRYKuILSdSHx4cg==/com/test/Test.class: Operation not permitted
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.$anonfun$applyOrElse$4(BuildServerConnection.scala:300)
	at scala.Option.getOrElse(Option.scala:201)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:298)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:286)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
_
Is there any advice on how to compile it correctly and steadily ?

**Comment by tgodzik** [comment]
So this is not a main class, but a test class, no?

```

        {
            "type": "scala",
            "request": "launch",
            "name": "Untitled",
            "testClass": "???"
        }
```

should work, though we don't accept arguments here.
