### ISSUE TITLE
[Metals][Visual studio code] Unable to debug scala code.

### ISSUE THREAD

**Issue by raiajithkumarr** [scalameta/metals#5364]
Hi Team,
I am Unable to debug scala code in visual studio code even after configuring launch setting file.
Could you please guide or provide me sample application with visual studio debugging settings .

Currently I am getting internal server error.

It will be grateful if you provide sample on Scala code runner version 3.3.0

[helloworld.zip](https://github.com/scalameta/metals/files/11816359/helloworld.zip)

**Comment by tgodzik** [comment]
Did you import the build before running? It should show up in the right bottom corner. You can also do it manually from the Metals view or via special metals command

**Comment by raiajithkumarr** [comment]
Yes I have done import build and in visual studio console I am able to see below error.

While creating maven project it will automatically create for java project and here I removed the java  class added scala object.
(In visual studio after remaining java to scala folder >> How to mark it as root directory in visual studio code I am suspecting this is the issue)

2023.06.21 22:19:46 INFO  compiling demo-test (1 scala source)
2023.06.21 22:19:54 ERROR '7' is not a valid choice for '-release'
2023.06.21 22:19:54 ERROR bad option: '-release'
2023.06.21 22:19:54 ERROR '7' is not a valid choice for '-release'
2023.06.21 22:19:54 ERROR bad option: '-release'
2023.06.21 22:19:54 INFO  time: compiled demo-test in 8.15s
[Error - 10:19:54 PM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.ClassNotFoundException: com.example.Main
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: com.example.Main
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.$anonfun$findClassAndBuildTarget$1(BuildTargetClassesFinder.scala:112)
	at scala.Option.fold(Option.scala:263)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findClassAndBuildTarget(BuildTargetClassesFinder.scala:113)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findMainClassAndItsBuildTarget(BuildTargetClassesFinder.scala:36)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$findMainClassAndItsBuildTarget$1(DebugProvider.scala:530)
	at scala.meta.internal.metals.debug.DebugProvider$$anonfun$withRebuildRetry$1.$anonfun$applyOrElse$6(DebugProvider.scala:809)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	... 3 more

**Comment by tgodzik** [comment]
There seems to be an issue with some of your settings:
```
2023.06.21 22:19:54 ERROR '7' is not a valid choice for '-release'
2023.06.21 22:19:54 ERROR bad option: '-release'
```
the code might have not compiled because of that

**Comment by raiajithkumarr** [comment]
Hi @tgodzik 
yes can you please suggest me or give me sample application document where it should run on **visual studio code with maven and scala with debugging settings**.

Same thing I was able to do it in IntelliJ IDE and able to debug.

**Comment by raiajithkumarr** [comment]
Hi @tgodzik 
After updating pom.xml file for the below lines
 **From** 
 <maven.compiler.source>1.7</maven.compiler.source>
  <maven.compiler.target>1.7</maven.compiler.target>
**To**
 <maven.compiler.source>20</maven.compiler.source>
 <maven.compiler.target>20</maven.compiler.target>
 
2023.06.21 22:19:54 ERROR '7' is not a valid choice for '-release'
2023.06.21 22:19:54 ERROR bad option: '-release'
 This issue got resolved 

But Actual issue is still persisted , I am unable to debug in vs code getting below error


Error - 11:07:03 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.ClassNotFoundException: com.example.Main
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: com.example.Main
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.$anonfun$findClassAndBuildTarget$1(BuildTargetClassesFinder.scala:112)
	at scala.Option.fold(Option.scala:263)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findClassAndBuildTarget(BuildTargetClassesFinder.scala:113)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findMainClassAndItsBuildTarget(BuildTargetClassesFinder.scala:36)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$findMainClassAndItsBuildTarget$1(DebugProvider.scala:530)
	at scala.meta.internal.metals.debug.DebugProvider$$anonfun$withRebuildRetry$1.$anonfun$applyOrElse$6(DebugProvider.scala:809)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	... 3 more

**Comment by raiajithkumarr** [comment]
Issue got resolved and closing this bug.
Steps :
1.  Created maven project with java
2. Removed java classes and created scala files
3. Here we need to verify JDK version in pom.xml file and it should be same as locally installed jdk version (java --version)
4. Next added "**package** com.example" in Main scala file
5. Next Import build in VS code
6. next configure debug configuration in vs code.(as mentioned in attachment.
[demo_VisualStudioCode.zip](https://github.com/scalameta/metals/files/11829275/demo_VisualStudioCode.zip)
