### ISSUE TITLE
OutOfMemoryError while starting Metals server

### ISSUE THREAD

**Issue by filipwiech** [scalameta/metals#5395]
### Describe the bug

Recently I've encountered an issue where Metals entered a crash loop and wasn't able to start, with the following error printed in the output over and over again:
```
[Error - 8:37:23 PM] Restarting server failed
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:178)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:172)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1249)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1241)
	at scala.collection.AbstractIterable.addString(Iterable.scala:933)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1191)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1189)
	at scala.collection.AbstractIterable.mkString(Iterable.scala:933)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1204)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1204)
	at scala.collection.AbstractIterable.mkString(Iterable.scala:933)
	at scala.meta.internal.metals.logging.MetalsLogger$.truncateLogFile(MetalsLogger.scala:137)
	at scala.meta.internal.metals.logging.MetalsLogger$.$anonfun$setupLspLogger$2(MetalsLogger.scala:119)
	at scala.meta.internal.metals.logging.MetalsLogger$.$anonfun$setupLspLogger$2$adapted(MetalsLogger.scala:119)
	at scala.meta.internal.metals.logging.MetalsLogger$$$Lambda$950/0x00000001004db840.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.logging.MetalsLogger$.setupLspLogger(MetalsLogger.scala:119)
	at scala.meta.metals.MetalsLanguageServer.initialize(MetalsLanguageServer.scala:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint$$Lambda$117/0x000000010024b840.apply(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
```

After removing the `.metals/metals.log` file it went away. Seems like the log truncation mechanism is trying to load the whole file to memory at once? Admittedly the size of my log file ballooned after #5386, which I now disabled by turning off debug logging (this compilation queue is very noisy, constantly producing messages and apparently printing whole semantic trees for opened files). :slightly_smiling_face:

### Expected behavior

Log truncation can handle large files without running out of memory.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

0.11.12+160-84f04454-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! It shouldn't have thrown OOM error, we might need to rethink that or use built int mechanism 🤔 

Alternatively, we could back up old file and keep like 10 last sessions.

@kasiaMarek could you take a look?

**Comment by kasiaMarek** [comment]
> could you take a look?

Yeah, I really was hoping that generator will be enough for it not to try and it read all in.
