### ISSUE TITLE
Diagnostics no longer appearing/updating

### ISSUE THREAD

**Issue by TimWSpence** [scalameta/metals#5400]
### Describe the bug

When attempting to import current `HEAD` (`7e2a80907830b4653a860b73fc40e0907fd15050`) of https://github.com/TimWSpence/cats-stm and then making a simple non-compiling change (eg the one on branch `metals-debug`), diagnostics stop refreshing after I make that change (even if I fix it).

At first I thought it was my editor setup because I'm in the process of moving from emacs to neovim but I've reproduced the behaviour in my old emacs setup, which I haven't updated in some time.

I've also observed the diagnostics working correctly when I make the same change in another project.

### Expected behavior

I should see a diagnostic to the effect that
`Found: ("foo": String) Required: Int`

### Operating system

macOS

### Editor/Extension

None

### Version of Metals

v0.11.12

**Comment by TimWSpence** [comment]
Metals logs:

```
2023.07.03 15:51:56 INFO  Started: Metals version 0.11.12 in workspace '/Users/tim/dev/cats-stm' for client emacs GNU Emacs 28.2 (build 2, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.5 (Build 21G531))
 of 2023-05-12.[0m
Jul 03, 2023 3:51:56 PM org.flywaydb.core.internal.license.VersionPrinter printVersionOnly
INFO: Flyway Community Edition 9.16.3 by Redgate
Jul 03, 2023 3:51:56 PM org.flywaydb.core.internal.license.VersionPrinter printVersion
INFO: See release notes here: https://rd.gt/416ObMi
Jul 03, 2023 3:51:56 PM org.flywaydb.core.internal.license.VersionPrinter printVersion
INFO: 
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.database.base.BaseDatabaseType createDatabase
INFO: Database: jdbc:h2:file:/Users/tim/dev/cats-stm/.metals/metals (H2 2.1)
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory allAppliedMigrations
INFO: Schema history table "PUBLIC"."flyway_schema_history" does not exist yet
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.command.DbValidate validate
INFO: Successfully validated 4 migrations (execution time 00:00.007s)
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory create
INFO: Creating Schema History table "PUBLIC"."flyway_schema_history" ...
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.command.DbMigrate migrateGroup
INFO: Current version of schema "PUBLIC": << Empty Schema >>
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.command.DbMigrate doMigrateGroup
INFO: Migrating schema "PUBLIC" to version "1 - Create tables"
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.command.DbMigrate doMigrateGroup
INFO: Migrating schema "PUBLIC" to version "2 - Server discovery"
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.command.DbMigrate doMigrateGroup
INFO: Migrating schema "PUBLIC" to version "3 - Jar symbols"
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.command.DbMigrate doMigrateGroup
INFO: Migrating schema "PUBLIC" to version "4 - Fingerprints"
Jul 03, 2023 3:51:57 PM org.flywaydb.core.internal.command.DbMigrate logSummary
INFO: Successfully applied 4 migrations to schema "PUBLIC", now at version v4 (execution time 00:00.028s)
2023.07.03 15:51:57 INFO  time: initialize in 0.33s[0m
2023.07.03 15:51:58 INFO  no build target found for /Users/tim/dev/cats-stm/core/shared/src/main/scala/io/github/timwspence/cats/stm/STM.scala. Using presentation compiler with project's scala-library version: 3.2.0[0m
Jul 03, 2023 3:51:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 3
2023.07.03 15:51:59 WARN  Build server is not auto-connectable.[0m
2023.07.03 15:51:59 WARN  no build target for: /Users/tim/dev/cats-stm/core/shared/src/main/scala/io/github/timwspence/cats/stm/STM.scala[0m
Align: top-level presets deprecated; use 'preset' subsection
2023.07.03 15:51:59 INFO  time: code lens generation in 2.38s[0m
2023.07.03 15:52:00 INFO  running '/Users/tim/.sdkman/candidates/java/current/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Xmx4G -jar /var/folders/qp/4v3198jx3hd3sdqdrl36wzsc0000gn/T/metals3102345814402439857/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
2023.07.03 15:52:05 INFO  [info] welcome to sbt 1.9.0 (Eclipse Adoptium Java 17.0.7)[0m
2023.07.03 15:52:07 INFO  [info] loading settings for project global-plugins from plugins.sbt ...[0m
2023.07.03 15:52:07 INFO  [info] loading global plugins from /Users/tim/.sbt/1.0/plugins[0m
2023.07.03 15:52:08 INFO  [info] loading settings for project cats-stm-build-build-build from metals.sbt ...[0m
2023.07.03 15:52:08 INFO  [info] loading project definition from /Users/tim/dev/cats-stm/project/project/project[0m
2023.07.03 15:52:08 INFO  [info] loading settings for project cats-stm-build-build from metals.sbt ...[0m
2023.07.03 15:52:08 INFO  [info] loading project definition from /Users/tim/dev/cats-stm/project/project[0m
2023.07.03 15:52:09 INFO  [success] Generated .bloop/cats-stm-build-build.json[0m
2023.07.03 15:52:09 INFO  [success] Total time: 1 s, completed 3 Jul 2023, 15:52:09[0m
2023.07.03 15:52:09 INFO  [info] loading settings for project cats-stm-build from metals.sbt,plugins.sbt ...[0m
2023.07.03 15:52:09 INFO  [info] loading project definition from /Users/tim/dev/cats-stm/project[0m
2023.07.03 15:52:11 INFO  [success] Generated .bloop/cats-stm-build.json[0m
2023.07.03 15:52:11 ERROR Could not load Logmanager "wvlet.log.AirframeLogManager"[0m
2023.07.03 15:52:11 ERROR java.lang.ClassNotFoundException: wvlet.log.AirframeLogManager[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)[0m
2023.07.03 15:52:11 ERROR 	at java.logging/java.util.logging.LogManager$1.run(LogManager.java:239)[0m
2023.07.03 15:52:11 ERROR 	at java.logging/java.util.logging.LogManager$1.run(LogManager.java:223)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)[0m
2023.07.03 15:52:11 ERROR 	at java.logging/java.util.logging.LogManager.<clinit>(LogManager.java:222)[0m
2023.07.03 15:52:11 ERROR 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
2023.07.03 15:52:11 ERROR 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)[0m
2023.07.03 15:52:11 ERROR 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)[0m
2023.07.03 15:52:11 ERROR 	at java.management/sun.management.ManagementFactoryHelper$LoggingMXBeanAccess.getMXBeanImplementation(ManagementFactoryHelper.java:243)[0m
2023.07.03 15:52:11 ERROR 	at java.management/sun.management.ManagementFactoryHelper$LoggingMXBeanAccess.<init>(ManagementFactoryHelper.java:259)[0m
2023.07.03 15:52:11 ERROR 	at java.management/sun.management.ManagementFactoryHelper$PlatformLoggingImpl.getInstance(ManagementFactoryHelper.java:339)[0m
2023.07.03 15:52:11 ERROR 	at java.management/sun.management.ManagementFactoryHelper$PlatformLoggingImpl.<clinit>(ManagementFactoryHelper.java:342)[0m
2023.07.03 15:52:11 ERROR 	at java.management/sun.management.ManagementFactoryHelper.getPlatformLoggingMXBean(ManagementFactoryHelper.java:160)[0m
2023.07.03 15:52:11 ERROR 	at java.management/java.lang.management.DefaultPlatformMBeanProvider$9.nameToMBeanMap(DefaultPlatformMBeanProvider.java:378)[0m
2023.07.03 15:52:11 ERROR 	at java.management/java.lang.management.ManagementFactory.lambda$getPlatformMBeanServer$0(ManagementFactory.java:488)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)[0m
2023.07.03 15:52:11 ERROR 	at java.management/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:489)[0m
2023.07.03 15:52:11 ERROR 	at wvlet.log.LogEnv$.liftedTree1$1(LogEnv.scala:76)[0m
2023.07.03 15:52:11 ERROR 	at wvlet.log.LogEnv$.getMBeanServer$lzycompute(LogEnv.scala:75)[0m
2023.07.03 15:52:11 ERROR 	at wvlet.log.LogEnv$.getMBeanServer(LogEnv.scala:71)[0m
2023.07.03 15:52:11 ERROR 	at wvlet.log.LogEnv$.registerJMX(LogEnv.scala:88)[0m
2023.07.03 15:52:11 ERROR 	at wvlet.log.LogEnv$.<init>(LogEnv.scala:69)[0m
2023.07.03 15:52:11 ERROR 	at wvlet.log.LogEnv$.<clinit>(LogEnv.scala)[0m
2023.07.03 15:52:11 ERROR 	at wvlet.log.Logger$.<init>(Logger.scala:217)[0m
2023.07.03 15:52:11 ERROR 	at wvlet.log.Logger$.<clinit>(Logger.scala)[0m
2023.07.03 15:52:11 ERROR 	at xerial.sbt.Sonatype$.<init>(Sonatype.scala:25)[0m
2023.07.03 15:52:11 ERROR 	at xerial.sbt.Sonatype$.<clinit>(Sonatype.scala)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.lang.Class.forName0(Native Method)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.lang.Class.forName(Class.java:467)[0m
2023.07.03 15:52:11 ERROR 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:24)[0m
2023.07.03 15:52:11 ERROR 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:32)[0m
2023.07.03 15:52:11 ERROR 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:37)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.generic.Growable.loop$1(Growable.scala:57)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.TraversableLike.to(TraversableLike.scala:786)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.TraversableLike.to$(TraversableLike.scala:783)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.AbstractTraversable.to(Traversable.scala:108)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:350)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:350)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.AbstractTraversable.toList(Traversable.scala:108)[0m
2023.07.03 15:52:11 ERROR 	at scala.collection.immutable.List.$plus$plus(List.scala:216)[0m
2023.07.03 15:52:11 ERROR 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:58)[0m
2023.07.03 15:52:11 ERROR 	at bloop.integrations.sbt.BloopDefaults$.$anonfun$computeSbtMetadata$3(SbtBloop.scala:825)[0m
2023.07.03 15:52:11 ERROR 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)[0m
2023.07.03 15:52:11 ERROR 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)[0m
2023.07.03 15:52:11 ERROR 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)[0m
2023.07.03 15:52:11 ERROR 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)[0m
2023.07.03 15:52:11 ERROR 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)[0m
2023.07.03 15:52:11 ERROR 	at sbt.Execute.work(Execute.scala:291)[0m
2023.07.03 15:52:11 ERROR 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)[0m
2023.07.03 15:52:11 ERROR 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)[0m
2023.07.03 15:52:11 ERROR 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)[0m
2023.07.03 15:52:11 ERROR 	at java.base/java.lang.Thread.run(Thread.java:833)[0m
2023.07.03 15:52:11 INFO  [success] Total time: 1 s, completed 3 Jul 2023, 15:52:11[0m
2023.07.03 15:52:11 INFO  [info] loading settings for project root from build.sbt ...[0m
2023.07.03 15:52:11 INFO  [info] resolving key references (14173 settings) ...[0m
2023.07.03 15:52:11 INFO  [info] set scmInfo to https://github.com/TimWSpence/cats-stm[0m
2023.07.03 15:52:18 INFO  [info] set current project to root (in build file:/Users/tim/dev/cats-stm/)[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/rootJVM-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/unidocs.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/rootJS-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/rootJVM.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/rootJS.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/root.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/rootNative.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/coreJVM.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/rootNative-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/unidocs-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/root-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/coreJS.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/coreJVM-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/coreJS-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/examplesJS.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/examplesJVM.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/laws.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/examplesJS-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/benchmarks.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/examplesJVM-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/benchmarks-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/laws-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/coreNative.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/coreNative-test.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/docs.json[0m
2023.07.03 15:52:18 INFO  [success] Generated .bloop/docs-test.json[0m
2023.07.03 15:52:18 INFO  [success] Total time: 1 s, completed 3 Jul 2023, 15:52:18[0m
2023.07.03 15:52:18 INFO  time: ran 'sbt bloopInstall' in 18s[0m
2023.07.03 15:52:18 INFO  Attempting to connect to the build server...[0m
2023.07.03 15:52:18 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/tim/dev/cats-stm/.metals/bsp.trace.json or /Users/tim/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
2023.07.03 15:52:18 INFO  Attempting to connect to the build server...[0m
2023.07.03 15:52:18 INFO  Attempting to connect to the build server...[0m
2023.07.03 15:52:18 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/tim/dev/cats-stm/project/project/.metals/bsp.trace.json or /Users/tim/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
2023.07.03 15:52:18 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/tim/dev/cats-stm/project/.metals/bsp.trace.json or /Users/tim/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
2023.07.03 15:52:18 INFO  time: Connected to build server in 0.18s[0m
2023.07.03 15:52:18 INFO  Connected to Build server: Bloop v1.5.6[0m
2023.07.03 15:52:27 INFO  time: indexed workspace in 8.79s[0m
2023.07.03 15:52:27 ERROR Detecting test frameworks in Scala Native projects is not yet supported[0m
2023.07.03 15:52:27 INFO  Generated JavaScript file '/Users/tim/dev/cats-stm/.bloop/examplesJS/examplesJS-test.js'[0m
2023.07.03 15:52:36 INFO  compiling corejs (7 scala sources)[0m
2023.07.03 15:52:36 INFO  compiling corejvm (6 scala sources and 1 java source)[0m
2023.07.03 15:52:36 INFO  compiling corenative (7 scala sources)[0m
2023.07.03 15:52:41 WARN  Unexpected javac output: warning: [path] bad path element "/Users/tim/dev/cats-stm/.bloop/coreJVM/scala-2.13/classes-empty-coreJVM": no such file or directory
1 warning.[0m
2023.07.03 15:52:41 INFO  compiling corenative-test (9 scala sources)[0m
2023.07.03 15:52:41 INFO  compiling benchmarks (1 scala source)[0m
2023.07.03 15:52:41 INFO  compiling corejvm-test (10 scala sources)[0m
2023.07.03 15:52:41 INFO  compiling laws-test (5 scala sources)[0m
2023.07.03 15:52:41 INFO  time: compiled coreJVM in 4.36s[0m
2023.07.03 15:52:41 INFO  time: compiled coreNative in 4.38s[0m
2023.07.03 15:52:41 INFO  compiling corejs-test (9 scala sources)[0m
2023.07.03 15:52:41 INFO  time: compiled coreJS in 4.69s[0m
2023.07.03 15:52:41 INFO  time: compiled benchmarks in 0.41s[0m
2023.07.03 15:52:42 INFO  time: compiled laws-test in 1.35s[0m
Jul 03, 2023 3:52:42 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 15
Jul 03, 2023 3:52:42 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 19
2023.07.03 15:52:42 INFO  time: compiled coreJVM-test in 1.98s[0m
2023.07.03 15:52:42 INFO  time: compiled coreJS-test in 1.86s[0m
2023.07.03 15:52:42 INFO  time: compiled coreNative-test in 2.28s[0m
```

**Comment by tgodzik** [comment]
Thanks for reporting! I dug in a bit and it seems the added settings such have some kind of conflict, but I am unable to figure out why. The generate Bloop config has:
```
                "-Wvalue-discard",
                "-Ywarn-dead-code",
                "-Ybackend-parallelism",
                "8",
                "-language:_",
                "-release",
                "8",
```

which breaks. If I remove `-Ybackend-parallelism` altogether or change it to `-Ybackend-parallelism:8` this works, otherwise, the compiler shows:
```
[E] Usage: -release:<release> where <release> choices are 8, 9, 10, 11 (default: 11).
[E] bad option: '-release'
```
which I am not sure where it's coming from at this point :thinking:

**Comment by tgodzik** [comment]
Ok, I think I see it, that was a very hidden bug! Will fix it tomorrow!

**Comment by TimWSpence** [comment]
> Ok, I think I see it, that was a very hidden bug! Will fix it tomorrow!

Amazing!!! I didn't give you much to go on so thank you so much for taking the time to investigate ❤️
