### ISSUE TITLE
Diagnostics not updated

### ISSUE THREAD

**Issue by ktonga** [scalameta/metals#5424]
### Describe the bug

I modified a file in a way that should produce compile errors but metals says there are not diagnostics after I saved the file.
If I compile the project with bloop it does report the errors.

When I check the logs file I see a lot of errors like this:

```
July 11, 2023 12:16:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 712
July 11, 2023 12:16:41 PM scala.meta.internal.pc.CompilerAccess retryWithCleanCompiler
INFO: compiler crashed due to an error in the Scala compiler, retrying with new compiler instance.
July 11, 2023 12:16:41 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: class Object does not have a method getClass
scala.reflect.internal.FatalError: class Object does not have a method getClass
        at scala.reflect.internal.Definitions$DefinitionsClass.fatalMissingSymbol(Definitions.scala:1404)
        at scala.reflect.internal.Definitions$DefinitionsClass.miss$1(Definitions.scala:1457)
        at scala.reflect.internal.Definitions$DefinitionsClass.$anonfun$getMemberMethod$2(Definitions.scala:1459)
        at scala.reflect.internal.Definitions$DefinitionsClass.getMemberMethod(Definitions.scala:1459)
        at scala.reflect.internal.Definitions$DefinitionsClass.Any_getClass$lzycompute(Definitions.scala:1166)
        at scala.reflect.internal.Definitions$DefinitionsClass.Any_getClass(Definitions.scala:1166)
        at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreMethods$lzycompute(Definitions.scala:1571)
        at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreMethods(Definitions.scala:1565)
        at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1596)
        at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1596)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1652)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1236)
        at scala.tools.nsc.interactive.Global$TyperRun.<init>(Global.scala:1351)
        at scala.tools.nsc.interactive.Global.newTyperRun(Global.scala:1374)
        at scala.tools.nsc.interactive.Global.<init>(Global.scala:294)
        at scala.meta.internal.pc.MetalsGlobal.<init>(MetalsGlobal.scala:40)
```

### Expected behavior

Compile errors should be listed in the workspace diagnostics view.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v0.11.12

**Comment by tgodzik** [comment]
Thanks for reporting! Those errors are from Metals, not sure where they come from. There might be something in `.metals/reports` 

The problem with errors not being reported is most likely a problem with Bloop and unrelated to the stack trace. Are there any other errors? You can try cancelling compilation or doing clean compile to see if that helps. Or if there are any other errors in the logs do let us know.

**Comment by ktonga** [comment]
I can't see any file or dir called `.metals/reports` either in the project home or my user home.

It's hard to tell if there are other errors some times, those stacktraces are all over the place, they happen every second and it says it's trying a fresh compiler, isn't that a huge performance penalty? Is there any other issue tracking that problem? I searched and couldn't find any.

I scrolled up quite a bit and couldn't see any other errors, I'll keep an eye open when it happens again.

**Comment by tgodzik** [comment]
Starting a fresh compiler shouldn't be an issue unless it happens all the time. And it seems we could report some more data here, like the classpath and maybe checking if it exists.

The error is super weird though.

As for Bloop diagnostics, I am working on some improvements that can help diagnose the problem.

**Comment by tgodzik** [comment]
I added additional option to compile with increased verbosity. It's available in the newest snapshot and can be turned on with an option in the Metals settings (though it might require to be tweaked in the nvim plugin). If you encounter any issue again, we could try to get the logs from the compiler to see why no diagnostics are being show.
