### ISSUE TITLE
Metals H2 database error and redundant import build prompt (upgrade H2 database)

### ISSUE THREAD

**Issue by filipwiech** [scalameta/metals#5447]
### Describe the bug

Recently in one of my projects I've noticed that I'm always asked to re-import it by Metals, even if absolutely nothing has changed (i.e. I can restart the editor right after a successful project import and build and the prompt is still shown). In the logs I see the following:
```
2023.07.14 07:25:47 WARN  resetting database: /<...>/.metals/metals.h2.db
2023.07.14 07:25:47 ERROR org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:h2:file:/<...>/.metals/metals;AUTO_SERVER=TRUE) for user 'sa': Unsupported database file version or invalid file header in file "/<...>/.metals/metals.mv.db" [90048-220]
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 90048
Error Code : 90048
Message    : Unsupported database file version or invalid file header in file "/<...>/.metals/metals.mv.db" [90048-220]

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:140)
	at org.flywaydb.core.Flyway.clean(Flyway.java:234)
	at scala.meta.internal.metals.Tables.migrateOrRestart(Tables.scala:156)
	at scala.meta.internal.metals.Tables.tryUrl(Tables.scala:144)
	at scala.meta.internal.metals.Tables.persistentConnection(Tables.scala:138)
	at scala.meta.internal.metals.Tables.tryAutoServer(Tables.scala:81)
	at scala.meta.internal.metals.Tables.connect(Tables.scala:48)
	at scala.meta.internal.metals.Tables.connection(Tables.scala:74)
	at scala.meta.internal.metals.Tables.$anonfun$fingerprints$1(Tables.scala:39)
	at scala.meta.internal.metals.Fingerprints.load(Fingerprints.scala:52)
	at scala.meta.internal.metals.MetalsLspService.loadFingerPrints(MetalsLspService.scala:848)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3(WorkspaceLspService.scala:993)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3$adapted(WorkspaceLspService.scala:993)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$2(WorkspaceLspService.scala:993)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported database file version or invalid file header in file "/home/filipwie/mc4/smdp/.metals/metals.mv.db" [90048-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:158)
	at org.h2.mvstore.db.Store.<init>(Store.java:142)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:258)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:140)
	at org.flywaydb.core.Flyway.clean(Flyway.java:234)
	at scala.meta.internal.metals.Tables.migrateOrRestart(Tables.scala:156)
	at scala.meta.internal.metals.Tables.tryUrl(Tables.scala:144)
	at scala.meta.internal.metals.Tables.persistentConnection(Tables.scala:138)
	at scala.meta.internal.metals.Tables.tryAutoServer(Tables.scala:81)
	at scala.meta.internal.metals.Tables.connect(Tables.scala:48)
	at scala.meta.internal.metals.Tables.connection(Tables.scala:74)
	at scala.meta.internal.metals.Tables.$anonfun$fingerprints$1(Tables.scala:39)
	at scala.meta.internal.metals.Fingerprints.load(Fingerprints.scala:52)
	at scala.meta.internal.metals.MetalsLspService.loadFingerPrints(MetalsLspService.scala:848)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3(WorkspaceLspService.scala:993)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3$adapted(WorkspaceLspService.scala:993)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$2(WorkspaceLspService.scala:993)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.mvstore.MVStoreException: The write format 2 is smaller than the supported format 3 [2.2.220/5]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.FileStore.getUnsupportedWriteFormatException(FileStore.java:944)
	at org.h2.mvstore.FileStore.processCommonHeaderAttributes(FileStore.java:547)
	at org.h2.mvstore.RandomAccessStore.readStoreHeader(RandomAccessStore.java:227)
	at org.h2.mvstore.FileStore.start(FileStore.java:917)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:289)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2036)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:258)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:140)
	at org.flywaydb.core.Flyway.clean(Flyway.java:234)
	at scala.meta.internal.metals.Tables.migrateOrRestart(Tables.scala:156)
	at scala.meta.internal.metals.Tables.tryUrl(Tables.scala:144)
	at scala.meta.internal.metals.Tables.persistentConnection(Tables.scala:138)
	at scala.meta.internal.metals.Tables.tryAutoServer(Tables.scala:81)
	at scala.meta.internal.metals.Tables.connect(Tables.scala:48)
	at scala.meta.internal.metals.Tables.connection(Tables.scala:74)
	at scala.meta.internal.metals.Tables.$anonfun$fingerprints$1(Tables.scala:39)
	at scala.meta.internal.metals.Fingerprints.load(Fingerprints.scala:52)
	at scala.meta.internal.metals.MetalsLspService.loadFingerPrints(MetalsLspService.scala:848)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3(WorkspaceLspService.scala:993)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3$adapted(WorkspaceLspService.scala:993)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$2(WorkspaceLspService.scala:993)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)

2023.07.14 07:25:47 WARN  resetting database: /<...>/.metals/metals.h2.db
2023.07.14 07:25:47 ERROR unable to setup persistent H2 database with AUTO_SERVER=false, falling back to in-memory database. This means you may be redundantly asked to execute 'Import build', even if it's not needed. Also, code navigation will not work for existing files in the .metals/readonly/ directory. To fix this problem, make sure you only have one running Metals server in the directory '/<...>'.
```

I have tried a few steps from the provided Metals actions to remedy this, but the problem still persisted:

- Re-import the build.
- Clean compile.
- Clean and restart build server (I hoped this one would definitely fix it).

Then I manually removed the whole `.bloop` folder in the project root, which still didn't help. Only after I deleted the `.metals` directory the issue went away (note that in the logs there's a `resetting database: /<...>/.metals/metals.h2.db`, looks like it doesn't work as expected?). Not sure if it's caused by some H2 or Liquiubase update, but it would be nice if Metals could recover from such errors:

- The "Clean and restart build server" seems like an action that should take care of such things.
- Maybe we could show a message window to the user, to make the error more visible and less confusing? Perhaps even ask/provide an option to clean everything right in the prompt?
- Perform reset automatically?

Not sure if it helps, I hope it could be a valuable info for you. :slightly_smiling_face:  

### Expected behavior

No error and no redundant re-import prompt shown, at least not after everything has been reset.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

0.11.12+195-c2642c63-SNAPSHOT

**Comment by kasiaMarek** [comment]
It's the metals db, so restarting build server, doing clean compile or reimporting the project won't help.

Since there was a bump in the format version: https://github.com/h2database/h2database/pull/3834, from https://github.com/scalameta/metals/commit/cace7e1a5a994fe4fdcb90e415baf422294fa9af a lot of people will run into this problem.

The smoothest way to handle this would be to include a migration mechanism.

**Comment by tgodzik** [comment]
Looks like we need to revert for now then and reupdate with a migration mechanism. That seems over complicated though :thinking:

**Comment by tgodzik** [comment]
The other option is to delete the database automatically in such case :thinking: Though that would mean reindexing everything.

Might be a good fallback for the future.

**Comment by kasiaMarek** [comment]
> That seems over complicated though

I guess it's not a huge loss if just delete the old bd. It may be just a little confusing for people if they lose build server selection.

**Comment by tgodzik** [comment]
I would try to avoid that from happening though, we can freeze the H2 update for a while since it's not critical for us

**Comment by tgodzik** [comment]
I am doing the revert in https://github.com/scalameta/metals/pull/5449 so that we can do a release, but if anyone has time to work on a migration mechanism we can fix it in the future. Though it's not clear how the maintainers suggest that to happen.

**Comment by tgodzik** [comment]
There seems to be that `Upgrade` class that should work :thinking:
