### ISSUE TITLE
Import project fails with RuntimeException

### ISSUE THREAD

**Issue by mrt181** [scalameta/metals#555]
**Describe the bug**

When starting vscode in a sbt-project directory the project import is offered.
I get this error:
```
Import project failed, no functionality will work. See the logs for more details
````
and this in my metals.log
```
java.lang.RuntimeException: CreateProcessW() failed, error: 193
	at com.zaxxer.nuprocess.windows.WindowsProcess.start(WindowsProcess.java:248)
	at com.zaxxer.nuprocess.windows.WinProcessFactory.createProcess(WinProcessFactory.java:42)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at scala.meta.internal.metals.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:103)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:80)
	at scala.meta.internal.metals.BloopInstall.$anonfun$runIfApproved$2(BloopInstall.scala:157)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  sbt exit: -2147483648
INFO  time: ran 'sbt bloopInstall' in 1.61s
ERROR sbt command failed: C:\cygwin64\usr\local\bin\sbt metalsEnable bloopInstall
```
When I restart vscode after the first failure I get this error in metals.log next
```
INFO  time: initialize in 0.15s
INFO  skipping build import with status 'Failed'
```

**To Reproduce** Steps to reproduce the behavior:

1. Open vscode in a scala project
2. Accept the import of the project
3. See error

**Expected behavior**

I expect the project import to work and that the `.bloop` directory is created

**Installation:**

- Operating system: Windows 7 x64
- VSCode version: 1.32.1
- VSCode extension version: 1.2.7
- Metals version: 0.4.4

**Search terms**

metals import project windows

**Comment by olafurpg** [comment]
A workaround is to manually run the following from the console
```
METALS_ENABLED=true sbt metalsEnable bloopInstall
```

This step needs to run every time the build changes or when you remove the `.bloop` directory.

When Metals asks to "Import changes" you can select "Don't show again" to dismiss those questions in the future. We rely on NuProcess because it allows us to expose a `Future[Int]` for the sbt process, which I couldn't figure out how to do with `java.lang.ProcessBuilder`.

**Comment by olafurpg** [comment]
@mrt181 have you been able to reproduce this issue on another computer? I'm not sure what we can do to fix this issue. I am unable to reproduce and we test every pull request on a Windows Server 2012.

**Comment by olafurpg** [comment]
Please reopen if you are able to provide a reproduction.

**Comment by mrt181** [comment]
this error is gone since 0.5.0

**Comment by Voronar** [comment]
```bash
INFO  time: initialize in 0.25s
INFO  running '/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals3576706053101751697/sbt-launch.jar metalsEnable bloopInstall'
Aug 08, 2019 1:27:11 PM com.zaxxer.nuprocess.linux.LinuxProcess start
WARNING: Failed to start process
java.io.IOException: error=20, Not a directory
	at com.zaxxer.nuprocess.internal.LibJava8.Java_java_lang_UNIXProcess_forkAndExec(Native Method)
	at com.zaxxer.nuprocess.linux.LinuxProcess.start(LinuxProcess.java:109)
	at com.zaxxer.nuprocess.linux.LinProcessFactory.createProcess(LinProcessFactory.java:40)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at scala.meta.internal.metals.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:80)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:55)
	at scala.meta.internal.metals.BloopInstall.$anonfun$runIfApproved$2(BloopInstall.scala:151)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

INFO  build tool exit: -2147483648
INFO  time: ran 'sbt bloopInstall' in 86ms
ERROR sbt command failed: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals3576706053101751697/sbt-launch.jar metalsEnable bloopInstall

```
Reproduced today with this conditions:
- `sbt new scala/scala-seed.g8`
- `java-8-openjdk-amd64`
- `18.04.1-Ubuntu`
- `vscode-1.36.1`
- `metals-1.5.2`
- `sbt-1.2.8`

**Comment by tgodzik** [comment]
Looks like it detected `/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin/java`  as the path to Java - that's pretty weird. You can specify the java home inside metals settings and it should later work properly. It seems to work on my machine with a similar setup and same java version.

**Comment by Voronar** [comment]
Thanks, @tgodzik, you are right, `JAVA_HOME` in my system was not quite correct. I changed this one to `/usr/lib/jvm/java-1.8.0-openjdk-amd64` and `metals` works out of the box.
