### ISSUE TITLE
Build importation does not work, thus no functionality works

### ISSUE THREAD

**Issue by Tristan-C789** [scalameta/metals#5684]
### Describe the bug

When opening Visual Studio Code, I'm shown the following prompt :

![image](https://github.com/scalameta/metals/assets/48606473/2cb23ace-48fd-4d93-b56a-dbcbe0a6a5fc)

When clicking on "Import build", I am presented the following notification :

![image_1](https://github.com/scalameta/metals/assets/48606473/59858277-17e3-48e6-b2fe-99b4744b6b00)

Every time I open Visual Studio Code for a Scala project, this happens. As a consequence, auto-formatting destroy any kind of indentation, the worksheets don't work, etc...

The logs are the following :

```
2023.09.27 17:06:10 INFO  Started: Metals version 1.0.1+53-209a2984-SNAPSHOT in folders '\\wsl.localhost\Ubuntu\home\tristan\CS-214\Week1\find' for client Visual Studio Code 1.82.2.
2023.09.27 17:06:11 WARN  resetting database: \\wsl.localhost\Ubuntu\home\tristan\CS-214\Week1\find\.metals\metals.h2.db
2023.09.27 17:06:11 ERROR org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:h2:file:\\wsl.localhost\Ubuntu\home\tristan\CS-214\Week1\find\.metals\metals;AUTO_SERVER=TRUE) for user 'sa': Feature not supported: "AUTO_SERVER=TRUE && (readOnly || inMemory || FILE_LOCK=NO || FILE_LOCK=FS)" [50100-214]
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : HYC00
Error Code : 50100
Message    : Feature not supported: "AUTO_SERVER=TRUE && (readOnly || inMemory || FILE_LOCK=NO || FILE_LOCK=FS)" [50100-214]

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
	at org.flywaydb.core.Flyway.clean(Flyway.java:234)
	at scala.meta.internal.metals.Tables.migrateOrRestart(Tables.scala:159)
	at scala.meta.internal.metals.Tables.tryUrl(Tables.scala:147)
	at scala.meta.internal.metals.Tables.persistentConnection(Tables.scala:141)
	at scala.meta.internal.metals.Tables.tryAutoServer(Tables.scala:84)
	at scala.meta.internal.metals.Tables.connect(Tables.scala:48)
	at scala.meta.internal.metals.Tables.connection(Tables.scala:77)
	at scala.meta.internal.metals.Tables.$anonfun$fingerprints$1(Tables.scala:39)
	at scala.meta.internal.metals.Fingerprints.load(Fingerprints.scala:52)
	at scala.meta.internal.metals.MetalsLspService.loadFingerPrints(MetalsLspService.scala:852)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3(WorkspaceLspService.scala:1002)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3$adapted(WorkspaceLspService.scala:1002)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$2(WorkspaceLspService.scala:1002)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLFeatureNotSupportedException: Feature not supported: "AUTO_SERVER=TRUE && (readOnly || inMemory || FILE_LOCK=NO || FILE_LOCK=FS)" [50100-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:556)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:287)
	at org.h2.engine.Database.<init>(Database.java:304)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:258)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
	at org.flywaydb.core.Flyway.clean(Flyway.java:234)
	at scala.meta.internal.metals.Tables.migrateOrRestart(Tables.scala:159)
	at scala.meta.internal.metals.Tables.tryUrl(Tables.scala:147)
	at scala.meta.internal.metals.Tables.persistentConnection(Tables.scala:141)
	at scala.meta.internal.metals.Tables.tryAutoServer(Tables.scala:84)
	at scala.meta.internal.metals.Tables.connect(Tables.scala:48)
	at scala.meta.internal.metals.Tables.connection(Tables.scala:77)
	at scala.meta.internal.metals.Tables.$anonfun$fingerprints$1(Tables.scala:39)
	at scala.meta.internal.metals.Fingerprints.load(Fingerprints.scala:52)
	at scala.meta.internal.metals.MetalsLspService.loadFingerPrints(MetalsLspService.scala:852)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3(WorkspaceLspService.scala:1002)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3$adapted(WorkspaceLspService.scala:1002)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$2(WorkspaceLspService.scala:1002)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)

2023.09.27 17:06:11 WARN  resetting database: \\wsl.localhost\Ubuntu\home\tristan\CS-214\Week1\find\.metals\metals.h2.db
2023.09.27 17:06:11 ERROR unable to setup persistent H2 database with AUTO_SERVER=false, falling back to in-memory database. This means you may be redundantly asked to execute 'Import build', even if it's not needed. Also, code navigation will not work for existing files in the .metals/readonly/ directory. To fix this problem, make sure you only have one running Metals server in the directory '\\wsl.localhost\Ubuntu\home\tristan\CS-214\Week1\find'.
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:h2:file:\\wsl.localhost\Ubuntu\home\tristan\CS-214\Week1\find\.metals\metals;AUTO_SERVER=TRUE) for user 'sa': Feature not supported: "AUTO_SERVER=TRUE && (readOnly || inMemory || FILE_LOCK=NO || FILE_LOCK=FS)" [50100-214]
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : HYC00
Error Code : 50100
Message    : Feature not supported: "AUTO_SERVER=TRUE && (readOnly || inMemory || FILE_LOCK=NO || FILE_LOCK=FS)" [50100-214]

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
	at org.flywaydb.core.Flyway.clean(Flyway.java:234)
	at scala.meta.internal.metals.Tables.migrateOrRestart(Tables.scala:159)
	at scala.meta.internal.metals.Tables.tryUrl(Tables.scala:147)
	at scala.meta.internal.metals.Tables.persistentConnection(Tables.scala:141)
	at scala.meta.internal.metals.Tables.tryNoAutoServer(Tables.scala:101)
	at scala.meta.internal.metals.Tables.tryAutoServer(Tables.scala:95)
	at scala.meta.internal.metals.Tables.connect(Tables.scala:48)
	at scala.meta.internal.metals.Tables.connection(Tables.scala:77)
	at scala.meta.internal.metals.Tables.$anonfun$fingerprints$1(Tables.scala:39)
	at scala.meta.internal.metals.Fingerprints.load(Fingerprints.scala:52)
	at scala.meta.internal.metals.MetalsLspService.loadFingerPrints(MetalsLspService.scala:852)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3(WorkspaceLspService.scala:1002)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3$adapted(WorkspaceLspService.scala:1002)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$2(WorkspaceLspService.scala:1002)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLFeatureNotSupportedException: Feature not supported: "AUTO_SERVER=TRUE && (readOnly || inMemory || FILE_LOCK=NO || FILE_LOCK=FS)" [50100-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:556)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:287)
	at org.h2.engine.Database.<init>(Database.java:304)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:258)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
	at org.flywaydb.core.Flyway.clean(Flyway.java:234)
	at scala.meta.internal.metals.Tables.migrateOrRestart(Tables.scala:159)
	at scala.meta.internal.metals.Tables.tryUrl(Tables.scala:147)
	at scala.meta.internal.metals.Tables.persistentConnection(Tables.scala:141)
	at scala.meta.internal.metals.Tables.tryNoAutoServer(Tables.scala:101)
	at scala.meta.internal.metals.Tables.tryAutoServer(Tables.scala:95)
	at scala.meta.internal.metals.Tables.connect(Tables.scala:48)
	at scala.meta.internal.metals.Tables.connection(Tables.scala:77)
	at scala.meta.internal.metals.Tables.$anonfun$fingerprints$1(Tables.scala:39)
	at scala.meta.internal.metals.Fingerprints.load(Fingerprints.scala:52)
	at scala.meta.internal.metals.MetalsLspService.loadFingerPrints(MetalsLspService.scala:852)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3(WorkspaceLspService.scala:1002)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$3$adapted(WorkspaceLspService.scala:1002)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.WorkspaceLspService.$anonfun$initialize$2(WorkspaceLspService.scala:1002)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)

2023.09.27 17:06:11 INFO  time: initialize in 1.15s
2023.09.27 17:06:15 WARN  Build server is not auto-connectable.
2023.09.27 17:06:16 INFO  running 'C:\Program Files\Java\jdk-17\bin\java.exe -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar C:\Users\Admin\AppData\Local\Temp\metals18321234813593844399\sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
2023.09.27 17:06:20 INFO  [info] welcome to sbt 1.8.2 (Oracle Corporation Java 17.0.6)
2023.09.27 17:06:20 INFO  [warn] sbt version mismatch, using: 1.8.2, in build.properties: "1.9.4", use 'reboot' to use the new value.
2023.09.27 17:06:20 ERROR java.lang.RuntimeException: Invalid build URI (no handler available): file:/wsl.localhost/Ubuntu/home/tristan/CS-214/Week1/find/
2023.09.27 17:06:20 ERROR 	at scala.sys.package$.error(package.scala:30)
2023.09.27 17:06:20 ERROR 	at sbt.internal.Load$.$anonfun$builtinLoader$1(Load.scala:489)
2023.09.27 17:06:20 ERROR 	at sbt.internal.BuildLoader.$anonfun$apply$3(BuildLoader.scala:244)
2023.09.27 17:06:20 ERROR 	at scala.Option.getOrElse(Option.scala:189)
2023.09.27 17:06:20 ERROR 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:244)
2023.09.27 17:06:20 ERROR 	at sbt.internal.Load$.loadURI$1(Load.scala:554)
2023.09.27 17:06:20 ERROR 	at sbt.internal.Load$.loadAll(Load.scala:570)
2023.09.27 17:06:20 ERROR 	at sbt.internal.Load$.loadURI(Load.scala:500)
2023.09.27 17:06:20 ERROR 	at sbt.internal.Load$.load(Load.scala:479)
2023.09.27 17:06:20 ERROR 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:241)
2023.09.27 17:06:20 ERROR 	at sbt.internal.Load$.timed(Load.scala:1406)
2023.09.27 17:06:20 ERROR 	at sbt.internal.Load$.apply(Load.scala:241)
2023.09.27 17:06:20 ERROR 	at sbt.internal.Load$.defaultLoad(Load.scala:56)
2023.09.27 17:06:20 ERROR 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:961)
2023.09.27 17:06:20 ERROR 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:961)
2023.09.27 17:06:20 ERROR 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:914)
2023.09.27 17:06:20 ERROR 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
2023.09.27 17:06:20 ERROR 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
2023.09.27 17:06:20 ERROR 	at sbt.Command$.process(Command.scala:189)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
2023.09.27 17:06:20 ERROR 	at scala.Option.getOrElse(Option.scala:189)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.process$1(MainLoop.scala:245)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
2023.09.27 17:06:20 ERROR 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
2023.09.27 17:06:20 ERROR 	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
2023.09.27 17:06:20 ERROR 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.next(MainLoop.scala:163)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.run(MainLoop.scala:144)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
2023.09.27 17:06:20 ERROR 	at sbt.io.Using.apply(Using.scala:27)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
2023.09.27 17:06:20 ERROR 	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
2023.09.27 17:06:20 ERROR 	at sbt.StandardMain$.runManaged(Main.scala:223)
2023.09.27 17:06:20 ERROR 	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
2023.09.27 17:06:20 ERROR 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
2023.09.27 17:06:20 ERROR 	at scala.Console$.withIn(Console.scala:230)
2023.09.27 17:06:20 ERROR 	at sbt.internal.util.Terminal$.withIn(Terminal.scala:578)
2023.09.27 17:06:20 ERROR 	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:358)
2023.09.27 17:06:20 ERROR 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
2023.09.27 17:06:20 ERROR 	at scala.Console$.withOut(Console.scala:167)
2023.09.27 17:06:20 ERROR 	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:568)
2023.09.27 17:06:20 ERROR 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
2023.09.27 17:06:20 ERROR 	at scala.Console$.withErr(Console.scala:196)
2023.09.27 17:06:20 ERROR 	at sbt.internal.util.Terminal$.withOut(Terminal.scala:568)
2023.09.27 17:06:20 ERROR 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:358)
2023.09.27 17:06:20 ERROR 	at sbt.xMain$.withStreams$1(Main.scala:87)
2023.09.27 17:06:20 ERROR 	at sbt.xMain$.run(Main.scala:121)
2023.09.27 17:06:20 ERROR 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023.09.27 17:06:20 ERROR 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023.09.27 17:06:20 ERROR 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023.09.27 17:06:20 ERROR 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023.09.27 17:06:20 ERROR 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
2023.09.27 17:06:20 ERROR 	at sbt.xMain.run(Main.scala:46)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Launch$.run(Launch.scala:149)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Launch$.launch(Launch.scala:159)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Launch$.apply(Launch.scala:44)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Launch$.apply(Launch.scala:21)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Boot$.run(Boot.scala:73)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Boot$.main(Boot.scala:21)
2023.09.27 17:06:20 ERROR 	at xsbt.boot.Boot.main(Boot.scala)
2023.09.27 17:06:20 INFO  [error] Invalid build URI (no handler available): file:/wsl.localhost/Ubuntu/home/tristan/CS-214/Week1/find/
2023.09.27 17:06:20 INFO  [error] Use 'last' for the full log.
2023.09.27 17:06:20 INFO  [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
2023.09.27 17:06:21 INFO  time: ran 'sbt bloopInstall' in 4.17s
2023.09.27 17:06:21 ERROR sbt command failed: C:\Program Files\Java\jdk-17\bin\java.exe -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar C:\Users\Admin\AppData\Local\Temp\metals18321234813593844399\sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall
```

I tried the following :

-     Closing every program, and reopening them one by one - on different days as well.
-     Deleting the entire project folder, including the .metals folder, and cloning it from Git again.
-     Deleting the .metals folder alone, reloading the Visual Studio Code window (the logs above are from this try).
-     Switching back and forth between the Pre-Release and Release versions of Metals.
-     Clicking on the "Clean metals and restart build server" button.
-     Manually clicking on the "Import build" button after the initial prompt was shown.

None of this attempts worked.

**It is to be noted that this behaviour only appeared when using WSL on Windows 11, and trying directly on Windows 11 works perfectly well.**

### Expected behavior

A successful SBT build import, implying the ability of using all of the functionalities of Metals.

### Operating system

Other (note only the above 3 are officially supported)

### Editor/Extension

VS Code

### Version of Metals

1.0.1+53-209a2984-SNAPSHOT

### Extra context or search terms

As stated at the end of the bug description, Metals and my whole SBT setup used to work on WSL, then stopped when the above bug appeared from nowhere, as far as I recall. It works, and always did, on Windows 11.

**Comment by tgodzik** [comment]
Thanks for reporting! It looks like you started metals directly in windows using the same directory as you did for wsl and it's breaking all sorts of things. I can see information about using java.exe both with info about a wsl workspace.

There also seems to be an SBT process running somewhere. Did you try restarting the computer? Just wondering how persistent is the problem

**Comment by Tristan-C789** [comment]
Thanks for the quick answer ! 
I did restart my computer a few times between the first time it appeared and now, I'd say at least 5 times. Sadly, it did not change a thing.
The issue could be coming from me using WSL, but as I'm not really experienced in WSL, nor in Metals, I can't tell what could be wrong.
I should add that the first few days I tried this setup, Metals did work in Ubuntu WSL as it should, and I can't remember if anything special happened before this issue arised.

**Comment by tgodzik** [comment]
Are you sure you are starting the workspace via WSL? If you start via normal Windows it will break.

**Comment by Tristan-C789** [comment]
I'm not really sure how to know for sure, but basically my steps for opening a project in Ubuntu are :
- Open the Windows PowerShell
- Type the `ubuntu` command
- Navigate to the my project location
- Type the `code .` command
- Click on the "Import build" pop-up

Should I try another way ? That's how I've always done.

**Comment by tgodzik** [comment]
Hmm... what I usually did when testing is just open VS Code and then connect to the workspace using the WSL extension like in https://code.visualstudio.com/docs/remote/wsl#_open-a-remote-folder-or-workspace

**Comment by Tristan-C789** [comment]
I was not aware that this was a feature, to be fully honest. 
So, doing that does seem to work for now.
However, I must add that I've now ran into the same issue on my full Windows setup, right when I changed my Scala project to a different one. The bug described above now occures on Windows.
My working option is now doing what you said, opening VS Code then connecting to the WSL workspace, and then it appear to works how it should.
I'm simply afraid I'll run in the same issue again with my 3rd setup.
