### ISSUE TITLE
Mill BSP import bug

### ISSUE THREAD

**Issue by sake92** [scalameta/metals#5953]
### Describe the bug

I tried the BSP stuff for the first time in VSCode, got this exception:
```
2023.12.16 18:44:36 WARN  Retrying connection to the build server mill-bsp
2023.12.16 18:44:36 INFO  Running BSP server List(0.11.5, --bsp, --disable-ticker, --color, false, --jobs, 1)
2023.12.16 18:44:36 ERROR Running process '0.11.5 --bsp --disable-ticker --color false --jobs 1' failed
java.io.IOException: Cannot run program "0.11.5" (in directory "C:\projects\sake\squery"): CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
    at scala.meta.internal.process.SystemProcess$.run(SystemProcess.scala:45)
    at scala.meta.internal.bsp.BspServers.newConnection$1(BspServers.scala:96)
    at scala.meta.internal.bsp.BspServers.$anonfun$newServer$8(BspServers.scala:142)
    at scala.meta.internal.metals.BuildServerConnection$.setupServer$1(BuildServerConnection.scala:511)
    at scala.meta.internal.metals.BuildServerConnection$.fromSockets(BuildServerConnection.scala:566)
    at scala.meta.internal.metals.BuildServerConnection$$anonfun$fromSockets$16.applyOrElse(BuildServerConnection.scala:581)
    at scala.meta.internal.metals.BuildServerConnection$$anonfun$fromSockets$16.applyOrElse(BuildServerConnection.scala:578)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
    ............
```

This is the contents of mill-bsp.json:
```
{"name":"mill-bsp","argv":["0.11.5","--bsp","--disable-ticker","--color","false","--jobs","1"],"millVersion":"0.11.5","bspVersion":"2.1.0-M7","languages":["scala","java"]}
```

I am on Windows 11 if that matters.

### Expected behavior

Import works

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

Latest

**Comment by tgodzik** [comment]
Thanks for reporting! We use `mill.bsp.BSP/install` mill command to generate that config. Could you check if just running the command produces the incorrect `.bsp/mill.json` file? Looks like it might need to be fixed in Mill. We could do a workaround if this fail and prefix with mill script, but that could be highly error prone.

**Comment by sake92** [comment]
@tgodzik yeah, seems like there is a bug in Millw wrapper, fix here https://github.com/lefou/millw/pull/57

---

Btw, is there a reason why Metals is using an embedded wrapper and not one in the project workspace?

**Comment by tgodzik** [comment]
hmm... we should default to the one in the workspace yeah, though normally this shouldn't be a problem since we keep up to date with the latest wrapper

You can set it manually in the metals settings. `metals.millScript` I think?
