### ISSUE TITLE
DocumentHighlightSuite and SemanticTokensSuite failing in latest Scala 2.13.13 nightly

### ISSUE THREAD

**Issue by SethTisue** [scalameta/metals#5975]
full failure log https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/1556/artifact/logs/metals-build.log

```
[metals] [info] tests.tokens.SemanticTokensSuite.import-rename_2.13.13-bin-97c2515 started
[metals] [error] ==> X tests.tokens.SemanticTokensSuite.import-rename_2.13.13-bin-97c2515  0.013s munit.ComparisonFailException: /home/jenkins/workspace/scala-2.13.x-jdk17-integrate-community-build/target-0.9.20/project-builds/metals-18062ca9befaf80e4882cc22e9d0c1d8f5a8da96/tests/cross/src/test/scala/tests/tokens/SemanticTokensSuite.scala:256
[metals] [error] 255:
[metals] [error] 256:  check(
[metals] [error] 257:    "import-rename",
[metals] [error] values are not the same
[metals] [error] => Obtained
[metals] [error] package <<example>>/*namespace*/
[metals] [error] 
[metals] [error] import <<util>>/*namespace*/.{<<Failure>>/*class*/ => NoBad}
[metals] [error] 
[metals] [error] class <<Imports>>/*class*/ {
[metals] [error]   // rename reference
[metals] [error]   <<NoBad>>/*class*/(null)
[metals] [error] }
[metals] [error] => Diff (- obtained, + expected)
[metals] [error]  âˆ™
[metals] [error] -import <<util>>/*namespace*/.{<<Failure>>/*class*/ => NoBad}
[metals] [error] +import <<util>>/*namespace*/.{<<Failure>>/*class*/ => <<NoBad>>/*class*/}
[metals] [error]  âˆ™
[metals] [error]     at munit.Assertions.failComparison(Assertions.scala:274)
```

and a series of similar failures in DocumentHighlightSuite; here's a sample

```
[metals] [error] ==> X tests.highlight.DocumentHighlightSuite.rename1_2.13.13-bin-97c2515  0.003s munit.ComparisonFailException: /home/jenkins/workspace/scala-2.13.x-jdk17-integrate-community-build/target-0.9.20/project-builds/metals-18062ca9befaf80e4882cc22e9d0c1d8f5a8da96/tests/cross/src/test/scala/tests/highlight/DocumentHighlightSuite.scala:620
[metals] [error] 619:
[metals] [error] 620:  check(
[metals] [error] 621:    "rename1",
[metals] [error] values are not the same
[metals] [error] => Obtained
[metals] [error] 
[metals] [error] import scala.util.{ <<Try>> => ATry<<}
[metals] [error] ob>>ject Test {
[metals] [error]    <<ATry>>(1)
[metals] [error] }
[metals] [error] => Diff (- obtained, + expected)
[metals] [error] -import scala.util.{ <<Try>> => ATry<<}
[metals] [error] -ob>>ject Test {
[metals] [error] +import scala.util.{ <<Try>> => <<ATry>>}
[metals] [error] +object Test {
[metals] [error]     <<ATry>>(1)
[metals] [error]     at munit.Assertions.failComparison(Assertions.scala:274)
```

the failures began somewhere between scala/scala@43aa816 and scala/scala@97c2515

```
* 97c2515f3d - Merge pull request #10517 from kapunga/12845-use-java-deprecation (2 days ago) <Lukas Rytz>
* 85fa13dc76 - Merge pull request #10615 from lrytz/t12918 (2 days ago) <Lukas Rytz>
* eeccf19a22 - Merge pull request #10447 from som-snytt/issue/12813 (3 days ago) <Lukas Rytz>
* d2f97a34eb - Merge pull request #10157 from joroKr21/sammy-refined (4 days ago) <Lukas Rytz>
* 343b85bfa9 - Merge pull request #10601 from som-snytt/tweak/nonfatal (4 days ago) <Lukas Rytz>
* c80c0ff086 - Merge pull request #10637 from lrytz/sd857 (4 days ago) <Seth Tisue>
* c5873aafa7 - Merge pull request #10634 from som-snytt/tweak/invoke (5 days ago) <Lukas Rytz>
* af50726e74 - Merge pull request #10635 from som-snytt/issue/7530-multiassign-warn (5 days ago) <Lukas Rytz>
* dfe9be389c - Merge pull request #10636 from som-snytt/tweak/7349-opt-followup (5 days ago) <Lukas Rytz>
* df7a8403bd - Merge pull request #10631 from som-snytt/tweak/callgraphtest (8 days ago) <som-snytt>
* 61d31ab5bc - Merge pull request #10629 from som-snytt/issue/9414-known-subclasses (9 days ago) <Lukas Rytz>
* ed8005fae3 - Merge pull request #10448 from dragonfly-ai/2.13.x (9 days ago) <som-snytt>
```

### Version of Metals

scalameta/metals@615add640710e25dd0c4a1b01176ffca2e15b365 (built from source in Scala 2 community build)

**Comment by tgodzik** [comment]
Thanks for reporting!

Looks like renamePos is broken.

In:
`import scala.util.{ Try => ATry}` renamePos points at the closing `}`

My guess would be https://github.com/scala/scala/commit/93b3e56adb1f2d70ab02a94afd50f05d9906f865 <- the parser change most likely caused it.

**Comment by tgodzik** [comment]
Currently being fixed in https://github.com/scala/scala/pull/10647

**Comment by SethTisue** [comment]
verified fixed. scala/community-build@8b21e81c6962e03d7320e3fd07b26491cd8cd733
