### ISSUE TITLE
1.2.1 Breaks all builds

### ISSUE THREAD

**Issue by mlhales** [scalameta/metals#6104]
### Describe the bug

When I upgraded to Metals 1.28.0 in VSCode, on Windows, none of my projects will build. I have up to date sbt (1.9.8) and the paths shown in the logs for sbt, the JDK and for my project location are all correct.

Everything worked fine with the previous version

### Expected behavior

I expect them to run.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

Metals VSCode plugin 1.28.0 but in the output the log shows 1.2.1 not sure if the plugin number is decoupled from the actual Metals version.

### Extra context or search terms

Java home: C:\Program Files\Amazon Corretto\jdk11.0.20_8
Metals version: 1.2.1
2024.02.08 14:02:10 INFO  logging to files E:\sensor-platform\scala\config-server\.metals\metals.log
2024.02.08 14:02:10 INFO  Started: Metals version 1.2.1 in folders 'E:\sensor-platform\scala\config-server' for client Visual Studio Code 1.85.2.
Initializing Scala Debugger
Release notes was not shown: not showing release notes since they've already been seen for your current version
2024.02.08 14:02:11 WARN  Build server is not auto-connectable.
2024.02.08 14:02:15 INFO  running 'C:\Program Files (x86)\sbt\bin\sbt -Dbloop.export-jar-classifiers=sources bloopInstall'
2024.02.08 14:02:15 ERROR Running process 'C:\Program Files (x86)\sbt\bin\sbt -Dbloop.export-jar-classifiers=sources bloopInstall' failed
java.io.IOException: Cannot run program "C:\Program Files (x86)\sbt\bin\sbt" (in directory "E:\sensor-platform\scala\config-server"): CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at scala.meta.internal.process.SystemProcess$.run(SystemProcess.scala:45)
	at scala.meta.internal.builds.ShellRunner.run(ShellRunner.scala:122)
	at scala.meta.internal.builds.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:75)
	at scala.meta.internal.builds.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:49)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall(BloopInstallProvider.scala:19)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall$(BloopInstallProvider.scala:15)
	at scala.meta.internal.builds.SbtBuildTool.bloopInstall(SbtBuildTool.scala:23)
	at scala.meta.internal.builds.BloopInstall.runUnconditionally(BloopInstall.scala:46)
	at scala.meta.internal.builds.BloopInstall.$anonfun$runIfApproved$3(BloopInstall.scala:145)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:492)
	at java.lang.ProcessImpl.start(ProcessImpl.java:153)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at scala.meta.internal.process.SystemProcess$.run(SystemProcess.scala:45)
	at scala.meta.internal.builds.ShellRunner.run(ShellRunner.scala:122)
	at scala.meta.internal.builds.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:75)
	at scala.meta.internal.builds.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:49)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall(BloopInstallProvider.scala:19)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall$(BloopInstallProvider.scala:15)
	at scala.meta.internal.builds.SbtBuildTool.bloopInstall(SbtBuildTool.scala:23)
	at scala.meta.internal.builds.BloopInstall.runUnconditionally(BloopInstall.scala:46)
	at scala.meta.internal.builds.BloopInstall.$anonfun$runIfApproved$3(BloopInstall.scala:145)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)

2024.02.08 14:02:15 INFO  time: ran 'sbt bloopInstall' in 37ms
2024.02.08 14:02:15 ERROR sbt command failed: C:\Program Files (x86)\sbt\bin\sbt -Dbloop.export-jar-classifiers=sources bloopInstall

**Comment by kasiaMarek** [comment]
Thanks for the report. We changed which `sbt` is used to run things like `bloopInstall`. We have previously used an embedded launcher , now we try to find `sbt` on the path. My guess is that the spaces in your path are at fault here. So what you can try as a workaround for now is open Metals Settings and set `Sbt Script` to either: `sbt` or full escaped path to `sbt`.

**Comment by generalmimon** [comment]
I've just hit the same error as soon as VS Code automatically updated https://github.com/scalameta/metals-vscode to [v1.28.0](https://github.com/scalameta/metals-vscode/releases/tag/v1.28.0). Fortunately, VS Code allows to easily downgrade to the previous version [v1.27.0](https://github.com/scalameta/metals-vscode/releases/tag/v1.27.0), which fixes the issue for me:

![Expand Uninstall menu > Install Another Version...](https://github.com/scalameta/metals/assets/47499687/1b2f4782-c290-4c03-8ec9-d02f3e5f18a4)

@kasiaMarek:

> My guess is that the spaces in your path are at fault here.

I don't think so - if I may guess, it's because the `C:\Program Files (x86)\sbt\bin\sbt` file is a Bash script:

```
pp@DESKTOP-89OPGF3 MINGW64 /c/Program Files (x86)/sbt/bin
$ file *
sbt:                      Bourne-Again shell script, ASCII text executable
sbt.bat:                  DOS batch file, ASCII text, with CRLF line terminators
sbt-launch.jar:           Zip archive data, at least v1.0 to extract, compression method=store
sbtn-x86_64-pc-win32.exe: PE32+ executable (console) x86-64, for MS Windows, 7 sections
```

From the `CreateProcess error=193, %1 is not a valid Win32 application` part of the error message, it looks like this `C:\Program Files (x86)\sbt\bin\sbt` file path was passed to `CreateProcess` as the executable. But as already mentioned, the referenced `sbt` file is a Bash script (i.e. a text file), not an executable file (e.g. `.exe`) that `CreateProcess` expects.

It seems that directly passing a path to a batch file (`.bat`) into the first parameter `lpApplicationName` wouldn't work with this function either (see https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa#parameters), apparently it must really be an executable:

> To run a batch file, you must start the command interpreter; set _lpApplicationName_ to cmd.exe and set _lpCommandLine_ to the following arguments: /c plus the name of the batch file.

---

And BTW, "spaces in **_your_** path" is a bit weird thing to say (to me, it subtly suggests that we have deliberately chosen a path with spaces), because `C:\Program Files (x86)\sbt` is the default install location of the official sbt .msi installer for Windows (https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Windows.html#Windows+installer). But I don't think spaces in the path are a problem in this case.

**Comment by kasiaMarek** [comment]
It should work on the newest snapshot, I reverted back to using the embedded launcher for Windows. In Metals settings you can choose `Metals Server Version` to be `1.2.1+5-6914fee8-SNAPSHOT`, if you want to have the benefits of the newest release, which I would recommend, since it contains many bug fixes.

**Comment by generalmimon** [comment]
> It should work on the newest snapshot, I reverted back to using the embedded launcher for Windows. In Metals settings you can choose `Metals Server Version` to be `1.2.1+5-6914fee8-SNAPSHOT`, (...)

This seems to work, thank you.

**Comment by kasiaMarek** [comment]
Closing this since it's resolved by https://github.com/scalameta/metals/pull/6111. The fix is also in the newest release.
