### ISSUE TITLE
Metals is not starting in vscode

### ISSUE THREAD

**Issue by a01fe** [scalameta/metals#6168]
### Describe the bug

Starting with today's pre-release, Metals is not starting when opening a project in vscode. It was working before today's update.

This is what shows in Output > Metals:

```
Metals version: 1.2.2+41-4ecdb894-SNAPSHOT
Error: ENOENT: no such file or directory, stat '/Users/finchr/.metals/cs'
Release notes was not shown: not showing release notes since they've already been seen for your current version
```

If I click on "Start Metals", this shows up in Output > Window:

```
2024-02-27 09:40:52.874 [error] command 'metals.start-server' not found: Error: command 'metals.start-server' not found
    at k.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1587:12345)
    at k.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1587:12274)
    at async c.open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:653:44311)
    at async a.open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:653:45692)
```

### Expected behavior

Metals starting nomally 😹 

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.2.2+41-4ecdb894-SNAPSHOT

### Extra context or search terms

I've stopped bloop and metals processes (running before today's update) and removed `.bloop` and `.metals` in the project directory.

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like we are not downloading correctly coursier for downloading Java, we should add some kind of fallback in that case. For now you can revert VS Code to the latest stable version.

@kasiaMarek can you take a look?

**Comment by a01fe** [comment]
Switched back to Metals release version and its working fine. ty for the quick reply!
