### ISSUE TITLE
Bazel import error. java.nio.file.FileSystemNotFoundException: Provider "bytestream" not installed

### ISSUE THREAD

**Issue by aishfenton** [scalameta/metals#6214]
### Describe the bug

During import Bazel build a `FileSystemNotFoundException: Provider "bytestream" not installed` exception is thrown.

Full stack trace
```
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException:             java.nio.file.FileSystemNotFoundException: Provider "bytestream" not installed
            java.util.concurrent.CompletionException: java.nio.file.FileSystemNotFoundException: Provider "bytestream" not installed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.nio.file.FileSystemNotFoundException: Provider "bytestream" not installed
	at java.base/java.nio.file.Path.of(Path.java:212)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at org.jetbrains.bsp.bazel.server.sync.TargetInfoReader.addExtensionInfo(TargetInfoReader.kt:55)
	at org.jetbrains.bsp.bazel.server.sync.TargetInfoReader.access$addExtensionInfo(TargetInfoReader.kt:29)
	at org.jetbrains.bsp.bazel.server.sync.TargetInfoReader$readTargetMapFromAspectOutputs$1$1.emit(TargetInfoReader.kt:41)
	at org.jetbrains.bsp.bazel.server.sync.TargetInfoReader$readTargetMapFromAspectOutputs$1$1.emit(TargetInfoReader.kt:41)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:116)
	at org.jetbrains.bsp.bazel.server.sync.TargetInfoReader$readTargetMapFromAspectOutputs$1.invokeSuspend(TargetInfoReader.kt:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at scala.meta.internal.metals.RequestMonitorImpl$$anon$1.consume(ServerLivenessMonitor.scala:41)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

Import works to completion.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.2.2

### Extra context or search terms

Using [Remote SSH](https://code.visualstudio.com/docs/remote/ssh) in VSCode. It's possibily related to this [bug fix](https://youtrack.jetbrains.com/issue/BAZEL-793/Provider-bytestream-not-installed-while-importing-bazel-bsp) in bazel-bsp

**Comment by tgodzik** [comment]
This should be fixed already in main, we did bump the bazel bsp version to newer nightly.

**Comment by aishfenton** [comment]
Excellent ! Trying now.

**Comment by aishfenton** [comment]
Can confirm resolved in nightlies.
