### ISSUE TITLE
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TYPE_HIERARCHY_JAR" not found

### ISSUE THREAD

**Issue by arturopala** [scalameta/metals#6250]
```
2024.03.23 17:12:11 INFO  Started: Metals version 1.2.2+90-8e975366-SNAPSHOT in folders '/Users/arturopala/workspace/xxxxxxxx/xxxxxxxx-api-integration-tests' for client Visual Studio Code 1.87.2.[0m
SLF4J: Class path contains multiple SLF4J providers.
SLF4J: Found provider [scribe.slf4j.ScribeServiceProvider@3f4214e5]
SLF4J: Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@81dd982]
SLF4J: See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual provider is of type [scribe.slf4j.ScribeServiceProvider@3f4214e5]
2024.03.23 17:12:11 WARN  Flyway upgrade recommended: H2 2.2.224 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.220.[0m
2024.03.23 17:12:11 INFO  Attempting to connect to the build server...[0m
2024.03.23 17:12:11 INFO  Bloop uses /Users/arturopala/.jenv/versions/21.0 defined at /Users/arturopala/.bloop/bloop.json[0m
2024.03.23 17:12:15 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/arturopala/workspace/xxxxxxxx/xxxxxxxx-api-integration-tests/.metals/bsp.trace.json or /Users/arturopala/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
2024.03.23 17:12:15 INFO  time: Connected to build server in 4.39s[0m
2024.03.23 17:12:15 INFO  Connected to Build server: Bloop v1.5.15[0m
2024.03.23 17:12:18 INFO  time: indexed workspace in 2.3s[0m
2024.03.23 17:13:26 INFO  Disconnecting from Bloop session...[0m
2024.03.23 17:13:26 INFO  Shut down connection with build server.[0m
2024.03.23 17:13:26 INFO  Deleted directories inside .bloop[0m
2024.03.23 17:13:26 ERROR failed to clean database: /Users/arturopala/workspace/xxxxxxxx/xxxxxxxx-api-integration-tests/.metals/metals.h2.db
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TYPE_HIERARCHY_JAR" not found; SQL statement:
truncate table type_hierarchy_jar [42102-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8064)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8035)
	at org.h2.command.Parser.readTableOrView(Parser.java:8024)
	at org.h2.command.Parser.readTableOrView(Parser.java:7990)
	at org.h2.command.Parser.parseTruncate(Parser.java:2018)
	at org.h2.command.Parser.parsePrepared(Parser.java:760)
	at org.h2.command.Parser.parse(Parser.java:592)
	at org.h2.command.Parser.parse(Parser.java:564)
	at org.h2.command.Parser.prepareCommand(Parser.java:483)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:316)
	at scala.meta.internal.metals.JarTopLevels.clearAll(JarTopLevels.scala:233)
	at scala.meta.internal.metals.Tables.cleanAll(Tables.scala:215)
	at scala.meta.internal.metals.MetalsLspService.$anonfun$resetWorkspace$1(MetalsLspService.scala:2832)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1583)
[0m
2024.03.23 17:13:26 INFO  Attempting to connect to the build server...[0m
2024.03.23 17:13:26 INFO  Bloop uses /Users/arturopala/.jenv/versions/21.0 defined at /Users/arturopala/.bloop/bloop.json[0m
2024.03.23 17:13:27 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/arturopala/workspace/xxxxxxxx/xxxxxxxx-api-integration-tests/.metals/bsp.trace.json or /Users/arturopala/Library/Caches/org.scalameta.metals/bsp.trace.json[0m
2024.03.23 17:13:27 INFO  time: Connected to build server in 1.66s[0m
2024.03.23 17:13:27 INFO  Connected to Build server: Bloop v1.5.15[0m
2024.03.23 17:13:28 INFO  time: indexed workspace in 0.74s[0m
2024.03.23 17:13:39 INFO  no build target found for /Users/arturopala/workspace/xxxxxxxx/xxxxxxxx-api-integration-tests/src/test/scala/org/xxxxxxxxsoftware/api/ZeroHashAlphaApiSpec.scala. Using presentation compiler with project's scala-library version: 3.3.3[0m
2024.03.23 17:13:40 INFO  time: code lens generation in 4.47s[0m
```

### Expected behaviour:

**Operating system:**
Mac OS X

**Java version:**
21.0.1

**Editor/extension:**
Visual Studio Code v1.87.2

**Metals version:**
1.2.2+90-8e975366-SNAPSHOT

### Workspace information:
 - **Scala versions:** 3.4.0
 - **Build tools:** 0. scala-cli
 - **Build servers:**
    0. scala-cli v1.2.0
 - **All build tools in workspace:**

**Comment by tgodzik** [comment]
Thanks for reporting! @kasiaMarek looks like it's related to your recent changes

**Comment by tgodzik** [comment]
Seems I am also getting:
```
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_4 ON PUBLIC.INDEXED_JAR(MD5) VALUES ( /* 1 */ 'D21CA0778A9C5742F52D9B14E8F6C56D' )"; SQL statement:
insert into indexed_jar (md5, type_hierarchy_indexed) values (?, ?) [23505-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:520)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:527)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:242)
	at org.h2.command.CommandContainer.update(CommandContainer.java:163)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:216)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:174)
	at scala.meta.internal.metals.JarTopLevels.putJarIndexingInfo(JarTopLevels.scala:121)
	at scala.meta.internal.metals.Indexer.addSourceJarSymbols(Indexer.scala:651)
	at scala.meta.internal.metals.Indexer.indexJdkSources(Indexer.scala:518)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$24(Indexer.scala:386)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$23(Indexer.scala:383)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$23$adapted(Indexer.scala:379)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at scala.meta.internal.metals.Indexer.indexWorkspace(Indexer.scala:379)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$2(Indexer.scala:166)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$1(Indexer.scala:166)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:842)
```
on an empty Scala 3.4.0 project. Might be also good to take a look at that before the release
