### ISSUE TITLE
In VSCode, metals always use the wrong Scala 2.13 version

### ISSUE THREAD

**Issue by tribbloid** [scalameta/metals#6253]
When importing a Gradle bloop project, the following command is used:

```
./gradlew --stacktrace --console=plain --init-script /tmp/metals5311744264606695985/init-script.gradle bloopInstall
```

which got the following error:

```
Java home: /usr/lib/jvm/java-11-openjdk-amd64
Metals version: 1.2.2
Using coursier located at /home/peng/.local/share/coursier/bin/coursier
2024.03.24 17:48:41 INFO  logging to files /home/peng/git/spookystuff/.metals/metals.log
2024.03.24 17:48:41 INFO  Started: Metals version 1.2.2 in folders '/home/peng/git/spookystuff' for client Visual Studio Code - Insiders 1.88.0-insider.
Initializing Scala Debugger
Release notes was not shown: not showing release notes since they've already been seen for your current version
2024.03.24 17:48:49 INFO  Attempting to connect to the build server...
2024.03.24 17:48:49 INFO  Bloop uses /usr/lib/jvm/java-11-openjdk-amd64 defined at /home/peng/.bloop/bloop.json
2024.03.24 17:48:49 ERROR Starting the bsp launcher for bloop...
2024.03.24 17:48:49 ERROR Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher1240467891510917282/bsp.socket'...
2024.03.24 17:48:49 ERROR Waiting for the bsp connection to come up...
2024.03.24 17:48:49 ERROR error: The command bsp --protocol local --socket /tmp/bsp-launcher1240467891510917282/bsp.socket returned with an error
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-compiler/2.13.12/ba2bfd2991537e8a5163c502f7c326a23acf74a4/scala-compiler-2.13.12.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-bridge_2.13/1.6.1/15798fdc2d9dca8962ba3c14ae8deaf34eca2213/compiler-bridge_2.13-1.6.1-sources.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-interface/1.6.1/fa68930e1686c5d251a025ae656fa1e5f0af53fc/compiler-interface-1.6.1.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-reflect/2.13.12/88be4dbc90fdd2d12c05b6a872a9add60524461d/scala-reflect-2.13.12.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.13.12/3c51da898af4ebfac356fcde11388afb2ae8ee82/scala-library-2.13.12.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/util-interface/1.6.1/b6280fa8056b59788d04084994fcf5ee9f1ca9f0/util-interface-1.6.1.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[31m[E][0m Failed to load project from /home/peng/git/spookystuff/.bloop/mldsl-testFixtures.json
2024.03.24 17:48:49 ERROR error: Trying a tcp-based connection to the server instead...
2024.03.24 17:48:49 ERROR Opening a bsp server connection with 'bsp --protocol tcp --port 27767'...
2024.03.24 17:48:49 ERROR Waiting for the bsp connection to come up...
2024.03.24 17:48:49 ERROR error: The command bsp --protocol tcp --port 27767 returned with an error
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-compiler/2.13.12/ba2bfd2991537e8a5163c502f7c326a23acf74a4/scala-compiler-2.13.12.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-bridge_2.13/1.6.1/15798fdc2d9dca8962ba3c14ae8deaf34eca2213/compiler-bridge_2.13-1.6.1-sources.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-interface/1.6.1/fa68930e1686c5d251a025ae656fa1e5f0af53fc/compiler-interface-1.6.1.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-reflect/2.13.12/88be4dbc90fdd2d12c05b6a872a9add60524461d/scala-reflect-2.13.12.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.13.12/3c51da898af4ebfac356fcde11388afb2ae8ee82/scala-library-2.13.12.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/util-interface/1.6.1/b6280fa8056b59788d04084994fcf5ee9f1ca9f0/util-interface-1.6.1.jar doesn't exist!
2024.03.24 17:48:49 ERROR > [0m[31m[E][0m Failed to load project from /home/peng/git/spookystuff/.bloop/spookystuff-showcase-testFixtures.json
2024.03.24 17:48:49 ERROR error: The launcher failed to establish a bsp connection, aborting...
2024.03.24 17:48:49 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:92)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:119)
	at scala.meta.internal.metals.BloopServers$$anon$2.run(BloopServers.scala:502)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)


```

```
2024.03.24 17:51:04 INFO  running '/home/peng/git/spookystuff/gradlew --stacktrace --console=plain --init-script /tmp/metals2511985343717486124/init-script.gradle bloopInstall'
2024.03.24 17:51:05 INFO  > Task :buildSrc:checkKotlinGradlePluginConfigurationErrors
2024.03.24 17:51:05 INFO  > Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
2024.03.24 17:51:05 INFO  > Task :buildSrc:extractPrecompiledScriptPluginPlugins UP-TO-DATE
2024.03.24 17:51:05 INFO  > Task :buildSrc:compilePluginsBlocks UP-TO-DATE
2024.03.24 17:51:05 INFO  > Task :buildSrc:generatePrecompiledScriptPluginAccessors UP-TO-DATE
2024.03.24 17:51:05 INFO  > Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE
2024.03.24 17:51:05 INFO  > Task :buildSrc:compileKotlin UP-TO-DATE
2024.03.24 17:51:05 INFO  > Task :buildSrc:compileJava NO-SOURCE
2024.03.24 17:51:05 INFO  > Task :buildSrc:compileGroovy NO-SOURCE
2024.03.24 17:51:05 INFO  > Task :buildSrc:pluginDescriptors UP-TO-DATE
2024.03.24 17:51:05 INFO  > Task :buildSrc:processResources UP-TO-DATE
2024.03.24 17:51:05 INFO  > Task :buildSrc:classes UP-TO-DATE
2024.03.24 17:51:05 INFO  > Task :buildSrc:jar UP-TO-DATE
2024.03.24 17:51:05 INFO  
2024.03.24 17:51:05 INFO  > Configure project :
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in root project 'spookystuff' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':repack' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:assembly' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:benchmark' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:commons' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:core' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:integration' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:parsing' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:showcase' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:unused' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:web' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons:core' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons:meta2' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons:spark' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':repack:selenium' / scalaCompilerPlugins
2024.03.24 17:51:05 INFO  Sonatype API key not defined, skipping configuration of Maven Central publishing repository
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  PGP signing key not defined, skipping signing configuration
2024.03.24 17:51:05 INFO  
2024.03.24 17:51:05 INFO  > Configure project :prover-commons:core
2024.03.24 17:51:05 INFO  using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons:core' / dependencies
2024.03.24 17:51:05 INFO  
2024.03.24 17:51:05 INFO  > Task :parent:configureBloopInstall
2024.03.24 17:51:05 INFO  > Task :repack:configureBloopInstall
2024.03.24 17:51:05 INFO  > Task :prover-commons:configureBloopInstall
2024.03.24 17:51:05 INFO  > Task :configureBloopInstall
2024.03.24 17:51:05 INFO  > Task :prover-commons:meta2:configureBloopInstall
2024.03.24 17:51:05 INFO  > Task :prover-commons:bloopInstall
2024.03.24 17:51:05 INFO  > Task :bloopInstall
2024.03.24 17:51:05 INFO  > Task :prover-commons:core:configureBloopInstall
2024.03.24 17:51:05 INFO  > Task :repack:bloopInstall
2024.03.24 17:51:05 INFO  > Task :parent:bloopInstall
2024.03.24 17:51:05 INFO  > Task :repack:selenium:configureBloopInstall
2024.03.24 17:51:05 INFO  > Task :prover-commons:meta2:bloopInstall
2024.03.24 17:51:05 INFO  > Task :prover-commons:core:bloopInstall
2024.03.24 17:51:06 INFO  > Task :prover-commons:spark:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :repack:selenium:bloopInstall
2024.03.24 17:51:06 INFO  > Task :prover-commons:spark:bloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:commons:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:showcase:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:assembly:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:parsing:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:unused:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:integration:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:web:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:core:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:benchmark:configureBloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:commons:bloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:parsing:bloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:benchmark:bloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:unused:bloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:integration:bloopInstall
2024.03.24 17:51:06 INFO  > Task :parent:assembly:bloopInstall
2024.03.24 17:51:07 INFO  > Task :parent:core:bloopInstall
2024.03.24 17:51:07 INFO  > Task :parent:web:bloopInstall
2024.03.24 17:51:07 INFO  > Task :parent:showcase:bloopInstall
2024.03.24 17:51:07 INFO  
2024.03.24 17:51:07 INFO  Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
2024.03.24 17:51:07 INFO  
2024.03.24 17:51:07 INFO  You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
2024.03.24 17:51:07 INFO  
2024.03.24 17:51:07 INFO  For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
2024.03.24 17:51:07 INFO  
2024.03.24 17:51:07 INFO  BUILD SUCCESSFUL in 2s
2024.03.24 17:51:07 INFO  44 actionable tasks: 35 executed, 9 up-to-date
2024.03.24 17:51:07 INFO  time: ran 'gradle bloopInstall' in 2.86s
2024.03.24 17:51:09 INFO  Attempting to connect to the build server...
2024.03.24 17:51:09 INFO  Bloop uses /usr/lib/jvm/java-11-openjdk-amd64 defined at /home/peng/.bloop/bloop.json
2024.03.24 17:51:09 ERROR Starting the bsp launcher for bloop...
2024.03.24 17:51:09 ERROR Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher5371718133495011161/bsp.socket'...
2024.03.24 17:51:09 ERROR Waiting for the bsp connection to come up...
2024.03.24 17:51:09 ERROR error: The command bsp --protocol local --socket /tmp/bsp-launcher5371718133495011161/bsp.socket returned with an error
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-compiler/2.13.12/ba2bfd2991537e8a5163c502f7c326a23acf74a4/scala-compiler-2.13.12.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-bridge_2.13/1.6.1/15798fdc2d9dca8962ba3c14ae8deaf34eca2213/compiler-bridge_2.13-1.6.1-sources.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-interface/1.6.1/fa68930e1686c5d251a025ae656fa1e5f0af53fc/compiler-interface-1.6.1.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-reflect/2.13.12/88be4dbc90fdd2d12c05b6a872a9add60524461d/scala-reflect-2.13.12.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.13.12/3c51da898af4ebfac356fcde11388afb2ae8ee82/scala-library-2.13.12.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/util-interface/1.6.1/b6280fa8056b59788d04084994fcf5ee9f1ca9f0/util-interface-1.6.1.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[31m[E][0m Failed to load project from /home/peng/git/spookystuff/.bloop/core.json
2024.03.24 17:51:09 ERROR error: Trying a tcp-based connection to the server instead...
2024.03.24 17:51:09 ERROR Opening a bsp server connection with 'bsp --protocol tcp --port 20258'...
2024.03.24 17:51:09 ERROR Waiting for the bsp connection to come up...
2024.03.24 17:51:09 ERROR error: The command bsp --protocol tcp --port 20258 returned with an error
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-compiler/2.13.12/ba2bfd2991537e8a5163c502f7c326a23acf74a4/scala-compiler-2.13.12.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-bridge_2.13/1.6.1/15798fdc2d9dca8962ba3c14ae8deaf34eca2213/compiler-bridge_2.13-1.6.1-sources.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-compiler/2.13.12/ba2bfd2991537e8a5163c502f7c326a23acf74a4/scala-compiler-2.13.12.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-interface/1.6.1/fa68930e1686c5d251a025ae656fa1e5f0af53fc/compiler-interface-1.6.1.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-bridge_2.13/1.6.1/15798fdc2d9dca8962ba3c14ae8deaf34eca2213/compiler-bridge_2.13-1.6.1-sources.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-reflect/2.13.12/88be4dbc90fdd2d12c05b6a872a9add60524461d/scala-reflect-2.13.12.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-interface/1.6.1/fa68930e1686c5d251a025ae656fa1e5f0af53fc/compiler-interface-1.6.1.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.13.12/3c51da898af4ebfac356fcde11388afb2ae8ee82/scala-library-2.13.12.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-reflect/2.13.12/88be4dbc90fdd2d12c05b6a872a9add60524461d/scala-reflect-2.13.12.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/util-interface/1.6.1/b6280fa8056b59788d04084994fcf5ee9f1ca9f0/util-interface-1.6.1.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.13.12/3c51da898af4ebfac356fcde11388afb2ae8ee82/scala-library-2.13.12.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[33m[W][0m Scala instance jar /home/peng/.gradle/caches/modules-2/files-2.1/org.scala-sbt/util-interface/1.6.1/b6280fa8056b59788d04084994fcf5ee9f1ca9f0/util-interface-1.6.1.jar doesn't exist!
2024.03.24 17:51:09 ERROR > [0m[31m[E][0m Failed to load project from /home/peng/git/spookystuff/.bloop/mldsl-test.json
2024.03.24 17:51:09 ERROR error: The launcher failed to establish a bsp connection, aborting...
2024.03.24 17:51:09 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:92)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:119)
	at scala.meta.internal.metals.BloopServers$$anon$2.run(BloopServers.scala:502)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)


```

### Expected behaviour:

```
$ ./gradlew --stacktrace --console=plain --init-script /tmp/metals5311744264606695985/init-script.gradle bloopInstall
> Task :buildSrc:checkKotlinGradlePluginConfigurationErrors
> Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
> Task :buildSrc:extractPrecompiledScriptPluginPlugins UP-TO-DATE
> Task :buildSrc:compilePluginsBlocks UP-TO-DATE
> Task :buildSrc:generatePrecompiledScriptPluginAccessors UP-TO-DATE
> Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE

> Configure project :
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in root project 'spookystuff' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':repack' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:assembly' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:benchmark' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:commons' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:core' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:integration' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:parsing' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:showcase' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:unused' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':parent:web' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons:core' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons:meta2' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons:spark' / scalaCompilerPlugins
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':repack:selenium' / scalaCompilerPlugins
Sonatype API key not defined, skipping configuration of Maven Central publishing repository
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration
PGP signing key not defined, skipping signing configuration

> Configure project :prover-commons:core
using io.tryp:splain_2.13.13:1.1.0-RC1 ...	 in project ':prover-commons:core' / dependencies

> Task :parent:configureBloopInstall
> Task :prover-commons:configureBloopInstall
> Task :repack:configureBloopInstall
> Task :configureBloopInstall
> Task :prover-commons:meta2:configureBloopInstall
> Task :parent:bloopInstall
> Task :prover-commons:bloopInstall
> Task :bloopInstall
> Task :prover-commons:core:configureBloopInstall
> Task :repack:bloopInstall
> Task :repack:selenium:configureBloopInstall
> Task :prover-commons:core:bloopInstall
> Task :prover-commons:meta2:bloopInstall
> Task :repack:selenium:bloopInstall
> Task :prover-commons:spark:configureBloopInstall
> Task :parent:showcase:configureBloopInstall
> Task :parent:assembly:configureBloopInstall
> Task :parent:parsing:configureBloopInstall
> Task :parent:commons:configureBloopInstall
> Task :parent:benchmark:configureBloopInstall
> Task :parent:web:configureBloopInstall
> Task :parent:core:configureBloopInstall
> Task :parent:unused:configureBloopInstall
> Task :parent:integration:configureBloopInstall
> Task :prover-commons:spark:bloopInstall
> Task :parent:parsing:bloopInstall
> Task :parent:commons:bloopInstall
> Task :parent:assembly:bloopInstall
> Task :parent:benchmark:bloopInstall
> Task :parent:web:bloopInstall
> Task :parent:integration:bloopInstall
> Task :parent:showcase:bloopInstall
> Task :parent:core:bloopInstall
> Task :parent:unused:bloopInstall

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 2s

```

**Operating system:**
Linux

**Java version:**
11.0.22

**Editor/extension:**
Visual Studio Code - Insiders v1.88.0-insider

**Metals version:**
1.2.2

### Extra context or search terms:

Gradle version is 8.7

### Workspace information:
 - **Scala versions:2.13.13** 
 - **Build tools:** 0. gradle
 - **Build servers:**
    0. Disconnected: Bloop
 - **All build tools in workspace:** Bloop; Gradle

**Comment by tgodzik** [comment]
Thanks for reporting! Any idea where these jars come from and why they were deleted? Is this an issue with the newer Gradle? Did you maybe update recently?

Do you have a project this fails in?

**Comment by tribbloid** [comment]
no idea :D I've deleted all 2.13.12 declaring or moved to 2.13.13 in my project. The local .gradle repo is also cleaned and downloaded from scratch

in fact, even metals doesn't use it (still on 2.13.10), is there a stacktrace option that can reveal where it came from?

**Comment by tgodzik** [comment]
You could try inspecting the .json files inside `.bloop`, if the version there is the old one it means they are not correctly imported and we might need to fix in the bloop-gradle plugin

You could also try fully reseting the codebase via a command or just remove .bloop files so that we are sure things are being generated anew.

**Comment by kasiaMarek** [comment]
I wasn't able to reproduce that behaviour but I've noticed that gradle `bloopInstall` doesn't properly clean previous information. E.g. if you rename the project the old build targets are still there.
![Screenshot 2024-04-09 at 13 06 33](https://github.com/scalameta/metals/assets/26606662/0d86f652-1876-4f12-b7de-5b9ff747fb56)
![Screenshot 2024-04-09 at 13 07 14](https://github.com/scalameta/metals/assets/26606662/0fc1d7fd-c85b-4a64-9ef0-6cd31db3cd0b)

@tribbloid, did deleting `.bloop` solved your issue?

**Comment by tribbloid** [comment]
@kasiaMarek yes I have tested your solution and it worked!
