### ISSUE TITLE
NoSuchMethodError: sbt.internal.Load$.reapply

### ISSUE THREAD

**Issue by ggPeti** [scalameta/metals#635]
**Describe the bug**
`sbt metalsEnable bloopInstall` fails with a stack trace like:

```
java.lang.NoSuchMethodError: sbt.internal.Load$.reapply(Lscala/collection/Seq;Lsbt/internal/BuildStructure;Lsbt/util/Show;)Lsbt/internal/BuildStructure;
[error]   at sbt.Compat$.appendImpl(MetalsPlugin.scala:111)
[error]         at sbt.Compat$.appendWithSession(MetalsPlugin.scala:94)
[error]         at scala.meta.metals.MetalsPlugin$.$anonfun$metalsEnable$1(MetalsPlugin.scala:72)
[error]         at sbt.Command$.$anonfun$command$2(Command.scala:91)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
```

I cannot easily give you a SSCCE unfortunately. But in general, does anyone have an idea what could be the root cause of this kind of error?

**Comment by olafurpg** [comment]
Thanks for reporting! What Scala version are you using? We support 0.13.17+

**Comment by ggPeti** [comment]
You surely mean sbt, and we use 1.2.0 in here. Thanks for the info, actually even sbt 1.1.0 will work with Metals.

**Comment by olafurpg** [comment]
Whoops, yes, meant "sbt version".

Hmm, I use metals with sbt 1.2.8 and we publish the plugin compiled against 1.0.4, I wonder what might have caused the problem on 1.2.0 🤔

**Comment by ryneflood** [comment]
in case anyone stumbles on this, I had the same issue with sbt 1.2.0, but using 1.2.8 fixes it
