### ISSUE TITLE
Сonstant Scalafix errors

### ISSUE THREAD

**Issue by brndt** [scalameta/metals#6501]
### Describe the bug

Sorry, don't know how to reproduce it. I will attach logs and scalafix configuration, maybe it will hep to resolve it.

The popup "Unable to run scalafix..." appears while working with the code, I don't trigger it by myself.

Configuration:
```
rules = [
  DisableSyntax
  LeakingImplicitClassVal
  NoAutoTupling
  NoValInForComprehension
  OrganizeImports
]

OrganizeImports.targetDialect = Scala3
```

Logs:
```
2024.06.12 21:18:48 ERROR Unable to run scalafix, please check logs for more info.
java.util.concurrent.ExecutionException: Boxed Exception
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolve(Promise.scala:99)
	at scala.concurrent.impl.Promise$Transformation.handleFailure(Promise.scala:444)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:506)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1570)
Caused by: java.util.ServiceConfigurationError: scalafix.v1.Rule: scalafix.internal.rule.DisableSyntax not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1269)
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1305)
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1387)
	at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.hasNext(JavaCollectionWrappers.scala:46)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1446)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1446)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1303)
	at scalafix.internal.v1.Rules$.all(Rules.scala:104)
	at scalafix.v1.RuleDecoder$$anon$1.<init>(RuleDecoder.scala:106)
	at scalafix.v1.RuleDecoder$.decoder(RuleDecoder.scala:105)
	at scalafix.internal.v1.Args.ruleDecoder(Args.scala:253)
	at scalafix.internal.v1.Args.configuredRules(Args.scala:287)
	at scalafix.internal.v1.Args.$anonfun$validate$1(Args.scala:421)
	at metaconfig.Configured.andThen(Configured.scala:45)
	at scalafix.internal.v1.Args.validate(Args.scala:417)
	at scalafix.internal.interfaces.ScalafixArgumentsImpl.evaluate(ScalafixArgumentsImpl.scala:43)
	at scala.meta.internal.metals.ScalafixProvider.$anonfun$scalafixEvaluate$11(ScalafixProvider.scala:410)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1570)

2024.06.12 21:18:48 ERROR Unable to run scalafix, please check logs for more info.
java.util.concurrent.ExecutionException: Boxed Exception
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolve(Promise.scala:99)
	at scala.concurrent.impl.Promise$Transformation.handleFailure(Promise.scala:444)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:506)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1570)
Caused by: java.util.ServiceConfigurationError: scalafix.v1.Rule: scalafix.internal.rule.DisableSyntax not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1269)
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1305)
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1387)
	at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.hasNext(JavaCollectionWrappers.scala:46)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1446)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1446)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1303)
	at scalafix.internal.v1.Rules$.all(Rules.scala:104)
	at scalafix.v1.RuleDecoder$$anon$1.<init>(RuleDecoder.scala:106)
	at scalafix.v1.RuleDecoder$.decoder(RuleDecoder.scala:105)
	at scalafix.internal.v1.Args.ruleDecoder(Args.scala:253)
	at scalafix.internal.v1.Args.configuredRules(Args.scala:287)
	at scalafix.internal.v1.Args.$anonfun$validate$1(Args.scala:421)
	at metaconfig.Configured.andThen(Configured.scala:45)
	at scalafix.internal.v1.Args.validate(Args.scala:417)
	at scalafix.internal.interfaces.ScalafixArgumentsImpl.evaluate(ScalafixArgumentsImpl.scala:43)
	at scala.meta.internal.metals.ScalafixProvider.$anonfun$scalafixEvaluate$11(ScalafixProvider.scala:410)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1570)

Jun 12, 2024 9:18:48 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.util.concurrent.ExecutionException: Boxed Exception
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: Boxed Exception
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.util.concurrent.ExecutionException: Boxed Exception
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolve(Promise.scala:99)
	at scala.concurrent.impl.Promise$Transformation.handleFailure(Promise.scala:444)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:506)
	... 3 more
Caused by: java.util.ServiceConfigurationError: scalafix.v1.Rule: scalafix.internal.rule.DisableSyntax not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1269)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1305)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1387)
	at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.hasNext(JavaCollectionWrappers.scala:46)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1446)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1446)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1303)
	at scalafix.internal.v1.Rules$.all(Rules.scala:104)
	at scalafix.v1.RuleDecoder$$anon$1.<init>(RuleDecoder.scala:106)
	at scalafix.v1.RuleDecoder$.decoder(RuleDecoder.scala:105)
	at scalafix.internal.v1.Args.ruleDecoder(Args.scala:253)
	at scalafix.internal.v1.Args.configuredRules(Args.scala:287)
	at scalafix.internal.v1.Args.$anonfun$validate$1(Args.scala:421)
	at metaconfig.Configured.andThen(Configured.scala:45)
	at scalafix.internal.v1.Args.validate(Args.scala:417)
	at scalafix.internal.interfaces.ScalafixArgumentsImpl.evaluate(ScalafixArgumentsImpl.scala:43)
	at scala.meta.internal.metals.ScalafixProvider.$anonfun$scalafixEvaluate$11(ScalafixProvider.scala:410)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	... 3 more

2024.06.12 21:18:47 INFO  compiling root (1 scala source)
2024.06.12 21:18:48 INFO  time: compiled root in 0.44s

```

Scala version 3.4.2

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

**Comment by tgodzik** [comment]
Thanks for reporting! I have seen this before and hoped this was fixed, but it seems like this reproduces in your workspace. Any chance to take a look at a reproduction?
 
@bjaglin Did you ever see an issue like that? My guess is that we are loading interface from a different classloader than the class, but I can't figure it out where.

**Comment by brndt** [comment]
@tgodzik 
https://github.com/scalameta/metals/assets/21007364/3b611e14-0679-494d-b34b-660d10151c43

**Comment by brndt** [comment]
The curious thing is that the popup always appears when i move cursor to the unused import

**Comment by brndt** [comment]
https://github.com/scalameta/metals/assets/21007364/848d3f2e-e1df-4acf-9fe3-8399becd66ed

**Comment by tgodzik** [comment]
I merged a potential fix, which should be available in the new release (being released today). Do let me know if anything helped, I also added additional reporting that will show up in .metals/reports in case of any issues

**Comment by bjaglin** [comment]
@tgodzik it doesn't ring a bell - https://github.com/scalameta/metals/pull/6516/files#r1642699326 does look like a potential culprit indeed, let's see 🤞

**Comment by brndt** [comment]
@tgodzik
So far I haven't had this problem after the fix.
I think we can close it.
