### ISSUE TITLE
java.lang.NoSuchMethodError: 'void bloop.config.Config$Scala.<init>

### ISSUE THREAD

**Issue by tanin47** [scalameta/metals#6592]
### Describe the bug

After the sbt-bloop is upgraded from 1.5.17 to 1.6.0, I've got the below error:

```
[error] Couldn't run bloopGenerate. The issue could be caused by failing to compile the project.
[error] java.lang.NoSuchMethodError: 'void bloop.config.Config$Scala.<init>(java.lang.String, java.lang.String, java.lang.String, scala.collection.immutable.List, scala.collection.immutable.List, scala.Option, scala.Option)'
[error] 	at bloop.integrations.sbt.BloopDefaults$.$anonfun$bloopGenerate$4(SbtBloop.scala:1035)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:[24](https://github.com/klutchlabs/klutch/actions/runs/9920720283/job/27407895387#step:11:25))
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:[26](https://github.com/klutchlabs/klutch/actions/runs/9920720283/job/27407895387#step:11:27)5)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Expected behavior

It shouldn't have crashed.

Quick question: is there a way to lock down Metals' version? 

Currently, it keeps upgrading and we have to keep rolling back the version of bloop in `project/metals.sbt`

Thank you.

### Operating system

macOS

### Editor/Extension

None

### Version of Metals

v1.3.2

**Comment by tgodzik** [comment]
Thanks for reporting, I need to check how is this possible, but in the meantime you should be able to set the bloop version in the settings or change the setting that says that Bloop is already installed. Let me know if you need help finding those

**Comment by tanin47** [comment]
@tgodzik thank you so much.

This is due to the fact that my project depends on another project like below:

```
lazy val root = Project("plugins", file("."))
  .aggregate(SbtSvelte)
  .dependsOn(SbtSvelte)
lazy val SbtSvelte = RootProject(uri("https://github.com/tanin47/sbt-svelte.git#4961b9aad6f43c8df347071278b817d201626de3"))
```

Then, the main project is upgraded to 1.6 but sbt-svelte is at 1.5.

I upgraded sbt-svelte to 1.6. Now I can upgrade the main project to 1.6.

I am a bit surprised that Scala Metals, which is for IDE, plays a significant role in `sbt compile` in CI. I wonder if there's a way to configure it to only impact the IDE.

Thank you so much. Your comment is tremendously helpful.

**Comment by tgodzik** [comment]
Och and actually you should not commit metals.sbt to the CI, best to add it to .gitignore

**Comment by tanin47** [comment]
oh wow such a simple solution. Thank you so much.
