### ISSUE TITLE
`JdbcBatchUpdateException`: Unique index or primary key violation

### ISSUE THREAD

**Issue by filipwiech** [scalameta/metals#6643]
### Describe the bug

Noticed the following error in the Metals log after fresh project indexing:
```
2024.07.30 21:02:25 INFO  Database: jdbc:h2:file:/home/user/.metals/metals (H2 2.3)
2024.07.30 21:02:25 WARN  Flyway upgrade recommended: H2 2.3.230 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.220.
2024.07.30 21:02:25 INFO  Successfully validated 1 migration (execution time 00:00.002s)
2024.07.30 21:02:25 INFO  Current version of schema "PUBLIC": 1
2024.07.30 21:02:25 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2024.07.30 21:02:31 WARN  org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_3 ON PUBLIC.TOPLEVEL_SYMBOL(JAR, PATH, SYMBOL) VALUES ( /* key:20684 */ 107, '/org/scalatest/enablers/TableAsserting.scala', 'org/scalatest/enablers/ForResult#')"; SQL statement:
insert into toplevel_symbol (symbol, path, jar) values (?, ?, ?) [23505-230]
	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1277)
	at scala.meta.internal.metals.JarTopLevels.putToplevels(JarTopLevels.scala:139)
	at scala.meta.internal.metals.JarTopLevels.$anonfun$putJarIndexingInfo$1(JarTopLevels.scala:85)
	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.scala:17)
	at scala.Option.map(Option.scala:242)
	at scala.meta.internal.metals.JarTopLevels.putJarIndexingInfo(JarTopLevels.scala:84)
	at scala.meta.internal.metals.Indexer.addSourceJarSymbols(Indexer.scala:666)
	at scala.meta.internal.metals.Indexer.$anonfun$indexDependencySources$5(Indexer.scala:491)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:905)
	at scala.meta.internal.metals.Indexer.$anonfun$indexDependencySources$1(Indexer.scala:482)
	at scala.meta.internal.metals.Indexer.$anonfun$indexDependencySources$1$adapted(Indexer.scala:481)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at scala.meta.internal.metals.Indexer.indexDependencySources(Indexer.scala:481)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$17(Indexer.scala:302)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$16(Indexer.scala:295)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$16$adapted(Indexer.scala:291)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at scala.meta.internal.metals.Indexer.indexWorkspace(Indexer.scala:291)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$2(Indexer.scala:167)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$1(Indexer.scala:167)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:840)
2024.07.30 21:02:48 INFO  time: indexed workspace in 45s
```

Seems that something in the Scalatest (we use 3.2.19) is breaking the indexing process:
```
VALUES ( /* key:20684 */ 107, '/org/scalatest/enablers/TableAsserting.scala', 'org/scalatest/enablers/ForResult#')
```

Observed in the project with Scala 3.5.0-RC6, SBT 1.10.1 and Bloop 1.6.0. :+1: 

### Expected behavior

No error present.

### Operating system

Linux

### Editor/Extension

Other

### Version of Metals

1.3.4+23-c744a47f-SNAPSHOT

### Extra context or search terms

JDBC, SQL, DB, database, H2, indexing

**Comment by filipwiech** [comment]
Sorry, just realized that the same issue is already reported in #6408 and #6630, will close this one as duplicate. :+1:

**Comment by kasiaMarek** [comment]
Actually it's good to have it in a separate issue.
