### ISSUE TITLE
Issues when trying to run a test

### ISSUE THREAD

**Issue by kostaskougios** [scalameta/metals#6656]
### Describe the bug

I got a couple of issues lately when trying to run scala tests.

- despite there are no compilation errors , the test runner doesn't start, I see this error in metals.log:

```
exception caught when loading class module-info: java.lang.AssertionError: assertion failed: attempt to parse java.lang.Object from classfile
Aug 07, 2024 3:43:08 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.DiscoveryFailures$WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.DiscoveryFailures$WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: scala.meta.internal.metals.debug.DiscoveryFailures$WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.DiscoveryFailures$WorkspaceErrorsException$.<clinit>(DiscoveryFailures.scala:53)
	at scala.meta.internal.metals.debug.DebugProvider.ensureNoWorkspaceErrors(DebugProvider.scala:443)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$startTestSuite$5(DebugProvider.scala:615)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	... 3 more
```

I am able to reproduce this by going to a test, adding an error (i.e. "x" on any line), compiling with errors, then fixing the error, recompiling, trying to run the test and the issue happens. Well at least that happens on my test-repo:

https://github.com/kostaskougios/metals-bugs

if you can't reproduce with any test, checkout the above, open class Map3DTest, run it, it should run. Put "x" on a random line to create a compilation error, compile, run, it doesn't run, so far so good. Fix the compilation issue and try to run the test, it won't run and you should see the exception in the log.

Also there is no visible error msg in vscode , it just does nothing when trying to run the test.

- rather frequently tests start running but gets stuck seemingly doing nothing. Can't reproduce this one. After restarting vscode, test run OK.

- also tests run very slowly (this was the case till yesterday, today they seem to run faster), but always in debugging mode. Do they have to run in debugging mode?

### Expected behavior

tests to run normally

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.39.2

**Comment by tgodzik** [comment]
Thanks for reporting! I will try to reproduce your issue, if I can't I will probably relax the requirement since it seems the error detection is rather flaky.

> also tests run very slowly (this was the case till yesterday, today they seem to run faster), but always in debugging mode. Do they have to run in debugging mode?

debugging mode is the default, but you can actually run without debugging which should be much faster. You probably need to do a right click and choose `run test`. You can choose the default action with `testing.defaultGutterClickAction`

**Comment by kostaskougios** [comment]
ah ok thanks for the debugging hint, I was actually pressing cmd-; + cmd-f which reruns tests in debugging, I should be pressing cmd-; + f  to just run them.

Anyway I'll add any extra info for the rest of the issues if I manage to find any.
