### ISSUE TITLE
PC errors in build.sbt: illegal cyclic reference involving object Main

### ISSUE THREAD

**Issue by dos65** [scalameta/metals#6657]
### Describe the bug

I'm often getting this kind of error when I work with build.sbt

```
[Error - 23:20:33] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object Main
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object Main
``` 

After that nothing from PC (completion, hovers) doesn't work in this file.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting! Does it happen in any build.sbt project or are you able to send a reproduction? Do you have any object Main in sbt?

**Comment by tgodzik** [comment]
Also, is there anything further after `Caused by: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object Main`? I would assume the PC would get restarted after an error like that

**Comment by dos65** [comment]
@tgodzik I will try to minimilize it. I noticed that issue few weeks ago but didn't have time to investigate it. Decided to report it as is at least to raise awareness
