### ISSUE TITLE
Unable to build docs

### ISSUE THREAD

**Issue by scarf005** [scalameta/metals#6703]
## Summary

Unable to build docs site following https://scalameta.org/metals/docs/contributors/updating-website#running-the-site-locally

## Reproduction

followed the [documentation](https://scalameta.org/metals/docs/contributors/updating-website#running-the-site-locally) verbatim.

```
$ git clone https://github.com/scalameta/metals.git --filter=blob:none
$ cd metals
$ cs setup
$ sbt
> docs/run -w
```

## Output

```
$ sbt                                          1m  2024년 08월 22일 (목) 오후 11시 14분 18초
Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/home/scarf/.config/java
copying runtime jar...
Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/home/scarf/.config/java
Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/home/scarf/.config/java
[info] [launcher] getting org.scala-sbt sbt 1.9.9  (this may take some time)...
[info] [launcher] getting Scala 2.12.18 (for sbt)...
[info] welcome to sbt 1.9.9 (Oracle Corporation Java 23)
[info] loading settings for project metals-build from plugins.sbt ...
[info] loading project definition from /home/scarf/repo/etc/one-time-contribution/metals/project
[info] Updating 
<installation log omitted for brevity>
[info] Resolved  dependencies
[info] Fetching artifacts of 
<installation log omitted for brevity>
[info] Fetched artifacts of 
[info] compiling 26 Java sources to /home/scarf/repo/etc/one-time-contribution/metals/mtags-interfaces/target/classes ...
[warn] source value 8 is obsolete and will be removed in a future release
[warn] target value 8 is obsolete and will be removed in a future release
[warn] To suppress warnings about obsolete options, use -Xlint:-options.
[info] compiling 65 Scala sources to /home/scarf/repo/etc/one-time-contribution/metals/mtags-shared/target/scala-2.13.14/classes ...
[warn] /home/scarf/repo/etc/one-time-contribution/metals/mtags-shared/src/main/scala/scala/meta/internal/pc/CompilerWrapper.scala:17:16: parameter params in method compiler is never used
[warn]   def compiler(params: VirtualFileParams): Compiler = compiler()
[warn]                ^
[warn] 1 deprecation; re-run with -deprecation for details
[warn] two warnings found
[info] compiling 14 Scala sources to /home/scarf/repo/etc/one-time-contribution/metals/mtags-java/target/scala-2.13/classes ...
[info] compiling 107 Scala sources to /home/scarf/repo/etc/one-time-contribution/metals/mtags/target/scala-2.13.14/classes ...
[warn] 1 deprecation; re-run with -deprecation for details
[warn] one warning found
[warn] 33 deprecations
[warn] 1 deprecation (since 1.2)
[warn] 15 deprecations (since 2.13.0)
[warn] 2 deprecations (since 2.13.1)
[warn] 3 deprecations (since 2.13.3)
[warn] 1 deprecation (since 20)
[warn] 55 deprecations in total; re-run with -deprecation for details
[warn] 7 warnings found
[info] compiling 368 Scala sources to /home/scarf/repo/etc/one-time-contribution/metals/metals/target/scala-2.13/classes ...
[warn] /home/scarf/repo/etc/one-time-contribution/metals/metals/src/main/scala/scala/meta/internal/bsp/BspConfigGenerator.scala:30:5: parameter statusBar in class BspConfigGenerator is never used
[warn]     statusBar: StatusBar,
[warn]     ^
[warn] 78 deprecations
[warn] 1 deprecation (since 0.9.0)
[warn] 1 deprecation (since 1.2)
[warn] 1 deprecation (since 2.11.0)
[warn] 24 deprecations (since 2.13.0)
[warn] 22 deprecations (since 2.13.3)
[warn] 9 deprecations (since 2.13.7)
[warn] 1 deprecation (since >4.4.35)
[warn] 137 deprecations in total; re-run with -deprecation for details
[warn] 10 warnings found
[info] compiling 20 Scala sources to /home/scarf/repo/etc/one-time-contribution/metals/metals-docs/target/scala-2.13/classes ...
[warn] 1 deprecation; re-run with -deprecation for details
[warn] one warning found
[info] running docs.Docs -w
[error] java.lang.RuntimeException: UT000202: Failed to initialize path manager for '/home/scarf/repo/etc/one-time-contribution/metals/website/target/docs' path.
[error]         at io.undertow.server.handlers.resource.PathResourceManager.<init>(PathResourceManager.java:145)
[error]         at io.undertow.server.handlers.resource.PathResourceManager.<init>(PathResourceManager.java:122)
[error]         at io.undertow.server.handlers.resource.PathResourceManager.<init>(PathResourceManager.java:118)
[error]         at io.undertow.server.handlers.resource.PathResourceManager.<init>(PathResourceManager.java:78)
[error]         at mdoc.internal.livereload.UndertowLiveReload$.apply(UndertowLiveReload.scala:82)
[error]         at mdoc.internal.cli.MainOps.startLivereload(MainOps.scala:55)
[error]         at mdoc.internal.cli.MainOps.run(MainOps.scala:187)
[error]         at mdoc.internal.cli.MainOps$.process(MainOps.scala:286)
[error]         at mdoc.MainProcess.process(Main.scala:44)
[error]         at mdoc.MainProcess.process$(Main.scala:43)
[error]         at mdoc.Main$.process(Main.scala:13)
[error]         at docs.Docs$.main(Docs.scala:91)
[error]         at docs.Docs.main(Docs.scala)
[error]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[error] Caused by: java.nio.file.NoSuchFileException: /home/scarf/repo/etc/one-time-contribution/metals/website/target/docs
[error]         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[error]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[error]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[error]         at java.base/sun.nio.fs.UnixPath.toRealPath(UnixPath.java:936)
[error]         at io.undertow.server.handlers.resource.PathResourceManager.<init>(PathResourceManager.java:142)
[error]         at io.undertow.server.handlers.resource.PathResourceManager.<init>(PathResourceManager.java:122)
[error]         at io.undertow.server.handlers.resource.PathResourceManager.<init>(PathResourceManager.java:118)
[error]         at io.undertow.server.handlers.resource.PathResourceManager.<init>(PathResourceManager.java:78)
[error]         at mdoc.internal.livereload.UndertowLiveReload$.apply(UndertowLiveReload.scala:82)
[error]         at mdoc.internal.cli.MainOps.startLivereload(MainOps.scala:55)
[error]         at mdoc.internal.cli.MainOps.run(MainOps.scala:187)
[error]         at mdoc.internal.cli.MainOps$.process(MainOps.scala:286)
[error]         at mdoc.MainProcess.process(Main.scala:44)
[error]         at mdoc.MainProcess.process$(Main.scala:43)
[error]         at mdoc.Main$.process(Main.scala:13)
[error]         at docs.Docs$.main(Docs.scala:91)
[error]         at docs.Docs.main(Docs.scala)
[error]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[error] stack trace is suppressed; run last docs / Compile / run for the full output
[error] (docs / Compile / run) UT000202: Failed to initialize path manager for '/home/scarf/repo/etc/one-time-contribution/metals/website/target/docs' path.
[error] Total time: 162 s (02:42), completed 2024. 8. 22. 오후 11:19:45
sbt:default-290e0c> 
```

## System Information

```
coursier: 2.1.10
sbt:1.10.1
Scala CLI version: 1.4.3
Scala version (default): 3.4.2
Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/home/scarf/.config/java

$ java --version
openjdk 23 2024-09-17
OpenJDK Runtime Environment (build 23+36-2368)
OpenJDK 64-Bit Server VM (build 23+36-2368, mixed mode, sharing)

OS: KDE neon jammy 22.04 x86_64
```

**Comment by kasiaMarek** [comment]
Thanks for the report. It seems the folder wasn't created. You can just create `/home/scarf/repo/etc/one-time-contribution/metals/website/target/docs` manually to have it working.

**Comment by scarf005** [comment]
is it possible to edit `sbt` (or other build setup) to `mkdir -p website/target/docs`? i'm willing to open a PR.

**Comment by kasiaMarek** [comment]
> would it be possible to edit sbt (or other build setup) to mkdir -p website/target/docs?

I already added a fix in: https://github.com/scalameta/metals/pull/6704 😄
