### ISSUE TITLE
ERROR issues while parsing: UnexpectedInputEndException

### ISSUE THREAD

**Issue by susliko** [scalameta/metals#6717]
### Describe the bug

1. Create file `doobie.scala`
```scala
//> using scala 2.13
//> using dep org.tpolecat::doobie-free::1.0.0-RC5

import doobie.free._

trait X
```
2. Execute `scala-cli setup-ide doobie.scala`
3. Open file with any editor, import the build
4. Open logs:
```
2024.08.25 21:04:03 ERROR issues while parsing: /home/susliko/.cache/coursier/v1/https/repo1.maven.org/maven2/org/tpolecat/doobie-free_2.13/1.0.0-RC5/doobie-free_2.13-1.0.0-RC5-sources.jar
scala.meta.internal.tokenizers.package$UnexpectedInputEndException
        at scala.meta.internal.tokenizers.LegacyScanner.$anonfun$nextToken$1(LegacyScanner.scala:172)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at scala.meta.internal.tokenizers.LegacyScanner.scala$meta$internal$tokenizers$LegacyScanner$$nextToken(LegacyScanner.scala:178)
        at scala.meta.internal.tokenizers.LegacyScanner.nextToken(LegacyScanner.scala:172)
        at scala.meta.internal.mtags.ScalaToplevelMtags$XtensionScanner.mtagsNextToken(ScalaToplevelMtags.scala:72)
        at scala.meta.internal.mtags.ScalaToplevelMtags.loop(ScalaToplevelMtags.scala:481)
        at scala.meta.internal.mtags.ScalaToplevelMtags.indexRoot(ScalaToplevelMtags.scala:84)
        at scala.meta.internal.mtags.MtagsIndexer.index(MtagsIndexer.scala:21)
        at scala.meta.internal.mtags.MtagsIndexer.index$(MtagsIndexer.scala:20)
        at scala.meta.internal.mtags.ScalaToplevelMtags.index(ScalaToplevelMtags.scala:44)
        at scala.meta.internal.mtags.Mtags.indexWithOverrides(Mtags.scala:74)
        at scala.meta.internal.mtags.SymbolIndexBucket.indexSource(SymbolIndexBucket.scala:124)
        at scala.meta.internal.mtags.SymbolIndexBucket.addSourceFile(SymbolIndexBucket.scala:107)
        at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$addSourceJar$2(SymbolIndexBucket.scala:71)
...
```

### Expected behavior

No exceptions while indexing dependency jars

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting! This actually a valid exception since that file ends in the middle, the source is broken. I added an improvement to handle single broken file like that
