### ISSUE TITLE
scala.reflect.internal.Positions$ValidateException: Enclosing tree [xxx] does not include tree [yyy]

### ISSUE THREAD

**Issue by puffnfresh** [scalameta/metals#674]
**Describe the bug**

Trying to import my large code base and the log contains an error. My coworker has confirmed this problem:

```
scala.reflect.internal.Positions$ValidateException: Enclosing tree [xxx] does not include tree [yyy]
        at scala.reflect.internal.Positions$class.positionError$1(Positions.scala:102)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:124)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
        at scala.reflect.internal.Positions$class.validatePositions(Positions.scala:147)
        at scala.reflect.internal.SymbolTable.validatePositions(SymbolTable.scala:16)
        at scala.tools.nsc.ast.parser.SyntaxAnalyzer$ParserPhase.apply(SyntaxAnalyzer.scala:102)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
        at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:207)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:178)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:162)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:49)
```

**Expected behavior**

No exception while importing.

**Installation:**
- Operating system: macOS/Linux
- Editor: Visual Studio Code
- Metals version: v0.5.0

**Comment by olafurpg** [comment]
Thanks for reporting! This looks like an issue related to -Yrangepos, which I believe got fixed in the 2.12.x series. What Scala version are you using?

**Comment by puffnfresh** [comment]
Ah yes thanks was just about to comment with Scala version because I realised that would be relevant. We're on 2.11.12

**Comment by olafurpg** [comment]
A workaround is to do the `sbt bloopInstall` step manually and select "Don't show again" when Metals asks to import the build. This means the SemanticDB compiler plugin won't be enabled and editor squiggles won't have range positions, but you should still be able to use completions/hover/definition

You can try the following command
```
METALS_ENABLED=true sbt 'set bloopExportJarClassifiers in Global := Some(Set("sources"))' bloopInstall
```

**Comment by olafurpg** [comment]
Please reopen if the workaround above is not sufficient.
