### ISSUE TITLE
Error downloading org.scalameta:mtags-interfaces:1.3.0+56-a06a024d-SNAPSHOT

### ISSUE THREAD

**Issue by Quafadas** [scalameta/metals#6757]
### Describe the bug

I'm behind a firewall which which prevents open access to maven central. With open access to maven, metals is working great.

I can access maven through an artifactory instance, which I've done my best to configure. 
```COURSIER_REPOSITORIES=ivy2local|https://packages.corp.com/artifactory/maven|https://packages.corp.com/artifactory/sbt```

When I start metals, with scala 3.5.0, I get this result. 
```
2024.09.04 11:51:13 ERROR Failed to resolve Scala 3 presentation compiler for 3.5.0
coursierapi.error.SimpleResolutionError$1: Error downloading org.scalameta:mtags-interfaces:1.3.0+56-a06a024d-SNAPSHOT
  not found: https://packages.corp.com/artifactory/maven/org/scalameta/mtags-interfaces/1.3.0+56-a06a024d-SNAPSHOT/mtags-interfaces-1.3.0+56-a06a024d-SNAPSHOT.pom
  not found: https://packages.corp.com/artifactory/sbt/org/scalameta/mtags-interfaces/1.3.0+56-a06a024d-SNAPSHOT/mtags-interfaces-1.3.0+56-a06a024d-SNAPSHOT.pom
  not found: /home/worker/.ivy2/local/org.scalameta/mtags-interfaces/1.3.0+56-a06a024d-SNAPSHOT/ivys/ivy.xml
  not found: /home/worker/.ivy2/local/org.scalameta/mtags-interfaces/1.3.0+56-a06a024d-SNAPSHOT/ivys/ivy.xml
  download error: Caught java.net.SocketException (Connection reset) while downloading https://oss.sonatype.org/content/repositories/public/org/scalameta/mtags-interfaces/1.3.0+56-a06a024d-SNAPSHOT/mtags-interfaces-1.3.0+56-a06a024d-SNAPSHOT.pom
  download error: Caught java.net.SocketException (Connection reset) while downloading https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/mtags-interfaces/1.3.0+56-a06a024d-SNAPSHOT/mtags-interfaces-1.3.0+56-a06a024d-SNAPSHOT.pom
	at coursierapi.error.SimpleResolutionError.of(SimpleResolutionError.java:11)
	at coursierapi.shaded.coursier.internal.api.ApiHelper$.simpleResError(ApiHelper.scala:371)
	at coursierapi.shaded.coursier.internal.api.ApiHelper$.doFetch(ApiHelper.scala:415)
	at coursierapi.shaded.coursier.internal.api.ApiHelper.doFetch(ApiHelper.scala)
	at coursierapi.Fetch.fetchResult(Fetch.java:244)
	at coursierapi.Fetch.fetch(Fetch.java:239)
	at scala.meta.internal.metals.Embedded$.downloadDependency(Embedded.scala:301)
	at scala.meta.internal.metals.Embedded$.downloadScala3PresentationCompiler(Embedded.scala:346)
	at scala.meta.internal.metals.MtagsResolver$Default.$anonfun$resolve$3(MtagsResolver.scala:158)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1583)

2024.09.04 11:51:13 WARN  unsupported Scala 3.5.0
```

As far as I can tell, this message is terminal - the last line is repeated frequently, and basic editor functionality doesn't work. 

### Expected behavior

Metals to start.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting! This is already fixed in 3.5.1-RC1, we are no longer bumping mtags-interfaces versions unless they are stable.

**Comment by Quafadas** [comment]
That's very exciting... thankyou 🙏 ! 

I hadn't realized, apologies for spam.

**Comment by tgodzik** [comment]
> I hadn't realized, apologies for spam.

It's better to report something always, thanks for doing it!
