### ISSUE TITLE
After some time metals stopped working

### ISSUE THREAD

**Issue by adamw** [scalameta/metals#6828]
### Describe the bug

Unfortunately I don't have much details to share, but after a couple of days working on Ox, Metals just stopped working. I've got an infinitely spinning startup:

<img width="401" alt="image" src="https://github.com/user-attachments/assets/909f2742-056c-4f67-beff-6df547afd291">

And nothing else happens.

I tried closing VS Code, killing all java process, removing `.bsp`, `.metals` and `.bloop` from the source tree, as well as running `sbt clean`. Still, the problems persists. Is there anything else that I can remove?

metals.log:

```
2024.10.08 11:04:15 INFO  Started: Metals version 1.3.5 in folders '/Users/adamw/projects/ox' for client Visual Studio Code 1.94.0.
SLF4J(W): Class path contains multiple SLF4J providers.
SLF4J(W): Found provider [scribe.slf4j.ScribeServiceProvider@1c8acef5]
SLF4J(W): Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@7bd28e4]
SLF4J(W): See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J(I): Actual provider is of type [scribe.slf4j.ScribeServiceProvider@1c8acef5]
2024.10.08 11:04:15 WARN  Flyway upgrade recommended: H2 2.3.230 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.220.
2024.10.08 11:04:15 INFO  Attempting to connect to the build server...
2024.10.08 11:04:17 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/adamw/projects/ox/.metals/bsp.trace.json or /Users/adamw/Library/Caches/org.scalameta.metals/bsp.trace.json
2024.10.08 11:04:17 INFO  time: Connected to build server in 2.03s
2024.10.08 11:04:17 INFO  Connected to Build server: Bloop v1.6.0
2024.10.08 11:04:18 INFO  running doctor check
2024.10.08 11:04:18 INFO  java targets:
2024.10.08 11:04:19 WARN  Flyway upgrade recommended: H2 2.3.230 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.220.
2024.10.08 11:04:19 INFO  time: indexed workspace in 1.83s
2024.10.08 11:04:19 WARN  no build target for: /Users/adamw/projects/ox/core/src/test/scala/ox/flow/FlowOpsDrainTest.scala
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.3.5

**Comment by adamw** [comment]
Ah! After a couple of minutes I got an OOM in the logs:

```
Exception in thread "pool-1-thread-3" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOfRangeByte(Arrays.java:3863)
	at java.base/java.util.Arrays.copyOfRange(Arrays.java:3854)
	at java.base/java.lang.String.<init>(String.java:4788)
	at java.base/java.lang.String.<init>(String.java:1507)
	at java.base/java.lang.StringBuilder.toString(StringBuilder.java:475)
	at scala.meta.internal.tokenizers.LegacyScanner.reportIllegalCharacter$1(LegacyScanner.scala:237)
	at scala.meta.internal.tokenizers.LegacyScanner.fetchOther$1(LegacyScanner.scala:451)
	at scala.meta.internal.tokenizers.LegacyScanner.fetchToken(LegacyScanner.scala:452)
	at scala.meta.internal.tokenizers.LegacyScanner.scala$meta$internal$tokenizers$LegacyScanner$$nextToken(LegacyScanner.scala:195)
	at scala.meta.internal.tokenizers.LegacyScanner.nextTokenOrEof(LegacyScanner.scala:167)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(ScalametaTokenizer.scala:150)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:162)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.$anonfun$tokenize$1(ScalametaTokenizer.scala:16)
	at scala.meta.internal.tokenizers.ScalametaTokenizer$$Lambda/0x000000030151c068.apply(Unknown Source)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:960)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:16)
	at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$1.apply(ScalametaTokenizer.scala:313)
	at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:22)
	at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:13)
	at scala.meta.internal.parsers.ScannerTokens$.apply(ScannerTokens.scala:924)
	at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:34)
	at scala.meta.parsers.Parse$$anon$1.apply(Parse.scala:36)
	at scala.meta.internal.mtags.ScalametaCommonEnrichments$XtensionInputOffset.safeParse(ScalametaCommonEnrichments.scala:565)
	at scala.meta.internal.parsing.Trees.$anonfun$parse$2(Trees.scala:150)
	at scala.meta.internal.parsing.Trees$$Lambda/0x00000003015053a0.apply(Unknown Source)
	at scala.Option.map(Option.scala:242)
	at scala.meta.internal.parsing.Trees.parse(Trees.scala:141)
	at scala.meta.internal.parsing.Trees.$anonfun$get$1(Trees.scala:40)
	at scala.meta.internal.parsing.Trees$$Lambda/0x00000003014ee990.apply(Unknown Source)
	at scala.Option.orElse(Option.scala:477)
	at scala.meta.internal.parsing.Trees.get(Trees.scala:40)
	at scala.meta.internal.parsing.DocumentSymbolProvider.documentSymbols(DocumentSymbolProvider.scala:29)
Oct 08, 2024 11:06:43 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:251)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1180)
	at java.base/java.util.Formatter.parse(Formatter.java:2844)
	at java.base/java.util.Formatter.format(Formatter.java:2774)
	at java.base/java.util.Formatter.format(Formatter.java:2728)
	at java.base/java.lang.String.format(String.java:4390)
	at scala.collection.StringOps$.format$extension(StringOps.scala:991)
	at scala.meta.internal.tokenizers.LegacyScanner.reportIllegalCharacter$1(LegacyScanner.scala:237)
	at scala.meta.internal.tokenizers.LegacyScanner.fetchOther$1(LegacyScanner.scala:451)
	at scala.meta.internal.tokenizers.LegacyScanner.fetchToken(LegacyScanner.scala:452)
	at scala.meta.internal.tokenizers.LegacyScanner.scala$meta$internal$tokenizers$LegacyScanner$$nextToken(LegacyScanner.scala:195)
	at scala.meta.internal.tokenizers.LegacyScanner.nextTokenOrEof(LegacyScanner.scala:167)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(ScalametaTokenizer.scala:150)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:162)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.$anonfun$tokenize$1(ScalametaTokenizer.scala:16)
	at scala.meta.internal.tokenizers.ScalametaTokenizer$$Lambda/0x000000030151c068.apply(Unknown Source)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:960)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:16)
	at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$1.apply(ScalametaTokenizer.scala:313)
	at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:22)
	at scala.meta.internal.metals.codeactions.StringActions.$anonfun$contribute$1(StringActions.scala:36)
	at scala.meta.internal.metals.codeactions.StringActions$$Lambda/0x0000000301505768.apply(Unknown Source)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.metals.codeactions.StringActions.contribute(StringActions.scala:35)
	at scala.meta.internal.metals.codeactions.CodeActionProvider$$anonfun$1.applyOrElse(CodeActionProvider.scala:79)
	at scala.meta.internal.metals.codeactions.CodeActionProvider$$anonfun$1.applyOrElse(CodeActionProvider.scala:77)
	at scala.collection.immutable.List.collect(List.scala:276)
	at scala.meta.internal.metals.codeactions.CodeActionProvider.codeActions(CodeActionProvider.scala:77)
	at scala.meta.internal.metals.MetalsLspService.$anonfun$codeAction$1(MetalsLspService.scala:1213)
	at scala.meta.internal.metals.MetalsLspService$$Lambda/0x00000003014f1a30.apply(Unknown Source)
	at scala.meta.internal.metals.CancelTokens$.future(CancelTokens.scala:38)
	at scala.meta.internal.metals.MetalsLspService.codeAction(MetalsLspService.scala:1212)
```

**Comment by adamw** [comment]
Ok found it ... the problem was a `§` character in one of the lines. Specifically (last but one line):

```
cat core/src/test/scala/ox/flow/FlowOpsDrainTest.scala

package ox.flow

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import ox.*
import java.util.concurrent.atomic.AtomicInteger

class FlowOpsDrainTest extends AnyFlatSpec with Matchers:
  behavior of "drain"

  it should "drain all elements" in:
    val f = Flow.fromValues(1, 2, 3)
    f.drain().runToList() shouldBe List.empty

  it should "run any side-effects that are part of the flow" in:
    val c = new AtomicInteger(0)
    val f = Flow.fromValues(1, 2, 3).tap(_ => c.incrementAndGet().discard)
    f.drain().runDrain()
    c.get() shouldBe 3

  it should "merge with another flow" in:
    val c = new AtomicInteger(0)
    val f1 = Flow.fromValues(1, 2, 3).tap(_ => c.incrementAndGet().discard)
    val f2 = Flow.fromValues(4, 5, 6).tap(_ => c.incrementAndGet().discard)
    f1.drain().merge(f2).runToList()§ shouldBe List(4, 5, 6)
    c.get() shouldBe 6
```

**Comment by tgodzik** [comment]
Och, I fixed that, but it's an evil one. I need to update scalameta and do a release.

**Comment by tgodzik** [comment]
I can confirm it's fixed, we have a test in scalameta
