### ISSUE TITLE
Stuck on Starting Metals server

### ISSUE THREAD

**Issue by DreamLand7707** [scalameta/metals#6862]
### Describe the bug

When I want to create a scala project, I press the icon "Metal" and VSCode will stuck on "Starting Metals server"
Just like:
![image](https://github.com/user-attachments/assets/0c416a58-36b9-4bda-ab77-9e23206eb68c)
![image](https://github.com/user-attachments/assets/c6d594b2-c2fb-4b83-a245-0fa4d745a491)
I set the environment variable:JAVA_HOME correctly: C:\Program Files\Java\jdk-18.0.2.1
![image](https://github.com/user-attachments/assets/01889d7c-5826-4470-81b8-d900a1a01797)
I can't press the buttons: New scala project and Start Metals.

### Expected behavior

Metal should works correctly.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.3.5

**Comment by tgodzik** [comment]
Thanks for reporting! Do you see something in the metals output? `View -> Output -> Select Metals`

**Comment by DreamLand7707** [comment]
> Thanks for reporting! Do you see something in the metals output? `View -> Output -> Select Metals`

Yes, I'll show to you:
![image](https://github.com/user-attachments/assets/7cb6b85e-7b45-4769-9a57-10c2002d514a)

**Comment by DreamLand7707** [comment]
> Thanks for reporting! Do you see something in the metals output? `View -> Output -> Select Metals`

as you can see, it is stuck.

**Comment by tgodzik** [comment]
Looks like it,  though I don't see why. It seems that the MEtal server is not starting, it might be related to another issue that I did a workaround for. You can try updating metals.serverVersion to 1.3.5+180-97cc5572-SNAPSHOT	 to see if that workaround helped.

Related https://github.com/scalameta/metals/issues/6762

**Comment by tgodzik** [comment]
You need to change the setting inside metals extension settings

**Comment by DreamLand7707** [comment]
> 1.3.5+180-97cc5572-SNAPSHOT

I got some error
```
[Error - 01:35:36] Client Metals: connection to server is erroring. Shutting down server.
[Error - 01:35:36] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\common\client.js:914:19)
	at LanguageClient.stop (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\common\client.js:885:21)
	at LanguageClient.stop (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\node\main.js:150:22)
	at LanguageClient.handleConnectionError (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\common\client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 01:35:36] Client Metals: connection to server is erroring. Shutting down server.
[Error - 01:35:36] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\common\client.js:914:19)
	at LanguageClient.stop (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\common\client.js:885:21)
	at LanguageClient.stop (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\node\main.js:150:22)
	at LanguageClient.handleConnectionError (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\common\client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 01:35:36] Client Metals: connection to server is erroring. Shutting down server.
[Error - 01:35:36] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\common\client.js:914:19)
	at LanguageClient.stop (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\common\client.js:885:21)
	at LanguageClient.stop (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\node\main.js:150:22)
	at LanguageClient.handleConnectionError (c:\Users\DreamLAND\.vscode\extensions\scalameta.metals-1.39.0\node_modules\vscode-languageclient\lib\common\client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 01:35:39] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 01:35:39] Connection to server got closed. Server will restart.
true
[Error - 01:35:39] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
```

**Comment by DreamLand7707** [comment]
> You need to change the setting inside metals extension settings, which is in VS Code settings
> 
> Or alternatively you can wait until the next release, which should be next week

Ok, I'm really looking forward to your next stable release

**Comment by tgodzik** [comment]
However it looks like it actually started now? Do you see anything in `.metals/metals.log`, any logs? I am worried that my workaround didn't help and I have no way of reproducing it.

**Comment by DreamLand7707** [comment]
> 1.3.5+180-97cc5572-SNAPSHOT

Yes I got it
[metals.log](https://github.com/user-attachments/files/17446771/metals.log)

**Comment by tgodzik** [comment]
Looks like https://github.com/scalameta/metals/pull/6869 should help
