### ISSUE TITLE
metals can't create connection to server

### ISSUE THREAD

**Issue by stockstock2006** [scalameta/metals#6926]
IDE: Theia IDE
JDK: Tencent Konna JDK 21

Coursier is in the PATH

Metals version: 1.4.0
Fetching coursier
% Total
% Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent
Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--
:-- 0
0 0
0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
0 0 0 0
0 0 0 0 --:--:-- 0:00:01 --:--:-- 0
curl: (6) C
ould not resolve host: raw.githubusercontent.com
Failed to fetch coursier. You may want to try installing coursier manually and adding it to PATH.
Will try to use jar based coursier if Java is available on the machine.
Using coursier located at undefined
Checking Java in JAVA_HOME, which points to D:\CodingSoftware\TencentKona21JDK\TencentKona21JDK
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment TencentKonaJDK (build 21.0.4+1-LTS)
OpenJDK 64-Bit Server VM TencentKonaJDK (build 21.0.4+1-LTS, mixed mode, sharing)
Using Java Home: D:\CodingSoftware\TencentKona21JDK\TencentKona21JDK
[Error - 16:37:58] Metals client: couldn't create connection to server.
Error: spawn EPERM
at ChildProcess.spawn (node:internal/child_process:421:11)
at Object.spawn (node:child_process:776:9)
at C:\Users\Lenovo.theia-ide\deployedPlugins\scalameta.metals-1.42.0\extension\node_modules\vscode-languageclient\lib\node\main.js:426:46
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async LanguageClient.createConnection (C:\Users\Lenovo.theia-ide\deployedPlugins\scalameta.metals-1.42.0\extension\node_modules\vscode-languageclient\lib\common\client.js:1094:28)
at async LanguageClient.start (C:\Users\Lenovo.theia-ide\deployedPlugins\scalameta.metals-1.42.0\extension\node_modules\vscode-languageclient\lib\common\client.js:634:32)
Could not launch Metals Language Server:
spawn EPERM
Error, couldn't show release notes for Metals 1.4.0
Error: getaddrinfo ENOENT raw.githubusercontent.com

**Comment by tgodzik** [comment]
Looks like that JDK is not working, we don't test with every possible JDK so not sure what might be a problem here. 

You might need to install another JDK such as temurin manually. 

It's also possible that the metals.serverPropeties might be changed to a more minimal set to see if maybe some options are not supported by the current jdk
