### ISSUE TITLE
java.lang.RuntimeException: invalid symbol format causing Metals to go silent?

### ISSUE THREAD

**Issue by adamw** [scalameta/metals#7018]
### Describe the bug

When working on sttp/circe integration I noticed that Metals stopped being responsive (code navigation stops working quite frequently). The only thing in the log is the following stack trace:

```
2024.12.11 17:03:24 ERROR searching for `().` failed
java.lang.RuntimeException: invalid symbol format
().
^
	at scala.sys.package$.error(package.scala:27)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.fail(Scala.scala:164)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.readChar(Scala.scala:176)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.parseValue(Scala.scala:192)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.parseDescriptor(Scala.scala:209)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.entryPoint(Scala.scala:232)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser$.apply(Scala.scala:240)
	at scala.meta.internal.semanticdb.Scala$ScalaSymbolOps$.owner$extension(Scala.scala:80)
	at scala.meta.internal.mtags.Symbol.toplevel(Symbol.scala:50)
	at scala.meta.internal.mtags.SymbolIndexBucket.query0(SymbolIndexBucket.scala:200)
	at scala.meta.internal.mtags.SymbolIndexBucket.query(SymbolIndexBucket.scala:177)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$findSymbolDefinition$1(OnDemandSymbolIndex.scala:142)
	at scala.collection.immutable.List.flatMap(List.scala:294)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.findSymbolDefinition(OnDemandSymbolIndex.scala:142)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.definition(OnDemandSymbolIndex.scala:48)
	at scala.meta.internal.metals.FallbackDefinitionProvider.findInIndex$1(FallbackDefinitionProvider.scala:125)
	at scala.meta.internal.metals.FallbackDefinitionProvider.$anonfun$search$15(FallbackDefinitionProvider.scala:132)
	at scala.collection.immutable.List.flatMap(List.scala:294)
	at scala.meta.internal.metals.FallbackDefinitionProvider.$anonfun$search$3(FallbackDefinitionProvider.scala:131)
	at scala.Option.map(Option.scala:242)
	at scala.meta.internal.metals.FallbackDefinitionProvider.$anonfun$search$2(FallbackDefinitionProvider.scala:43)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.metals.FallbackDefinitionProvider.$anonfun$search$1(FallbackDefinitionProvider.scala:40)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.metals.FallbackDefinitionProvider.search(FallbackDefinitionProvider.scala:39)
	at scala.meta.internal.metals.DefinitionProvider.$anonfun$definition$3(DefinitionProvider.scala:120)
	at scala.Option.orElse(Option.scala:477)
	at scala.meta.internal.metals.DefinitionProvider.$anonfun$definition$2(DefinitionProvider.scala:120)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1583)
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.4.1

**Comment by kasiaMarek** [comment]
I'm not sure, this is the reason Metals goes silent. But [this PR](https://github.com/scalameta/metals/pull/7028/) adds a try clause around fallback definition search. It also adds more information about failed go to definition request in an error report, so  if this error occurs again, there should be more context logged.
