### ISSUE TITLE
`SignatureHelpSuite` fails in Scala 2 community build after Scalameta upgrade

### ISSUE THREAD

**Issue by SethTisue** [scalameta/metals#7075]
as seen at e.g. https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/2424/artifact/logs/metals-build.log

the failure started occurring when we upgraded Scalameta from 4.12.1 to 4.12.3. (I haven't tried replicating it outside of the community build context, but I imagine you'd see it if you attempt the same upgrade in-repo here. if not, let me know and I can dig deeper)

it looks like it might actually be a progression...?

```
[metals] ==> X tests.pc.SignatureHelpSuite.named_2.13.16-bin-f44badf  0.031s munit.Compa
risonFailException: tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala:578
[metals] 577:
[metals] 578:  check(
[metals] 579:    "named",
[metals] diff assertion failed
[metals] => Obtained
[metals]     """|apply(<age: Int = 42>, <name: String = "John">): User
[metals]        |                       ^^^^^^^^^^^^^^^^^^^^^^^
[metals]        |""".stripMargin
[metals] => Diff (- obtained, + expected)
[metals] -apply(<age: Int = 42>, <name: String = "John">): User
[metals] -                       ^^^^^^^^^^^^^^^^^^^^^^^
[metals] +apply(<age: Int = ...>, <name: String = ...>): User
[metals] +                        ^^^^^^^^^^^^^^^^^^^^
[metals]     at munit.FunSuite.assertNoDiff(FunSuite.scala:11)
[metals]     at tests.BaseSignatureHelpSuite.$anonfun$check$1(BaseSignatureHelpSuite.scala:97)
[metals] ==> X tests.pc.SignatureHelpSuite.named1_2.13.16-bin-f44badf  0.012s munit.ComparisonFailException: tests/cross/src/test/scala/tests/pc/SignatureHelpSuite.scala:597
[metals] 596:
[metals] 597:  check(
[metals] 598:    "named1",
[metals] diff assertion failed
[metals] => Obtained
[metals]     """|apply(name: String = "John", age: Int = 42): User
[metals]        |                             ^^^^^^^^^^^^^
[metals]        |""".stripMargin
[metals] => Diff (- obtained, + expected)
[metals] -apply(name: String = "John", age: Int = 42): User
[metals] -                             ^^^^^^^^^^^^^
[metals] +apply(name: String = ..., age: Int = ...): User
[metals] +                          ^^^^^^^^^^^^^^
[metals]     at munit.FunSuite.assertNoDiff(FunSuite.scala:11)
[metals]     at tests.BaseSignatureHelpSuite.$anonfun$check$1(BaseSignatureHelpSuite.scalogs/metals-build.log byte 66971/201817 33%
```

**Comment by SethTisue** [comment]
oh but hmm wait you did upgrade it already: https://github.com/scalameta/metals/pull/7069

🤔
