### ISSUE TITLE
Infinite loop doing completions

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#749]
**Describe the bug**

Triggering a completion results in the Metals process getting stuck and using a lot of CPU.

**To Reproduce**
Trigger a completion at this line here https://github.com/megri/metals-bug-example/blob/c752debe3ba0cab3ac3bd6ae9175a684c0574cc6/js/src/main/scala/com/megri/App.scala#L11

Big thanks to @megri for minimizing the reproduction 🙏 

**Expected behavior**

The Metals process should return normal completions instead of getting stuck.

**Stack trace**

The stack trace leads to a call to `Symbols.overrides` in the compiler.
```
$ jps -l | grep scala.meta.metals.Main | awk '{ print $1 }' | xargs -I % jstack %
...
at scala.reflect.internal.Symbols$SymbolContextApiImpl.overrides(Symbols.scala:208)
    at scala.meta.internal.pc.MetalsGlobal.loop$1(MetalsGlobal.scala:192)
...
```

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.5.0

**Search terms**

infinite loop, forever, slow, frozen, hot

**Comment by olafurpg** [comment]
A minimized reproduction
```scala
trait Observable[+A] {
  type Self[+T] <: Observable[T]
}
trait EventStream[+A] extends Observable[A] {
  override type Self[+T] = EventStream[T]
}
class Main {
  val stream: EventStream[Int] = ???
  stream.<COMPLETE>
}
```
