### ISSUE TITLE
StringIndexOutOfBoundsException during workspace/symbol

### ISSUE THREAD

**Issue by arosien** [scalameta/metals#832]
**Describe the bug**

**To Reproduce**
Not sure how it happened, I only noticed it after randomly scrolling through the Metals output tab.

**Expected behavior**

**Screenshots**
```
[Error - 2:55:16 PM] Request workspace/symbol failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:38)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:36)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at scala.meta.internal.metals.Fuzzy.exactMatch(Fuzzy.scala:118)
	at scala.meta.internal.metals.Fuzzy.isExactMatch(Fuzzy.scala:130)
	at scala.meta.internal.metals.ClasspathSearch.$anonfun$search$11(ClasspathSearch.scala:70)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:742)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:741)
	at scala.meta.internal.metals.ClasspathSearch.$anonfun$search$9(ClasspathSearch.scala:67)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.meta.internal.metals.ClasspathSearch.search(ClasspathSearch.scala:26)
	at scala.meta.internal.metals.WorkspaceSymbolProvider.search(WorkspaceSymbolProvider.scala:54)
	at scala.meta.internal.metals.WorkspaceSymbolProvider.searchUnsafe(WorkspaceSymbolProvider.scala:138)
	at scala.meta.internal.metals.WorkspaceSymbolProvider.search(WorkspaceSymbolProvider.scala:41)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$workspaceSymbol$2(MetalsLanguageServer.scala:977)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more
```

**Installation:**
```
Name: Scala (Metals)
Id: scalameta.metals
Description: Scala language server with rich IDE features
Version: 1.5.1
Publisher: Scalameta
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=scalameta.metals
```

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Hi, thanks for reporting! If you manage any reproduction it would be great, but I think we can try to figure something out based on the stack trace.

**Comment by tgodzik** [comment]
Looks to be a problem when we are looking for AA and there is something like A.class on the classpath.

**Comment by arosien** [comment]
Amazing time-to-fix! 👍
