### ISSUE TITLE
JavaMtags creates bogus position

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#86]
While testing the server in slick/slick
```scala
23:45:52.280 ERROR s.m.l.mtags.Mtags$ - Error indexing jar:file:///Users/ollie/.ivy2/cache/net.sourceforge.fmpp/fmpp/srcs/fmpp-0.9.15-sources.jar!/fmpp/tools/CommandLine.java
java.lang.IllegalArgumentException: 1101 is not a valid line number, allowed [0..1083]
	at org.langmeta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:31)
	at org.langmeta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:27)
	at org.langmeta.inputs.Input$VirtualFile.lineToOffset(Input.scala:74)
	at org.langmeta.languageserver.InputEnrichments$XtensionInputOffset$.toOffset$extension(InputEnrichments.scala:32)
	at scala.meta.languageserver.mtags.JavaMtags$$anon$1.toRangePosition(JavaMtags.scala:58)
	at scala.meta.languageserver.mtags.JavaMtags$$anon$1.$anonfun$visitClass$1(JavaMtags.scala:84)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.meta.languageserver.mtags.MtagsIndexer.withOwner(MtagsIndexer.scala:32)
```

**Comment by olafurpg** [comment]
Supposedly fixed in https://github.com/scalameta/metals/pull/325
