### ISSUE TITLE
CustomRepositories are not propagated to Metals itself 

### ISSUE THREAD

**Issue by antonoal** [scalameta/metals#902]
I've just upgraded to mertals 0.7.2 and now Metals fails to resolve org.scalameta:mtags_2.11.12:0.7.2. 
In the log it says it tries to resolve it against the following repos: List(Maven("https://repo1.maven.org/maven2"), Ivy2Local, Maven("https://oss.sonatype.org/content/repositories/releases"), Maven("https://oss.sonatype.org/content/repositories/snapshots"))

I assumed it uses Coursier to download that jar and hence tried to change the repos it looks the jar in to either maven2Local or our private repo via the "Metals: Custom Repositories" setting but despite setting it I still see the same error with the same repositories tried.

**Installation:**
- Operating system: Windows 7
- Editor: Visual Studio Code
- Metals version: v0.7.2

**Comment by tgodzik** [comment]
Thanks for reporting! How are you specifying the Custom Repositories?

Also, could you attach the log output you are getting?

**Comment by antonoal** [comment]
Metals VS Code plugin has a setting called "Metals: Custom Repositories". According to its description I needed to enter a comma separated list of repos which I did.

Here's the last few error in the metals.log: 

INFO  running embedded 'bloop bsp --protocol tcp --host 127.0.0.1 --port 57353'
The server is listening for incoming connections at tcp://127.0.0.1:57353...
INFO  bloop exit: 0
Accepted incoming BSP client connection at tcp://127.0.0.1:57353
INFO  tracing is enabled: C:\Users\1575520\AppData\Local\scalameta\metals\cache\bsp.trace.json
request received: build/initialize
INFO  time: connected to build server in 6.21s
BSP initialization handshake complete.
INFO  time: imported build in 17s
INFO  time: indexed workspace in 6.46s
Downloading https://repo1.maven.org/maven2/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom
Downloading https://repo1.maven.org/maven2/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom.sha1
https://repo1.maven.org/maven2/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.1� 
https://repo1.maven.org/maven2/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.1� 

Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom
Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom
Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom.sha1
ERROR failed: Downloading presentation compiler
com.geirsson.coursiersmall.ResolutionException: Failed to resolve Settings(
  dependencies  = List(Dependency("org.scalameta", "mtags_2.11.12", "0.7.2").intransitive)
  repositories  = List(Maven("https://repo1.maven.org/maven2"), Ivy2Local, Maven("https://oss.sonatype.org/content/repositories/releases"), Maven("https://oss.sonatype.org/content/repositories/snapshots"))
  ttl           = Some(Duration.Inf)
  forceVersions = List()
)
Dependency 'org.scalameta:mtags_2.11.12:0.7.2'
  download error: Caught java.net.UnknownHostException: repo1.maven.org (repo1.maven.org) while downloading https://repo1.maven.org/maven2/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom
  not found: C:\Users\1575520\.ivy2\local\org.scalameta\mtags_2.11.12\0.7.2\ivys\ivy.xml
  download error: Caught java.net.UnknownHostException: oss.sonatype.org (oss.sonatype.org) while downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom
  download error: Caught java.net.UnknownHostException: oss.sonatype.org (oss.sonatype.org) while downloading https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom
	at com.geirsson.coursiersmall.CoursierSmall$.fetch(CoursierSmall.scala:80)
	at scala.meta.internal.metals.Embedded$.newPresentationCompilerClassLoader(Embedded.scala:128)
	at scala.meta.internal.metals.Embedded.$anonfun$presentationCompiler$2(Embedded.scala:81)
	at scala.meta.internal.metals.Embedded$$Lambda$2461/1126322723.apply(null)
	at scala.meta.internal.metals.StatusBar.trackSlowTask(StatusBar.scala:56)
	at scala.meta.internal.metals.Embedded.$anonfun$presentationCompiler$1(Embedded.scala:81)
	at scala.meta.internal.metals.Embedded$$Lambda$2460/1671541864.apply(null)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)
	at scala.meta.internal.metals.Embedded.presentationCompiler(Embedded.scala:80)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:296)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$10(Compilers.scala:251)
	at scala.meta.internal.metals.Compilers$$Lambda$2458/2024103429.apply(null)
	at scala.meta.internal.metals.StatusBar.trackBlockingTask(StatusBar.scala:44)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$9(Compilers.scala:251)
	at scala.meta.internal.metals.Compilers$$Lambda$2457/372119033.apply(null)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$8(Compilers.scala:247)
	at scala.meta.internal.metals.Compilers$$Lambda$2456/2229219.apply(null)
	at scala.Option.map(Option.scala:230)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$7(Compilers.scala:244)
	at scala.meta.internal.metals.Compilers$$Lambda$2455/658708137.apply(null)
	at scala.Option$WithFilter.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$3(Compilers.scala:236)
	at scala.meta.internal.metals.Compilers$$Lambda$2452/1757020149.apply(null)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.loadCompiler(Compilers.scala:235)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3(Compilers.scala:91)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3$adapted(Compilers.scala:90)
	at scala.meta.internal.metals.Compilers$$Lambda$536/1468680417.apply(null)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.Compilers.$anonfun$load$1(Compilers.scala:90)
	at scala.meta.internal.metals.Compilers$$Lambda$522/1343952528.apply$mcV$sp(null)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.concurrent.Future$$$Lambda$80/2132515953.apply(null)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.Future$$Lambda$81/1370058521.apply(null)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.Promise$$Lambda$82/797830634.apply(null)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

INFO  compiling root-test (10 scala sources)
INFO  time: compiled root-test in 38s
ERROR Failed to compile 'root-test'
INFO  disconnected: build server
ERROR Failed to connect with build server, no functionality will work.
com.geirsson.coursiersmall.ResolutionException: Failed to resolve Settings(
  dependencies  = List(Dependency("org.scalameta", "mtags_2.11.12", "0.7.2").intransitive)
  repositories  = List(Maven("https://repo1.maven.org/maven2"), Ivy2Local, Maven("https://oss.sonatype.org/content/repositories/releases"), Maven("https://oss.sonatype.org/content/repositories/snapshots"))
  ttl           = Some(Duration.Inf)
  forceVersions = List()
)
Dependency 'org.scalameta:mtags_2.11.12:0.7.2'
  download error: Caught java.net.UnknownHostException: repo1.maven.org (repo1.maven.org) while downloading https://repo1.maven.org/maven2/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom
  not found: C:\Users\1575520\.ivy2\local\org.scalameta\mtags_2.11.12\0.7.2\ivys\ivy.xml
  download error: Caught java.net.UnknownHostException: oss.sonatype.org (oss.sonatype.org) while downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom
  download error: Caught java.net.UnknownHostException: oss.sonatype.org (oss.sonatype.org) while downloading https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/mtags_2.11.12/0.7.2/mtags_2.11.12-0.7.2.pom
	at com.geirsson.coursiersmall.CoursierSmall$.fetch(CoursierSmall.scala:80)
	at scala.meta.internal.metals.Embedded$.newPresentationCompilerClassLoader(Embedded.scala:128)
	at scala.meta.internal.metals.Embedded.$anonfun$presentationCompiler$2(Embedded.scala:81)
	at scala.meta.internal.metals.Embedded$$Lambda$2461/1126322723.apply(null)
	at scala.meta.internal.metals.StatusBar.trackSlowTask(StatusBar.scala:56)
	at scala.meta.internal.metals.Embedded.$anonfun$presentationCompiler$1(Embedded.scala:81)
	at scala.meta.internal.metals.Embedded$$Lambda$2460/1671541864.apply(null)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)
	at scala.meta.internal.metals.Embedded.presentationCompiler(Embedded.scala:80)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:296)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$10(Compilers.scala:251)
	at scala.meta.internal.metals.Compilers$$Lambda$2458/2024103429.apply(null)
	at scala.meta.internal.metals.StatusBar.trackBlockingTask(StatusBar.scala:44)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$9(Compilers.scala:251)
	at scala.meta.internal.metals.Compilers$$Lambda$2457/372119033.apply(null)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$8(Compilers.scala:247)
	at scala.meta.internal.metals.Compilers$$Lambda$2456/2229219.apply(null)
	at scala.Option.map(Option.scala:230)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$7(Compilers.scala:244)
	at scala.meta.internal.metals.Compilers$$Lambda$2455/658708137.apply(null)
	at scala.Option$WithFilter.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$3(Compilers.scala:236)
	at scala.meta.internal.metals.Compilers$$Lambda$2452/1757020149.apply(null)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.loadCompiler(Compilers.scala:235)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3(Compilers.scala:91)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3$adapted(Compilers.scala:90)
	at scala.meta.internal.metals.Compilers$$Lambda$536/1468680417.apply(null)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.Compilers.$anonfun$load$1(Compilers.scala:90)
	at scala.meta.internal.metals.Compilers$$Lambda$522/1343952528.apply$mcV$sp(null)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.concurrent.Future$$$Lambda$80/2132515953.apply(null)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.Future$$Lambda$81/1370058521.apply(null)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.Promise$$Lambda$82/797830634.apply(null)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

shutdown request received: build/shutdown
Client in C:\workspace\projects\sabre-store-catalogue\.bloop triggered cancellation. Cancelling tasks...
[0m[31m[E][0m BSP server cancelled, closing socket...
INFO  bloop exit: 0

**Comment by tgodzik** [comment]
> Metals VS Code plugin has a setting called "Metals: Custom Repositories". According to its description I needed to enter a comma separated list of repos which I did.

It actually says "Optional space separated list of custom resolvers" - I don't think commas will work.

**Comment by gabro** [comment]
> It actually says "Optional space separated list of custom resolvers" - I don't think commas will work.

Related: https://github.com/scalameta/metals-vscode/pull/141

**Comment by antonoal** [comment]
Apologies I'm not sure why I wrote comma separated. I tried it with repos space separated. In fact the first time I put there only 1 repo (our corporate one) and when that didn't work I added maven2Local.

**Comment by tgodzik** [comment]
I will try to figure out what's going on (I might have some idea), but right now you can use coursier to download the dependencies themselves before running.

**Comment by antonoal** [comment]
Ok, it's a bit weird now. I've decided to try a different approach and run VSCode from cygwin. The first time I run it it can't resolve anything. Then I set in my retminal the env variable COURSIER_REPOSITORIES to point to our corporate repo and I can see stuff (like metals itself) being downloaded until it gets to mtags_2.11.12. At this point it fails with the aforementioned error.
This means that the env variable does work but there must be some special logic for mtags_2.11.12. 
I have now downgraded to metals v 0.7.0 which works just fine.
Any ideas?

**Comment by tgodzik** [comment]
Confirmed it's a bug - you can work around it by downloading the missing library via coursier itself.

**Comment by gabro** [comment]
@tgodzik I can confirm `customRepositories` was added to `metals-vscode` as a client-only setting to allow downloading the Metals artifact itself.

This is not really a bug, it's rather a missing feature in Metals, in the sense that the setting was never really meant for propagation.

I'm not opposed to this change, but I just wanted to make clear that if we propagate this setting to the server, we're effectively using it to configure two different things.

**Comment by tgodzik** [comment]
> I'm not opposed to this change, but I just wanted to make clear that if we propagate this setting to the server, we're effectively using it to configure two different things.

We can add information about it sure, however we really need this for any bigger clients that have their own repositories. Though from what I see this change would require a couple of things:
1. Change coursiermini to official coursier API
2. Add user setting same custom repositories - it will use already existing one
3. Parse the setting and add repositories to all invocations of coursier in Embedded.

**Comment by olafurpg** [comment]
The COURSIER_REPOSITORIES environment variable gets automatically picked up by coursier..

**Comment by tgodzik** [comment]
@olafurpg so we should just forward it when starting the server? Will it be picked up by coursiermini?

**Comment by olafurpg** [comment]
I think that should do the trick in metals-vscode. My understanding is that Coursier picks up the environment variable regardless of what repositories we explicitly configure via the library API.

**Comment by olafurpg** [comment]
@antonoal you can validate if it works by opening up VS Code from the terminal with the `code` command

```
export COURSIER_REPOSITORIES=...
code .
```

Environment variables are not the same when VS Code is opened as a regular GUI application.

**Comment by antonoal** [comment]
I've actually tried that but as I said in my last comment although some things get resolved successfully when it gets to downloading mtags_2.11.12 it fails as if that env var is not set. Also this seems to have been introduced in metals 0.7.2

**Comment by antonoal** [comment]
Having said that it might be that the reason 0.7.0 works on my machine cause I manually downloaded some of the dependencies when set the env up a few months ago

**Comment by tgodzik** [comment]
This should be fixed with https://github.com/scalameta/metals-vscode/pull/161
